'use strict';
const query = new URLSearchParams(location.search);
const initialScreen = ['home','booking','tech','store'].includes(query.get('screen')) ? query.get('screen') : 'home';
const capture = query.has('capture');
const app = document.getElementById('app');
const icon = name => `<i data-lucide="${name}" aria-hidden="true"></i>`;
const button = (action, label, cls = 'primary', attrs = '') => `<button class="button ${cls}" data-action="${action}" ${attrs}>${label}</button>`;
const chevron = icon('chevron-right');
const avatar = (name='林', cls='') => `<span class="avatar ${cls}" aria-hidden="true">${name}</span>`;
const escapeText = value => String(value).replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const services = [
  {id:'body',name:'舒缓放松',category:'全身',duration:60,price:298,description:'全身放松 · 适合日常疲劳',icon:'hand',theme:'',label:'全身舒缓'},
  {id:'neck',name:'肩颈放松',category:'肩颈',duration:45,price:198,description:'肩颈舒缓 · 适合久坐人群',icon:'activity',theme:'sage',label:'肩颈舒缓'}
];
const defaults = () => ({screen:initialScreen,category:'全部服务',service:'body',tech:'林',assignment:'就近安排',address:'幸福里小区 2号楼',unit:'8层 802室',slot:'14:00–15:00',price:298,checked:false,paid:false,paidOrder:null,paymentExpired:false,techFilter:'全部',accepted:false,rejected:false,techExpired:false,arrived:false,started:false,storeExpired:false,dispatched:false,dispatchedTech:null,specificPending:false,specificTech:null,sosAck:false,sosClosed:false,sosResult:'',remaining:522,dispatchRemaining:1116,sosRemaining:120});
let state=defaults();
let draftAddress='幸福里小区 2号楼';
let draftSlot='14:00–15:00';
let draftPrice=298;
let draftTech='陈';
let toastTimer;
function icons(){lucide.createIcons({attrs:{'stroke-width':1.7}})}
function art(service){return `<div class="service-art ${service.theme}" aria-hidden="true">${icon(service.icon)}<span>${service.label}</span></div>`}
function countdown(seconds){return `${String(Math.floor(Math.max(0,seconds)/60)).padStart(2,'0')}分${String(Math.max(0,seconds)%60).padStart(2,'0')}秒`}
function statusbar(){return `<div class="statusbar"><span>${state.screen==='store'?'14:07':state.screen==='tech'?'13:45':'09:41'}</span><div class="status-icons">${icon('signal')}${icon('wifi')}${icon('battery-full')}</div></div>`}
function nav(title,back=false){return `<header class="navigation">${back?`<button class="back" data-action="home" aria-label="返回首页">${icon('chevron-left')}</button>`:''}${title==='天俪'?'<div class="navbrand"><span class="brand-mark">俪</span><strong>天俪<small>上门保健</small></strong></div>':`<h1>${title}</h1>`}<div class="capsule" aria-label="微信菜单占位"><b>•••</b><i></i><span></span></div></header>`}
function tabs(role){
  const lists={user:[['house','首页','home'],['clipboard-list','订单','user-orders'],['user-round','我的','profile']],tech:[['layout-dashboard','工作台','tech'],['calendar-days','排班','schedule'],['wallet','收入','income'],['user-round','我的','tech-profile']],store:[['list-checks','派单','store'],['clipboard-list','今日订单','store-orders'],['shield-alert','告警','alert-detail'],['calendar-days','排班','store-schedule']]};
  return `<footer class="tabbar">${lists[role].map(([i,label,action],n)=>`<button data-action="${action}" class="${n===0?'active':''}">${icon(i)}<span>${label}</span>${role==='store'&&n===2&&!state.sosAck?'<span class="nav-dot"></span>':''}</button>`).join('')}<span class="home-indicator"></span></footer>`;
}
function home(){return `${nav('天俪')}<main class="content" id="content"><div class="location">${icon('map-pin')}<div class="grow"><button class="address-button" data-action="address">${state.address.split(' ')[0]}${chevron}</button><p>根据上门地址，为你匹配附近服务</p></div><span class="badge good">可上门</span></div><div class="service-tabs">${['全部服务','肩颈','全身'].map(x=>`<button data-action="category" data-category="${x}" class="${state.category===x?'selected':''}">${x}</button>`).join('')}</div><div class="trust-strip"><span>${icon('badge-check')}培训记录可查</span><span>${icon('store')}门店负责</span><span>${icon('circle-check')}一口价含交通</span></div><section class="padded"><div class="section-head"><h2>预约上门服务</h2><button data-action="service-rules">服务说明${chevron}</button></div>${services.filter(s=>state.category==='全部服务'||s.category===state.category).map(s=>`<article class="service-row">${art(s)}<div class="grow"><h3>${s.name}<span class="badge" style="margin-left:7px">${s.duration}分钟</span></h3><p class="description">${s.description}</p><div class="price-line"><div class="price brand"><em>¥</em>${s.price}<small>总价</small></div>${button('book','预约','primary',`data-service="${s.id}"`)}</div></div></article>`).join('')}</section><div class="section-gap"></div><section class="padded"><div class="section-head"><h2>附近可约技师</h2><button data-action="nearby-sort">距离优先${icon('arrow-down-wide-narrow')}</button></div>${[['林','肩颈 / 全身放松','明天 14:00 可约',''],['陈','肩颈 / 肩背舒缓','明天 15:30 可约','chen']].map(([name,skills,slot,cls])=>`<article class="tech-row">${avatar(name,cls)}<div class="grow"><div class="name-line"><h3>${name}师傅</h3><span class="badge">档案可查</span></div><p>${skills}</p><p class="availability">${slot}</p></div><button class="choose" data-action="technician" data-tech="${name}">查看</button></article>`).join('')}</section><p class="footnote">服务由天俪·示例门店提供</p></main>${tabs('user')}`}
function booking(){const service=services.find(s=>s.id===state.service);return `${nav('确认预约',true)}<main class="content gray booking-content" id="content"><section class="group address-card"><div class="row">${icon('map-pin').replace('<i ','<i class="map-icon" ')}<div class="grow"><p class="address-line">${state.address}</p><p style="font-size:13px;margin-top:3px">${state.unit}</p><p class="contact">王女士<span style="margin-left:12px">138****8000</span></p></div><button class="link" data-action="address" aria-label="修改上门地址">修改${chevron}</button></div></section><section class="group"><div class="compact-service">${art(service)}<div class="grow"><h3>${service.name}</h3><p>${service.duration}分钟 · 上门服务</p></div></div><div class="form-row"><span class="label">预约时间</span><button class="value" data-action="time">明天 10月2日 ${state.slot}${chevron}</button></div><div class="technician-confirm">${avatar(state.tech,`small-avatar ${state.tech==='陈'?'chen':''}`)}<div class="grow"><div class="row"><strong>${state.tech}师傅</strong><span class="badge">${state.assignment}</span></div><p>已为你匹配具体技师</p></div><button class="link" data-action="technician" data-tech="${state.tech}">查看档案${chevron}</button></div><div class="form-row"><span class="label">服务门店</span><span class="value">天俪·示例门店</span></div></section><section class="group"><div class="total-row"><span>服务总价</span><strong>¥${state.price.toFixed(2)}</strong></div><div class="included">${icon('circle-check')}已含上门交通费，无其他附加费用</div></section><section class="group"><div class="form-row"><span class="label">取消规则</span><button class="value" data-action="cancel-rules">出发前免费取消${chevron}</button></div></section><div class="booking-notes">${state.checked?`<p class="brand">${icon('circle-check')} 服务范围、技师与时段已重新匹配</p>`:''}<p>支付后等待技师确认接单，订单进度将及时通知你。</p><button data-action="service-rules">预约即表示已阅读服务须知${chevron}</button></div></main><footer class="payment-footer"><div><span class="pay-label">应付</span><span class="price brand"><em>¥</em>${state.price}</span></div>${button(state.paymentExpired?'restart-booking':'pay',state.paymentExpired?'重新选择时段':'确认并支付','primary')}<span class="home-indicator"></span></footer>`}
function pendingOrder(){if(state.rejected||state.techExpired)return `<article class="order-card"><div class="order-top"><span>订单尾号 0132</span><span class="badge">已转门店派单</span></div><h3>舒缓放松 · 60分钟</h3><p class="order-time"><small>今天</small>16:00–17:00</p><p class="small muted" style="margin-top:8px">${state.techExpired?'确认时间已结束，本次接单已失效。':'已拒绝此订单，由门店重新安排技师。'}</p>${button('view-expired','查看订单','secondary full','style="margin-top:12px"')}</article>`;return `<article class="order-card"><div class="order-top"><span>订单尾号 0132</span>${state.accepted?'<span class="badge good">已接单</span>':`<span class="timer">${icon('timer')}剩余 <b data-timer="accept">${countdown(state.remaining)}</b></span>`}</div><div class="order-title"><h3>舒缓放松 · 60分钟</h3>${!state.accepted?'<span class="badge warm">待接单</span>':''}</div><p class="order-time"><small>今天</small>16:00–17:00</p><p class="order-place">${icon('map-pin')}幸福里小区 · 2号楼</p><p class="order-meta"><span>王女士</span><span>就近安排</span></p><div class="actions">${state.accepted?button('accepted-detail','查看已接订单','secondary'):button('reject','拒单','secondary narrow')+button('accept','确认接单')}</div></article>`}
function currentOrder(){return `<article class="order-card"><div class="order-top"><span>订单尾号 0126</span><span class="badge good">${state.started?'服务中':state.arrived?'已到达':'已出发'}</span></div><div class="order-title"><h3>舒缓放松 · 60分钟</h3></div><p class="order-time"><small>今天</small>14:00–15:00</p><div class="order-place">${icon('map-pin')}雅园小区 · 6号楼<button class="nav-link" data-action="navigation">导航${icon('navigation')}</button></div><div class="order-statusline">${icon('circle-check')}${state.started?'已开始服务，请在结束后完成打卡':state.arrived?'已到达，请与客户确认后开始服务':'13:30 已出发，请到达后打卡'}</div><div class="actions">${button('contact-customer','联系客户','secondary narrow')}${button(state.started?'end-service':state.arrived?'start-service':'arrive',state.started?'结束服务':state.arrived?'开始服务':'到达打卡')}</div></article>`}
function additionalOrders(){return [['0109','09:00–10:00','已完成','幸福里小区'],['0140','19:00–20:00','已接单','阳光花园']].map(([id,time,status,place])=>'<article class="order-card"><div class="order-top"><span>订单尾号 '+id+'</span><span class="badge">'+status+'</span></div><h3>舒缓放松 · 60分钟</h3><p class="order-time"><small>今天</small>'+time+'</p><p class="order-place">'+icon('map-pin')+place+'</p>'+button('other-order','查看订单','secondary full','data-order="'+id+'" style="margin-top:12px"')+'</article>').join('')}
function tech(){return `${nav('工作台')}<main class="content gray" id="content"><div class="worker-header surface">${avatar('林','small-avatar')}<div class="grow"><button data-action="role"><strong>林师傅</strong>${icon('chevron-down')}</button><p>天俪·示例门店</p></div><button class="safety" data-action="sos">${icon('shield-alert')}安全求助</button></div><div class="stats"><div class="stat"><strong>4</strong><span>今日订单</span></div><div class="stat emphasis"><strong>${state.accepted||state.rejected||state.techExpired?0:1}</strong><span>待确认</span></div><div class="stat"><strong>1</strong><span>已完成</span></div></div><div class="filterbar">${['全部','待确认','进行中'].map(x=>`<button data-action="tech-filter" data-filter="${x}" class="${state.techFilter===x?'selected':''}">${x}<span class="count">${x==='全部'?4:x==='待确认'?(state.accepted||state.rejected||state.techExpired?0:1):1}</span></button>`).join('')}</div><section class="order-list">${state.techFilter!=='进行中'?(state.techFilter==='待确认'&&(state.accepted||state.rejected||state.techExpired)?'<div class="empty">'+icon('circle-check')+'<h3>暂无待确认订单</h3><p>有新的预约时会通知你</p></div>':pendingOrder()):''}${state.techFilter!=='待确认'?currentOrder():''}${state.techFilter==='全部'?additionalOrders():''}</section></main>${tabs('tech')}`}
function alertCard(){if(state.sosClosed)return `<div class="alert-card processing"><div class="alert-heading">${icon('shield-check')}安全事件已处理<time>14:07</time></div><p>处理结果已记录，可在告警记录中查看。</p></div>`;return `<section class="alert-card ${state.sosAck?'processing':''}"><div class="alert-heading">${icon('shield-alert')}${state.sosAck?'安全求助 · 处理中':'安全求助待接报'}<time>今日 14:06</time></div><p>林师傅 · 雅园小区 ${!state.sosAck?`<span class="danger small" data-sos-status style="float:right">${state.sosRemaining?'<span data-timer="sos">'+countdown(state.sosRemaining)+'</span>后升级':'已升级通知'}</span>`:'<span class="small muted" style="float:right">王店长已接报</span>'}</p><div class="actions">${button('alert-detail','查看详情','secondary')}${button(state.sosAck?'sos-result':'ack',state.sosAck?'记录处理结果':'立即接报',state.sosAck?'soft':'red')}</div></section>`}
function pendingStoreCount(){return 2-((state.dispatched||state.storeExpired)?1:0)-(state.specificPending?1:0)}
function dispatchOrder(second=false){if(second&&state.specificPending)return '<article class="order-card"><div class="order-top"><span>订单尾号 0161</span><span class="badge warm">等待用户确认</span></div><h3>肩颈放松 · 45分钟</h3><p class="order-time"><small>今天</small>18:00–18:45</p><p class="order-place">拟改派：'+state.specificTech+'师傅</p><p class="small muted" style="margin-top:7px">已发送改派申请，等待用户确认。</p>'+button('specific-result','查看改派进度','secondary full','style="margin-top:12px"')+'</article>';if(!second&&(state.storeExpired||state.dispatched))return `<article class="order-card"><div class="order-top"><span>订单尾号 0158</span><span class="badge ${state.dispatched?'good':''}">${state.dispatched?'已派单':'已退款'}</span></div><h3>舒缓放松 · 60分钟</h3><p class="order-time"><small>今天</small>17:00–18:00</p><p class="small muted" style="margin-top:8px">${state.dispatched?`已安排${state.dispatchedTech}师傅，已通知用户。`:'派单期限已结束，已自动全额退款。'}</p>${button('dispatch-result','查看处理记录','secondary full','style="margin-top:12px"')}</article>`;return `<article class="order-card"><div class="order-top"><span>订单尾号 ${second?'0161':'0158'}</span><span class="timer">${icon('timer')}剩余 <b ${second?'':'data-timer="dispatch"'}>${second?'24分08秒':countdown(state.dispatchRemaining)}</b></span></div><div class="order-title"><h3>${second?'肩颈放松 · 45分钟':'舒缓放松 · 60分钟'}</h3><span class="badge warm">待派单</span></div><p class="order-time"><small>今天</small>${second?'18:00–18:45':'17:00–18:00'}</p><p class="order-place">${icon('map-pin')}${second?'阳光花园 · 3号楼':'幸福里小区 · 2号楼'}</p><p class="order-meta"><span>${second?'指定技师':'就近安排'}</span><span>${second?'改派需用户确认':'原技师拒单，需店内改派'}</span></p>${button(second?'dispatch-specific':'dispatch','选择技师派单','primary full','style="margin-top:12px"')}</article>`}
function store(){return `${nav('门店派单')}<main class="content gray" id="content"><div class="store-header surface">${icon('store')}<div class="grow"><strong>天俪·示例门店</strong><p>10月1日 · 今日门店订单</p></div><button data-action="role">店长${icon('chevron-down')}</button></div><div class="stats"><div class="stat emphasis"><strong>${pendingStoreCount()}</strong><span>待派单</span></div><div class="stat"><strong>3</strong><span>服务中</span></div><div class="stat"><strong>12</strong><span>今日订单</span></div></div>${alertCard()}<div class="filterbar"><button class="selected" data-action="store">待派订单<span class="count">${pendingStoreCount()}</span></button><button data-action="store-orders">全部订单</button><button data-action="store-schedule" style="margin-left:auto;gap:4px;font-size:11px">技师排班${chevron}</button></div><section class="order-list">${dispatchOrder()}${dispatchOrder(true)}</section></main>${tabs('store')}`}
function render(keepScroll=false){const scroll=keepScroll?document.getElementById('content')?.scrollTop||0:0;app.innerHTML=statusbar()+({home,booking,tech,store}[state.screen]());icons();if(keepScroll)document.getElementById('content').scrollTop=scroll;document.title=`天俪 · ${{home:'用户首页',booking:'确认预约',tech:'技师工作台',store:'门店派单'}[state.screen]}`}
function sheet(title,body,footer=''){closeSheet();const el=document.createElement('div');el.className='overlay';el.innerHTML=`<section class="sheet" role="dialog" aria-modal="true" aria-label="${title}"><header class="sheet-head"><h2>${title}</h2><button data-action="close" aria-label="关闭">${icon('x')}</button></header><div class="sheet-body">${body}</div>${footer?`<footer class="sheet-footer">${footer}</footer>`:''}</section>`;app.append(el);icons();el.addEventListener('click',e=>{if(e.target===el)closeSheet()});el.querySelector('button,textarea')?.focus({preventScroll:true})}
function closeSheet(){app.querySelector('.overlay')?.remove()}
function toast(text){app.querySelector('.toast')?.remove();clearTimeout(toastTimer);const el=document.createElement('div');el.className='toast';el.role='status';el.textContent=text;app.append(el);toastTimer=setTimeout(()=>el.remove(),3300)}
function info(title,text){sheet(title,`<p>${text}</p>`,button('close','知道了','primary full'))}
function addressSheet(){sheet('选择上门地址',`${['幸福里小区 2号楼','阳光花园 3号楼','远郊花园 1号楼'].map((x,i)=>`<button class="choice ${draftAddress===x?'selected':''}" data-action="pick-address" data-address="${x}"><span class="grow">${x}<small>${i===0?'王女士 · 138****8000 · 当前地址':i===1?'王女士 · 138****8000 · 可提供上门服务':'暂未覆盖该地址'}</small></span>${draftAddress===x?icon('circle-check'):chevron}</button>`).join('')}${draftAddress.startsWith('远郊')?'<p class="error-message">当前地址暂未开通上门服务，请选择服务范围内的地址。</p>':'<p class="small muted">变更地址后，将重新匹配可服务的技师与时段。</p>'}`,button('save-address','使用此地址','primary full',draftAddress.startsWith('远郊')?'disabled':''))}
function timeSheet(){
 const duration=services.find(s=>s.id===state.service).duration;
 const choices=[['14:00',state.service==='neck'?198:298],['15:30',state.service==='neck'?198:298],['18:00',state.service==='neck'?198:328]].map(([begin,price])=>{const [h,m]=begin.split(':').map(Number);const finish=h*60+m+duration;return {begin,price,slot:begin+'–'+String(Math.floor(finish/60)).padStart(2,'0')+':'+String(finish%60).padStart(2,'0')}});
 sheet('选择预约时间','<p style="font-weight:600;margin-bottom:12px">明天 · 10月2日</p><div class="slot-grid">'+choices.map(c=>'<button class="choice '+(draftSlot===c.slot?'selected':'')+'" data-action="pick-time" data-slot="'+c.slot+'" data-price="'+c.price+'"><span>'+c.begin+'</span><small>总价 ¥'+c.price+'</small></button>').join('')+'<button class="choice" disabled><span>16:30</span><small>已约满</small></button></div><p class="small muted" style="margin-top:15px">服务时长'+duration+'分钟。总价已包含上门交通费，确认时会校验技师可约状态。</p>',button('save-time','确认预约时间','primary full'));
}
function dispatchSheet(specific=false){sheet(specific?'店内改派 · 指定技师订单':'选择本店技师',`<p class="small muted" style="margin-bottom:12px">${specific?'18:00–18:45 · 改派需用户确认':'17:00–18:00 · 就近安排订单'}</p>${[['陈','可接单 · 时段无冲突','chen'],['周','可接单 · 时段无冲突','zhou']].map(([n,t,c])=>`<button class="choice ${draftTech===n?'selected':''}" data-action="pick-dispatch" data-tech="${n}" data-specific="${specific}">${avatar(n,'small-avatar '+c)}<span class="grow">${n}师傅<small>${t}</small></span>${draftTech===n?icon('circle-check'):''}</button>`).join('')}<p class="small muted">仅列出本店、资质有效且符合订单要求的技师。</p>`,button(specific?'confirm-specific':'confirm-dispatch',specific?'提交改派，等待用户确认':'确认派单','primary full'))}
function alertDetail(){sheet('安全求助详情',`<div class="detail-line"><span>事件状态</span><span class="${state.sosClosed?'':state.sosAck?'brand':'danger'}">${state.sosClosed?'已结案':state.sosAck?'处理中':'待接报'}</span></div><div class="detail-line"><span>求助人</span><span>林师傅</span></div><div class="detail-line"><span>关联订单</span><span>尾号 0126 · 雅园小区</span></div><div class="detail-line"><span>发生时间</span><span>今日 14:06</span></div><div class="detail-line"><span>最近记录位置</span><span>雅园小区 · 14:06</span></div>${state.sosAck?'<div class="detail-line"><span>接报人</span><span>王店长 · 14:07</span></div>':''}<div class="actions">${button('contact-tech','联系技师','secondary')}${button('contact-customer','联系客户','secondary')}</div><div class="timeline"><p>14:06 收到求助，已通知门店与值班客服</p>${state.sosAck?'<p>14:07 王店长已接报，处理中</p>':'<p>3分钟内无人接报，将升级通知安全负责人</p>'}${state.sosClosed?`<p>处理结果：${escapeText(state.sosResult)}</p>`:''}</div>`,state.sosClosed?button('close','关闭','secondary full'):button(state.sosAck?'sos-result':'ack',state.sosAck?'记录处理结果':'确认接报并开始处理',state.sosAck?'primary full':'red full'))}
app.addEventListener('click',event=>{
 const target=event.target.closest('[data-action]');if(!target||target.disabled)return;const a=target.dataset.action;
 switch(a){
 case 'home':case 'tech':case 'store':state.screen=a;render();break;
 case 'close':closeSheet();break;
 case 'category':state.category=target.dataset.category;render(true);break;
 case 'nearby-sort':info('距离优先','当前按上门地址附近的技师展示。完整选技师页面将支持距离、评分排序。');break;
 case 'book':{const s=services.find(x=>x.id===target.dataset.service);state.service=s.id;state.price=s.price;state.slot=s.duration===45?'14:00–14:45':'14:00–15:00';state.screen='booking';state.paid=false;state.paymentExpired=false;render();break;}
 case 'service-rules':sheet('服务须知','<p>本期提供上门保健服务，项目总价已包含交通费。请提前准备便于开展服务的空间。</p><p>服务开始前与技师确认项目内容；如有不适，请及时告知并停止服务。</p><p>可通过订单联系门店、申请售后或使用安全求助。</p>',button('close','我知道了','primary full'));break;
 case 'cancel-rules':sheet('取消规则','<div class="detail-line"><span>技师出发前</span><span>免费取消，全额退款</span></div><div class="detail-line"><span>已出发、未到达</span><span>扣订单金额20%</span></div><div class="detail-line"><span>技师迟到超过15分钟</span><span>可免费取消</span></div><div class="detail-line"><span>技师已到达</span><span>联系平台客服处理</span></div><p class="small muted" style="margin-top:12px">此处展示需求文档的默认规则，实际规则随订单确认。</p>',button('close','知道了','primary full'));break;
 case 'address':draftAddress=state.address;addressSheet();break;
 case 'pick-address':draftAddress=target.dataset.address;addressSheet();break;
 case 'save-address':if(draftAddress.startsWith('远郊'))return;state.address=draftAddress;state.unit=draftAddress.startsWith('阳光')?'12层 1201室':'8层 802室';state.tech=draftAddress.startsWith('阳光')?'陈':'林';state.assignment='就近安排';state.checked=true;render(true);toast('已重新匹配服务范围内的技师，请确认预约信息');break;
 case 'time':draftSlot=state.slot;draftPrice=state.price;timeSheet();break;
 case 'pick-time':draftSlot=target.dataset.slot;draftPrice=Number(target.dataset.price);timeSheet();break;
 case 'save-time':state.slot=draftSlot;state.price=draftPrice;state.checked=true;state.paymentExpired=false;render(true);toast('技师时段与总价已更新，请核对后支付');break;
 case 'technician':{const n=target.dataset.tech||state.tech;sheet(`${n}师傅 · 技师档案`,`${avatar(n,n==='陈'?'chen':'')}<div class="detail-line"><span>所属门店</span><span>天俪·示例门店</span></div><div class="detail-line"><span>擅长项目</span><span>${n==='林'?'肩颈 / 全身放松':'肩颈 / 肩背舒缓'}</span></div><div class="detail-line"><span>培训批次</span><span>2026年 第03期</span></div><div class="detail-line"><span>培训记录</span><span>门店已登记，可查验</span></div><p class="demo-hint">此原型使用姓名头像和示例档案，正式展示需使用审核后的照片与真实证书记录。</p>`,state.screen==='home'?button('select-tech','选择该技师预约','primary full',`data-tech="${n}"`):button('close','返回确认预约','primary full'));break;}
 case 'select-tech':state.tech=target.dataset.tech;state.assignment='指定技师';state.screen='booking';state.paid=false;state.service='body';state.price=298;state.slot=state.tech==='陈'?'15:30–16:30':'14:00–15:00';render();break;
 case 'pay':if(state.paymentExpired)return;sheet('微信支付 · 演示',`<p style="text-align:center;font-size:30px;font-weight:600;padding:14px 0">¥${state.price.toFixed(2)}</p><p class="muted small" style="text-align:center">本地原型演示，不会发起真实扣款。</p><div class="detail-line"><span>收款门店</span><span>天俪·示例门店</span></div>`,button('paid','模拟支付成功','primary full'));break;
 case 'paid':{const service=services.find(s=>s.id===state.service);state.paid=true;state.paidOrder={name:service.name,duration:service.duration,price:state.price,tech:state.tech,slot:state.slot,address:state.address,unit:state.unit};state.screen='home';render();sheet('预约已提交','<p>'+state.paidOrder.tech+'师傅将在接单时限内确认，请留意订单通知。</p><div class="detail-line"><span>订单状态</span><span class="brand">待接单</span></div><div class="detail-line"><span>预约时间</span><span>明天 '+state.paidOrder.slot+'</span></div>',button('user-orders','查看订单','primary full'));break;}
 case 'restart-booking':draftSlot=state.slot;draftPrice=state.price;timeSheet();break;
 case 'user-orders':{const order=state.paidOrder;sheet('我的订单',order?'<h3>'+order.name+' · '+order.duration+'分钟</h3><div class="detail-line"><span>状态</span><span class="brand">待接单</span></div><div class="detail-line"><span>技师</span><span>'+order.tech+'师傅</span></div><div class="detail-line"><span>预约时间</span><span>明天 '+order.slot+'</span></div><div class="detail-line"><span>实付总价</span><span>¥'+order.price.toFixed(2)+'</span></div><div class="detail-line"><span>上门地址</span><span>'+order.address+'</span></div><p class="small muted" style="margin-top:10px">技师确认后会更新订单状态。出发前可免费取消。</p>':'<div class="empty">'+icon('clipboard-list')+'<h3>还没有预约订单</h3><p>选择服务后即可预约上门</p></div>',button('close','返回','secondary full'));break;}
 case 'profile':sheet('我的',`<div class="detail-line"><span>姓名</span><span>王女士</span></div><div class="detail-line"><span>实名状态</span><span>已核验</span></div><button class="choice" data-action="address">常用地址${chevron}</button><button class="choice" data-action="privacy">隐私与账号${chevron}</button><p class="small muted">首次预约前须完成实名核验，本页演示已实名用户。</p>`);break;
 case 'privacy':info('隐私与账号','正式版本在此提供隐私告知、同意管理和注销入口。原型不采集身份证、手机号或位置信息。');break;
 case 'tech-filter':state.techFilter=target.dataset.filter;render(true);break;
 case 'accept':if(state.techExpired||state.rejected)return;state.accepted=true;render(true);toast('已接单，请按预约时间提供服务');break;
 case 'reject':sheet('确认拒单？','<p>拒单后由本店重新安排技师，请确认你无法提供本次服务。</p>',`<div class="actions">${button('close','返回','secondary')}${button('confirm-reject','确认拒单')}</div>`);break;
 case 'confirm-reject':state.rejected=true;render(true);toast('已拒单，订单已转门店待派单');break;
 case 'other-order':info('订单详情',target.dataset.order==='0109'?'今天09:00–10:00的服务已完成，正在售后期内。':'今天19:00–20:00，阳光花园，已接单。请按时出发并完成服务打卡。');break;
 case 'view-expired':info('订单已转门店派单','此订单已不属于你的可接单任务，门店将为客户重新安排技师。');break;
 case 'accepted-detail':info('已接订单','今天16:00–17:00，幸福里小区2号楼。请在出发前授权位置，并按订单步骤完成服务打卡。');break;
 case 'arrive':sheet('确认到达',`<p>请确认已到达雅园小区6号楼。</p><p class="small muted">到达打卡会记录本次位置；定位失败时允许继续并标记异常。</p>`,button('confirm-arrive','确认到达','primary full'));break;
 case 'confirm-arrive':state.arrived=true;render(true);toast('到达打卡成功，请与客户确认后开始服务');break;
 case 'start-service':state.started=true;render(true);toast('服务已开始');break;
 case 'end-service':info('结束服务','此处演示结束服务确认。正式版本按实际结束时间记录打卡，并进入售后期。');break;
 case 'navigation':info('前往服务地址','导航目的地：雅园小区6号楼。正式版本将打开地图导航，原型不会获取真实位置。');break;
 case 'contact-customer':info('联系客户','通过平台虚拟号码联系客户，技师端不展示客户的真实手机号。本地原型不会拨出电话。');break;
 case 'contact-tech':info('联系林师傅','正式版本在此呼叫订单关联技师。本地原型不会拨出电话。');break;
 case 'sos':sheet('安全求助','<p>如遇紧急危险，请直接拨打110。</p><p class="small muted">发起求助后将通知门店与值班客服，并记录当前或最后已知位置。</p>',`${button('call-police',icon('phone')+'直接拨打110','red full')}<div style="height:10px"></div>${button('send-sos','通知门店与值班客服','secondary full')}`);break;
 case 'call-police':info('直接拨打110','这是原型演示，不会拨出真实报警电话。正式版本将调用手机拨号能力。');break;
 case 'send-sos':sheet('求助已发出','<p>演示状态：门店与值班客服已收到求助通知。无人确认时将按3分钟规则升级处理。</p>',button('call-police','直接拨打110','red full'));break;
 case 'role':sheet('切换身份','<p class="small muted" style="margin-bottom:12px">正式账号仅展示已授权身份。以下为本地原型的角色预览。</p><button class="choice" data-action="home">用户端'+chevron+'</button><button class="choice" data-action="tech">技师端'+chevron+'</button><button class="choice" data-action="store">店长端'+chevron+'</button>');break;
 case 'schedule':sheet('今日排班','<div class="detail-line"><span>14:00–15:00</span><span>雅园小区 · 已出发</span></div><div class="detail-line"><span>16:00–17:00</span><span>幸福里小区 · 待确认</span></div><p class="small muted" style="margin-top:12px">排班管理将在后续页面展开，预约时段前后需预留路程缓冲。</p>',button('close','返回工作台','secondary full'));break;
 case 'income':sheet('收入','<div class="detail-line"><span>服务提成</span><span>由门店发放</span></div><div class="detail-line"><span>分销佣金</span><span>结算后可申请提现</span></div><p class="small muted" style="margin-top:12px">服务提成、取消补偿与分销佣金分开记账。此页仅说明收入结构。</p>',button('close','返回','secondary full'));break;
 case 'tech-profile':info('技师档案','正式版本包含证书、培训记录、保单与到期提醒、实名核验及推广码。当前四页原型未展开档案管理。');break;
 case 'ack':state.sosAck=true;render(true);toast('已接报，事件进入处理中，请联系当事人');break;
 case 'alert-detail':alertDetail();break;
 case 'sos-result':sheet('记录处理结果','<p>确认已联系当事人、完成处理后，再提交结案。</p><label for="result" class="small muted">处理结果（必填）</label><textarea id="result" placeholder="记录联系情况、采取措施及处理结果"></textarea><p class="small danger" id="result-error" role="alert"></p>',button('save-result','提交处理结果并结案','primary full'));break;
 case 'save-result':{const value=document.getElementById('result').value.trim();if(!value){document.getElementById('result-error').textContent='请填写实际处理结果后再提交';return}state.sosResult=value;state.sosClosed=true;render(true);toast('处理结果已记录，安全事件已结案');break;}
 case 'dispatch':if(state.storeExpired)return;draftTech='陈';dispatchSheet();break;
 case 'dispatch-specific':draftTech='陈';dispatchSheet(true);break;
 case 'pick-dispatch':draftTech=target.dataset.tech;dispatchSheet(target.dataset.specific==='true');break;
 case 'confirm-dispatch':if(state.storeExpired){info('派单已超时','当前订单已失效，请查看退款处理记录');return}state.dispatched=true;state.dispatchedTech=draftTech;render(true);toast(`已安排${state.dispatchedTech}师傅，已通知用户`);break;
 case 'confirm-specific':state.specificPending=true;state.specificTech=draftTech;render(true);info('等待用户确认','此订单原为指定技师，改派请求已提交。用户拒绝或15分钟未确认时，将全额退款。');break;
 case 'specific-result':info('改派进度','已申请改派给'+state.specificTech+'师傅，等待用户确认；拒绝或15分钟未确认将全额退款。');break;
 case 'dispatch-result':info('派单处理记录',state.storeExpired?'派单期限已结束，演示订单已全额退款并通知用户。':`已改派给本店${state.dispatchedTech}师傅，就近安排订单已发送变更通知。`);break;
 case 'store-orders':sheet('今日订单','<div class="detail-line"><span>待派单</span><span>'+(pendingStoreCount())+'笔</span></div><div class="detail-line"><span>服务中</span><span>3笔</span></div><div class="detail-line"><span>已完成及其他状态</span><span>其余订单</span></div><p class="small muted" style="margin-top:12px">仅查看本店订单。完整订单列表将在后续页面展开。</p>',button('close','返回派单','secondary full'));break;
 case 'store-schedule':sheet('本店今日技师排班',`${[['林','14:00–15:00 服务中',''],['陈','17:00–18:00 可接单','chen'],['周','17:00–18:00 可接单','zhou']].map(([n,t,c])=>`<div class="tech-row">${avatar(n,c)}<div class="grow"><h3>${n}师傅</h3><p>${t}</p></div></div>`).join('')}<p class="small muted" style="margin-top:12px">这里只查看今日排班，完整排班和请假管理在对应页面处理。</p>`,button('close','返回派单','secondary full'));break;
 }
});
function expire(){if(!state.accepted&&!state.rejected)state.techExpired=true;if(!state.dispatched)state.storeExpired=true;state.paymentExpired=true;state.remaining=0;state.dispatchRemaining=0;render(true);if(state.screen==='booking')toast('支付时段锁定已过期，请重新选择可约时段')}
window.addEventListener('message',event=>{if(event.source!==window.parent)return;if(event.data?.type==='reset'){state=defaults();render()}if(event.data?.type==='expire')expire()});
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeSheet();if(event.key==='Tab'){const dialog=app.querySelector('.sheet');if(!dialog)return;const focusables=[...dialog.querySelectorAll('button:not(:disabled),textarea,input,a[href]')];const first=focusables[0],last=focusables[focusables.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}});
if(!capture)setInterval(()=>{if(!state.accepted&&!state.rejected&&!state.techExpired){state.remaining=Math.max(0,state.remaining-1);if(!state.remaining){state.techExpired=true;if(state.screen==='tech')render(true)}}if(!state.dispatched&&!state.storeExpired){state.dispatchRemaining=Math.max(0,state.dispatchRemaining-1);if(!state.dispatchRemaining){state.storeExpired=true;if(state.screen==='store')render(true)}}if(!state.sosAck)state.sosRemaining=Math.max(0,state.sosRemaining-1);app.querySelectorAll('[data-timer]').forEach(el=>{el.textContent=countdown(el.dataset.timer==='accept'?state.remaining:el.dataset.timer==='dispatch'?state.dispatchRemaining:state.sosRemaining)});if(!state.sosRemaining&&!state.sosAck){const escalation=app.querySelector('[data-sos-status]');if(escalation)escalation.textContent='已升级通知'}},1000);
render();
if(query.get('scenario')==='expired')expire();
if(query.get('scenario')==='escalated'){state.sosRemaining=0;render()}
