'use strict';
const V=View,A=Admin;
const ui={page:'dashboard',tab:'全部',search:'',storeFilter:'',state:'normal',menuOpen:false,dialog:null,focus:null};
let toastTimer;
function toast(message){const e=document.getElementById('toast');e.textContent=message;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),3000);}
function route(page='dashboard'){ui.tab='全部';ui.search='';ui.storeFilter='';ui.state='normal';ui.menuOpen=false;location.hash=`/${A.state.session?.role||'store'}/${page}`;if(ui.page===page)render();}
function icons(){lucide.createIcons({attrs:{'stroke-width':1.65}});}
function title(){return AdminData.menus[A.state.session?.role||'store'].find(m=>m[0]===ui.page)?.[1]||({dashboard:'工作台',orders:'预约总览'}[ui.page]||'页面');}
function login(){return `<div class="login-wrap"><section class="login-side"><div class="brand-lockup"><span class="brand-mark">俪</span>天俪 <small>运营管理</small></div><div><h1>每一笔预约<br>都有序可循。</h1><p>连接门店、技师与集团<br>让安排、服务与结算各有归属</p></div><div class="login-lines"><span class="small">TIANLI · OPERATIONS</span></div></section><main class="login-main"><div class="login-form"><h2>进入运营后台</h2><p>选择演示账号，查看对应业务与数据范围。</p><button class="login-choice" data-action="login" data-role="store">${V.icon('store')}<div><h3>门店后台</h3><small>何店长 · 幸福里门店</small></div><span class="arrow">${V.icon('arrow-right')}</span></button><button class="login-choice" data-action="login" data-role="hq">${V.icon('building-2')}<div><h3>集团后台</h3><small>周运营 · 全集团演示权限</small></div><span class="arrow">${V.icon('arrow-right')}</span></button><p class="login-help">原型评审账号 · 所有资料均为示例<br>操作结果保存在当前浏览器，可随时恢复初始数据。</p></div></main></div>`;}
function render(){
  if(!A.state.session){document.getElementById('app').innerHTML=login();icons();document.body.dataset.ready='1';return;}
  const role=A.state.session.role,menus=AdminData.menus[role],count=page=>page==='orders'?A.orders().filter(o=>o.status==='待分配').length:page==='safety'?A.state.safety.filter(s=>A.visible(s)&&s.status!=='已结案').length:0;
  const navigation=`<a href="#/${role}/dashboard" class="nav-link ${ui.page==='dashboard'?'active':''}">${V.icon('layout-dashboard')}<span>工作台</span></a>`+menus.map(([id,name,ico,group])=>`${group?`<div class="nav-group">${group}</div>`:''}<a href="#/${role}/${id}" class="nav-link ${ui.page===id?'active':''}">${V.icon(ico)}<span>${name}</span>${count(id)?`<span class="nav-count">${count(id)}</span>`:''}</a>`).join('');
  let content;
  if(ui.state==='loading')content=V.head(title(),'正在加载业务数据')+V.panel('加载中',`<div class="panel-body">${Array.from({length:7},()=>'<div class="skeleton"></div>').join('')}</div>`);
  else if(ui.state==='error')content=V.head(title(),'')+`<div class="panel">${V.empty('加载失败','网络连接暂时不可用，请重试。','retry')}</div>`;
  else if(ui.state==='denied')content=V.head('访问受限','')+`<div class="panel">${V.empty('没有访问权限','当前账号只能访问已授权门店和业务，请返回工作台。','home')}</div>`;
  else if(ui.state==='empty')content=V.head(title(),'')+`<div class="panel">${V.empty('暂无业务记录','后续记录将在这里显示，可恢复样例继续评审。','retry')}</div>`;
  else content=V.content(ui.page,ui);
  document.getElementById('app').innerHTML=`<div class="mobile-backdrop ${ui.menuOpen?'visible':''}" data-action="menu"></div><aside class="sidebar ${ui.menuOpen?'open':''}"><div class="brand-wrap"><div class="brand-lockup"><span class="brand-mark">俪</span>天俪<small>管理后台</small></div></div><div class="org-box"><strong>${role==='hq'?'集团运营中心':'幸福里门店'}</strong><p>${role==='hq'?'全集团业务范围':'南京 · 鼓楼区　直营门店'}</p></div><nav class="nav">${navigation}</nav><div class="sidebar-foot"><span class="dot"></span>天俪管理后台 <span class="muted">v1.0</span></div></aside><div class="shell"><header class="topbar"><div class="flexrow"><button class="icon-btn menu-toggle" aria-label="打开导航" data-action="menu">${V.icon('menu')}</button><div class="breadcrumb">运营后台 ${V.icon('chevron-right')}<b>${title()}</b></div></div><div class="top-actions"><span class="tiny muted top-time">${V.date(A.state.now)} · 演示时间</span><span class="badge top-brand-tag">评审稿</span><button class="icon-btn" data-action="review-controls" aria-label="演示设置" title="演示设置">${V.icon('settings-2')}</button><select class="role-switch" id="role-switch" aria-label="切换后台端"><option value="store" ${role==='store'?'selected':''}>门店后台</option><option value="hq" ${role==='hq'?'selected':''}>集团后台</option></select><span class="top-separator"></span><button class="flexrow" data-action="profile"><span class="avatar">${role==='hq'?'周':'何'}</span><span class="account-name">${role==='hq'?'周运营':'何店长'}<small>${role==='hq'?'集团运营':'门店管理员'}</small></span>${V.icon('chevron-down')}</button></div></header><main class="workspace" id="main">${content}<footer class="footnote">天俪运营管理 · 原型评审　数据与渠道操作均为本地演示</footer></main></div>`;
  icons();document.body.dataset.ready='1';document.title=title()+' · 天俪管理后台';
}
function readRoute(){if(!A.state.session){render();return;}const [,role,page]=location.hash.split('/');ui.page=page||'dashboard';ui.tab='全部';ui.search='';ui.storeFilter='';ui.state='normal';ui.menuOpen=false;const permitted=['dashboard',...AdminData.menus[A.state.session.role].map(m=>m[0]),...(A.state.session.role==='hq'?['orders']:[])];if(role&&role!==A.state.session.role||!permitted.includes(ui.page))ui.state='denied';render();window.scrollTo(0,0);document.querySelector('.nav-link.active')?.scrollIntoView({block:'nearest'});}
function overlay(title,body,footer='',drawer=false,wide=false){ui.focus=document.activeElement;document.body.style.overflow='hidden';document.getElementById('overlay').innerHTML=`<div class="overlay-backdrop ${drawer?'':'modal-center'}"><section class="${drawer?'drawer':'modal'} ${wide?'wide':''}" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><header class="overlay-head"><h2 id="dialog-title">${title}</h2><button class="icon-btn" data-action="close" aria-label="关闭">${V.icon('x')}</button></header><div class="overlay-body">${body}</div>${footer?`<footer class="overlay-footer">${footer}</footer>`:''}</section></div>`;icons();document.querySelector('#overlay input:not([type=hidden]),#overlay textarea,#overlay button')?.focus();}
function close(){document.getElementById('overlay').innerHTML='';document.body.style.overflow='';ui.dialog=null;if(ui.focus?.isConnected)ui.focus.focus();}
function form(title,body,submit,hidden={},label='确认提交',wide=false){ui.dialog={type:submit,id:hidden.id||hidden.order};overlay(title,`<form id="dialog-form" data-submit="${submit}">${Object.entries(hidden).map(([k,v])=>`<input type="hidden" name="${k}" value="${V.h(v)}">`).join('')}<div class="form-error" role="alert"></div>${body}</form>`,V.btn('取消','close')+`<button form="dialog-form" class="btn primary" type="submit"><span class="control-label">${label}</span></button>`,false,wide);}
function showOrder(id){const o=A.find('orders',id);A.check(o);ui.dialog={type:'order',id};const p=o.proposal,payments=o.payments||[{name:'主单支付',paid:o.paid,refunded:o.refund}],c=A.state.cases.find(c=>c.order===id),s=A.state.safety.find(s=>s.order===id);overlay(`预约详情 <small>${V.no(o)} · ${V.storeName(o.store)}</small>`,
  `<div class="detail-summary"><div class="between"><div><h3>${V.h(o.customer)} · ${A.item(o).name}</h3><span class="small muted">${V.date(o.start)}　${A.duration(o)}分钟　${V.techName(o.tech)}</span></div>${V.badge(A.displayStatus(o))}</div><div class="detail-actions">${['待分配','已确认'].includes(o.status)&&!p?V.btn(o.status==='待分配'?'分配技师':'店内改派','assign',{id},'primary')+V.btn('提出改约','reschedule',{id})+V.btn('取消预约','cancel',{id}):''}${c?V.btn('查看售后','case',{id:c.id}):''}${s?V.btn('安全事件','safety',{id:s.id},'danger-btn'):''}</div></div>`+
  (p?`<div class="proposal-box"><div class="between"><strong class="small">${p.type==='assign'?'指定改派':'门店改约'} · 等待用户确认</strong>${V.badge('剩余 '+V.remaining(p.expires),'warn')}</div><div class="compare-grid"><div class="compare-part"><small>原安排</small>${p.type==='assign'?V.techName(o.tech):V.date(o.start)}</div>${V.icon('arrow-right')}<div class="compare-part new"><small>拟变更为</small>${p.type==='assign'?V.techName(p.tech):V.date(p.start)}</div></div><p class="tiny muted mt-sm">用户确认前保留原预约；确认结果通过消息回传。</p></div>`:'')+
  V.section('预约信息',`<div class="kv-grid">${V.kv('服务门店',V.storeName(o.store))}${V.kv('预约项目',A.item(o).name)}${V.kv('预约时段',V.date(o.start)+' — '+V.time(A.end(o)))}${V.kv('安排方式',o.mode==='specified'?'指定技师':'就近安排')}${V.kv('联系人',V.h(o.customer)+' · '+o.phone)}${V.kv('匹配片区',V.h(A.find('stores',o.store).district)+' · 门店覆盖范围')}${V.kv('备注',V.h(o.note||'无特殊备注'),true)}</div>`)+
  V.section('分配与履约事实',`<div class="kv-grid">${V.kv('当前派单轮','第'+o.round+'轮')}${V.kv('本轮固定截止',V.date(o.deadline))}${V.kv('实际开始',V.date(o.startedAt))}${V.kv('实际完成',V.date(o.completedAt))}</div>${o.status==='待分配'?`<div class="notice mt-sm">${V.icon('clock-3')}<span>本轮剩余 ${V.remaining(o.deadline)}。切换候选和重试均不延长期限。</span></div>`:''}`)+
  V.section('付款与退款',V.table(['支付记录','实付','已退','尚未退款'],payments.map(p=>V.tr([p.name,A.money(p.paid),A.money(p.refunded),A.money(p.paid-p.refunded)])),{footer:false})+`<div class="result-box mt-sm between"><span>退款处理中 <strong>${A.money(o.refundPending)}</strong></span><span>已成功退款 <strong>${A.money(o.refund)}</strong></span></div>`)+
  V.section('处理记录',`<div class="timeline">${o.logs.map(l=>`<div class="timeline-item"><small>${V.date(l.at)} · ${V.h(l.actor)}</small>${V.h(l.text)}</div>`).join('')}</div>`),V.btn('关闭详情','close'),true);
}
function showAssign(id){const o=A.find('orders',id);A.check(o);if(o.proposal)throw new Error('当前已有待确认变更。');const candidates=A.state.techs.filter(t=>t.store===o.store);form(o.status==='待分配'?'分配技师':'店内改派',`<div class="notice gray mb">${V.icon('calendar-clock')}<span>${V.no(o)} · ${A.item(o).name} · ${V.date(o.start)}<br>本轮固定截止 ${V.date(o.deadline)}</span></div>${candidates.map(t=>{const reason=A.techReason(t,o);return `<label class="choice ${reason?'disabled':''}"><input type="radio" name="tech" value="${t.id}" ${reason?'disabled':''} ${!reason&&t.id===o.tech?'checked':''}><span class="avatar ${t.gender==='女'?'green':''}">${t.name[0]}</span><span class="grow"><span class="choice-title">${t.name} ${t.id===o.tech?'<span class="tiny muted">原预约技师</span>':''}</span><span class="choice-meta block">${t.skills.map(id=>A.find('items',id).name).join(' / ')} · ${t.rating}</span></span>${V.badge(reason||'时段可用',reason?'':'good')}</label>`;}).join('')}<p class="tiny muted mt">${o.mode==='specified'?'更换指定技师需用户确认；仍分配原技师可直接确认。':'就近安排可在本店内更换符合条件的技师，分配后直接确认。'}</p>`,'assign',{order:id},'确认分配');}
function showReschedule(id){const o=A.find('orders',id);A.check(o);form('提出改约',`<div class="result-box mb">原约：${V.date(o.start)} · ${V.techName(o.tech)}<br>同店、同价；用户接受后才更改预约。</div><div class="form-grid">${V.field('建议新时间','start','2026-10-03T14:00','datetime-local','至少2小时后，首次支付7天内',true)}${V.textarea('改约原因','reason')}</div>`,'reschedule',{order:id},'发送给用户');}
function showCase(id){const c=A.find('cases',id),o=A.find('orders',c?.order);A.check(o);const p=c.plan,isHq=A.state.session.role==='hq',canHandle=c.status==='待门店处理'&&!isHq||c.status==='集团介入中'&&isHq;ui.dialog={type:'case',id};overlay(`售后详情 <small>${c.id} · ${V.no(o)}</small>`,`<div class="detail-summary between"><div><h3>${c.type}</h3><p class="small muted">${o.customer} · ${A.item(o).name} · ${V.storeName(o.store)}</p></div>${V.badge(c.status)}</div>`+V.section('用户诉求',`<p class="small">${V.h(c.reason)}</p><div class="mt-sm">${V.table(['支付记录','实付','申请退款','已成功退'],o.payments.map(x=>V.tr([x.name,A.money(x.paid),A.money(x.request),A.money(x.refunded)])),{footer:false})}</div>`)+
  (p?V.section('当前处理方案',`<div class="result-box">${p.kind==='reject'?'驳回申请':`协商退款总额 <strong>${A.money(p.total)}</strong>`}<br>${V.h(p.reason)}</div>${p.kind==='refund'?V.table(['分笔支付','固定退款金额','执行结果'],p.lines.map(l=>V.tr([l.name,A.money(l.amount),V.badge(l.status)])),{footer:false}):''}`):'')+
  V.section('处理时限',`<div class="kv-grid">${V.kv('当前截止',V.date(c.deadline))}${V.kv('处理范围',isHq?'集团裁决':'本店售后处理')}</div>`)+
  `<div class="notice gray mt">${V.icon('info')}<span>${isHq?'集团裁决后生成退款执行记录。到账结果与裁决状态分别追踪。':'主单与加时按申请额比例分配，用户接受后固定分笔金额。'}</span></div>`,V.btn('关闭','close')+(canHandle?V.btn('驳回申请','case-edit',{id,type:'reject'})+V.btn(isHq?'裁决退款':'制定退款方案','case-edit',{id,type:'refund'},'primary'):'')+(['退款处理中','退款待处理'].includes(c.status)?V.btn('查询 / 重试退款','case-refund',{id},'primary'):''),true);}
function showCaseEdit(id,type){const c=A.find('cases',id),o=A.find('orders',c.order);const amount=o.payments.reduce((a,x)=>a+x.request,0);form(type==='reject'?'驳回售后申请':'制定退款方案',`<div class="notice gray mb">${V.icon('receipt')}<span>申请总额 ${A.money(amount)}。按主单与加时申请比例拆分到分，确认后固定。</span></div><div class="form-grid">${type==='refund'?V.field('协商退款总额（元）','amount',(amount/100).toFixed(2),'number','可填写0至'+(amount/100).toFixed(2)+'元',true):''}${V.textarea(type==='reject'?'驳回理由（必填）':'处理说明','reason')}</div>${type==='refund'?'<div class="result-box mt" id="refund-preview">输入金额后预览分笔金额</div>':''}`,'case-plan',{id,action:type},type==='reject'?'提交驳回':'提交处理方案');refundPreview(id);}
function refundPreview(id){const input=document.querySelector('#dialog-form [name=amount]'),box=document.getElementById('refund-preview');if(!input||!box)return;try{const lines=A.split(Math.round(Number(input.value)*100),A.find('orders',A.find('cases',id).order).payments);box.innerHTML=lines.map(l=>`${V.h(l.name)}：<strong>${A.money(l.amount)}</strong>`).join('<br>');}catch(e){box.textContent=e.message;}}
function showLeave(id){const l=A.find('leaves',id);A.check(l);const affected=A.state.orders.filter(o=>o.tech===l.tech&&o.start<l.end&&A.end(o)>l.start&&!['已取消','已关闭'].includes(o.status));form('请假审批',`<div class="kv-grid mb">${V.kv('申请人',V.techName(l.tech))}${V.kv('请假类型',l.type)}${V.kv('完整时段',V.date(l.start)+' — '+V.date(l.end),true)}${V.kv('申请原因',V.h(l.reason),true)}</div>${V.section('受影响预约',V.table(['预约','预约时段','当前状态','批准后'],affected.map(o=>V.tr([V.no(o),V.date(o.start),V.badge(o.status),l.type==='普通请假'?'需先协调处理':o.status==='已确认'&&!o.departed?'进入待分配池':'保持当前事实'])),{footer:false}))}<div class="notice mt">${V.icon('info')}<span>普通请假先协调重叠预约；紧急请假只重派本人已确认且未开始履约的预约。正在服务和已完成的事实保持。</span></div>${l.status==='待审批'?`<div class="form-grid mt">${V.selectField('审批结果','decision',['批准','驳回'],'批准')}${V.textarea('审批说明（驳回时必填）','reason')}</div>`:`<div class="result-box mt">已处理：${l.status}</div>`}`,'leave',{id},l.status==='待审批'?'提交审批':'确认',true);if(l.status!=='待审批')document.querySelector('.overlay-footer').innerHTML=V.btn('关闭','close');}
function showSafety(id){const s=A.find('safety',id);A.check(s);const o=A.find('orders',s.order);ui.dialog={type:'safety',id};overlay(`安全事件 <small>${s.id} · ${V.no(o)}</small>`,`<div class="notice red mb">${V.icon('shield-alert')}<span>${V.h(s.reason)}</span></div><div class="kv-grid">${V.kv('事件状态',V.badge(s.status))}${V.kv('预约状态',V.badge(A.displayStatus(o)))}${V.kv('发起时间',V.date(s.created))}${V.kv('当前处理人',V.h(s.handler))}${V.kv('联系信息','用户 '+o.phone+'；技师由受控联系通道接通',true)}</div>${V.section('响应流程',`<div class="timeline"><div class="timeline-item"><small>${V.date(s.created)}</small>通知门店和集团值班人员</div><div class="timeline-item"><small>3分钟仍无人确认</small>升级集团安全负责人</div><div class="timeline-item"><small>再过3分钟仍无人确认</small>标记无人响应，保留直接报警入口</div></div>`)}${s.result?V.section('处理结果',`<div class="result-box">${V.h(s.result)}<br>${s.unresolved?'仍有服务争议，继续客服处理':'已核实无未解争议'}</div>`):''}`,V.btn('关闭','close')+(s.status==='已结案'?'':s.status==='处理中'?V.btn('记录结果并结案','safety-close',{id},'primary'):V.btn('确认接报','safety-claim',{id},'primary')),true);}
function reviewControls(){ui.dialog={type:'review'};const pending=A.orders().filter(o=>o.proposal),cs=A.state.cases.filter(c=>A.visible(A.find('orders',c.order))&&c.status==='待用户确认');overlay('演示设置',`<div class="notice gray mb">${V.icon('flask-conical')}<span>用于核验时限和跨端结果。所有操作只更新当前浏览器的示例记录。</span></div><div class="between mb"><span class="small">演示时间 ${V.date(A.state.now)}</span>${V.badge('本地数据')}</div><div class="scenario-grid">${V.btn('+ 10分钟','advance',{minutes:10})}${V.btn('+ 30分钟','advance',{minutes:30})}${V.btn('加载状态','view-state',{value:'loading'})}${V.btn('空数据状态','view-state',{value:'empty'})}${V.btn('网络错误状态','view-state',{value:'error'})}${V.btn('无权限状态','view-state',{value:'denied'})}</div>${pending.length?V.section('模拟用户确认',pending.map(o=>`<div class="result-box mt-sm"><p>${V.no(o)} · ${o.proposal.type==='assign'?'指定改派':'门店改约'}</p><div class="flexrow mt-sm">${V.btn('用户接受','decision',{order:o.id,accept:'yes'},'small-btn')}${V.btn('用户拒绝','decision',{order:o.id,accept:'no'},'small-btn')}</div></div>`).join('')):''}${cs.length?V.section('模拟售后确认',cs.map(c=>`<div class="result-box"><p>${c.id}</p><div class="flexrow mt-sm">${V.btn('接受方案','case-decision',{id:c.id,accept:'yes'},'small-btn')}${V.btn('申请集团介入','case-decision',{id:c.id,accept:'no'},'small-btn')}</div></div>`).join('')):''}${A.orders().some(o=>o.refundPending>0&&!A.state.cases.some(c=>c.order===o.id&&c.plan))?V.section('模拟退款通知',A.orders().filter(o=>o.refundPending>0&&!A.state.cases.some(c=>c.order===o.id&&c.plan)).map(o=>`<div class="between result-box mt-sm"><span>${V.no(o)} · ${A.money(o.refundPending)}</span>${V.btn('退款到账','refund-result',{order:o.id},'small-btn')}</div>`).join('')):''}`,V.btn('操作日志','audit')+V.btn('恢复初始数据','reset-confirm')+V.btn('关闭','close'));}
function showGeneric(action,id,day){
  if(action==='profile'){overlay('当前演示账号',`<div class="kv-grid">${V.kv('账号',A.actor())}${V.kv('数据范围',A.state.session.role==='hq'?'全集团演示权限':'仅幸福里门店')}</div><div class="notice gray mt">${V.icon('info')}<span>本稿演示业务流程，正式系统仍需按规划接入服务端认证与权限校验。</span></div>`,V.btn('退出演示账号','logout')+V.btn('关闭','close'));}
  else if(action==='audit'){const rows=A.state.audit.filter(r=>A.state.session.role==='hq'||r.store==='s1');overlay('操作记录',V.table(['时间','操作人','内容 / 关联记录'],rows.map(r=>V.tr([V.date(r.at),V.h(r.actor),`${V.h(r.text)}<small>${V.h(r.id)}</small>`])),{footer:false}),V.btn('关闭','close'),true);}
  else if(action==='duty')form('编辑值班安排',V.field('值班人员','value',A.state.duty,'text','门店与集团至少各一名值班人员',true),'duty');
  else if(action==='promoter-add')form('邀请推广员',`<div class="notice gray mb">${V.icon('user-plus')}<span>邀请后需本人签署推广协议并完成实名，才会生效。</span></div>${V.field('推广员姓名','name','','text','演示中仅创建待签约记录',true)}`,'promoter-add',{},'发送邀请');
  else if(action==='promoter'){const p=A.find('promoters',id);if(p.store)A.check(p);form('推广员管理',`<div class="kv-grid mb">${V.kv('姓名',V.h(p.name))}${V.kv('归属',V.storeName(p.store))}${V.kv('绑定客户',p.customers+'人')}${V.kv('当前状态',V.badge(p.status))}</div>${V.selectField('更新状态','status',['有效','停用','待签约'],p.status)}`,'generic-update',{id,collection:'promoters',description:'更新推广员状态'});}
  else if(action==='invoice'){const i=A.find('invoices',id);A.check(i);const o=A.find('orders',i.order);form('发票处理',`<div class="result-box mb">${V.h(i.title)}<br>净可开票：<strong>${A.money(o.paid-o.refund)}</strong><br>当前状态：${i.status}</div><div class="form-grid">${V.selectField('处理方式','status',i.status==='待红冲'?['已红冲']:['已开票','已驳回'],i.status==='待红冲'?'已红冲':'已开票')}${V.textarea('处理说明','note')}</div><label class="file-label mt">${V.icon('upload')} 选择发票或红冲凭证<input type="file" name="file" accept=".pdf,.png,.jpg,.jpeg" aria-label="发票文件"></label>`,'invoice',{id},'保存处理结果');}
  else if(action==='paid-tech')form('登记提成发放',`<div class="result-box mb">技师：${V.techName(id)}<br>按已完成预约台账登记线下发放凭证。</div>${V.field('发放凭证编号','proof','','text','必填；本原型不发起真实打款',true)}`,'paid-tech',{tech:id},'标记已发放');
  else if(action==='catalog-edit'){const i=A.find('items',id);form('编辑项目价格',`<div class="form-grid">${V.field('项目名称','name',i.name)}${V.field('日间总价（元）','price',(i.price/100).toFixed(2),'number')}${V.field('21:00起总价（元）','night',(i.night/100).toFixed(2),'number')}${V.field('加时30分钟（元）','overtime',(i.overtime/100).toFixed(2),'number')}${V.selectField('上架状态','status',['已上架','已下架'],i.status)}</div><div class="notice gray mt">${V.icon('info')}<span>已有预约保持原有项目和价格快照。</span></div>`,'catalog',{id},'保存新价格');}
  else if(action==='store-detail'){const s=A.find('stores',id);const hasTech=A.state.techs.some(t=>t.store===id&&t.status==='在岗');overlay('门店详情',`<div class="kv-grid">${V.kv('名称',s.name)}${V.kv('状态',V.badge(s.status))}${V.kv('类型',s.type)}${V.kv('子商户',s.merchant)}${V.kv('分账授权',s.authorized?'已授权':'未授权')}${V.kv('可接单技师',hasTech?'已有在岗技师':'尚无审核通过的技师')}${s.suspension?V.kv('暂停安排',V.date(s.suspension.start)+' 至 '+V.date(s.suspension.end),true):''}</div><div class="notice gray mt">${V.icon('clipboard-check')}<span>上线须完成子商户、分账授权和营业配置，且至少有一名在岗并有有效保单的技师。</span></div>`,V.btn('关闭','close')+V.btn('编辑资料','store-edit',{id})+(s.status==='待上线审核'?V.btn('审核上线','store-approve',{id},'primary'):V.btn('营业状态','pause-store',{id})));}
  else if(action==='store-edit'){const s=A.find('stores',id);form('编辑门店资料',`<div class="form-grid">${V.field('门店名称','name',s.name)}${V.field('服务半径（公里）','radius',s.radius,'number')}${V.field('营业时间','open',s.open,'text','例如09:00–23:00')}${V.field('门店地址','address',s.address)}</div>`,'store-edit',{id});}
  else if(action==='pause-store'){const s=A.find('stores',id);const os=A.state.orders.filter(o=>o.store===id&&['待分配','已确认'].includes(o.status));form('营业时段调整',`<div class="notice mb">${V.icon('info')}<span>门店须提前24小时设置暂停；集团可立即设置。下方为全部未开始预约，重叠预约须逐笔改约或全退。</span></div>${V.table(['受影响预约','客户','预约时间'],os.map(o=>V.tr([V.no(o),o.customer,V.date(o.start)])),{footer:false})}<div class="form-grid mt">${V.selectField('营业状态','status',['营业中','暂停营业'],s.suspension?'营业中':'暂停营业')}${V.field('暂停开始','start','2026-10-03T12:00','datetime-local')}${V.field('暂停结束','end','2026-10-04T23:00','datetime-local')}${V.textarea('原因','reason')}</div>`,'pause-store',{id},'保存暂停安排');}
  else if(action==='tech'){const t=A.find('techs',id);form('技师档案 / 审核',`<div class="kv-grid mb">${V.kv('技师',t.name)}${V.kv('门店',V.storeName(t.store))}${V.kv('证书',V.h(t.certificate||'待补充'))}${V.kv('保单有效至',t.insurance)}</div><div class="form-grid">${V.field('证书编号','certificate',t.certificate||'')}${V.field('保单有效至','insurance',t.insurance,'date')}${V.selectField('项目资格','skills',['全部项目','舒缓放松','肩颈舒缓'],t.skills.length===2?'全部项目':t.skills[0]==='neck'?'肩颈舒缓':'舒缓放松')}${V.selectField('审核结果 / 状态','status',['在岗','资料审核','请假','停单','离职'],t.status)}${V.textarea('审核说明','note')}</div><div class="notice gray mt">${V.icon('shield-check')}<span>状态调整会先检查受影响预约；已开始和已完成的预约保持事实。</span></div>`,'tech',{id},'保存审核结果');}
  else if(action==='edit-shift'){const t=A.find('techs',id||'t1'),date=day||A.day(A.state.now);form('编辑指定日期排班',`<div class="form-grid">${V.selectField('技师','tech',A.state.techs.filter(t=>t.store==='s1').map(t=>t.name),t.name)}${V.field('排班日期','date',date,'date')}${V.field('排班时间','shift',A.shiftAt(t,date)==='请假'?'09:00–23:00':A.shiftAt(t,date),'text','格式09:00–23:00；保存时核对现有预约')}</div>`,'shift',{},'保存排班');}
  else if(action==='review'){const r=A.find('reviews',id);A.check(r);const hq=A.state.session.role==='hq';form(hq?'评价申诉终审':'评价申诉初审',`<div class="result-box mb">评价：${V.h(r.content)}<br>技师说明：${V.h(r.appeal||'无申诉')}<br>状态：${r.status}</div>${V.selectField('处理结果','status',hq?['已隐藏','显示中']:['集团终审'],hq?'已隐藏':'集团终审')}${V.textarea('处理依据','result',r.result)}`,'review',{id},hq?'提交终审':'提交集团');}
  else if(action==='sharing'){const o=A.find('orders',id);overlay('分账处理',`<div class="kv-grid">${V.kv('预约号',V.no(o))}${V.kv('门店',V.storeName(o.store))}${V.kv('净实付',A.money(o.paid-o.refund))}${V.kv('集团抽成预估',A.money(Math.floor((o.paid-o.refund)*o.ruleSnapshot.hqRate/100)))}${V.kv('当前状态',V.badge(A.shareBlock(o)||o.sharing||'待结算'))}${V.kv('操作方式','查询原渠道单号，确认结果后重试')}</div><div class="notice gray mt">${V.icon('info')}<span>${A.shareBlock(o)?A.shareBlock(o)+'，解除前不执行普通分账。':'重试沿用原交易单号，本原型模拟渠道最终成功结果。'}</span></div>`,V.btn('关闭','close')+(!A.shareBlock(o)&&o.sharing!=='已分账'?V.btn('查询并重试','share',{order:id},'primary'):''));}
  else if(action==='recovery'){const r=A.find('recoveries',id);form('登记回款',`<div class="result-box mb">${r.type} · ${V.storeName(r.store)}<br>应收 ${A.money(r.amount)}，已回款 ${A.money(r.returned)}</div>${V.field('本次回款金额（元）','amount',((r.amount-r.returned)/100).toFixed(2),'number')}${V.field('回款凭证','proof','','text','填写核对依据')}`,'recovery',{id},'登记回款');}
  else if(action==='withdrawal'){const w=A.find('withdrawals',id);form('查询提现结果',`<div class="kv-grid mb">${V.kv('申请人',w.name)}${V.kv('金额',A.money(w.amount))}${V.kv('渠道状态',V.badge(w.status))}${V.kv('当日计次',w.count+' / 3')}</div>${V.selectField('模拟渠道最终结果','status',['成功','已撤销'].includes(w.status)?[w.status]:['成功','失败待处理','已撤销'],w.status==='已撤销'?'已撤销':'成功')}<div class="notice gray mt">${V.icon('info')}<span>失败和撤销仍占创建当天次数，结果查询不新建申请。</span></div>`,'withdrawal',{id},'更新查询结果');}
  else if(action==='user'){const u=A.find('users',id);form('用户限制处理',`<div class="result-box mb">${u.name} · ${u.phone}<br>来源：${V.h(u.reason||'无待处理限制申请')}</div>${V.selectField('审核结果','status',['正常','限制下单30天','已拉黑'],u.status==='正常'?'正常':'限制下单30天')}${V.textarea('处理依据','reason',u.reason)}`,'generic-update',{id,collection:'users',description:'更新用户限制处理'});}
  else if(action==='account'){const a=A.find('accounts',id);form('账号授权详情',`<div class="kv-grid mb">${V.kv('账号',a.name)}${V.kv('数据范围',a.scope)}</div><div class="form-grid">${V.selectField('角色','role',a.scope==='集团'?['集团运营','集团财务','集团客服','安全负责人']:['店长','门店财务'],a.role)}${V.selectField('账号状态','status',['启用','停用'],a.status)}</div><div class="notice gray mt">${V.icon('lock-keyhole')}<span>角色调整保留原组织范围，所有变更写入操作记录。</span></div>`,'generic-update',{id,collection:'accounts',description:'更新账号授权'});}
  else if(action==='import-tech')form('导入结业名单',`<p class="small muted mb">粘贴姓名，每行一名，创建江宁门店的待审核档案。证书与保单在档案审核中补齐。</p>${V.textarea('技师姓名（一行一名）','names')}`,'import-tech',{},'导入待审核档案');
  else throw new Error('页面操作尚未识别：'+action);
}
function execute(type,p={},next){A.command(type,p);render();if(next)next();else close();toast('操作已保存');}
document.addEventListener('click',e=>{const target=e.target.closest('[data-action]');if(!target)return;const d=target.dataset;try{
  switch(d.action){
    case 'login':A.command('login',{role:d.role});route();render();break;
    case 'logout':A.command('logout');close();render();break;
    case 'menu':ui.menuOpen=!ui.menuOpen;render();break;
    case 'go':close();route(d.page);break;
    case 'home':close();route();break;
    case 'close':close();break;
    case 'refresh':render();toast('已刷新当前演示记录');break;
    case 'retry':ui.state='normal';render();break;
    case 'clear-filter':ui.search='';ui.tab='全部';ui.storeFilter='';render();break;
    case 'tab':ui.tab=d.value;ui.state='normal';render();break;
    case 'order':showOrder(d.id);break;
    case 'assign':showAssign(d.id);break;
    case 'reschedule':showReschedule(d.id);break;
    case 'cancel':form('取消预约',V.textarea('门店取消原因（必填）','reason')+`<div class="notice mt">${V.icon('info')}<span>按门店原因取消，生成全额退款；到账前显示退款处理中。</span></div>`,'cancel',{order:d.id},'确认取消并退款');break;
    case 'case':showCase(d.id);break;
    case 'case-edit':showCaseEdit(d.id,d.type);break;
    case 'case-refund':form('退款执行结果',`<p class="small muted mb">按已确认金额执行原分笔退款，不重新分配金额。</p>${V.selectField('模拟渠道返回','result',['全部成功','第二笔失败'],'全部成功')}`,'case-refund',{id:d.id},'查询 / 重试');break;
    case 'leave':showLeave(d.id);break;
    case 'safety':showSafety(d.id);break;
    case 'safety-claim':execute('safety-claim',{id:d.id},()=>showSafety(d.id));break;
    case 'safety-close':form('记录结果并结案',V.textarea('处理结果（必填）','result')+`<label class="checkline"><input type="checkbox" name="unresolved">仍有未解决的服务争议，继续客服处理</label>`,'safety-close',{id:d.id},'确认结案');break;
    case 'share':execute('share',{order:d.order},()=>showGeneric('sharing',d.order));break;
    case 'review-controls':reviewControls();break;
    case 'advance':execute('advance',{minutes:d.minutes},reviewControls);break;
    case 'decision':execute('decision',{order:d.order,accept:d.accept==='yes'},()=>showOrder(d.order));break;
    case 'case-decision':execute('case-decision',{id:d.id,accept:d.accept==='yes'},()=>showCase(d.id));break;
    case 'refund-result':execute('refund-result',{order:d.order,success:true},()=>showOrder(d.order));break;
    case 'view-state':ui.state=d.value;close();render();break;
    case 'reset-confirm':form('恢复初始演示数据','<p class="small">当前浏览器的演示操作将恢复为初始样例。继续使用当前账号。</p>','reset',{},'恢复初始数据');break;
    case 'store-approve':{const s=A.find('stores',d.id),valid=A.state.techs.some(t=>t.store===s.id&&t.status==='在岗'&&Date.parse(t.insurance+'T23:59:59+08:00')>A.state.now);if(!s.authorized||!valid)throw new Error('尚未满足上线条件：需要有效授权及至少一名已审核在岗技师。');execute('update',{collection:'stores',id:d.id,values:{status:'营业中'},description:'门店审核上线'},()=>showGeneric('store-detail',d.id));break;}
    case 'export':{const rows=[...document.querySelectorAll('#main table tr')].map(row=>[...row.querySelectorAll('th,td')].map(c=>{let text=c.innerText.replace(/\n/g,' ');if(/^[=+@-]/.test(text))text="'"+text;return '"'+text.replace(/"/g,'""')+'"';}).join(','));if(!rows.length)throw new Error('当前页面没有可导出的明细。');const blob=new Blob(['\ufeff'+rows.join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='天俪-'+title()+'-20261002.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);A.audit('导出当前授权范围的'+title());A.save();toast('已导出当前筛选的记录');break;}
    default:showGeneric(d.action,d.id,d.day);
  }
}catch(error){A.save();toast(error.message);}});
document.addEventListener('submit',e=>{const formEl=e.target.closest('form[data-submit]');if(!formEl)return;e.preventDefault();const data=Object.fromEntries(new FormData(formEl)),type=formEl.dataset.submit;const error=formEl.querySelector('.form-error');if(error)error.textContent='';try{
  if(type==='search'){ui.search=data.keyword||'';ui.storeFilter=data.store||'';render();return;}
  if(type==='assign'){execute(type,{order:data.order,tech:data.tech},()=>showOrder(data.order));}
  else if(type==='reschedule'){if(!data.reason?.trim())throw new Error('请填写改约原因。');execute(type,{...data,start:data.start+':00+08:00'},()=>showOrder(data.order));}
  else if(type==='cancel'){execute(type,data,()=>showOrder(data.order));}
  else if(type==='case-plan'){execute(type,{...data,amount:Math.round(Number(data.amount||0)*100)},()=>showCase(data.id));}
  else if(type==='case-refund'){execute(type,{id:data.id,failSecond:data.result==='第二笔失败'},()=>showCase(data.id));}
  else if(type==='leave'){execute(type,{...data,accept:data.decision==='批准'});}
  else if(type==='safety-close'){execute(type,{...data,unresolved:data.unresolved==='on'},()=>showSafety(data.id));}
  else if(type==='rules'){execute('rules',{values:data});}
  else if(type==='reset'){execute('reset',{},reviewControls);}
  else if(type==='duty'||type==='paid-tech'){execute(type,data);}
  else if(type==='promoter-add'){execute('add-promoter',data);}
  else if(type==='catalog'){if(!data.name.trim()||![data.price,data.night,data.overtime].every(v=>Number(v)>0))throw new Error('项目名称与价格需有效填写。');execute('update',{collection:'items',id:data.id,values:{name:data.name,price:Math.round(Number(data.price)*100),night:Math.round(Number(data.night)*100),overtime:Math.round(Number(data.overtime)*100),status:data.status},description:'发布项目新价格'});}
  else if(type==='generic-update'){const {id,collection,description,...values}=data;if(collection==='users'&&!values.reason?.trim()&&values.status!=='正常')throw new Error('请填写限制处理依据。');execute('update',{collection,id,values,description});}
  else if(type==='invoice'){const file=data.file;if(['已开票','已红冲'].includes(data.status)&&(!file||!file.name))throw new Error('请选择发票或红冲凭证。');if(data.status==='已驳回'&&!data.note?.trim())throw new Error('请填写驳回原因。');execute('update',{collection:'invoices',id:data.id,values:{status:data.status,file:file?.name||null,note:data.note},description:'处理发票 '+data.status});}
  else if(type==='review'){if(!data.result?.trim())throw new Error('请填写处理依据。');execute('update',{collection:'reviews',id:data.id,values:{status:data.status,result:data.result},description:'评价申诉审核'});}
  else if(type==='recovery'){const r=A.find('recoveries',data.id),amount=Math.round(Number(data.amount)*100);if(!amount||amount<0||amount>r.amount-r.returned)throw new Error('回款金额需大于0且不超剩余应收。');if(!data.proof.trim())throw new Error('请填写回款凭证。');execute('update',{collection:'recoveries',id:r.id,values:{returned:r.returned+amount,status:r.returned+amount===r.amount?'已结清':'部分回款',proof:data.proof},description:'登记追偿回款'});}
  else if(type==='withdrawal'){execute('update',{collection:'withdrawals',id:data.id,values:{status:data.status},description:'查询提现最终结果'});}
  else if(type==='store-edit'||type==='pause-store'||type==='shift'||type==='tech'||type==='import-tech'){execute(type,data);}
  else throw new Error('未识别的表单。');
}catch(err){A.save();if(error){error.textContent=err.message;error.scrollIntoView({block:'nearest'});}else toast(err.message);}});
document.addEventListener('input',e=>{if(e.target.matches('#dialog-form [name=amount]')&&ui.dialog?.type==='case-plan')refundPreview(ui.dialog.id);});
document.addEventListener('change',e=>{if(e.target.id==='role-switch'){A.command('login',{role:e.target.value});close();route();render();}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){close();return;}if(e.key==='Tab'&&document.querySelector('[role=dialog]')){const items=[...document.querySelectorAll('#overlay button,#overlay input:not([type=hidden]),#overlay select,#overlay textarea')].filter(el=>!el.disabled&&el.offsetParent!==null);if(!items.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
window.addEventListener('hashchange',()=>{close();readRoute();});
readRoute();
