'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'H:/connextes/edu-plate/node_modules/playwright');
const base=process.env.PROTOTYPE_URL||'http://127.0.0.1:4186/';
const out=path.join(__dirname,'verification');fs.mkdirSync(out,{recursive:true});
const report={started:new Date().toISOString(),base,renders:[],checks:[],screenshots:[],errors:[]};
const browserErrors=[];
let browser,p;
const check=(name,value)=>{assert.ok(value,name);report.checks.push(name);};
const state=()=>p.evaluate(()=>JSON.parse(JSON.stringify(Admin.state)));
const action=(name,id,scope='')=>p.locator(`${scope}[data-action="${name}"]${id?`[data-id="${id}"]`:''}:not([disabled])`).first();
const submit=()=>p.locator('button[form="dialog-form"][type="submit"]').click();
const close=async()=>{if(await p.locator('[role=dialog]').count())await p.keyboard.press('Escape');};
async function go(role,id){await close();await p.goto(base+`#/${role}/${id}`);await p.waitForFunction(({role,id})=>typeof Admin!=='undefined'&&Admin.state.session?.role===role&&ui.page===id,{role,id});await p.locator('#main h1').waitFor();}
async function selectRole(role){await close();await p.locator('#role-switch').selectOption(role);await p.waitForFunction(role=>Admin.state.session.role===role&&ui.page==='dashboard',role);}
async function reset(role='store'){await close();await action('review-controls').click();await action('reset-confirm').click();await submit();await close();if((await state()).session.role!==role)await selectRole(role);await go(role,'dashboard');}
async function screen(name){await p.evaluate(async()=>{clearTimeout(toastTimer);document.getElementById('toast').classList.remove('show');document.getElementById('toast').style.visibility='hidden';if(!document.querySelector('[role=dialog]'))scrollTo(0,0);await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);});await p.screenshot({path:path.join(out,name+'.png'),fullPage:!(await p.locator('[role=dialog]').count())});await p.evaluate(()=>document.getElementById('toast').style.visibility='');report.screenshots.push(name+'.png');}
async function bounds(label){const findings=await p.evaluate(()=>{const errors=[];if(document.documentElement.scrollWidth>innerWidth+1)errors.push('body overflow '+document.documentElement.scrollWidth+'/'+innerWidth);for(const el of document.querySelectorAll('.btn,.icon-btn,.shift-block,.badge')){const r=el.getBoundingClientRect();if(!r.width||!r.height||r.bottom<0||r.top>innerHeight||el.closest('.sidebar')&&innerWidth<=760)continue;const scroll=el.closest('.table-wrap,.tabs');if(scroll)continue;const dialog=el.closest('[role=dialog]');if(document.querySelector('[role=dialog]')&&!dialog)continue;const parent=el.parentElement.getBoundingClientRect();if(r.left<parent.left-1||r.right>parent.right+1)errors.push('parent bounds: '+el.textContent.trim());const content=el.querySelector('.control-label');if(content){const q=content.getBoundingClientRect();if(q.width>r.width+1||q.height>r.height+1||Math.abs(q.left+q.width/2-r.left-r.width/2)>1.5||Math.abs(q.top+q.height/2-r.top-r.height/2)>1.5)errors.push('alignment: '+el.textContent.trim());}}return errors;});assert.deepEqual(findings,[],label+': '+findings.join('; '));}
async function order(id){await go((await state()).session.role,'orders');await action('order',id).click();}
async function reviewDecision(name,attrs){await close();await action('review-controls').click();await p.locator(`[data-action="${name}"]${attrs}`).click();}
async function test(name,fn){await fn();console.log('PASS '+name);}
(async()=>{
 browser=await chromium.launch({executablePath:process.env.BROWSER_PATH||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
 p=await browser.newPage({viewport:{width:1440,height:900},acceptDownloads:true});p.setDefaultTimeout(8000);
 p.on('pageerror',e=>browserErrors.push(e.message));p.on('console',m=>{if(m.type()==='error')browserErrors.push(m.text());});
 p.on('response',r=>{if(r.status()>=400)browserErrors.push(r.status()+' '+r.url());});
 await p.goto(base);await p.locator('[data-action=login][data-role=store]').waitFor();await screen('login');await action('login',null,'[data-role=store]').click();await p.locator('#main').waitFor();
 await test('27个业务路由与四种窗口宽度',async()=>{
  const menus=await p.evaluate(()=>AdminData.menus);
  for(const role of ['store','hq']){if((await state()).session.role!==role)await selectRole(role);for(const width of [1440,1280,1024,390]){await p.setViewportSize({width,height:900});for(const id of ['dashboard',...menus[role].map(m=>m[0]),...(role==='hq'?['orders']:[])]){await go(role,id);check(`页面 ${role}/${id} @${width}`,!(await p.locator('#main').innerText()).includes('页面不存在'));await bounds(role+'/'+id+' '+width);report.renders.push({role,page:id,width});if(width===1440&&['dashboard','orders','schedule','sharing','analytics'].includes(id)||width===390&&['dashboard','schedule'].includes(id))await screen(`${role}-${id}-${width}`);}}}
  check('页面运行无控制台或资源错误',browserErrors.length===0);
 });
 await p.setViewportSize({width:1440,height:900});
 await test('门店隔离、搜索、导出',async()=>{
  await reset();await go('store','orders');check('门店仅8条本店预约',(await p.locator('#main tbody tr').count())===8);check('河西订单不可见',!(await p.locator('#main').innerText()).includes('1007'));
  await p.getByLabel('搜索关键词').fill('李先生');await p.locator('form[data-submit=search] button[type=submit]').click();check('搜索结果单条',await p.locator('#main tbody tr').count()===1);
  const downloadPromise=p.waitForEvent('download');await action('export').click();const d=await downloadPromise;check('导出CSV',d.suggestedFilename().endsWith('.csv'));await d.saveAs(path.join(out,'filtered-orders.csv'));const csv=fs.readFileSync(path.join(out,'filtered-orders.csv'),'utf8');check('导出仅当前筛选',csv.includes('李先生')&&!csv.includes('王女士'));
  await go('store','sharing');check('门店不能访问集团页面',(await p.locator('#main').innerText()).includes('没有访问权限'));await go('store','dashboard');
 });
 await test('直接派单固定期限，指定改派用户确认',async()=>{
  await reset();const initial=(await state()).orders[0];await go('store','orders');await action('assign','1001').click();await bounds('分配弹窗');await screen('assign-dialog');await submit();let o=(await state()).orders[0];check('分配后直接已确认',o.status==='已确认');check('首次派单截止不变',o.deadline===initial.deadline&&o.round===1);
  await action('assign','1001','#overlay ').click();await p.locator('input[name=tech][value=t2]').check();await submit();o=(await state()).orders[0];check('指定改派先保留原技师',o.tech==='t1'&&o.proposal.tech==='t2');await reviewDecision('decision','[data-order="1001"][data-accept="yes"]');o=(await state()).orders[0];check('用户接受后直接确认新技师',o.tech==='t2'&&o.status==='已确认'&&!o.proposal);check('已确认变更新开一轮',o.round===2&&o.deadline===o.roundStart+1800000);await screen('order-detail');
  await reset();await go('store','orders');await action('assign','1001').click();await p.locator('input[value=t2]').check();await submit();await reviewDecision('decision','[data-order="1001"][data-accept="no"]');o=(await state()).orders[0];check('拒绝指定改派全额退款中',o.status==='已取消'&&o.refundPending===29800&&o.refund===0);
 });
 await test('派单超时自动退款与重复结果保护',async()=>{
  await reset();await action('review-controls').click();await p.locator('[data-action=advance][data-minutes="10"]').click();let o=(await state()).orders[0];check('原期限到即取消',o.status==='已取消'&&o.refundPending===29800);await p.locator('[data-action=refund-result][data-order="1001"]').click();o=(await state()).orders[0];check('退款成功后才计已退',o.refund===29800&&o.refundPending===0);
  const message=await p.evaluate(()=>{try{Admin.command('refund-result',{order:'1001',success:true});return '';}catch(e){return e.message;}});check('重复退款结果不重复累计',message.includes('暂无')&&(await state()).orders[0].refund===29800);
 });
 await test('改约原约保留、接受开新轮、拒绝及超时保留',async()=>{
  await reset();await order('1005');const old=(await state()).orders.find(o=>o.id==='1005');await action('reschedule','1005','#overlay ').click();await p.getByLabel('改约原因').fill('用户希望调整到次日下午');await submit();let o=(await state()).orders.find(o=>o.id==='1005');check('改约提案保持原时间',o.start===old.start&&!!o.proposal);await reviewDecision('decision','[data-order="1005"][data-accept="yes"]');o=(await state()).orders.find(o=>o.id==='1005');check('接受改约生效并待分配',o.start!==old.start&&o.round===2&&o.status==='待分配'&&o.paidAt===old.paidAt);check('新轮期限取较早值',o.deadline===Math.min(o.roundStart+1800000,o.start-3600000));
  for(const kind of ['reject','expire']){await reset();await order('1005');await action('reschedule','1005','#overlay ').click();await p.getByLabel('改约原因').fill('改约演示');await submit();if(kind==='reject')await reviewDecision('decision','[data-order="1005"][data-accept="no"]');else{await close();await action('review-controls').click();await p.locator('[data-action=advance][data-minutes="30"]').click();}o=(await state()).orders.find(o=>o.id==='1005');check('改约'+kind+'原约保持',o.start===old.start&&!o.proposal&&o.status==='已确认');}
 });
 await test('请假影响范围与排班占用',async()=>{
  await reset();const before=await state();await go('store','schedule');await action('leave','L1001').click();await screen('leave-impact');await submit();let s=await state();check('紧急请假只重派符合订单',s.orders.find(o=>o.id==='1002').status==='待分配');check('进行中未回退',s.orders.find(o=>o.id==='1003').status==='进行中');check('已完成未回退',s.orders.find(o=>o.id==='1004').status==='已完成');check('其他技师订单不变',s.orders.find(o=>o.id==='1005').status==='已确认');check('无重叠预约不变',s.orders[0].status===before.orders[0].status);const count=s.orders.find(o=>o.id==='1002').round;
  await action('leave','L1001').click();check('已审批不再显示提交',await p.locator('button[form=dialog-form]').count()===0);await close();
  const repeat=await p.evaluate(()=>{try{Admin.command('leave',{id:'L1001',accept:true});return false;}catch{return true;}});check('重复审批不重置派单轮',repeat&&(await state()).orders.find(o=>o.id==='1002').round===count);
  await p.locator('[data-action=edit-shift][data-id=t2][data-day="2026-10-02"]').click();await p.getByLabel('排班时间').fill('09:00–15:00');await submit();check('排班排除已有预约被阻止',(await p.locator('.form-error').innerText()).includes('已有预约'));await p.getByLabel('排班时间').fill('09:00–22:00');await submit();check('合法排班按日期保存',(await state()).techs.find(t=>t.id==='t2').shifts['2026-10-02']==='09:00–22:00');
 });
 await test('协商退款分笔、部分失败、重试与红冲',async()=>{
  await reset();await go('store','aftersales');await action('case','AS1001').click();await p.locator('[data-action=case-edit][data-type=refund]').click();await p.getByLabel('协商退款总额（元）').fill('100');check('到分舍入预览',(await p.locator('#refund-preview').innerText()).includes('66.67')&&(await p.locator('#refund-preview').innerText()).includes('33.33'));await submit();check('方案等待用户确认',(await state()).cases[0].status==='待用户确认');await reviewDecision('case-decision','[data-id=AS1001][data-accept=yes]');await action('case-refund','AS1001').click();await p.getByLabel('模拟渠道返回').selectOption('第二笔失败');await submit();let s=await state(),o=s.orders.find(o=>o.id==='1004');check('部分成功保留准确金额',o.refund===6667&&o.refundPending===3333&&s.cases[0].status==='退款待处理');check('已开发票随退款转待红冲',s.invoices.find(i=>i.id==='FP1002').status==='待红冲');await screen('partial-refund');await action('case-refund','AS1001').click();await submit();s=await state();o=s.orders.find(o=>o.id==='1004');check('重试只执行失败笔',o.refund===10000&&o.refundPending===0&&o.payments[0].refunded===6667&&s.cases[0].status==='已完成');check('退款不覆盖完成事实',o.status==='已完成'&&!!o.completedAt);
  await go('store','invoices');await action('invoice','FP1002').click();await p.getByLabel('发票文件').setInputFiles({name:'红冲凭证.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4 demo receipt')});await submit();check('红冲凭证登记',(await state()).invoices.find(i=>i.id==='FP1002').status==='已红冲');await action('invoice','FP1002').click();await p.getByLabel('发票文件').setInputFiles({name:'重开发票.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4 demo invoice')});await submit();const invoice=(await state()).invoices.find(i=>i.id==='FP1002');check('按新净额重开',invoice.status==='已开票'&&invoice.amount===34700);
 });
 await test('集团裁决与安全结案',async()=>{
  await reset();await go('store','aftersales');await action('case','AS1001').click();await p.locator('[data-action=case-edit][data-type=reject]').click();await p.getByLabel('驳回理由（必填）').fill('门店核实需补充证据');await submit();await reviewDecision('case-decision','[data-id=AS1001][data-accept=no]');check('用户异议转集团',(await state()).cases[0].status==='集团介入中');await selectRole('hq');await go('hq','aftersales');await action('case','AS1001').click();await p.locator('[data-action=case-edit][data-type=refund]').click();await submit();check('集团裁决直接形成执行任务',(await state()).cases[0].status==='退款处理中');
  await reset();await go('store','safety');await action('safety','SOS1001').click();await action('safety-claim','SOS1001').click();await action('safety-close','SOS1001').click();await p.getByLabel('处理结果（必填）').fill('已联系双方核实，继续正常服务，无未解争议。');await submit();let s=await state();check('安全结案恢复事实状态',s.safety[0].status==='已结案'&&!s.safety[0].unresolved&&s.orders.find(o=>o.id==='1003').status==='进行中');check('页面投影恢复进行中',(await p.locator('#overlay').innerText()).includes('进行中'));await screen('safety-closed');
  await reset();await action('review-controls').click();await p.locator('[data-action=advance][data-minutes="10"]').click();check('无人接报自动升级',(await state()).safety[0].status==='无人响应');
 });
 await test('规则校验、价格快照、分账时限',async()=>{
  await reset('hq');await go('hq','rules');await p.getByLabel('集团客户抽成').fill('25');await p.locator('form[data-submit=rules] button[type=submit]').click();check('非法比例不能发布',(await p.locator('.form-error').innerText()).includes('30%')&&(await state()).rules.version===1);await p.getByLabel('集团客户抽成').fill('18');await p.locator('form[data-submit=rules] button[type=submit]').click();check('合法规则发布v2',(await state()).rules.version===2);await go('hq','catalog');await action('catalog-edit','neck').click();await p.getByLabel('日间总价（元）').fill('208');await submit();let s=await state();check('目录新价格已保存',s.items.find(i=>i.id==='neck').price===20800);check('旧预约价格与比例保持快照',s.orders.find(o=>o.id==='1002').itemSnapshot.price===19800&&s.orders[0].ruleSnapshot.hqRate===15);
  await go('hq','sharing');await action('sharing','1004').click();check('阻断订单不显示分账按钮',await p.locator('#overlay [data-action=share]').count()===0);await close();await action('sharing','1008').click();await action('share').click();check('无阻断且售后期满可重试成功',(await state()).orders.find(o=>o.id==='1008').sharing==='已分账');check('成功分账不再显示重试',await p.locator('#overlay [data-action=share]').count()===0);
 });
 await test('门店上线、名单、资料审核、暂停',async()=>{
  await reset('hq');await go('hq','stores');await action('store-detail','s3').click();await action('store-approve','s3').click();check('未就绪门店不能上线',(await state()).stores[2].status==='待上线审核'&&(await p.locator('#toast').innerText()).includes('上线条件'));await go('hq','technicians');await action('tech','t6').click();await p.getByLabel('审核结果 / 状态').selectOption('在岗');await submit();check('技师审核通过',(await state()).techs[5].status==='在岗');await go('hq','stores');await action('store-detail','s3').click();await action('store-approve','s3').click();check('满足条件后门店上线',(await state()).stores[2].status==='营业中');await go('hq','technicians');await action('import-tech').click();await p.getByLabel('技师姓名（一行一名）').fill('钱师傅\n钱师傅\n蒋师傅');await submit();let s=await state();check('名单去重并保留待审',s.techs.length===8&&s.techs[6].status==='资料审核'&&!s.techs[6].certificate);await action('tech','t7').click();await p.getByLabel('审核结果 / 状态').selectOption('在岗');await submit();check('缺证书保单不能通过',(await p.locator('.form-error').innerText()).includes('证书与保单'));
  await reset();await go('store','settings');await action('store-edit','s1').click();await p.getByLabel('服务半径（公里）').fill('6');await submit();check('门店可编辑本店资料',(await state()).stores[0].radius===6);await action('pause-store','s1').click();await p.getByLabel('暂停开始').fill('2026-10-02T12:00');await p.getByLabel('原因',{exact:true}).fill('设备维护');await submit();check('门店暂停需提前24小时',(await p.locator('.form-error').innerText()).includes('24小时'));await p.getByLabel('暂停开始').fill('2026-10-03T12:00');await submit();check('暂停安排保存不取消已有预约',!!(await state()).stores[0].suspension&&(await state()).orders[0].status==='待分配');
 });
 await test('追偿、提现、评价、推广与账号',async()=>{
  await reset('hq');await go('hq','recovery');await action('recovery','RC1001').click();await p.getByLabel('本次回款金额（元）').fill('10');await p.getByLabel('回款凭证').fill('RC-DEMO-01');await submit();check('部分回款准确累计',(await state()).recoveries[0].returned===1000&&(await state()).recoveries[0].status==='部分回款');await action('recovery','RC1001').click();await p.getByLabel('回款凭证').fill('RC-DEMO-02');await submit();check('剩余回款后结清',(await state()).recoveries[0].returned===1470&&(await state()).recoveries[0].status==='已结清');await go('hq','withdrawals');await action('withdrawal','TX1002').click();await submit();check('提现查询不增加次数',(await state()).withdrawals[1].count===3&&(await state()).withdrawals[1].status==='成功');
  await selectRole('store');await go('store','reviews');await action('review','RV1001').click();await p.getByLabel('处理依据').fill('核对沟通记录，提交集团终审');await submit();check('店长初审提交集团',(await state()).reviews[0].status==='集团终审');await selectRole('hq');await go('hq','reviews');await action('review','RV1001').click();await p.getByLabel('处理依据').fill('申诉成立，隐藏争议评价');await submit();check('集团可完成终审',(await state()).reviews[0].status==='已隐藏');await go('hq','promotion');await action('promoter-add').click();await p.getByLabel('推广员姓名').fill('郑推广员');await submit();check('邀请创建待签约记录',(await state()).promoters.at(-1).status==='待签约');await go('hq','accounts');await action('account','A02').click();await p.getByLabel('账号状态').selectOption('停用');await submit();check('账号调整保存',(await state()).accounts.find(a=>a.id==='A02').status==='停用');await go('hq','users');await action('user','U1002').click();await submit();check('用户限制申请完成处理',(await state()).users[1].status==='限制下单30天');
 });
 await test('空、加载、错误、无权限状态与刷新持久化',async()=>{
  await reset();for(const value of ['empty','loading','error','denied']){await action('review-controls').click();await p.locator(`[data-action=view-state][data-value=${value}]`).click();await bounds('通用状态 '+value);await screen('state-'+value);check('状态 '+value,await p.locator('#main').count()===1);await go('store','dashboard');}
  await go('store','orders');await action('assign','1001').click();await submit();await close();await p.reload();await p.locator('#main').waitFor();check('刷新保留演示操作',(await state()).orders[0].status==='已确认');
  await reset();await p.setViewportSize({width:390,height:844});await go('store','orders');await action('assign','1001').click();await bounds('窄屏派单');await screen('assign-mobile');await close();await go('store','rules');await bounds('窄屏表单');await screen('rules-mobile');
 });
 await test('提成快照、发放凭证与退款调整',async()=>{
  await p.setViewportSize({width:1280,height:900});await reset();await go('store','finance');check('含两主预约交通补贴',await p.evaluate(()=>Admin.techAmount('t2')===31800));await action('paid-tech','t2').click();await p.getByLabel('发放凭证编号').fill('PAY-20261002-01');await submit();let s=await state();check('登记发放固定金额和凭证',s.techPayouts[0].amount===31800&&s.techPayouts[0].proof==='PAY-20261002-01');await screen('finance-1280');
  await go('store','rules');await p.getByLabel('技师提成',{exact:true}).fill('45');await p.locator('form[data-submit=rules] button[type=submit]').click();await go('store','orders');await action('assign','1001').click();await submit();s=await state();check('首次派单固定最新提成版本',s.orders[0].techSnapshot.rate===45);check('原已接订单提成保持40%',s.orders.find(o=>o.id==='1005').techSnapshot.rate===40);
  await go('store','aftersales');await action('case','AS1001').click();await p.locator('[data-action=case-edit][data-type=refund]').click();await p.getByLabel('协商退款总额（元）').fill('100');await submit();await reviewDecision('case-decision','[data-id=AS1001][data-accept=yes]');await action('case-refund','AS1001').click();await submit();await go('store','finance');check('退款后保留已付并显示调整差额',(await p.locator('#main').innerText()).includes('退款后待调整')&&await p.evaluate(()=>Admin.techAmount('t2')===27800&&Admin.state.techPayouts[0].amount===31800));
  await p.setViewportSize({width:1024,height:900});await go('store','schedule');await bounds('排班1024');await screen('schedule-1024');
 });
 await test('普通请假不能跳过占用，弹窗在窄屏可操作',async()=>{
  await p.setViewportSize({width:1440,height:900});await reset();await go('store','schedule');await action('leave','L1002').click();await submit();check('普通请假先处理冲突',(await p.locator('.form-error').innerText()).includes('先协调')&&(await state()).leaves[1].status==='待审批');
  await p.setViewportSize({width:390,height:844});await bounds('普通请假窄屏');await screen('leave-mobile');await close();
  const dialogs=[['store','orders','order','1001'],['store','orders','reschedule','1005'],['store','aftersales','case','AS1001'],['store','invoices','invoice','FP1001'],['store','settings','pause-store','s1'],['store','schedule','edit-shift','t1'],['store','reviews','review','RV1001'],['store','safety','safety','SOS1001'],['hq','catalog','catalog-edit','full'],['hq','technicians','tech','t6'],['hq','stores','store-detail','s3'],['hq','withdrawals','withdrawal','TX1001'],['hq','users','user','U1002'],['hq','accounts','account','A01']];
  for(const [role,pageId,act,id]of dialogs){if((await state()).session.role!==role)await selectRole(role);await go(role,pageId);if(act==='reschedule'){await action('order',id).click();await action(act,id,'#overlay ').click();}else await action(act,id).click();await bounds('窄屏弹窗 '+act);check('窄屏弹窗 '+act,await p.locator('[role=dialog]').count()===1);await close();}
 });
 check('全部流程无脚本、控制台和HTTP错误',browserErrors.length===0);
 report.finished=new Date().toISOString();report.summary={routeCount:27,renderChecks:report.renders.length,assertions:report.checks.length,screenshots:report.screenshots.length,browserErrors};fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report.summary));await browser.close();
})().catch(async error=>{report.errors.push(error.stack);report.browserErrors=browserErrors;fs.writeFileSync(path.join(out,'report-failed.json'),JSON.stringify(report,null,2));console.error(error);if(p)await p.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});if(browser)await browser.close();process.exitCode=1;});
