'use strict';
window.View=(()=>{
  const h=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const icon=name=>`<i data-lucide="${h(name)}" aria-hidden="true"></i>`;
  const attrs=data=>Object.entries(data).map(([k,v])=>` data-${k}="${h(v)}"`).join('');
  const btn=(label,action,data={},kind='')=>`<button type="button" class="btn ${kind}" data-action="${action}"${attrs(data)}><span class="control-label">${label}</span></button>`;
  const link=(label,action,data={})=>`<button type="button" class="link" data-action="${action}"${attrs(data)}>${label}</button>`;
  const badge=(label,tone)=>{const color=tone||(/失败|无人|待限制|客服|逾期/.test(label)?'bad':/待|处理中|介入|审核|请假/.test(label)?'warn':/成功|完成|营业中|在岗|有效|启用|已分账|批准/.test(label)?'good':'');return `<span class="badge ${color}">${h(label)}</span>`;};
  const date=(time,full=false)=>{if(!time)return '—';return new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false,...(full?{year:'numeric'}:{})}).format(new Date(time));};
  const time=t=>date(t).split(' ')[1]||date(t);
  const storeName=id=>h(Admin.find('stores',id)?.name||'集团');
  const techName=id=>h(Admin.find('techs',id)?.name||'待安排');
  const no=o=>'TL'+Admin.day(o.paidAt).slice(2).replaceAll('-','')+o.id;
  const remaining=end=>{const m=Math.max(0,Math.ceil((end-Admin.state.now)/60000));return m?m+'分钟':'已到期';};
  const empty=(title='暂无符合条件的记录',description='试试调整筛选条件，或清空关键词。',action='clear-filter')=>`<div class="empty">${icon('inbox')}<h3>${title}</h3><p>${description}</p>${action?btn(action==='home'?'返回工作台':action==='retry'?'重新加载':'重置筛选',action,{},'small-btn'):''}</div>`;
  const table=(headers,rows,options={})=>`<div class="table-wrap"><table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>${!rows.length?empty():''}${options.footer===false?'':`<div class="table-foot"><span>共 ${rows.length} 条记录</span><span class="flexrow">每页 20 条 <b class="page-number">1</b></span></div>`}`;
  const tr=cells=>'<tr>'+cells.map(c=>`<td>${c}</td>`).join('')+'</tr>';
  const metric=(label,value,sub,ico)=>`<div class="metric"><div class="metric-label">${label}${icon(ico)}</div><div class="metric-value">${value}</div><p class="metric-sub">${sub}</p></div>`;
  const head=(title,desc,tools='')=>`<div class="page-head"><div><h1>${title}</h1><p>${desc}</p></div><div class="page-tools">${tools}</div></div>`;
  const panel=(title,body,tools='')=>`<section class="panel"><div class="panel-head"><h2>${title}</h2>${tools}</div>${body}</section>`;
  const section=(title,body)=>`<section class="subsection"><h3>${title}</h3>${body}</section>`;
  const kv=(label,value,full=false)=>`<div class="kv ${full?'full':''}"><label>${label}</label><strong>${value}</strong></div>`;
  const field=(label,name,value='',type='text',hint='',full=false)=>`<div class="field ${full?'full':''}"><label for="f-${name}">${label}</label><input class="input" id="f-${name}" name="${name}" type="${type}" value="${h(value)}" ${type==='number'?'step="0.01" min="0"':''}><small>${hint}</small></div>`;
  const textarea=(label,name,value='')=>`<div class="field full"><label for="f-${name}">${label}</label><textarea id="f-${name}" name="${name}" rows="3">${h(value)}</textarea></div>`;
  const selectField=(label,name,values,selected='')=>`<div class="field"><label for="f-${name}">${label}</label><select id="f-${name}" name="${name}">${values.map(v=>`<option value="${h(v)}" ${v===selected?'selected':''}>${h(v)}</option>`).join('')}</select></div>`;
  const searchFilters=(ui,placeholder='搜索名称或编号',extra='')=>`<form class="filters" data-submit="search"><div class="search-field">${icon('search')}<input class="input" name="keyword" aria-label="搜索关键词" placeholder="${placeholder}" value="${h(ui.search)}"></div>${extra}<button class="btn" type="submit"><span class="control-label">查询</span></button>${link('重置','clear-filter')}<div class="grow"></div>${btn(icon('download')+'导出','export',{},'small-btn')}</form>`;
  const tabs=(values,ui,counts={})=>`<div class="tabs">${values.map(x=>`<button class="tab ${ui.tab===x?'on':''}" data-action="tab" data-value="${x}">${x}${counts[x]!==undefined?`<em>${counts[x]}</em>`:''}</button>`).join('')}</div>`;
  const filter=(rows,ui)=>rows.filter(r=>!ui.search||JSON.stringify(r).toLowerCase().includes(ui.search.toLowerCase()));
  const visibleRows=collection=>Admin.state[collection].filter(r=>r.order?Admin.visible(Admin.find('orders',r.order)):!r.store||Admin.visible(r));
  const money=Admin.money;
  function orderRows(rows,compact=false){return rows.map(o=>tr([`${link(no(o),'order',{id:o.id})}<small>${h(o.customer)} · ${o.phone}</small>`,`<strong>${Admin.item(o).name}</strong><small>${date(o.start)} · ${Admin.duration(o)}分钟</small>`,`${techName(o.tech)}<small>${o.mode==='specified'?'指定技师':'就近安排'}</small>`,`${badge(Admin.displayStatus(o))}${o.proposal?'<small class="danger">变更待用户确认</small>':o.status==='待分配'?`<small class="danger">本轮剩余 ${remaining(o.deadline)}</small>`:''}`,compact?`<span class="num">${money(o.paid)}</span>`:`<span class="num">${money(o.paid)}</span><small>${o.refundPending?'退款处理中 '+money(o.refundPending):o.refund?'已退 '+money(o.refund):o.paid?'已支付':'未支付'}</small>`,...(compact?[]:[storeName(o.store)]),`<div class="row-actions">${link('详情','order',{id:o.id})}${o.status==='待分配'&&!o.proposal?link('分配','assign',{id:o.id}):''}</div>`]));}
  function dashboard(){const state=Admin.state,isHq=state.session.role==='hq',os=Admin.orders(),waiting=os.filter(x=>x.status==='待分配'),cases=visibleRows('cases').filter(x=>x.status!=='已完成'),safety=visibleRows('safety').filter(x=>x.status!=='已结案');const gross=os.reduce((a,o)=>a+o.paid-o.refund,0);
    return head(isHq?'集团工作台':'门店工作台',isHq?'查看门店经营与跨店待办，及时跟进需要集团处理的问题。':'幸福里门店 · 先处理临近截止的预约和服务待办。',`<span class="date-label">${icon('calendar-days')}2026年10月2日 星期五</span>${btn(icon('rotate-cw')+'刷新','refresh')}`)+
    (safety.length?`<div class="notice red alert-row">${icon('shield-alert')}<span><strong>${safety.length} 项安全事件需要跟进</strong>　${h(safety[0].reason)}</span>${link('立即处理 '+icon('arrow-right'),'go',{page:'safety'})}</div>`:'')+
    `<div class="metrics">${metric(isHq?'营业门店':'预约记录',isHq?state.stores.filter(s=>s.status==='营业中').length:os.filter(o=>o.status!=='已关闭').length,isHq?'共 '+state.stores.length+' 家门店':'当前门店的有效及历史预约','calendar-days')}${metric('待分配预约',waiting.length,waiting.length?'最近截止 '+time(waiting[0].deadline):'暂无待分配','user-round-check')}${metric('售后待办',cases.length,'包含待处理及退款执行中的案件','messages-square')}${metric('预约净收款',money(gross),'演示记录实付减去已成功退款','wallet')}</div>`+
    `<div class="dashboard-grid"><div>${panel(isHq?'预约总览':'预约安排',table(['预约 / 客户','项目 / 时段','技师','预约状态','实付金额','操作'],orderRows(os.filter(o=>!['已关闭','已取消'].includes(o.status)).slice(0,6),true),{footer:false}),link('查看全部 '+icon('arrow-up-right'),'go',{page:'orders'}))}<div class="mt">${panel('当班技师',`<div class="panel-body staff-strip">${state.techs.filter(t=>isHq||t.store==='s1').slice(0,4).map(t=>`<div class="staff-chip"><span class="avatar ${t.gender==='女'?'green':''}">${h(t.name[0])}</span><div><strong>${h(t.name)}</strong><p>${badge(t.status)} ${t.shift==='请假'?'全天休息':t.shift}</p></div></div>`).join('')}</div>`,link('查看排班','go',{page:isHq?'technicians':'schedule'}))}</div></div><div>${panel('待办事项',`<div class="task-list">${[['安全事件',safety.length,'shield-alert','safety','按3分钟响应时限跟进'],['预约待分配',waiting.length,'calendar-clock','orders','固定截止，分配后直接确认'],['售后待处理',cases.length,'headset','aftersales','24小时内响应用户'],[isHq?'技师待审核':'请假待审批',isHq?state.techs.filter(t=>t.status==='资料审核').length:state.leaves.filter(l=>l.status==='待审批').length,'clipboard-list',isHq?'technicians':'schedule','核对资料与受影响预约']].map(([name,num,ico,page,sub])=>`<button class="task-row w-full" data-action="go" data-page="${page}"><span class="task-icon">${icon(ico)}</span><div class="grow text-left"><h3>${name}</h3><p>${sub}</p></div><span class="task-num">${num}</span>${icon('chevron-right')}</button>`).join('')}</div>`)}<div class="mt">${panel('值班与提醒',`<div class="panel-body"><p class="small strong">${h(state.duty)}</p><p class="tiny muted mt-sm">今日服务时段 09:00–23:00</p><div class="divider"></div><p class="small">退款到账以渠道最终结果为准。</p><p class="tiny muted mt-sm">门店、集团使用同一笔预约记录；业务决定和资金执行分别显示。</p></div>`)}</div></div></div>`;
  }
  function orders(ui){const all=Admin.orders(),statusList=['全部','待分配','已确认','进行中','已完成','已取消'];let rows=filter(all.map(o=>({...o,_tech:techName(o.tech),_item:Admin.item(o).name,_no:no(o)})),ui);if(ui.tab!=='全部')rows=rows.filter(o=>o.status===ui.tab);if(ui.storeFilter)rows=rows.filter(o=>o.store===ui.storeFilter);
    return head('预约与派单','按预约状态和时限安排服务，变更和资金结果可在详情中追踪。',btn(icon('list-filter')+'只看待分配','tab',{value:'待分配'}))+`<section class="panel">${tabs(statusList,ui,Object.fromEntries(statusList.map(s=>[s,s==='全部'?all.length:all.filter(o=>o.status===s).length])))}${searchFilters(ui,'预约号 / 客户 / 技师',Admin.state.session.role==='hq'?`<select name="store" aria-label="筛选门店"><option value="">全部门店</option>${Admin.state.stores.map(s=>`<option value="${s.id}" ${ui.storeFilter===s.id?'selected':''}>${h(s.name)}</option>`).join('')}</select>`:'')}${table(['预约 / 客户','项目 / 时段','技师','预约状态','实付 / 退款','服务门店','操作'],orderRows(rows))}</section>`;
  }
  function aftersales(ui){let rows=Admin.state.cases.filter(c=>Admin.visible(Admin.find('orders',c.order)));rows=filter(rows,ui);return head(Admin.state.session.role==='hq'?'售后与客服':'售后处理','核对用户诉求，制定处理方案，并跟进每笔退款结果。')+`<section class="panel">${tabs(['全部','待门店处理','待用户确认','集团介入中','已完成'],ui)}${searchFilters(ui,'售后单号 / 问题描述')}${table(['售后单 / 预约','客户与项目','申请金额','处理状态','处理时限','操作'],rows.filter(c=>ui.tab==='全部'||c.status===ui.tab).map(c=>{const o=Admin.find('orders',c.order);return tr([`<strong>${c.id}</strong><small>${no(o)}</small>`,`${o.customer}<small>${Admin.item(o).name} · 含加时</small>`,`<span class="num">${money(o.payments.reduce((a,p)=>a+p.request,0))}</span><small>主单 + 加时分笔申请</small>`,badge(c.status),`<span class="num">${date(c.deadline)}</span><small>剩余 ${remaining(c.deadline)}</small>`,link('处理详情','case',{id:c.id})]);}))}</section>`;}
  function schedule(){
    const ts=Admin.state.techs.filter(t=>t.store==='s1'),leaves=Admin.state.leaves.filter(Admin.visible);
    const days=['2026-09-28','2026-09-29','2026-09-30','2026-10-01','2026-10-02','2026-10-03','2026-10-04'];
    const labels=['周一 09/28','周二 09/29','周三 09/30','周四 10/01','周五 10/02','周六 10/03','周日 10/04'];
    const cells=t=>days.map(d=>{const start=Date.parse(d+'T00:00:00+08:00'),finish=start+86400000;
      const leave=leaves.find(l=>l.tech===t.id&&l.start<finish&&l.end>start&&['待审批','已批准'].includes(l.status));
      const count=Admin.orders().filter(o=>o.tech===t.id&&o.start>=start&&o.start<finish&&!['已取消','已关闭'].includes(o.status)).length;
      const caption=leave?time(leave.start)+(leave.status==='已批准'?'请假':'请假待审'):count?count+'笔预约':t.status==='请假'?'已批准':d<Admin.day(Admin.state.now)?'历史排班':'可接受预约';
      return `<div class="schedule-cell"><button class="shift-block ${t.status==='请假'?'off':leave?'warn':''}" data-action="edit-shift" data-id="${t.id}" data-day="${d}" ${d<Admin.day(Admin.state.now)?'disabled':''}>${t.status==='请假'?'休息':Admin.shiftAt(t,d)}<br>${caption}</button></div>`;}).join('');
    return head('技师与排班','按完整时段查看排班、占用和请假，批准前核对受影响预约。',btn(icon('calendar-days')+'编辑排班','edit-shift'))+
      panel('本周排班',`<div class="table-wrap"><div class="schedule-head"><span>技师</span>${labels.map(s=>`<span>${s}</span>`).join('')}</div>${ts.map(t=>`<div class="schedule-row"><div class="schedule-name"><span class="avatar ${t.gender==='女'?'green':''}">${h(t.name[0])}</span>${h(t.name)}</div>${cells(t)}</div>`).join('')}</div><div class="section-note">预约占用包含前后30分钟缓冲。历史排班只读；请假审批保留已开始、已完成事实。</div>`)+
      `<div class="mt">${panel('请假审批',table(['申请人','类型','请假时段','原因','状态','操作'],leaves.map(l=>tr([techName(l.tech),badge(l.type,'warn'),`${date(l.start)} — ${time(l.end)}`,h(l.reason),badge(l.status),link('查看影响 / 审批','leave',{id:l.id})]))))}</div>`;
  }
  function finance(){
    const os=Admin.orders().filter(o=>o.paid>0),gross=os.reduce((a,o)=>a+o.paid,0),refunded=os.reduce((a,o)=>a+o.refund,0);
    return head('对账与提成','逐笔核对实付、退款、分成与线下发放记录。',btn(icon('download')+'导出账单','export'))+
      `<div class="metrics">${metric('用户实付',money(gross),'全部演示交易','wallet')}${metric('已成功退款',money(refunded),'以到账结果累计','rotate-ccw')}${metric('待执行退款',money(os.reduce((a,o)=>a+o.refundPending,0)),'尚未计入已退金额','clock-3')}${metric('净收款',money(gross-refunded),'实付 − 已退','receipt')}</div>`+
      panel('交易明细',table(['预约','用户实付','已退 / 处理中','集团抽成预估','门店净额预估','结算状态','操作'],os.map(o=>{const net=o.paid-o.refund,share=Math.floor(net*o.ruleSnapshot.hqRate/100);return tr([no(o),money(o.paid),`${money(o.refund)}<small>处理中 ${money(o.refundPending)}</small>`,money(share),money(net-share),badge(Admin.currentBlock(o)?'结算阻断':o.sharing||'待结算'),link('明细','order',{id:o.id})]);})))+
      `<div class="section-note">本组预约为集团自然客户，抽成快照15%，无推广佣金；金额为当前净额预估。</div>`+
      `<div class="mt">${panel('技师提成台账',table(['技师','已完成预约','当前应计','已登记发放','发放状态','操作'],Admin.state.techs.filter(t=>t.store==='s1').map(t=>{const completed=os.filter(o=>o.tech===t.id&&o.status==='已完成'),amount=Admin.techAmount(t.id),paid=Admin.state.techPayouts.filter(x=>x.tech===t.id).reduce((a,x)=>a+x.amount,0),marked=Admin.state.paidTech.includes(t.id);return tr([h(t.name),completed.length+' 笔',money(amount),money(paid),badge(marked?(paid===amount?'已发放':'退款后待调整'):amount?'待发放':'暂无提成'),amount&&!marked?link('登记发放','paid-tech',{id:t.id}):marked&&paid!==amount?`<span class="danger">差额 ${money(amount-paid)}</span>`:'—']);})),`<span class="tiny muted">示例：净额×40% + 每主预约补贴¥10</span>`)}</div>`;
  }
  function invoices(ui){return head('发票管理','按实际净收款开票，退款后跟进红冲及重新开票。')+`<section class="panel">${searchFilters(ui,'发票编号 / 抬头')}${table(['申请单 / 预约','抬头 / 税号','净可开票额','状态','附件','操作'],filter(visibleRows('invoices'),ui).map(i=>{const o=Admin.find('orders',i.order);return tr([`${i.id}<small>${no(o)}</small>`,`${h(i.title)}<small>${i.tax}</small>`,money(o.paid-o.refund),badge(i.status),i.file?h(i.file):'<span class="muted">尚未上传</span>',link('处理','invoice',{id:i.id})]);}))}</section>`;}
  function rules(){const r=Admin.state.rules,hq=Admin.state.session.role==='hq',fields=hq?[['集团客户抽成','hqRate','%'],['门店客户抽成','storeRate','%'],['门店承担佣金','commission','%'],['最远可约','maxDays','天'],['售后期','afterHours','小时'],['最早可约','earliestHours','小时']]:[['技师提成','techRate','%'],['取消补偿','compensation','%'],['服务半径','radius','公里'],['前后路程缓冲','buffer','分钟']];return head(hq?'规则配置':'门店规则','规则发布后对新业务生效，已有预约保留提交时的价格和比例快照。',badge('当前 v'+r.version))+`<div class="settings-layout"><section class="panel"><div class="panel-head"><h2>${hq?'资金与预约参数':'提成与服务配置'}</h2></div><form class="panel-body" data-submit="rules"><div class="form-error"></div><div class="form-grid">${fields.map(([label,name,unit])=>field(label,name,r[name],'number',unit)).join('')}</div><div class="notice gray mt">${icon('info')}<span>${hq?'集团抽成与门店承担佣金合计不超过30%；最远可约天数 + 售后天数 + 10天 ≤ 25天。':'技师提成在确认分配时固定版本，已有预约保持原计算依据。'}</span></div><div class="form-actions"><button class="btn primary" type="submit"><span class="control-label">发布新版本</span></button></div></form></section>${panel('规则说明',`<div class="panel-body"><p class="small strong">派单期限按轮固定</p><p class="small muted mt-sm">首次支付或已确认变更开新轮。门店切换候选和重试不会延长截止。</p><div class="divider"></div><p class="small strong">保存前自动校验</p><p class="small muted mt-sm">不符合金额、时限约束的规则会说明原因，修改后可再次提交。</p><div class="divider"></div><p class="tiny muted">本轮更新记录可在演示设置的操作日志中查看。</p></div>`)}</div>`;}
  function settings(){const s=Admin.find('stores','s1');return head('门店设置','维护营业信息，暂停营业前先处理受影响预约。')+`<div class="settings-layout">${panel('幸福里门店',`<div class="panel-body"><div class="kv-grid">${kv('门店状态',badge(s.status))}${kv('门店类型',s.type)}${kv('所在区域',s.district)}${kv('营业时间',s.open)}${kv('门店地址',s.address,true)}${kv('服务半径',s.radius+'公里')}${kv('收款子商户',s.merchant)}${s.suspension?kv('暂停安排',date(s.suspension.start)+' 至 '+date(s.suspension.end),true):''}</div><div class="form-actions">${btn('设置暂停营业','pause-store',{id:s.id})}${btn('编辑门店资料','store-edit',{id:s.id},'primary')}</div></div>`)}${panel('营业提示',`<div class="panel-body"><p class="small">暂停时段内停止新增预约。已有预约需逐笔处理改约或门店原因取消。</p><p class="tiny muted mt-sm">本店有 ${Admin.orders().filter(o=>['待分配','已确认'].includes(o.status)).length} 笔尚未开始的预约。</p></div>`)}</div>`;}
  function safety(ui){return head(Admin.state.session.role==='hq'?'安全中心':'安全值班','先接报联系双方，再记录处置结果。安全结案与服务争议分别处理。',btn('编辑值班','duty'))+`<div class="notice gray mb">${icon('phone-call')}<span>今日值班：${h(Admin.state.duty)}　·　服务时段 09:00–23:00</span></div><section class="panel">${searchFilters(ui,'事件编号 / 事件说明')}${table(['事件 / 预约','事件说明','发起时间','状态','处理人','操作'],filter(visibleRows('safety'),ui).map(s=>tr([`${s.id}<small>${no(Admin.find('orders',s.order))}</small>`,h(s.reason),date(s.created),badge(s.status),h(s.handler),link('处置详情','safety',{id:s.id})])))}</section>`;}
  function reviews(ui){return head('投诉与评价',Admin.state.session.role==='hq'?'复核申诉与处理结果，记录事实、依据和决定。':'处理本店评价申诉，初审结果提交集团复核。')+`<section class="panel">${searchFilters(ui,'评价 / 技师 / 申诉内容')}${table(['关联预约','技师 / 评分','评价内容','处理状态','操作'],filter(visibleRows('reviews'),ui).map(r=>tr([no(Admin.find('orders',r.order)),`${techName(r.tech)}<small>${r.score} 分 / 5分</small>`,h(r.content),badge(r.status),link('审核详情','review',{id:r.id})])))}</section>`;}
  function promotion(ui){const rows=filter(visibleRows('promoters'),ui);return head(Admin.state.session.role==='hq'?'分销管理':'门店推广','邀请个人推广员，查看绑定数量和佣金汇总。',btn(icon('plus')+'邀请推广员','promoter-add',{},'primary'))+`<section class="panel">${searchFilters(ui,'姓名 / 推广员编号')}${table(['推广员','类型 / 归属','绑定客户','佣金汇总','状态','操作'],rows.map(p=>tr([`<strong>${h(p.name)}</strong><small>${p.id}</small>`,`${p.type}<small>${storeName(p.store)}</small>`,p.customers+' 人',money(p.commission),badge(p.status),link('管理','promoter',{id:p.id})])))}</section><div class="notice gray mt">${icon('info')}<span>一级分销；仅展示绑定数量和佣金。客户手机号与地址不向推广员开放。</span></div>`;}
  function stores(ui){return head('门店管理','从建档、授权到营业及关停，跟踪各门店的接单条件。')+`<section class="panel">${searchFilters(ui,'门店名称 / 区域')}${table(['门店','类型 / 区域','技师数','子商户 / 授权','生命周期','操作'],filter(Admin.state.stores,ui).map(s=>tr([`<strong>${h(s.name)}</strong><small>${s.id.toUpperCase()} · ${h(s.address)}</small>`,`${s.type}<small>${s.district}</small>`,Admin.state.techs.filter(t=>t.store===s.id&&t.status!=='离职').length+' 人',`${s.merchant}<small>${s.authorized?'分账已授权':'待分账授权'}</small>`,badge(s.status),link('门店详情','store-detail',{id:s.id})])))}</section>`;}
  function technicians(ui){return head('技师档案','核对证书、保单和入驻资料，审核后分配门店。',btn(icon('upload')+'导入结业名单','import-tech'))+`<section class="panel">${searchFilters(ui,'技师姓名 / 门店')}${table(['技师','所属门店','可服务项目','保单有效至','状态','操作'],filter(Admin.state.techs.map(t=>({...t,_store:storeName(t.store)})),ui).map(t=>tr([`<div class="flexrow"><span class="avatar ${t.gender==='女'?'green':''}">${h(t.name[0])}</span><div><strong>${h(t.name)}</strong><small>${t.gender} · ${t.id.toUpperCase()}</small></div></div>`,storeName(t.store),t.skills.map(id=>Admin.find('items',id).name).join(' / '),t.insurance,badge(t.status),link('档案 / 审核','tech',{id:t.id})])))}</section>`;}
  function catalog(){return head('项目与价格','维护项目、时段价格与加时配置。新价格对后续预约生效。')+panel('服务项目',table(['项目','服务时长','日间总价','21:00起总价','加时 / 30分钟','状态','操作'],Admin.state.items.map(i=>tr([`<strong>${h(i.name)}</strong><small>${h(i.description)}</small>`,i.duration+'分钟',money(i.price),money(i.night),money(i.overtime),badge(i.status),link('编辑','catalog-edit',{id:i.id})]))));}
  function sharing(ui){const rows=filter(Admin.state.orders.filter(o=>o.status==='已完成'),ui);return head('分账监控','查看实际分账状态、阻断原因和重试记录。',btn('查看操作记录','audit'))+`<section class="panel">${searchFilters(ui,'预约号 / 门店')}${table(['预约','服务门店','净实付','拟分账给集团','状态 / 阻断','操作'],rows.map(o=>tr([`${no(o)}<small>完成 ${date(o.completedAt)}</small>`,storeName(o.store),money(o.paid-o.refund),money(Math.floor((o.paid-o.refund)*o.ruleSnapshot.hqRate/100)),badge(Admin.shareBlock(o)||o.sharing||'待结算'),link('处理','sharing',{id:o.id})])))}</section><div class="notice gray mt">${icon('info')}<span>分账、退款与回退分别记录。渠道请求受理后需继续查询最终结果。</span></div>`;}
  function recovery(ui){return head('追偿台账','记录垫付、回退失败及回款结果，按来源订单追踪。')+`<section class="panel">${searchFilters(ui,'追偿编号 / 类型')}${table(['追偿编号','类型 / 门店','应收金额','已回款','状态','操作'],filter(Admin.state.recoveries,ui).map(r=>tr([r.id,`${r.type}<small>${storeName(r.store)}</small>`,money(r.amount),money(r.returned),badge(r.status),link('登记 / 查看','recovery',{id:r.id})])))}</section>`;}
  function withdrawals(ui){return head('佣金与提现','核对提现渠道结果、申请次数和失败原因。')+`<section class="panel">${searchFilters(ui,'提现编号 / 姓名')}${table(['提现申请','申请人 / 门店','提现金额','当日申请数','渠道状态','操作'],filter(Admin.state.withdrawals,ui).map(w=>tr([w.id,`${w.name}<small>${storeName(w.store)}</small>`,money(w.amount),w.count+' / 3',badge(w.status),link('查看 / 查询','withdrawal',{id:w.id})])))}</section><div class="notice gray mt">${icon('info')}<span>失败或撤销恢复余额，但仍计入申请创建日的次数；查询同一申请不会重复计次。</span></div>`;}
  function users(ui){return head('用户管理','处理限制申请和申诉，完整个人信息按授权查看。')+`<section class="panel">${searchFilters(ui,'用户名称 / 编号')}${table(['用户','手机号','预约次数','账号状态','来源说明','操作'],filter(Admin.state.users,ui).map(u=>tr([`${h(u.name)}<small>${u.id}</small>`,u.phone,u.orders,badge(u.status),h(u.reason)||'—',link('查看 / 处理','user',{id:u.id})])))}</section>`;}
  function accounts(ui){return head('账号与权限','账号权限包含可操作功能及数据范围，变更记录可追溯。',btn('查看操作日志','audit'))+`<section class="panel">${searchFilters(ui,'姓名 / 角色 / 范围')}${table(['账号','角色','数据范围','状态','操作'],filter(Admin.state.accounts,ui).map(a=>tr([`${h(a.name)}<small>${a.id}</small>`,a.role,a.scope,badge(a.status),link('授权详情','account',{id:a.id})])))}</section>`;}
  function analytics(){const os=Admin.state.orders.filter(o=>o.paid),paid=os.reduce((a,o)=>a+o.paid,0),refund=os.reduce((a,o)=>a+o.refund,0),counts=Admin.state.stores.map(s=>({name:s.name,orders:os.filter(o=>o.store===s.id)}));return head('数据看板','本页指标由当前演示订单计算，金额以付款和成功退款为口径。',btn(icon('download')+'导出明细','export'))+`<div class="metrics">${metric('支付订单',os.length,'含取消与退款订单','receipt')}${metric('支付总额',money(paid),'主单及已付加时','wallet')}${metric('成功退款',money(refund),'渠道已确认退款','rotate-ccw')}${metric('净收款',money(paid-refund),'支付总额 − 成功退款','chart-no-axes-combined')}</div><div class="dashboard-grid">${panel('门店支付订单分布',`<div class="panel-body"><div class="bars">${counts.map(c=>`<div class="bar-col"><span>${c.orders.length}单</span><div class="bar" style="height:${Math.max(2,c.orders.length/8*100)}%"></div><small>${c.name}</small></div>`).join('')}</div></div>`)}${panel('指标口径',`<div class="panel-body"><p class="small">支付订单：发生支付的主预约数。</p><p class="small muted mt-sm">金额包含已支付加时；处理中退款仍计入净收款，成功后扣减。</p><div class="divider"></div><p class="small muted">复购率需按正式首单及统计周期口径计算，当前样例不展示未经计算的比率。</p></div>`)}</div><div class="mt">${panel('门店明细',table(['门店','支付订单','支付总额','成功退款','净收款'],counts.map(c=>tr([c.name,c.orders.length,money(c.orders.reduce((a,o)=>a+o.paid,0)),money(c.orders.reduce((a,o)=>a+o.refund,0)),money(c.orders.reduce((a,o)=>a+o.paid-o.refund,0))]))))}</div>`;}
  function content(page,ui){return ({dashboard,orders,aftersales,schedule,finance,invoices,rules,settings,safety,reviews,promotion,stores,technicians,catalog,sharing,recovery,withdrawals,users,accounts,analytics}[page]||(()=>empty('页面不存在','请从左侧导航选择业务页面。','home')))(ui);}
  return {h,icon,attrs,btn,link,badge,date,time,storeName,techName,no,remaining,empty,table,tr,metric,head,panel,section,kv,field,textarea,selectField,searchFilters,tabs,filter,visibleRows,orderRows,content};
})();
