import test from 'node:test';
import assert from 'node:assert/strict';
import {seed,reduce,upgradeFinanceState} from './engine.mjs';
import {resolveAccountActor} from './staff-accounts.mjs';
import {privacyProfile,privacyBlockers} from './privacy.mjs';
import {createBookingDraft,patchBookingDraft,bookingDraftPayload} from './booking-draft.mjs';
import {bookingView} from './booking.mjs';
import {staffView} from './staff.mjs';
import {customerView} from './customer.mjs';
const user={role:'user',userId:'u1'}, support={role:'group',job:'support'};
const ui={esc:v=>String(v??''),money:v=>String(v),date:v=>String(v),empty:(a,b='')=>a+b,link:(n,p)=>`<a href="#${p}">${n}</a>`,button:()=>'',field:()=>'',select:()=>'',tag:v=>String(v)};
function harness(){let s=seed(),n=0,result;return {get s(){return s},get result(){return result},run(a,type,p={}){result=undefined;s=reduce(s,a,type,{requestId:'access-int-'+(++n),...p},r=>result=r);return result;}};}
function admin(h){const r=h.run(user,'account.enter',{accountId:'DEMO-ADMIN',grantId:'DEMO-ADMIN-GRANT'});return resolveAccountActor(h.s,r);}
function worker(h,a,job,storeId){const r=h.run(a,'account.create',{name:job+'演示员工',reason:'验证已授权岗位'});const granted=h.run(a,'account.grant',{id:r.id,version:r.version,job,storeId,reason:'明确岗位及范围'});const entered=h.run(user,'account.enter',{accountId:r.id,grantId:granted.grants.at(-1).id});return resolveAccountActor(h.s,entered);}
function book(h,extra={}){h.run(user,'booking.create',{storeId:'xingfu',serviceId:'neck',regionId:'home',techId:'lin',mode:'specified',startAt:'2026-10-02T13:00',contactName:'演示联系人',phone:'13800001111',healthConsent:true,identityVerified:true,adultConfirmed:true,...extra});return h.s.bookings.at(-1);}

test('账号岗位由会话推导，伪造URL对应actor不能升级为全能管理员',()=>{const h=harness(),a=admin(h),w=worker(h,a,'store-manager','xingfu');assert.throws(()=>h.run({...w,role:'group',job:'all',storeId:'silver'},'account.create',{name:'越权',reason:'不可越权'}),/无权|授权/);assert.equal(resolveAccountActor(h.s,{...w,role:'group',storeId:'silver'}).storeId,'xingfu');});
test('停用后旧页面和旧命令拒绝，重新启用不复活旧会话',()=>{const h=harness(),a=admin(h),w=worker(h,a,'store-manager','xingfu');const before=structuredClone(h.s.bookings);let account=h.s.staffAccounts.find(x=>x.id===w.accountId);h.run(a,'account.status',{id:account.id,version:account.version,enabled:false,reason:'停止工作访问'});assert.throws(()=>h.run(w,'booking.assign',{id:'none'}),/失效|变更/);assert.match(staffView(h.s,w,['bookings'],ui),/会话已失效/);assert.deepEqual(h.s.bookings,before);account=h.s.staffAccounts.find(x=>x.id===w.accountId);h.run(a,'account.status',{id:account.id,version:account.version,enabled:true,reason:'恢复后需重新进入'});assert.throws(()=>resolveAccountActor(h.s,w),/失效/);});
test('账号管理员无财务和预约业务权；门店主管无服务资金执行权',()=>{const h=harness(),a=admin(h),w=worker(h,a,'store-manager','xingfu');for(const actor of [a,w])assert.throws(()=>h.run(actor,'booking.refund-pay',{id:'none'}),/无权/);assert.match(staffView(h.s,a,['service-finance'],ui),/无权/);});
test('账号财务不能派单和查看交接，合法预约读取仍受单店限制',()=>{const h=harness(),a=admin(h),w=worker(h,a,'store-finance','silver');book(h);assert.throws(()=>h.run(w,'booking.assign',{id:h.s.bookings[0].id,techId:'lin'}),/无权/);assert.match(staffView(h.s,w,['handoffs',h.s.bookings[0].id],ui),/无权/);assert.equal(bookingView(h.s,w).length,0);});
test('正常用户预约保留原金额及时限，撤回后原预约取消仍可办理',()=>{const h=harness(),b=book(h,{privacyVersion:0,privacyConsent:true});h.run(user,'booking.pay',{id:b.id,outcome:'success'});const before=structuredClone(h.s.bookings[0]);h.run(user,'privacy.withdraw',{version:privacyProfile(h.s,'u1').version,purpose:'identity',reason:'撤回本用途'});assert.deepEqual(h.s.bookings[0],before);assert.throws(()=>book(h,{startAt:'2026-10-02T16:00'}),/版本|同意|授权/);h.run(user,'booking.cancel',{id:b.id,reason:'用户取消演示预约'});assert.equal(h.s.bookings[0].status,'cancelled');});
test('撤回之后原request重放只返回原订单，不恢复同意或增加记录',()=>{const h=harness();book(h,{requestId:'stable',privacyVersion:0,privacyConsent:true});h.run(user,'privacy.withdraw',{version:privacyProfile(h.s,'u1').version,reason:'停止授权'});const version=privacyProfile(h.s,'u1').version;book(h,{requestId:'stable',privacyVersion:0,privacyConsent:true});assert.equal(h.s.bookings.length,1);assert.equal(privacyProfile(h.s,'u1').identityConsent.agreed,false);assert.equal(privacyProfile(h.s,'u1').version,version);});
test('旧草稿撤回后不能重放，新明确同意仍通过原五步提交',()=>{const h=harness();const d={...createBookingDraft(h.s,'u1','fresh'),storeId:'xingfu',serviceId:'neck',regionId:'home',techId:'lin',mode:'specified',startAt:Date.parse('2026-10-02T13:00:00+08:00'),contactName:'演示本人',phone:'13800001111',recipientId:'visit',recipientKind:'self',recipientName:'本人',recipientRelationship:'本人',recipientConfirmed:true,adultConfirmed:true,healthConsent:true,identityConsent:true,identityVerified:true};h.run(user,'privacy.withdraw',{version:0,reason:'撤回'});assert.throws(()=>h.run(user,'booking.create',bookingDraftPayload(d)),/版本|更新/);const changed=patchBookingDraft(h.s,d,{date:d.date});assert.equal(changed.identityConsent,false);assert.equal(changed.identityVerified,false);const renewed=patchBookingDraft(h.s,changed,{identityConsent:true,identityVerified:true});h.run(user,'booking.create',bookingDraftPayload(renewed));assert.equal(h.s.bookings.length,1);assert.equal(privacyProfile(h.s,'u1').identityConsent.agreed,true);});
test('注销申请可撤回，客服不能跳过待付款订单直接关闭',()=>{const h=harness(),b=book(h);h.run(user,'privacy.request',{version:0,reason:'测试申请',acknowledged:true});const c=h.s.privacyClosures.at(-1);assert.equal(privacyBlockers(h.s,'u1').some(x=>x.id===b.id),true);assert.throws(()=>h.run(support,'privacy.close',{id:c.id,version:c.version,reason:'核查',custodian:'客服演示',acknowledged:true}),/未结/);h.run(user,'privacy.retract',{id:c.id,version:c.version,reason:'先处理订单'});assert.equal(h.s.privacyClosures[0].status,'retracted');assert.equal(h.s.bookings[0].status,'unpaid');});
test('关闭使用保留金额/交易事实，回执明确材料待处理，禁止新单',()=>{const h=harness(),b=book(h);h.run(user,'booking.cancel',{id:b.id,reason:'用户取消演示预约'});const bookings=structuredClone(h.s.bookings);h.run(user,'privacy.request',{version:0,reason:'停止普通使用',acknowledged:true});const c=h.s.privacyClosures.at(-1);h.run(support,'privacy.close',{id:c.id,version:c.version,reason:'核查无未结事项，留存范围待确认',custodian:'演示客服',acknowledged:true});assert.deepEqual(h.s.bookings,bookings);assert.equal(h.s.addresses.some(x=>x.userId==='u1'),false);assert.equal(privacyProfile(h.s,'u1').status,'use_closed');assert.match(customerView(h.s,user,['home'],ui),/使用关闭回执/);assert.match(customerView(h.s,user,['privacy'],ui),/不代表全部数据删除/);assert.throws(()=>book(h),/已关闭/);assert.equal(h.s.privacyClosures[0].cleanupStatus,'pending_review');});
test('客服完整手机号只作为临时结果返回，日志不存明文',()=>{const h=harness(),b=book(h);const result=h.run(support,'sensitive.reveal',{bookingId:b.id,reason:'核实本次预约联系需要'});assert.equal(result.phone,'13800001111');assert.equal(JSON.stringify(h.s.sensitiveAccessLogs).includes('13800001111'),false);assert.equal(bookingView(h.s,{role:'tech',techId:'lin'})[0].phone,'');assert.match(bookingView(h.s,{role:'store',storeId:'xingfu'})[0].phone,/\*/);});
test('schema5升级增量且幂等，不伪造既有同意',()=>{const s=seed();const original=structuredClone(s.bookings);upgradeFinanceState(s);const after=structuredClone(s);upgradeFinanceState(s);assert.deepEqual(s,after);assert.deepEqual(s.bookings,original);assert.equal(s.privacyProfiles.length,0);assert.equal(s.staffAccounts.length,1);});
