import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { seed,reduce } from './engine.mjs';
import { commerceInvoiceCommand } from './commerce-invoices.mjs';
import { resolveAccountActor } from './staff-accounts.mjs';
import { privacyCleanupInventory } from './privacy-cleanup-inventory.mjs';

// Original reduce/domain runtime tests. File metadata is an isolated domain
// fixture, not byte upload/browser acceptance. No old data is migrated/deleted.
const user={role:'user',userId:'u1'},other={role:'user',userId:'u2'},finance={role:'group',job:'finance'},support={role:'group',job:'support'},store={role:'store',job:'store-finance',storeId:'xingfu'},tech={role:'tech',techId:'lin'};
const canonical=x=>Array.isArray(x)?x.map(canonical):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,canonical(x[k])])):x;
const serialized=x=>JSON.stringify(canonical(x)),digest=x=>'sha256:'+createHash('sha256').update(serialized(x),'utf8').digest('hex');
const title={kind:'company',title:'C09原受票抬头',taxId:'91320100000000000X',email:'c09-private-copy@example.test'};
const bytes=Buffer.from('%PDF-1.4\nC09 original commerce digest\n%%EOF'),file={ref:'invoice-file:'+createHash('sha256').update(bytes).digest('hex'),name:'C09原私人姓名凭证🧾.pdf',type:'application/pdf',size:bytes.length};
const coverage={originScope:'https://isolated.test',revision:1,ledgerComplete:true,uploadsComplete:true,unregisteredStoredRefs:[],tabIds:['unit'],tabs:[{id:'unit',revision:1,status:'acknowledged',drafts:[]}]};
function harness({goods=true}={}) {
  let s=seed(),n=0;
  const h={get s(){return s;},set s(value){s=structuredClone(value);},get inv(){return s.commerceInvoices.at(-1);},get o(){return s.goods.at(-1);},get b(){return s.bookings.at(-1);},
    run(type,p={},actor=user){let result;h.lastPayload={requestId:'commerce-digest-'+(++n),...p};s=reduce(s,actor,type,h.lastPayload,x=>result=x);return result;},
    rule(category='goods',extra={}){return h.run('commerce-invoice.rule-publish',{category,version:0,issuerName:'明确输入的隔离Demo主体',issuerTaxId:'91320100000000000Y',invoiceItem:'隔离原开票项目',effectiveAt:s.now,sourceFromAt:Date.parse('2026-01-01T00:00:00+08:00'),reason:'隔离显式Demo输入，正式政策待业务确认',applicationStage:'paid',shipping:'include',windowDays:90,cycle:'monthly',timezoneMinutes:480,returnPolicy:'original-income-fifo',...extra},finance);},
    createGoods(){h.run('cart.set',{skuId:'oil',qty:1});h.run('goods.submit',{addressId:'AD1'});h.run('goods.pay',{id:h.o.id,outcome:'success'});h.run('goods.ship',{id:h.o.id,carrier:'隔离原物流',tracking:'ORIGINAL-'+n},{role:'group',job:'warehouse'});h.run('goods.receive',{id:h.o.id});return h.o.id;},
    apply(requestId='apply-once',extra={}){const p={orderId:h.o.id,...title,requestId,...extra};h.run('commerce-invoice.apply-goods',p);return p;},
    staff(job='finance',storeId='xingfu'){const entered=h.run('account.enter',{accountId:'DEMO-ADMIN',grantId:'DEMO-ADMIN-GRANT'}),admin=resolveAccountActor(s,entered);let account=h.run('account.create',{name:'C09实际作者-'+job+'-'+n,reason:'隔离原请求验收'},admin);account=h.run('account.grant',{id:account.id,version:account.version,job,...(job.startsWith('store-')?{storeId}:{}),reason:'实际原岗位授权'},admin);const grantId=account.grants.at(-1).id,entry=h.run('account.enter',{accountId:account.id,grantId});return {admin,accountId:account.id,grantId,actor:resolveAccountActor(s,entry)};},
    close(){h.run('privacy.request',{version:0,reason:'原本人关闭申请',acknowledged:true});const x=s.privacyClosures.at(-1);h.run('privacy.close',{id:x.id,version:x.version,reason:'正常关闭保留原商品票权益',custodian:'隔离原客服',acknowledged:true},support);return x.id;},
    feeSources(){h.run('finance.rule-publish',{scope:'global',version:0,groupBps:1000,storeBps:500,effectiveAt:s.now,reason:'明确隔离Demo原分账比例'},finance);const startAt=s.now+4*3600000;h.run('booking.create',{storeId:'xingfu',serviceId:'relax',regionId:'home',techId:'lin',startAt,mode:'specified',genderPreference:'any',contactName:'隔离原本人',phone:'13800000001',healthConsent:true,identityVerified:true,adultConfirmed:true});h.run('booking.pay',{id:h.b.id,outcome:'success'});h.run('booking.accept',{id:h.b.id},tech);h.run('clock.advance',{minutes:240},finance);h.run('booking.start',{id:h.b.id},tech);h.run('clock.advance',{minutes:h.b.duration},finance);h.run('booking.finish',{id:h.b.id,mode:'normal'},tech);h.run('clock.advance',{minutes:2880},finance);let e=s.serviceFinanceEntries.at(-1);h.run('finance.split-start',{id:e.id,version:e.version,outcome:'success'},finance);e=s.serviceFinanceEntries.at(-1);h.run('finance.finish-start',{id:e.id,version:e.version,outcome:'success'},finance);h.run('clock.advance',{minutes:Math.ceil((Date.parse('2026-11-02T12:00:00+08:00')-s.now)/60000)},finance);h.rule('fee');return '2026-10';}
  };if(goods){h.rule();h.createGoods();}return h;
}
function old(s,id,type,p,author) {const row=s.commerceInvoiceRequests.find(x=>x.requestId===id);row.fingerprint=serialized({type,p});delete row.type;delete row.digestAlgorithm;delete row.digestVersion;if(author)row.actor=serialized(author);return row;}
const sourceMoney=s=>structuredClone({goods:s.goods,bookings:s.bookings,bills:s.bills,recoveries:s.recoveries,serviceFinanceEntries:s.serviceFinanceEntries,skus:s.skus});
const replay=(s,a,type,p)=>reduce(s,a,type,p);
const row=s=>s.commerceInvoiceRequests.at(-1);
function direct(s,a,type,p){const next=structuredClone(s),result=commerceInvoiceCommand(next,a,type,p,{id:k=>k+(++next.seq),fail:m=>{throw Error(m);},log(){}});return {s:next,result};}

test('真实商品申请新版本摘要覆盖完整ASCII/中文/emoji/nested原{type,p}，请求不复制正文',()=>{
  for(const text of ['ASCII invoice','中文抬头🧾𠮷','长文'.repeat(50)]) {
    const h=harness(),money=sourceMoney(h.s),p=h.apply('sha-full',{title:text,extraPrivate:{z:[1,{b:text,a:null}],a:'C09-PRIVATE-BODY'}}),r=row(h.s);
    assert.deepEqual(Object.keys(r).sort(),['requestId','actor','type','fingerprint','digestAlgorithm','digestVersion','resultId','at'].sort());assert.equal(r.fingerprint,digest({type:'commerce-invoice.apply-goods',p}));assert.equal(r.digestVersion,1);assert.equal(r.digestAlgorithm,'SHA-256');assert.equal(r.type,'commerce-invoice.apply-goods');assert.equal(r.resultId,h.inv.id);assert.doesNotMatch(JSON.stringify(r),/c09-private-copy|C09-PRIVATE-BODY|extraPrivate|taxId|email|title|payload/);assert.deepEqual(sourceMoney(h.s),money);assert.equal(h.inv.title,text);
  }
});
test('真实配置规则结果保留typed rule根及摘要，原请求持久化反向键序重放不重复',()=>{
  const h=harness({goods:false}),p={category:'goods',version:0,issuerName:'明确隔离Demo',issuerTaxId:'91320100000000000Y',invoiceItem:'原商品',effectiveAt:h.s.now,sourceFromAt:h.s.now,reason:'C09-PRIVATE-RULE',applicationStage:'paid',shipping:'include',windowDays:90,requestId:'rule-stable'},r=h.run('commerce-invoice.rule-publish',p,finance),before=JSON.parse(JSON.stringify(h.s)),after=replay(before,finance,'commerce-invoice.rule-publish',Object.fromEntries(Object.entries(p).reverse()));assert.equal(row(after).fingerprint,digest({type:'commerce-invoice.rule-publish',p}));assert.doesNotMatch(JSON.stringify(row(after)),/C09-PRIVATE-RULE|issuerName/);assert.deepEqual(after.commerceInvoiceRules,before.commerceInvoiceRules);assert.deepEqual(after.commerceInvoiceRequests,before.commerceInvoiceRequests);assert.equal(r.id,row(after).resultId);
});
test('真实工作财务开票和补传不复制file.name/ref/reason，同请求旧version回读无重复',()=>{
  const h=harness();h.apply();const staff=h.staff(),p={id:h.inv.id,version:h.inv.version,ticketNumber:'C09-BLUE',file,requestId:'work-issue'};h.run('commerce-invoice.issue',p,staff.actor);const author=JSON.parse(row(h.s).actor);assert.equal(author.id,staff.accountId);assert.equal(author.job,'finance');assert.equal(author.accountId,staff.accountId);assert.equal(author.grantId,staff.grantId);assert.equal(row(h.s).fingerprint,digest({type:'commerce-invoice.issue',p}));assert.doesNotMatch(JSON.stringify(row(h.s)),/invoice-file:|原私人姓名|ticketNumber|reason/);
  const prior=structuredClone(h.s),after=replay(prior,staff.actor,'commerce-invoice.issue',p);assert.deepEqual(after.commerceInvoices,prior.commerceInvoices);assert.deepEqual(after.commerceInvoiceRequests,prior.commerceInvoiceRequests);assert.deepEqual(sourceMoney(after),sourceMoney(prior));
  const replace={id:h.inv.id,version:h.inv.version,slot:'issued',file:{...file,name:'C09-PRIVATE-REPLACEMENT.pdf'},reason:'C09-PRIVATE-REASON',requestId:'replace'};h.run('commerce-invoice.replace-file',replace,staff.actor);assert.equal(row(h.s).fingerprint,digest({type:'commerce-invoice.replace-file',p:replace}));assert.doesNotMatch(JSON.stringify(row(h.s)),/PRIVATE-REPLACE|PRIVATE-REASON|invoice-file:/);assert.equal(h.inv.history.at(-1).file.name,replace.file.name);
});
test('真实已结服务原分账产生月票来源，原门店工作作者和集团工作开票摘要',()=>{
  const h=harness({goods:false}),month=h.feeSources(),local=h.staff('store-finance'),group=h.staff('finance'),p={storeId:'xingfu',month,...title,requestId:'fee-apply'};h.run('commerce-invoice.apply-fee',p,local.actor);assert.equal(h.inv.category,'fee');assert.ok(h.inv.amount>0);assert.equal(row(h.s).fingerprint,digest({type:'commerce-invoice.apply-fee',p}));assert.equal(JSON.parse(row(h.s).actor).id,local.accountId);assert.equal(JSON.parse(row(h.s).actor).job,'store-finance');const issue={id:h.inv.id,version:h.inv.version,ticketNumber:'C09-FEE',file,requestId:'fee-issue'};h.run('commerce-invoice.issue',issue,group.actor);const before=structuredClone(h.s),after=replay(before,group.actor,'commerce-invoice.issue',issue);assert.deepEqual(after.commerceInvoices,before.commerceInvoices);assert.deepEqual(after.commerceInvoiceRequests,before.commerceInvoiceRequests);
});
test('旧明文和新摘要共存只读；发生时姓名不合并不同账号，同稳定作者重复请求明确拒绝',()=>{
  const h=harness(),p=h.apply();h.s.commerceInvoiceRequests.find(x=>x.requestId===p.requestId);old(h.s,p.requestId,'commerce-invoice.apply-goods',p);const before=structuredClone(h.s),after=replay(before,user,'commerce-invoice.apply-goods',p);assert.deepEqual(after.commerceInvoiceRequests,before.commerceInvoiceRequests);assert.deepEqual(after.commerceInvoices,before.commerceInvoices);
  const staff=h.staff(),issue={id:h.inv.id,version:h.inv.version,ticketNumber:'OLD-BLUE',file,requestId:'old-work'};h.run('commerce-invoice.issue',issue,staff.actor);const historical=JSON.parse(row(h.s).actor);historical.accountName='隔离原发生时姓名';old(h.s,issue.requestId,'commerce-invoice.issue',issue,historical);const original=structuredClone(h.s),replayed=replay(original,staff.actor,'commerce-invoice.issue',issue);assert.deepEqual(replayed.commerceInvoiceRequests,original.commerceInvoiceRequests);assert.deepEqual(replayed.commerceInvoices,original.commerceInvoices);
  const conflict=structuredClone(original),duplicate=structuredClone(row(conflict));const otherName=JSON.parse(duplicate.actor);otherName.accountName='另一旧姓名';duplicate.actor=serialized(otherName);conflict.commerceInvoiceRequests.push(duplicate);assert.throws(()=>replay(conflict,staff.actor,'commerce-invoice.issue',issue),/冲突/);assert.deepEqual(h.s,original);
});
test('同标识异内容/type/version及未知算法/版本/缺元数据/坏摘要或旧JSON全部拒绝',()=>{
  const h=harness(),p=h.apply(),s=structuredClone(h.s);for(const change of [p=>p.title+=' changed',p=>p.extraPrivate='changed'])assert.throws(()=>{const next=structuredClone(p);change(next);replay(s,user,'commerce-invoice.apply-goods',next);},/不同/);
  for(const change of [r=>r.digestVersion=2,r=>delete r.digestVersion,r=>r.digestAlgorithm='MD5',r=>delete r.digestAlgorithm,r=>r.fingerprint='sha256:bad',r=>r.type='commerce-invoice.issue',r=>{delete r.digestVersion;delete r.digestAlgorithm;r.fingerprint='broken';}]){const next=structuredClone(s);change(next.commerceInvoiceRequests.at(-1));assert.throws(()=>replay(next,user,'commerce-invoice.apply-goods',p),/摘要|明文|操作/);}
  h.run('commerce-invoice.reject',{id:h.inv.id,version:h.inv.version,reason:'原资料待核',requestId:'reject'},finance);const reject=row(h.s),wrong={id:h.inv.id,version:1,reason:'原资料待核',requestId:'reject'};assert.throws(()=>replay(h.s,finance,'commerce-invoice.issue',{...wrong,ticketNumber:'DIFFERENT',file}),/不同|操作/);assert.equal(reject.type,'commerce-invoice.reject');
});
test('幂等前当前工作会话/岗位与本人仍真实核验，撤权/切人不回放成功',()=>{
  const h=harness(),p=h.apply();assert.throws(()=>replay(h.s,other,'commerce-invoice.apply-goods',p),/本人|归属/);const staff=h.staff(),issue={id:h.inv.id,version:h.inv.version,ticketNumber:'AUTH-BLUE',file,requestId:'auth-issue'};h.run('commerce-invoice.issue',issue,staff.actor);const original=structuredClone(h.s),fake=replay.bind(null,original,{...staff.actor,sessionId:'unknown'},'commerce-invoice.issue',issue);assert.throws(fake,/会话|失效/);assert.throws(()=>replay(original,support,'commerce-invoice.issue',issue),/财务|岗位/);
  const current=original.staffAccounts.find(x=>x.id===staff.accountId);h.run('account.revoke',{id:current.id,version:current.version,grantId:staff.grantId,reason:'原岗位结束'},staff.admin);assert.throws(()=>replay(h.s,staff.actor,'commerce-invoice.issue',issue),/失效|未启用|撤/);assert.equal(h.s.commerceInvoices.length,1);
});
test('直接原命令幂等也核唯一结果和当前商品本人根，不find首条或跨根借回执',()=>{
  const h=harness(),p=h.apply();for(const change of [s=>s.commerceInvoices.push(structuredClone(s.commerceInvoices[0])),s=>s.commerceInvoices[0].userId='u2',s=>s.goods[0].userId='u2',s=>s.goods.push(structuredClone(s.goods[0])),s=>s.commerceInvoiceRequests.at(-1).resultId='MISSING',s=>s.commerceInvoices[0].version=0]){const s=structuredClone(h.s);change(s);const before=structuredClone(s);assert.throws(()=>direct(s,user,'commerce-invoice.apply-goods',p),/来源|结果|冲突|本人|唯一|版本/);assert.deepEqual(s,before);}
});
test('typed配置结果不会用同ID发票代替原rule；缺规则/类别串号拒绝',()=>{
  const h=harness({goods:false}),rule=h.rule('goods',{requestId:'typed-rule'}),p=h.lastPayload;
  for(const mutate of [s=>s.commerceInvoiceRules=[],s=>s.commerceInvoiceRules[0].category='fee',s=>s.commerceInvoiceRules.push(structuredClone(s.commerceInvoiceRules[0]))]){const s=structuredClone(h.s);mutate(s);s.commerceInvoices.push({id:rule.id,category:'goods',version:1});assert.throws(()=>direct(s,finance,'commerce-invoice.rule-publish',p),/结果|来源|冲突|唯一/);}
});
test('正常关闭原商品权益后补正可走新摘要，旧普通首次申请成功请求不能重放',()=>{
  const h=harness(),apply=h.apply();h.run('commerce-invoice.reject',{id:h.inv.id,version:h.inv.version,reason:'原资料补正'},finance);const closureId=h.close(),p={id:h.inv.id,version:h.inv.version,...title,requestId:'closed-resubmit'};h.run('commerce-invoice.resubmit',p);assert.equal(row(h.s).fingerprint,digest({type:'commerce-invoice.resubmit',p}));assert.throws(()=>replay(h.s,user,'commerce-invoice.apply-goods',apply),/既有权益|关闭/);const before=structuredClone(h.s),changed=structuredClone(before);changed.goods[0].userId='u2';assert.throws(()=>replay(changed,user,'commerce-invoice.resubmit',p),/来源|本人|闭域|权益/);assert.deepEqual(h.s,before);assert.equal(h.s.privacyClosures.at(-1).id,closureId);
});
test('pure inventory只识别准确两票producer的已知版本；旧明文/坏版本/任意hash仍待核',()=>{
  const h=harness();const p=h.apply();h.run('commerce-invoice.issue',{id:h.inv.id,version:h.inv.version,ticketNumber:'DIRECTORY',file},finance);const closureId=h.close(),base=structuredClone(h.s),inv=privacyCleanupInventory(base,'u1',closureId,{coverage}),index=base.commerceInvoiceRequests.findIndex(x=>x.requestId===p.requestId),entry=inv.items.find(x=>serialized(x.path)===serialized(['commerceInvoiceRequests',index,'fingerprint']));assert.equal(entry.classification,'retained_digest');assert.equal(entry.status,'retain_required');assert.equal(entry.deleteAllowed,false);assert.deepEqual(base,h.s);
  const legacy=structuredClone(base);old(legacy,p.requestId,'commerce-invoice.apply-goods',p);const oldInv=privacyCleanupInventory(legacy,'u1',closureId,{coverage});assert.equal(oldInv.items.find(x=>serialized(x.path)===serialized(['commerceInvoiceRequests',index,'fingerprint'])).classification,'request_plaintext');
  for(const change of [r=>r.digestVersion=7,r=>r.type='invented.digest',r=>r.fingerprint='a'.repeat(64),r=>delete r.digestAlgorithm]){const broken=structuredClone(base);change(broken.commerceInvoiceRequests[index]);const result=privacyCleanupInventory(broken,'u1',closureId,{coverage}),bad=result.items.find(x=>serialized(x.path)===serialized(['commerceInvoiceRequests',index,'fingerprint']));assert.equal(bad.status,'pending_review');assert.notEqual(bad.classification,'retained_digest');assert.equal(bad.deleteAllowed,false);}
  const fake=structuredClone(base);fake.unrecognizedRequests=[{resultId:h.inv.id,type:'commerce-invoice.apply-goods',digestVersion:1,digestAlgorithm:'SHA-256',fingerprint:digest({type:'commerce-invoice.apply-goods',p})}];const arbitrary=privacyCleanupInventory(fake,'u1',closureId,{coverage});assert.ok(arbitrary.unlocated.some(x=>x.container==='unrecognizedRequests'));assert.equal(arbitrary.items.some(x=>x.path[0]==='unrecognizedRequests'&&x.classification==='retained_digest'),false);
});

test('原费用月票同请求回读仍核准确门店/月及唯一结果，其他门店财务不能借本人原请求',()=>{
  const h=harness({goods:false}),month=h.feeSources(),local=h.staff('store-finance'),p={storeId:'xingfu',month,...title,requestId:'fee-root'};h.run('commerce-invoice.apply-fee',p,local.actor);
  for(const [change,expected] of [[s=>s.commerceInvoices[0].month='2026-09',/来源/],[s=>s.commerceInvoices[0].storeId='silver',/来源/],[s=>s.stores.push(structuredClone(s.stores.find(x=>x.id==='xingfu'))),/原工作会话已失效/],[s=>s.commerceInvoiceRequests.at(-1).resultId='MISSING',/结果/]]){const s=structuredClone(h.s);change(s);assert.throws(()=>direct(s,local.actor,'commerce-invoice.apply-fee',p),expected);}
  const otherStore=h.staff('store-finance','silver');assert.throws(()=>replay(h.s,otherStore.actor,'commerce-invoice.apply-fee',p),/本门店|归属|来源/);
});
test('原商品部分退款→red→净额重开真实命令摘要，旧结果互链改变不重建新票',()=>{
  const h=harness();h.apply();const prior=h.inv.id;h.run('commerce-invoice.issue',{id:prior,version:h.inv.version,ticketNumber:'REOPEN-BLUE',file},finance);h.run('goods.case',{id:h.o.id,kind:'refund',skuId:'oil',qty:1,amountCents:1000,reason:'原部分退款'});const caseId=h.o.cases.at(-1).id;h.run('goods.case-review',{id:h.o.id,caseId,decision:'approve',reason:'原核验'},support);h.run('goods.refund',{id:h.o.id,caseId,outcome:'success'},finance);assert.equal(h.inv.status,'red_pending');h.run('commerce-invoice.red',{id:prior,version:h.inv.version,ticketNumber:'REOPEN-RED',file},finance);const p={id:prior,version:h.inv.version,...title,requestId:'net-reapply'};h.run('commerce-invoice.reapply',p);assert.equal(row(h.s).fingerprint,digest({type:'commerce-invoice.reapply',p}));assert.equal(h.inv.replacesId,prior);const before=structuredClone(h.s),after=replay(before,user,'commerce-invoice.reapply',p);assert.deepEqual(after.commerceInvoices,before.commerceInvoices);assert.deepEqual(after.commerceInvoiceRequests,before.commerceInvoiceRequests);
  for(const change of [s=>s.commerceInvoices.at(-1).replacesId='OTHER',s=>s.commerceInvoices[0].replacedById='OTHER',s=>s.commerceInvoices.at(-1).orderId='OTHER']){const s=structuredClone(before);change(s);assert.throws(()=>direct(s,user,'commerce-invoice.reapply',p),/互链|来源/);}
});
test('原成功请求改version/坏作者不能绕校验，同岗位第二账户的相同提交标识保持独立',()=>{
  const h=harness();h.apply();const first=h.staff(),second=h.staff(),p={id:h.inv.id,version:h.inv.version,reason:'原资料不足',requestId:'same-staff-request'};h.run('commerce-invoice.reject',p,first.actor);assert.throws(()=>replay(h.s,first.actor,'commerce-invoice.reject',{...p,version:h.inv.version}),/不同/);const s=structuredClone(h.s);s.commerceInvoiceRequests.at(-1).actor='broken';assert.throws(()=>direct(s,first.actor,'commerce-invoice.reject',p),/作者/);
  // Different real authors may use the same UI request id on separate original
  // sources. This never substitutes the second author for the first old receipt.
  h.createGoods();h.apply('second-source');const otherP={id:h.inv.id,version:h.inv.version,reason:'另一原单资料不足',requestId:p.requestId};h.run('commerce-invoice.reject',otherP,second.actor);const requests=h.s.commerceInvoiceRequests.filter(x=>x.requestId===p.requestId);assert.equal(requests.length,2);assert.notEqual(JSON.parse(requests[0].actor).accountId,JSON.parse(requests[1].actor).accountId);
});
test('实际服务票已知version1目录保留摘要；旧明文仍列待policy及实际ref，坏版本不伪保留',()=>{
  const h=harness({goods:false}),startAt=h.s.now+4*3600000;h.run('booking.create',{storeId:'xingfu',serviceId:'relax',regionId:'home',techId:'lin',startAt,mode:'specified',genderPreference:'any',contactName:'原服务本人',phone:'13800000001',healthConsent:true,identityVerified:true,adultConfirmed:true});h.run('booking.pay',{id:h.b.id,outcome:'success'});h.run('booking.accept',{id:h.b.id},tech);h.run('clock.advance',{minutes:240},finance);h.run('booking.start',{id:h.b.id},tech);h.run('clock.advance',{minutes:h.b.duration},finance);h.run('booking.finish',{id:h.b.id,mode:'normal'},tech);h.run('invoice.apply',{bookingId:h.b.id,...title});const inv=h.s.serviceInvoices[0],p={id:inv.id,version:inv.version,ticketNumber:'SERVICE-DIRECTORY',file,requestId:'service-directory'};h.run('invoice.issue',p,store);const closureId=h.close(),s=structuredClone(h.s),index=s.serviceInvoiceRequests.findIndex(x=>x.requestId===p.requestId),path=['serviceInvoiceRequests',index,'fingerprint'],find=x=>x.items.find(e=>serialized(e.path)===serialized(path));const current=privacyCleanupInventory(s,'u1',closureId,{coverage});assert.equal(find(current).classification,'retained_digest');assert.equal(find(current).status,'retain_required');assert.equal(current.graph.references.some(x=>x.path[0]==='serviceInvoiceRequests'&&x.path.at(-1)==='fingerprint'),false);assert.ok(current.graph.references.some(x=>x.ref===file.ref&&x.path[0]==='serviceInvoices'));assert.deepEqual(s,h.s);
  const legacy=structuredClone(s),r=legacy.serviceInvoiceRequests[index];delete r.digestVersion;delete r.digestAlgorithm;delete r.type;r.fingerprint=serialized({type:'invoice.issue',payload:p});const oldInv=privacyCleanupInventory(legacy,'u1',closureId,{coverage});assert.equal(find(oldInv).classification,'request_plaintext');assert.ok(oldInv.graph.references.some(x=>x.ref===file.ref&&x.path[0]==='serviceInvoiceRequests'));
  for(const value of [true,'1',2]){const broken=structuredClone(s);broken.serviceInvoiceRequests[index].digestVersion=value;const result=find(privacyCleanupInventory(broken,'u1',closureId,{coverage}));assert.notEqual(result.classification,'retained_digest');assert.equal(result.status,'pending_review');assert.equal(result.deleteAllowed,false);}
});
test('坏作者显式空账号/授权字段不能被降成自由Demo成功请求',()=>{
  const h=harness(),p=h.apply(),source=structuredClone(h.s);
  for(const bad of [{accountId:null},{accountId:0},{accountId:''},{grantId:null},{grantId:0},{grantId:''},{accountId:'ACC',grantId:'GRANT'}]){
    const s=structuredClone(source),r=s.commerceInvoiceRequests.find(x=>x.requestId===p.requestId);
    r.actor=serialized({...JSON.parse(r.actor),...bad});const before=structuredClone(s);
    assert.throws(()=>direct(s,user,'commerce-invoice.apply-goods',p),/作者/);
    assert.deepEqual(s,before);
  }
  assert.deepEqual(replay(source,user,'commerce-invoice.apply-goods',p).commerceInvoiceRequests,source.commerceInvoiceRequests);
});
