import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { seed, reduce } from './engine.mjs';
import { serviceFinanceSummary } from './service-finance.mjs';
import { serviceFinanceComposition, serviceFinanceCompositionAllocationSources, serviceFinanceCompositionFingerprint } from './service-finance-composition.mjs';
import { serviceFinanceCompositionReview, serviceFinanceCompositionReviewCommand, prepareServiceFinanceCompositionEvidence, createServiceFinanceCompositionEvidenceValidator, authorizedServiceFinanceCompositionFile } from './service-finance-composition-review.mjs';
import { staffGrantCapabilities } from './staff-accounts.mjs';
import { prepareServicePromotionEvidence } from './service-promotion-file-validation.mjs';
import { commerceInvoiceCommand, feeInvoiceSummary, syncCommerceInvoices } from './commerce-invoices.mjs';

const DAY=86400000,finance={role:'group',job:'finance'},support={role:'group',job:'support'},manager={role:'store',job:'store-manager',storeId:'xingfu'},buyer={role:'user',userId:'u1'},person={role:'user',userId:'u2'},tech={role:'tech',techId:'lin'};
const bytes=new TextEncoder().encode('%PDF-1.4\nactual evidence bytes for cash review\n%%EOF'),blob=new Blob([bytes],{type:'application/pdf'}),file={ref:'invoice-file:'+createHash('sha256').update(bytes).digest('hex'),name:'逐笔原现金分类依据.pdf',type:blob.type,size:blob.size};
function harness(){let s=seed(),seq=0;const h={get s(){return s;},get entry(){return s.serviceFinanceEntries.find(e=>e.bookingId===h.bookingId);},get booking(){return s.bookings.find(b=>b.id===h.bookingId);},get key(){return 'split:'+h.entry.split.id;},proof:(reference='PROOF-'+ ++seq)=>({reference,occurredAt:s.now,file,reason:'原发生时间和实际Blob合成验证'}),
  async run(type,p={},actor=finance){const source=['servicePromoters','servicePromotionInvites','serviceFinanceEntries','serviceFinanceRecoveries'].flatMap(k=>s[k]||[]).find(x=>x.id===(p.id||p.promoterId));const payload={requestId:'ORIGINAL-'+ ++seq,version:source?.version||0,...p},runtime=await prepareServicePromotionEvidence(s,actor,type,payload,{readFile:async()=>blob});s=reduce(s,actor,type,payload,()=>{},runtime);return s;},
  async advance(minutes){while(minutes){const step=Math.min(minutes,44640);await h.run('clock.advance',{minutes:step});minutes-=step;}},
  async setup({cash=true}={}){await h.run('finance.rule-publish',{scope:'global',groupBps:1000,storeBps:500,effectiveAt:s.now,version:0,reason:'显式原H测试规则'});await h.run('service-promotion.agreement-publish',{promoterType:'store-promoter',title:'原协议',body:'本人核实的技术验证协议正文。',effectiveAt:s.now,...h.proof()},support);await h.run('service-promotion.invite',{userId:'u2',promoterType:'store-promoter',expiresAt:s.now+DAY,reason:'原本人邀请'},manager);const invite=s.servicePromotionInvites.at(-1);await h.run('service-promotion.invite-confirm',{id:invite.id,decision:'accept',agreementAccepted:true,agreementId:invite.agreementSnapshot.id,reason:'本人确认'},person);const promoter=s.servicePromoters.find(x=>x.personKind==='user'&&x.personId==='u2');await h.run('service-promotion.identity-review',{id:promoter.id,decision:'verified',...h.proof()},support);await h.run('service-promotion.rule-publish',{promoterType:'store-promoter',firstBps:2000,repeatBps:1000,storeCostBps:5000,csRounding:'floor',concurrency:'completed-created-id',lateFullRefund:'reassign',effectiveAt:s.now,version:0,basis:'显式原C技术配置，不代表财税批准'});await h.run('service-promotion.enter',{promoterId:promoter.id,version:s.users.find(u=>u.id==='u1').serviceBinding.version},buyer);await h.run('booking.create',{storeId:'xingfu',serviceId:'relax',regionId:'home',techId:'lin',startAt:Math.ceil((s.now+4*3600000)/1800000)*1800000,mode:'specified',genderPreference:'any',contactName:'本地合成顾客',phone:'13800000001',healthConsent:true,identityVerified:true,adultConfirmed:true},buyer);h.bookingId=s.bookings.at(-1).id;await h.run('booking.pay',{id:h.bookingId,outcome:'success'},buyer);await h.run('booking.accept',{id:h.bookingId},tech);await h.advance(Math.ceil((h.booking.startAt-s.now)/60000));await h.run('booking.start',{id:h.bookingId},tech);await h.advance(h.booking.duration);await h.run('booking.finish',{id:h.bookingId,mode:'normal'},tech);await h.advance(2881);if(cash)await h.run('finance.split-start',{id:h.entry.id,version:h.entry.version,outcome:'success'});},
  legacy(){delete h.entry.split.cashComposition;delete h.entry.split.cashCompositionRequest;},
  view(key=h.key,actor=finance){return serviceFinanceCompositionReview(s,actor,h.entry.id,key);},
  payload(extra={},key=h.key){const view=h.view(key);return{id:h.entry.id,version:view.entryVersion,sourceKey:key,sourceToken:view.sourceToken,requestId:'REVIEW-'+ ++seq,hCents:1490,csCents:view.facts.normalCents-1490,retainedCsCents:null,allocations:[],basisReference:'原逐笔分类依据-'+seq,basisDescription:'财务按本笔原分类凭据核对，未使用当前目标或默认比例',evidenceRefs:[file],reason:'补核实际历史款',...extra};},
  async command(p,type='finance.composition-confirm',actor=finance,options={},commandContext={}){const prepared=await prepareServiceFinanceCompositionEvidence(s,actor,type,p,{readFile:async()=>blob,getState:()=>s,...options}),next=structuredClone(s);const result=serviceFinanceCompositionReviewCommand(next,actor,type,p,{id:prefix=>prefix+ ++next.seq,validateCompositionEvidence:createServiceFinanceCompositionEvidenceValidator(prepared),...commandContext});s=next;return result;},
  cash(){return structuredClone({bookings:s.bookings,split:h.entry.split,splitHistory:h.entry.splitHistory,returns:h.entry.returns,recoveries:s.serviceFinanceRecoveries});},
  async refund(amount){await h.run('booking.special-aftersale',{id:h.bookingId,requests:[{paymentId:h.booking.payment.id,amountCents:amount}],reason:'真实原客服特批退款'},support);const r=h.booking.refunds.at(-1);await h.run('booking.refund-review',{id:h.bookingId,refundId:r.id,decision:'approve',reason:'原本款金额核准'},support);await h.run('booking.refund-pay',{id:h.bookingId,refundId:r.id,paymentId:h.booking.payment.id,outcome:'success'});},
  invoice(op,p={},actor=finance){const next=structuredClone(s),result=commerceInvoiceCommand(next,actor,'commerce-invoice.'+op,{requestId:'INVOICE-'+ ++seq,...p},{id:prefix=>prefix+ ++next.seq,fail:fail=>{throw Error(fail);},log:()=>{}});syncCommerceInvoices(next);s=next;return result;}
};return h;}
async function oldCash(){const h=harness();await h.setup();h.legacy();return h;}

import { financeView } from './finance-ui.mjs';
import { financeCompositionReviewPanel } from './finance-composition-ui.mjs';
import { resolveAccountActor } from './staff-accounts.mjs';
const decode=value=>value.replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
const render=(h,actor=finance)=>financeView(h.s,actor,['service-finance','entry',h.entry.id],{query:new URLSearchParams()});
function reviewForms(html){return [...html.matchAll(/<form\b([^>]*)>([\s\S]*?)<\/form>/g)].map(([,attrs,body])=>({attrs,body,payload:JSON.parse(decode(/data-payload="([^"]+)"/.exec(attrs)?.[1]||'{}')),command:/data-command="([^"]+)"/.exec(attrs)?.[1]})).filter(x=>['finance.composition-confirm','finance.composition-reconcile'].includes(x.command));}
test('真实旧现金详情有逐笔補核入口，金额为空、实际原现金只读、来源payload不含内部正文',async()=>{const h=await oldCash(),before=structuredClone(h.s),html=render(h),forms=reviewForms(html);assert.equal(forms.length,1);const form=forms[0];assert.equal(form.command,'finance.composition-confirm');assert.equal(form.payload.sourceKey,h.key);assert.equal(form.payload.version,h.entry.version);assert.match(form.payload.sourceToken,/^sha256:[a-f0-9]{64}$/);for(const name of ['hCents','csCents'])assert.match(form.body,new RegExp('name="'+name+'" value="" required min="0" step="0.01" data-unit="yuan"'));assert.match(form.body,/type="file" data-invoice-upload[^>]*required/);assert.match(form.body,/name="basisReference"/);assert.match(form.body,/name="basisDescription"/);assert.match(form.body,/name="reason"/);assert.doesNotMatch(form.body,/name="allocations"|name="actualAt"|name="actualReference"|name="normalCents"/);assert.deepEqual(Object.keys(form.payload).sort(),['id','sourceKey','sourceToken','version']);assert.match(decode(form.attrs),new RegExp(h.key));assert.deepEqual(h.s,before);});
test('原inline已核只给明确更正，全部精确候选payload只读且新金额不预填',async()=>{const h=harness();await h.setup();const forms=reviewForms(render(h));assert.equal(forms.length,1);const form=forms[0];assert.equal(form.command,'finance.composition-reconcile');assert.deepEqual(form.payload.supersedes,h.view().supersedes);assert.equal(form.payload.supersedes.length,1);assert.match(form.payload.supersedes[0].path,/\.cashComposition$/);assert.match(form.payload.supersedes[0].token,/^sha256:/);assert.doesNotMatch(form.body,/name="supersedes"|name="method"|name="allocationPolicySnapshot"|name="allocations"/);assert.match(form.body,/name="hCents" value=""/);});
test('原详情表单payload办理真实命令后可读精确历史槽，更正保留旧凭据与原现金',async()=>{const h=await oldCash(),cash=h.cash(),firstForm=reviewForms(render(h))[0],first=await h.command({...h.payload(),...firstForm.payload});const after=render(h);assert.match(after,/原核定与更正历史/);assert.match(after,new RegExp('data-invoice-id="'+first.id+'"'));assert.match(after,/data-invoice-domain="service-finance-composition"/);assert.match(after,/data-invoice-slot="evidence:0"/);const correction=reviewForms(after)[0];assert.equal(correction.command,'finance.composition-reconcile');await h.command({...h.payload({hCents:1000,csCents:h.entry.split.amountCents-1000}),...correction.payload},correction.command);const current=render(h);assert.match(current,new RegExp('data-invoice-id="'+first.id+'"'));assert.equal((current.match(/data-invoice-slot="evidence:0"/g)||[]).length,2);assert.deepEqual(h.cash(),cash);});
test('原processing与缺实际时间不给补核表单，仍有具体原请求核查原因',async()=>{const h=harness();await h.setup({cash:false});await h.run('finance.split-start',{id:h.entry.id,version:h.entry.version,outcome:'processing'});const unknown=render(h);assert.equal(reviewForms(unknown).length,0);assert.match(unknown,/本笔结果须沿原渠道请求查询/);const old=await oldCash();delete old.entry.split.completedAt;const invalid=render(old);assert.equal(reviewForms(invalid).length,0);assert.match(invalid,/原现金编号、类型、金额或实际成功时间无效/);});
test('普通门店原详情保留，内部核定历史/依据/更正payload不扩到其他岗位',async()=>{const h=await oldCash();await h.command(h.payload({basisReference:'FINANCE-PRIVATE-BASIS',basisDescription:'FINANCE-PRIVATE-DESCRIPTION'}));const store=render(h,{role:'store',job:'store-finance',storeId:'xingfu'});assert.match(store,/实际正常现金H \/ Cs组成/);assert.doesNotMatch(store,/逐笔现金组成补核|FINANCE-PRIVATE|service-finance-composition|composition-reconcile/);for(const actor of [support,{role:'group',job:'operations'},{role:'group',job:'account-admin'},tech,{role:'manager',storeId:'xingfu'},{role:'store',job:'store-finance',storeId:'silver'},{role:'user',userId:'u1'}])assert.equal(financeCompositionReviewPanel(h.s,actor,h.entry.id),'');});
test('待补核成功回退有真实逐原收入行，hidden原号准确且无JSON手填/默认金额',async()=>{const h=await oldCash();await h.command(h.payload());await h.refund(10000);const split=h.entry.split;await h.run('finance.return-start',{id:h.entry.id,version:h.entry.version,splitId:split.id,splitRequestNo:split.requestNo,amountCents:500,outcome:'success'});const ret=h.entry.returns.at(-1),key='return:'+ret.id;delete ret.cashComposition;delete ret.cashCompositionRequest;const form=reviewForms(render(h)).find(x=>x.payload.sourceKey===key);assert.ok(form);assert.match(form.body,new RegExp('name="compositionIncome:0" value="'+h.key+'"'));assert.match(form.body,new RegExp('name="compositionReference:0" value="'+split.requestNo+'"'));for(const field of ['compositionH:0','compositionCs:0'])assert.match(form.body,new RegExp('name="'+field+'" value="" min="0" step="0.01" data-unit="yuan"'));assert.doesNotMatch(form.body,/name="allocations"|type="radio"|selected/);await h.command({...h.payload({hCents:200,csCents:300,allocations:[{incomeSourceId:h.key,incomeRequestNo:split.requestNo,hCents:200,csCents:300}]}),...form.payload},form.command);assert.equal(serviceFinanceComposition(h.s,h.entry.id).known,true);const changed=reviewForms(render(h)).find(x=>x.payload.sourceKey===key);assert.equal(changed.command,'finance.composition-reconcile');assert.match(changed.body,/name="compositionH:0" value="" min="0" step="0.01" data-unit="yuan" max="14.9"/);});
test('其他原未知回退占额仍阻断本回退输入，不把待核收入余额填成0',async()=>{const h=await oldCash();await h.command(h.payload());await h.refund(10000);const split=h.entry.split;await h.run('finance.return-start',{id:h.entry.id,version:h.entry.version,splitId:split.id,splitRequestNo:split.requestNo,amountCents:500,outcome:'success'});const ret=h.entry.returns.at(-1),key='return:'+ret.id;delete ret.cashComposition;delete ret.cashCompositionRequest;await h.run('finance.return-start',{id:h.entry.id,version:h.entry.version,splitId:split.id,splitRequestNo:split.requestNo,amountCents:100,outcome:'processing'});const other=h.entry.returns.at(-1);delete other.cashComposition;delete other.cashCompositionRequest;const html=render(h);assert.equal(reviewForms(html).filter(x=>x.payload.sourceKey===key).length,0);assert.match(html,/其他回退占额尚未核清/);assert.doesNotMatch(html,/name="compositionH:0"[^>]*value="0"/);assert.equal(h.view(key).allocationSources[0].unknownReservedCents,100);});
test('同支付两筆实际店债收入各有独立原source/版本摘要formkey，无默认分配',async()=>{const h=harness();await h.setup({cash:false});await h.advance(30*1440);const debt=h.s.serviceFinanceRecoveries.find(r=>r.entryId===h.entry.id&&r.type==='unshared-release');for(const [amount,reference] of [[2000,'BANK-A'],[debt.amountCents-2000,'BANK-B']])await h.run('finance.recovery-receive',{id:debt.id,amountCents:amount,...h.proof(reference)});for(const record of h.s.serviceFinanceRecoveries.find(r=>r.id===debt.id).records){delete record.cashComposition;delete record.cashCompositionRequest;}const forms=reviewForms(render(h));assert.equal(forms.length,2);const keys=forms.map(x=>/data-management-form="([^"]+)"/.exec(x.attrs)[1]);assert.equal(new Set(keys).size,2);for(const form of forms){assert.match(form.payload.sourceKey,new RegExp('^recovery:'+debt.id+':'));assert.match(decode(form.attrs),new RegExp(form.payload.sourceToken));assert.match(decode(form.attrs),new RegExp(':'+form.payload.version+':'));assert.doesNotMatch(form.body,/compositionIncome:|name="allocations"/);}});
test('真实工作财务与原撤权边界，旧会话或伪岗位不暴露补核表单',async()=>{const h=await oldCash();await h.run('account.enter',{accountId:'DEMO-ADMIN',grantId:'DEMO-ADMIN-GRANT'});const admin={sessionId:h.s.staffSessions.at(-1).id};await h.run('account.create',{name:'页面补核测试财务',job:'finance',reason:'实际管理员建岗'},admin);let account=h.s.staffAccounts.at(-1);if(!account.grants.length)await h.run('account.grant',{id:account.id,version:account.version,job:'finance',reason:'实际管理员授予原财务岗'},admin);account=h.s.staffAccounts.find(a=>a.id===account.id);const grant=account.grants.find(g=>g.job==='finance');await h.run('account.enter',{accountId:account.id,grantId:grant.id});const session={sessionId:h.s.staffSessions.at(-1).id},actual=resolveAccountActor(h.s,session),html=render(h,actual);assert.equal(reviewForms(html).length,1);const oldKey=/data-management-form="([^"]+)"/.exec(reviewForms(html)[0].attrs)[1];assert.notEqual(oldKey,/data-management-form="([^"]+)"/.exec(reviewForms(render(h))[0].attrs)[1]);await h.run('account.revoke',{id:account.id,version:account.version,grantId:grant.id,reason:'实际撤权'},admin);assert.equal(financeCompositionReviewPanel(h.s,actual,h.entry.id),'');assert.equal(financeCompositionReviewPanel(h.s,{role:'group',job:'finance',sessionId:'missing'},h.entry.id),'');});
test('核对说明/原号转义，静态反馈有status语义且金额/附件沿原布局',async()=>{const h=await oldCash();await h.command(h.payload({basisDescription:'<script>original basis</script>',basisReference:'BASIS-<bad>',reason:'<b>核对原因</b>'}));const before=structuredClone(h.s),html=render(h);assert.match(html,/&lt;script&gt;original basis&lt;\/script&gt;/);assert.doesNotMatch(html,/<script>|<b>核对原因/);for(const [,attrs] of html.matchAll(/<p\b([^>]*class="notice[^>]*)>/g)){assert.match(attrs,/role="status"/);assert.doesNotMatch(attrs,/role="button"|data-command|tabindex/);}const form=reviewForms(html)[0];assert.match(form.body,/class="management-grid"/);assert.match(form.body,/class="actions"/);assert.match(form.body,/class="field wide"/);assert.match(form.body,/name="retainedCsCents" value=""/);assert.doesNotMatch(form.attrs,/cashCompositionRequest|sourceFactsToken|sessionId|evidenceRefs/);assert.deepEqual(h.s,before);});
