import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {bookingSeed,bookingCommand} from './booking.mjs';
import {upgradeAccounts,accountCommand,resolveAccountActor} from './staff-accounts.mjs';
import {upgradeFulfilment,fulfilmentBindingToken,fulfilmentCommand,fulfilmentView,fulfilmentPolicyView,fulfilmentEndingSource,captureFulfilmentTransition,tickFulfilment,fulfilmentBlockers,fulfilmentTaskRows} from './fulfilment.mjs';
const MIN=60000,NOW=Date.parse('2026-10-02T09:00+08:00'),user={role:'user',userId:'u1'},lin={role:'tech',techId:'lin'},zhou={role:'tech',techId:'zhou'},manager={role:'store',storeId:'xingfu'},foreign={role:'store',storeId:'silver'},support={role:'group',job:'support'};
function fixture(){
  let s=upgradeFulfilment(upgradeAccounts({...bookingSeed(),now:NOW,seq:0,logs:[],users:[{id:'u1'},{id:'u2'}]})),requests=0;
  const ctx=next=>({id:prefix=>`${prefix}${++next.seq}`,fail:m=>{throw Error(m);},log:()=>{}});
  const bookingRun=(a,type,p={})=>{const next=structuredClone(s),before=structuredClone(next.bookings.find(b=>b.id===p.id)); const result=bookingCommand(next,a,type,p,ctx(next));if(p.id)captureFulfilmentTransition(next,a,before,next.bookings.find(b=>b.id===p.id),type,ctx(next));s=next;return structuredClone(result);};
  const run=(a,type,p={})=>{const next=structuredClone(s),b=next.bookings.find(b=>b.id===p.bookingId);const out=fulfilmentCommand(next,a,type,{requestId:`test-${++requests}`,...(b?{bookingToken:fulfilmentBindingToken(b)}:{}),...p},ctx(next));s=next;return out;};
  const account=(a,type,p={})=>{const next=structuredClone(s),r=accountCommand(next,a,type,{requestId:`account-${++requests}`,...p},ctx(next));s=next;return r;};
  const entry=account(user,'account.enter',{accountId:'DEMO-ADMIN',grantId:'DEMO-ADMIN-GRANT'}),admin=resolveAccountActor(s,entry);
  const create=(job,storeId)=>{const x=account(admin,'account.create',{name:`真实${job}`,reason:'实际职责人员'}),g=account(admin,'account.grant',{id:x.id,version:x.version,job,storeId,reason:'实际岗位授权'}).grants.at(-1),entry=account(user,'account.enter',{accountId:x.id,grantId:g.id});return resolveAccountActor(s,entry);};
  const policy=(extra={})=>run(support,'fulfilment.policy-publish',{version:Math.max(0,...s.fulfilmentPolicies.filter(p=>p.storeId===null).map(p=>p.version)),collectorMode:'tech-store-confirm',noticeMode:'appointment-exception',blockUnconfirmed:false,basis:'仅测试显式配置，正式由用户决定',reason:'验证配置留痕',effectiveAt:s.now,...extra});
  const b=bookingRun(user,'booking.create',{storeId:'xingfu',serviceId:'relax',regionId:'home',techId:'lin',startAt:NOW+240*MIN,mode:'specified',genderPreference:'any',contactName:'测试顾客',phone:'13800000001',healthConsent:true,identityVerified:true,adultConfirmed:true,requestId:'booking-create'}); bookingRun(user,'booking.pay',{id:b.id,outcome:'success'});bookingRun(lin,'booking.accept',{id:b.id});
  return {get s(){return s;},b:b.id,run,bookingRun,account,admin,create,policy,get:()=>s.bookings.find(x=>x.id===b.id),view:a=>fulfilmentView(s,a,b.id),advance:n=>{s.now+=n;tickFulfilment(s);},payload:extra=>({bookingId:b.id,version:fulfilmentView(s,support,b.id).version,...extra}),fact:(a=lin,extra={})=>run(a,'fulfilment.fact-record',{bookingId:b.id,version:fulfilmentView(s,support,b.id).version,kind:'contact',occurredAt:s.now,positionMode:'none',evidence:'实际电话联系记录',...extra}),finish:(kind='normal')=>{s.now=s.bookings.find(x=>x.id===b.id).startAt;bookingRun(lin,'booking.start',{id:b.id});s.now+=kind==='normal'?60*MIN:15*MIN;return bookingRun(lin,kind==='interrupted'?'booking.stop':'booking.finish',{id:b.id,mode:kind,category:'other',reason:'实际结束原因'});},exit:extra=>({bookingId:b.id,departureId:fulfilmentView(s,lin,b.id).departure.id,version:fulfilmentView(s,lin,b.id).departure.version,...extra}),consent:active=>run(lin,'fulfilment.location-consent',{bookingId:b.id,version:fulfilmentView(s,lin,b.id).locationConsent.version,active,basis:'只用于履约及安全核实，位置另行同意，可撤回；历史依规定保留'}),duty:a=>run(support,'fulfilment.duty-save',{version:0,scope:a.role==='group'?'group':'store',storeId:a.storeId,accountId:a.accountId,grantId:a.grantId,startAt:s.now-MIN,endAt:s.now+720*MIN,enabled:true,reason:'实际人工值班安排'})};
}
test('迁移只添空容器，纯投影不造历史事实或安全离开',()=>{const f=fixture(),old=structuredClone(f.s.bookings);upgradeFulfilment(f.s);assert.deepEqual(f.s.bookings,old);const before=structuredClone(f.s);f.view(user);fulfilmentTaskRows(f.s);assert.deepEqual(f.s,before);f.get().status='done';f.get().completedAt=f.s.now;assert.equal(f.view(lin).unknownDeparture,true);assert.equal(f.view(lin).departure,null);});
test('未发布规则不能登记或通知，不能默认联系分钟和未确认结算',()=>{const f=fixture();assert.throws(()=>f.fact(),/尚未发布/);assert.equal(f.view(lin).canRecord,false);f.finish();assert.equal(f.view(lin).departure.contactDueAt,null);assert.deepEqual(fulfilmentBlockers(f.s,f.b),[]);assert.throws(()=>f.run(support,'fulfilment.policy-publish',{version:0,effectiveAt:f.s.now,basis:'依据',reason:'说明',collectorMode:'tech-only',noticeMode:'none'}),/明确选择/);});
test('发布规则记录作者依据版本，未明确分工或一半期限拒绝',()=>{const f=fixture();assert.throws(()=>f.policy({collectorMode:''}),/明确/);assert.throws(()=>f.policy({departureContactMinutes:3}),/同时/);assert.throws(()=>f.policy({departureContactMinutes:8,escalateMinutes:4}),/不得更早/);f.policy();const p=f.s.fulfilmentPolicies[0];assert.equal(p.departureContactMinutes,null);assert.equal(p.publishedBy.job,'support');assert.throws(()=>f.policy({version:0}),/已更新/);assert.throws(()=>f.run(manager,'fulfilment.policy-publish',{}),/无权/);});
test('实际时间与记录时间分别保存，未来及非法日历、预约前事实拒绝',()=>{const f=fixture();f.policy();f.advance(5*MIN);f.fact(lin,{occurredAt:NOW});assert.equal(f.s.fulfilmentRecords[0].facts[0].occurredAt,NOW);assert.equal(f.s.fulfilmentRecords[0].facts[0].recordedAt,NOW+5*MIN);for(const at of [f.s.now+1,NOW-1,'2026-02-30T12:00',true])assert.throws(()=>f.fact(lin,{occurredAt:at}),/时间/);assert.throws(()=>f.fact(lin,{kind:'late'}),/早于预约/);});
test('覆盖核验必须有实际地点与依据，片区不自动伪装GPS',()=>{const f=fixture();f.policy();assert.throws(()=>f.fact(lin,{kind:'location',coverage:'inside',coverageBasis:'仅片区'}),/没有实际地点/);assert.throws(()=>f.fact(lin,{kind:'location',coverage:'inside',positionMode:'manual',place:'客户实际说明',coverageBasis:''}),/核验依据/);f.fact(lin,{kind:'location',coverage:'unknown',coverageBasis:'定位失败，人工核实中',positionMode:'failed',positionFailure:'设备不可用，请人工联系'});const fact=f.s.fulfilmentRecords[0].facts[0];assert.equal(fact.coverage.result,'unknown');assert.equal(fact.position.lat,undefined);assert.equal(fact.coverage.storeSnapshot.id,'xingfu');});
test('GPS另行同意且不能补造采样前同意；撤回拒绝新位置，失败保存最后点',()=>{const f=fixture();f.policy();const gps={kind:'location',positionMode:'gps',place:'实际采样地点',lat:0,lng:0,coverage:'unknown',coverageBasis:'等待人工核实'};assert.throws(()=>f.fact(lin,gps),/单独同意/);f.advance(MIN);f.consent(true);assert.throws(()=>f.fact(lin,{...gps,occurredAt:NOW}),/采样前/);f.fact(lin,gps);assert.equal(f.s.fulfilmentRecords[0].facts[0].position.lat,0);f.fact(lin,{...gps,positionMode:'failed',positionFailure:'定位失败，沿用最后点',lastKnownAt:f.s.now});f.consent(false);assert.throws(()=>f.fact(lin,gps),/单独同意/);assert.equal(f.s.fulfilmentRecords[0].facts.length,2);assert.throws(()=>f.run(manager,'fulfilment.location-consent',{bookingId:f.b,version:2,active:true,basis:'代同意'}),/本人/);});
test('手工说明不接受坐标，坐标成对及范围严格校验',()=>{const f=fixture();f.policy();f.consent(true);for(const extra of [{positionMode:'manual',place:'说明',lat:1,lng:2},{positionMode:'gps',place:'说明',lat:1},{positionMode:'gps',place:'说明',lat:true,lng:2},{positionMode:'gps',place:'说明',lat:91,lng:2}])assert.throws(()=>f.fact(lin,extra),/坐标|经纬度/);});
test('门店补录等待原技师确认，客服先核实不能跳过技师',()=>{const f=fixture();f.policy();f.fact(manager);let fact=f.s.fulfilmentRecords[0].facts[0];assert.equal(fact.status,'pending-tech');f.run(support,'fulfilment.fact-verify',f.payload({factId:fact.id,decision:'verified',evidence:'核对实际联系凭证'}));fact=f.s.fulfilmentRecords[0].facts[0];assert.equal(fact.status,'pending-tech');f.run(lin,'fulfilment.fact-confirm',f.payload({factId:fact.id,decision:'accept',reason:'本人确认实际发生'}));assert.equal(f.s.fulfilmentRecords[0].facts[0].status,'verified');});
test('补录拒绝保留分歧和作者；更正追加原事实不覆盖',()=>{const f=fixture();f.policy();f.fact(manager);const source=structuredClone(f.s.fulfilmentRecords[0].facts[0]);f.run(lin,'fulfilment.fact-confirm',f.payload({factId:source.id,decision:'reject',reason:'时间不正确'}));assert.equal(f.s.fulfilmentRecords[0].facts[0].status,'disputed');f.run(manager,'fulfilment.fact-correct',f.payload({factId:source.id,occurredAt:f.s.now,positionMode:'none',evidence:'改为核实后的实际时间',reason:'电话凭证核验时间'}));const [old,newFact]=f.s.fulfilmentRecords[0].facts;assert.equal(old.evidence,source.evidence);assert.equal(newFact.replacesFactId,old.id);assert.equal(old.replacedBy,newFact.id);assert.equal(newFact.status,'pending-tech');assert.throws(()=>f.run(support,'fulfilment.fact-verify',f.payload({factId:old.id,decision:'verified',evidence:'尝试旧记录'})),/更正/);});
test('改派拒绝旧页面，新技师不能确认原技师补录，原技师刷新可核实',()=>{const f=fixture();f.policy();f.fact(manager);const oldToken=fulfilmentBindingToken(f.get()),fact=f.s.fulfilmentRecords[0].facts[0];f.get().techId='zhou';assert.throws(()=>f.run(lin,'fulfilment.fact-confirm',f.payload({bookingToken:oldToken,factId:fact.id,decision:'accept',reason:'旧页面'})),/变化/);assert.throws(()=>f.run(zhou,'fulfilment.fact-confirm',f.payload({factId:fact.id,decision:'accept',reason:'不能代替'})),/原技师/);f.run(lin,'fulfilment.fact-confirm',f.payload({factId:fact.id,decision:'accept',reason:'原技师实际确认'}));assert.equal(f.s.fulfilmentRecords[0].facts[0].confirmations[0].by.id,'lin');});
test('版本防止异步覆盖，原请求同内容重试幂等且换内容拒绝',()=>{const f=fixture();f.policy();const p={bookingId:f.b,bookingToken:fulfilmentBindingToken(f.get()),version:0,requestId:'fixed-request',kind:'contact',occurredAt:f.s.now,positionMode:'none',evidence:'相同事实'};const result=f.run(lin,'fulfilment.fact-record',p);assert.deepEqual(f.run(lin,'fulfilment.fact-record',p),result);assert.equal(f.s.fulfilmentRecords[0].facts.length,1);assert.throws(()=>f.run(lin,'fulfilment.fact-record',{...p,evidence:'不同内容'}),/不同内容/);assert.throws(()=>f.fact(lin,{version:0}),/已更新/);assert.ok(!('evidence' in result));});
test('岗位、用户、门店严格最小投影，读取不泄漏实际位置和证明',()=>{const f=fixture();f.policy();f.consent(true);f.fact(lin,{positionMode:'gps',place:'私密地点',lat:30,lng:120});assert.equal(f.view(user).facts.length,0);assert.equal(f.view(user).departure,null);assert.equal(f.view(foreign),null);assert.equal(f.view({role:'group',job:'finance'}),null);assert.equal(f.view(zhou),null);assert.equal(f.view(support).facts[0].position.lat,undefined);f.finish();const t=f.view(lin).facts[0];assert.equal(t.evidence,undefined);assert.equal(t.position.place,undefined);});
test('正常、提前和中止创建独立待确认事实，不读取伪造旧离开',()=>{for(const kind of ['normal','early','interrupted']){const f=fixture();f.policy();f.finish(kind);const row=f.view(lin).departure;assert.equal(row.endingKind,kind);assert.equal(row.status,'pending');assert.equal(row.safeLeftFact,null);assert.equal(row.endingAt,kind==='interrupted'?f.get().stoppedAt:f.get().completedAt);const before=structuredClone(f.s);tickFulfilment(f.s);assert.equal(f.s.fulfilmentDepartures.length,1);assert.deepEqual(f.s.bookings,before.bookings);assert.equal(captureFulfilmentTransition(f.s,lin,f.get(),f.get(),'booking.finish'),f.s.fulfilmentDepartures[0]);}});
test('安全计时冻结原生效快照，重发政策不延期，旧单不补造',()=>{const f=fixture();f.policy({departureContactMinutes:3,escalateMinutes:6,blockUnconfirmed:true});f.finish();const initial=f.view(lin).departure;f.policy({departureContactMinutes:30,escalateMinutes:60});assert.deepEqual(fulfilmentBlockers(f.s,f.b).length,1);f.advance(3*MIN);assert.equal(f.view(lin).departure.status,'contacting');f.advance(3*MIN);assert.equal(f.view(lin).departure.status,'escalated');assert.equal(f.view(lin).departure.escalationDueAt,initial.escalationDueAt);assert.equal(f.s.fulfilmentDepartures[0].contacts.length,0,'系统计时不声称已实际联系');});
test('实际安全离开时间独立于服务结束，确认不改任何原预约与资金',()=>{const f=fixture();f.finish('early');f.advance(2*MIN);const original=structuredClone({bookings:f.s.bookings,safety:f.s.safety}),r=f.run(lin,'fulfilment.departure-confirm',f.exit({safeLeft:true,occurredAt:f.s.now,evidence:'本人已经安全离开',positionMode:'none'}));assert.equal(r.status,'confirmed');assert.deepEqual({bookings:f.s.bookings,safety:f.s.safety},original);assert.deepEqual(fulfilmentBlockers(f.s,f.b),[]);});
test('未离开不能宣称已确认；求助后确认只能待核实，并保留原求助/争议',()=>{const f=fixture();f.finish('interrupted');assert.throws(()=>f.run(lin,'fulfilment.departure-confirm',f.exit({safeLeft:false,occurredAt:f.s.now,evidence:'尚未离开'})),/尚未安全/);f.run(lin,'fulfilment.departure-help',f.exit({reason:'实际仍有危险',positionMode:'failed',positionFailure:'设备定位失败，人工联系值班'}));assert.equal(fulfilmentBlockers(f.s,f.b).length,1);const source=structuredClone(f.get());f.advance(MIN);f.run(lin,'fulfilment.departure-confirm',f.exit({safeLeft:true,occurredAt:f.s.now,evidence:'实际已经安全离开'}));assert.equal(f.view(lin).departure.status,'awaiting_verification');assert.equal(fulfilmentBlockers(f.s,f.b).length,1);assert.deepEqual(f.get(),source);});
test('失败和未知联系不能宣称安全，人工联系不会自行结案',()=>{const f=fixture();f.finish();for(const outcome of ['failed','unknown']){assert.throws(()=>f.run(manager,'fulfilment.departure-contact',f.exit({channel:'phone',outcome,safetyOutcome:'safe-left',occurredAt:f.s.now,evidence:'没有实际联系成功'})),/未联系成功/);f.run(manager,'fulfilment.departure-contact',f.exit({channel:'phone',outcome,safetyOutcome:'unknown',occurredAt:f.s.now,evidence:'实际拨打未接通'}));}assert.equal(f.view(manager).departure.status,'contacting');assert.equal(f.view(manager).departure.contacts.length,2);assert.throws(()=>f.run(manager,'fulfilment.departure-resolve',f.exit({method:'contact-confirmation',occurredAt:f.s.now,evidence:'未接通'})),/尚无实际联系成功/);});
test('无值班名单不能接管，自由文本姓名不能替代真实工作授权',()=>{const f=fixture();f.finish();assert.throws(()=>f.run(support,'fulfilment.duty-save',{version:0,scope:'group',accountId:'虚构姓名',grantId:'X',startAt:f.s.now,endAt:f.s.now+MIN,enabled:true,reason:'自由文字'}),/已启用/);assert.throws(()=>f.run(support,'fulfilment.departure-takeover',f.exit({reason:'演示身份'})),/值班工作账号/);const a=f.create('support');assert.throws(()=>f.run(a,'fulfilment.departure-takeover',f.exit({reason:'非值班'})),/值班工作账号/);});
test('实际值班限定范围期限，升级只能集团接管，终态不能重复办理',()=>{const f=fixture();const a=f.create('support'),m=f.create('store-manager','xingfu');f.duty(a);f.duty(m);f.finish();f.run(manager,'fulfilment.departure-escalate',f.exit({reason:'人工核实发现风险'}));assert.throws(()=>f.run(m,'fulfilment.departure-takeover',f.exit({reason:'已升级'})),/集团接管/);f.run(a,'fulfilment.departure-takeover',f.exit({reason:'当前集团值班接管'}));assert.equal(f.view(a).departure.owner.accountId,a.accountId);f.run(a,'fulfilment.departure-resolve',f.exit({method:'onsite-verification',occurredAt:f.s.now,evidence:'已实际现场核实本人安全离开'}));assert.deepEqual(fulfilmentBlockers(f.s,f.b),[]);assert.throws(()=>f.run(a,'fulfilment.departure-escalate',f.exit({reason:'重复升级'})),/已有核实结果/);});
test('原责任账号停用后失效，不能结案，新的有效值班必须接管',()=>{const f=fixture(),a=f.create('support'),other=f.create('support');f.duty(a);f.duty(other);f.finish();f.run(lin,'fulfilment.departure-help',f.exit({reason:'离开前实际求助'}));f.run(a,'fulfilment.departure-takeover',f.exit({reason:'实际接管'}));const account=f.s.staffAccounts.find(x=>x.id===a.accountId);f.account(f.admin,'account.status',{id:a.accountId,version:account.version,enabled:false,reason:'实际离职'});assert.equal(f.view(support).departure.ownerValid,false);assert.ok(fulfilmentBlockers(f.s,f.b)[0].includes('失效'));assert.throws(()=>f.run(a,'fulfilment.departure-resolve',f.exit({method:'onsite-verification',occurredAt:f.s.now,evidence:'旧权限'})),/失效/);assert.throws(()=>f.run(other,'fulfilment.departure-resolve',f.exit({method:'onsite-verification',occurredAt:f.s.now,evidence:'尚未接管'})),/接管责任人/);f.run(other,'fulfilment.departure-takeover',f.exit({reason:'新的实际值班接管'}));assert.equal(f.view(other).departure.ownerValid,true);});
test('值班结束不撤销已接管事实；高风险结案必须有真实安全依据',()=>{const f=fixture(),a=f.create('support');f.duty(a);f.finish();f.run(lin,'fulfilment.departure-help',f.exit({reason:'实际求助'}));f.run(a,'fulfilment.departure-takeover',f.exit({reason:'当班接管'}));f.advance(721*MIN);assert.equal(f.view(a).departure.ownerValid,true);assert.throws(()=>f.run(a,'fulfilment.departure-resolve',f.exit({method:'tech-confirmation',occurredAt:f.s.now,evidence:'没有技师确认'})),/尚无技师/);assert.throws(()=>f.run(a,'fulfilment.departure-resolve',f.exit({method:'onsite-verification',occurredAt:f.s.now,evidence:''})),/结案核实依据/);});
test('安全核实只解除本来源，原求助和资金争议仍保留待办',()=>{const f=fixture(),a=f.create('support');f.duty(a);f.finish('interrupted');f.s.safety.push({id:'HELP-original',bookingId:f.b,status:'escalated'});f.run(lin,'fulfilment.departure-help',f.exit({reason:'未安全离开'}));f.run(a,'fulfilment.departure-takeover',f.exit({reason:'实际值班接管'}));const before=structuredClone({bookings:f.s.bookings,safety:f.s.safety});f.run(a,'fulfilment.departure-resolve',f.exit({method:'onsite-verification',occurredAt:f.s.now,evidence:'已经现场核实安全'}));assert.deepEqual({bookings:f.s.bookings,safety:f.s.safety},before);assert.equal(f.view(a).departure.resolution.remainingSourceIssues[0].id,'HELP-original');});
test('真实通知结果与本人已读分开，失败不声称发送成功、不给技师内部证明',()=>{const f=fixture();f.policy();f.run(manager,'fulfilment.notice-record',{bookingId:f.b,version:0,kind:'exception',channel:'phone',outcome:'failed',summary:'预约异常需要联系核实',evidence:'实际拨打未接通，仍需人工跟进',occurredAt:f.s.now});const u=f.view(user).notices[0];assert.equal(u.outcome,'failed');assert.equal(u.evidence,undefined);assert.equal(u.recordedBy,undefined);assert.equal(f.view(lin).notices.length,0);f.run(user,'fulfilment.notice-ack',{bookingId:f.b,noticeId:u.id,version:u.version});assert.ok(f.view(user).notices[0].ack);assert.throws(()=>f.run({role:'user',userId:'u2'},'fulfilment.notice-ack',{bookingId:f.b,noticeId:u.id,version:1}),/无权/);});
test('待办与配置只投影本店/客服最小元数据；停用责任为无效来源',()=>{const f=fixture(),a=f.create('support');f.duty(a);f.policy();f.fact(manager,{positionMode:'manual',place:'私密地点',evidence:'私密证明'});f.finish();f.run(a,'fulfilment.departure-takeover',f.exit({reason:'实际接管'}));const rows=fulfilmentTaskRows(f.s);assert.ok(rows.some(r=>r.category==='fulfilment'));assert.ok(rows.some(r=>r.category==='safe-departure'));assert.ok(!JSON.stringify(rows).includes('私密'));assert.equal(rows.find(r=>r.category==='safe-departure').nativeOwnerValid,true);assert.equal(fulfilmentPolicyView(f.s,user),null);assert.equal(fulfilmentPolicyView(f.s,{role:'group',job:'finance'}),null);assert.equal(fulfilmentPolicyView(f.s,foreign).rosters.length,0);});
test('门店独立规则覆盖通用分工，未来政策不会提前生效',()=>{const f=fixture();f.policy({effectiveAt:f.s.now+MIN});assert.throws(()=>f.fact(),/尚未发布/);f.advance(MIN);f.fact();f.policy({storeId:'xingfu',collectorMode:'store-only',version:0});assert.equal(f.view(lin).canRecord,false);assert.equal(f.view(manager).canRecord,true);assert.throws(()=>f.fact(lin),/无权/);f.fact(manager);assert.equal(f.s.fulfilmentRecords[0].facts.at(-1).status,'reported');});
test('安全离开不得在服务结束前发生，多次求助追加，确认事实不覆盖',()=>{const f=fixture();f.finish();assert.throws(()=>f.run(lin,'fulfilment.departure-confirm',f.exit({safeLeft:true,occurredAt:f.s.now-1,evidence:'早于服务结束'})),/实际发生时间/);for(const reason of ['第一次真实求助','第二次真实补充'])f.run(lin,'fulfilment.departure-help',f.exit({reason}));assert.equal(f.s.fulfilmentDepartures[0].help.reason,'第一次真实求助');assert.equal(f.s.fulfilmentDepartures[0].helpRecords.length,2);f.run(lin,'fulfilment.departure-confirm',f.exit({safeLeft:true,occurredAt:f.s.now,evidence:'本人实际安全离开'}));assert.throws(()=>f.run(lin,'fulfilment.departure-confirm',f.exit({safeLeft:true,occurredAt:f.s.now,evidence:'试图替换依据'})),/不得覆盖/);assert.equal(f.s.fulfilmentDepartures[0].safeLeftFact.evidence,'本人实际安全离开');});
test('值班变更保留前后实际时段；跨店授权、结束时段和旧版本拒绝',()=>{const f=fixture(),m=f.create('store-manager','xingfu'),row=f.duty(m);assert.throws(()=>f.run(manager,'fulfilment.duty-save',{id:row.id,version:row.version,scope:'store',storeId:'silver',accountId:m.accountId,grantId:m.grantId,startAt:f.s.now,endAt:f.s.now+MIN,enabled:true,reason:'跨店'}),/本店|不一致/);assert.throws(()=>f.run(manager,'fulfilment.duty-save',{id:row.id,version:row.version,scope:'store',storeId:'xingfu',accountId:m.accountId,grantId:m.grantId,startAt:f.s.now,endAt:f.s.now,enabled:true,reason:'无效时段'}),/晚于/);f.run(manager,'fulfilment.duty-save',{id:row.id,version:row.version,scope:'store',storeId:'xingfu',accountId:m.accountId,grantId:m.grantId,startAt:f.s.now,endAt:f.s.now+MIN,enabled:false,reason:'真实排班调整'});const updated=f.s.fulfilmentDutyRosters[0];assert.equal(updated.history.at(-1).previous.enabled,true);assert.equal(updated.history.at(-1).current.enabled,false);assert.equal(updated.history.at(-1).previous.endAt,NOW+720*MIN);});
test('主管可停用本店失效的旧值班安排，但不能恢复失效授权',()=>{const f=fixture(),m=f.create('store-manager','xingfu'),r=f.duty(m),account=f.s.staffAccounts.find(x=>x.id===m.accountId);f.account(f.admin,'account.status',{id:m.accountId,version:account.version,enabled:false,reason:'实际人员停用'});const p={id:r.id,version:r.version,scope:'store',storeId:'xingfu',accountId:m.accountId,grantId:m.grantId,startAt:r.startAt || NOW-MIN,endAt:NOW+720*MIN,reason:'撤下失效的旧安排'};assert.throws(()=>f.run(manager,'fulfilment.duty-save',{...p,enabled:true}),/已启用/);f.run(manager,'fulfilment.duty-save',{...p,enabled:false});assert.equal(f.s.fulfilmentDutyRosters[0].enabled,false);});
test('取消实际联系事实独立留痕，不手改原状态或原取消费用',()=>{const f=fixture();f.policy();f.advance(5*MIN);const old=structuredClone(f.get());f.fact(manager,{kind:'cancel',occurredAt:NOW,evidence:'顾客实际电话提出取消，等待原取消流程处理'});assert.deepEqual(f.get(),old);const fact=f.s.fulfilmentRecords[0].facts[0];assert.equal(fact.kind,'cancel');assert.equal(fact.occurredAt,NOW);assert.equal(fact.recordedAt,NOW+5*MIN);assert.equal(fact.recordedBy.id,'xingfu');});
const hash=v=>createHash('sha256').update(v).digest('hex');
const canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;
const canonicalText=v=>JSON.stringify(canonical(v));
function legacy(f,kind='normal'){f.finish(kind);f.s.fulfilmentDepartures=[];return fulfilmentEndingSource(f.s,f.get());}
function recognize(f,a=manager,extra={}){const source=fulfilmentEndingSource(f.s,f.get());return f.run(a,'fulfilment.departure-history',{bookingId:f.b,version:0,endingSourceToken:source.sourceToken,sourceEvidence:'对照原接单快照与原结束记录，技师和实际结束一致',reason:'旧单未采集离开，现登记待实际核实',...extra});}
test('同步SHA-256与Node标准实现一致，UTF8长内容不保存在请求或任务令牌',()=>{for(const content of ['', 'abc','中文🙂事实'.repeat(1000),'a'.repeat(100000)]){const s=upgradeFulfilment({fulfilmentRequests:[{requestId:'legacy',who:'{}',content,result:{id:'X'}}]});assert.equal(s.fulfilmentRequests[0].fingerprint,hash(content));assert.equal(s.fulfilmentRequests[0].digestAlgorithm,'SHA-256');assert.ok(!('content' in s.fulfilmentRequests[0]));}const f=fixture();f.policy();f.consent(true);const payload={bookingId:f.b,bookingToken:fulfilmentBindingToken(f.get()),version:0,requestId:'digest-known',kind:'contact',occurredAt:f.s.now,positionMode:'gps',place:'私密位置说明',lat:30,lng:120,evidence:'私密正文'};f.run(lin,'fulfilment.fact-record',payload);const req=f.s.fulfilmentRequests.at(-1);assert.equal(req.fingerprint,hash(canonicalText({type:'fulfilment.fact-record',p:payload})));assert.equal(req.actorDigest,hash(canonicalText({role:'tech',id:'lin'})));assert.ok(!JSON.stringify(req).includes('私密'));assert.ok(!('who' in req));assert.equal(req.recordedAt,f.s.now);assert.ok(!JSON.stringify(fulfilmentTaskRows(f.s)).includes('私密'));});
test('旧请求增量去正文且重试仍幂等，不修改实际事实或补造记录时间',()=>{const f=fixture();f.policy();const p={bookingId:f.b,bookingToken:fulfilmentBindingToken(f.get()),version:0,requestId:'old-content',kind:'contact',occurredAt:f.s.now,positionMode:'none',evidence:'旧请求正文'};const output=f.run(lin,'fulfilment.fact-record',p),before=structuredClone(f.s.fulfilmentRecords);f.s.fulfilmentRequests=[{requestId:p.requestId,who:canonicalText({role:'tech',id:'lin',job:null}),content:canonicalText({type:'fulfilment.fact-record',p}),result:output}];upgradeFulfilment(f.s);assert.deepEqual(f.run(lin,'fulfilment.fact-record',p),output);assert.deepEqual(f.s.fulfilmentRecords,before);assert.equal(f.s.fulfilmentRequests[0].recordedAt,undefined);assert.ok(!JSON.stringify(f.s.fulfilmentRequests).includes('旧请求正文'));const once=structuredClone(f.s);upgradeFulfilment(f.s);assert.deepEqual(f.s,once);});
test('历史正常、提前、中止只绑定原结束和原技师，补认不自动产生已离开',()=>{for(const kind of ['normal','early','interrupted']){const f=fixture(),source=legacy(f,kind);assert.equal(source.available,true);assert.equal(source.endingKind,kind);f.advance(24*60*MIN);const original=structuredClone({bookings:f.s.bookings,safety:f.s.safety});recognize(f);const exit=f.s.fulfilmentDepartures[0];assert.equal(exit.status,'pending');assert.equal(exit.safeLeftFact,null);assert.equal(exit.endingAt,source.endingAt);assert.equal(exit.techId,source.techId);assert.equal(exit.historicalRecognition.occurredAt,source.endingAt);assert.equal(exit.historicalRecognition.recordedAt,f.s.now);assert.equal(exit.historicalRecognition.by.id,'xingfu');assert.equal(exit.policySnapshot,null);assert.equal(exit.contactDueAt,null);assert.deepEqual({bookings:f.s.bookings,safety:f.s.safety},original);}});
test('缺少真实原结束或技师来源时历史入口拒绝，不能凭当前技师与预约时刻补造',()=>{const f=fixture();legacy(f);delete f.get().techIncomeSnapshot;f.get().techIncomeSnapshots=[];assert.equal(fulfilmentEndingSource(f.s,f.get()).available,false);assert.equal(f.view(manager).canRecognizeHistory,false);assert.throws(()=>recognize(f,manager,{techId:'lin',endingAt:f.get().startAt}),/来源不足/);assert.equal(f.s.fulfilmentDepartures.length,0);f.get().events=[{at:f.get().completedAt,actor:'tech',actorId:'lin',text:f.get().finishReason}];assert.equal(fulfilmentEndingSource(f.s,f.get()).available,true);delete f.get().completedAt;assert.equal(fulfilmentEndingSource(f.s,f.get()).available,false);});
test('历史中止采用原中止作者，裁定后completedAt不改原结束类型',()=>{const f=fixture();legacy(f,'interrupted');const d=f.get().disputes.find(x=>x.kind==='interruption');assert.equal(d.createdBy.id,'lin');f.get().status='done';f.get().completedAt=f.get().stoppedAt;f.get().completionKind='adjudicated-user';f.get().finishReason='中止核实处理后';f.get().techId='zhou';const source=fulfilmentEndingSource(f.s,f.get());assert.equal(source.sourceKind,'original-interruption');assert.equal(source.techId,'lin');assert.equal(source.endingKind,'interrupted');recognize(f);assert.equal(f.view(lin).departure.techId,'lin');assert.equal(f.view(zhou).departure,null);assert.throws(()=>f.run(zhou,'fulfilment.departure-confirm',f.exit({safeLeft:true,occurredAt:f.s.now,evidence:'不是原技师'})),/实际服务技师/);});
test('历史补认需明确来源证据和版本，技师本人、异店和其他岗位不能建立',()=>{const f=fixture();legacy(f);for(const a of [lin,user,foreign,{role:'group',job:'finance'}])assert.throws(()=>recognize(f,a),/无权|主管|客服/);assert.throws(()=>recognize(f,manager,{sourceEvidence:''}),/核对依据/);assert.throws(()=>recognize(f,manager,{version:1}),/已更新/);assert.throws(()=>recognize(f,manager,{endingSourceToken:'stale'}),/来源已变化/);assert.equal(f.s.fulfilmentDepartures.length,0);});
test('原结束技师快照异步变化拒绝旧页，补認后保留原来源快照',()=>{const f=fixture();const source=legacy(f);f.get().techIncomeSnapshot.techId='zhou';assert.throws(()=>recognize(f,manager,{endingSourceToken:source.sourceToken}),/来源已变化/);recognize(f);const snapshot=structuredClone(f.s.fulfilmentDepartures[0].endingSourceSnapshot);f.get().techIncomeSnapshot.techId='lin';assert.deepEqual(f.s.fulfilmentDepartures[0].endingSourceSnapshot,snapshot);assert.equal(snapshot.techId,'zhou');});
test('历史补认幂等，已有安全事项不另建；核实仍需实际安全事实',()=>{const f=fixture();legacy(f);f.advance(24*60*MIN);const p={requestId:'history-once'};const out=recognize(f,manager,p);assert.deepEqual(recognize(f,manager,p),out);assert.equal(f.s.fulfilmentDepartures.length,1);assert.throws(()=>recognize(f),/已有独立安全/);assert.throws(()=>f.run(manager,'fulfilment.departure-resolve',f.exit({method:'contact-confirmation',occurredAt:f.s.now,evidence:'还没联系'})),/尚无实际联系成功/);f.run(manager,'fulfilment.departure-contact',f.exit({channel:'phone',outcome:'success',safetyOutcome:'safe-left',occurredAt:f.s.now,evidence:'实际拨通，技师确认原日已安全离开'}));const before=structuredClone(f.get());f.run(manager,'fulfilment.departure-resolve',f.exit({method:'contact-confirmation',occurredAt:f.get().completedAt+MIN,evidence:'联系原技师及值班记录，原实际离开时间为结束后一分钟'}));const exit=f.s.fulfilmentDepartures[0];assert.equal(exit.status,'resolved');assert.equal(exit.resolution.occurredAt,before.completedAt+MIN);assert.equal(exit.resolution.recordedAt,f.s.now);assert.deepEqual(f.get(),before);});
test('补认旧结束不套以后发布的政策或重新计时',()=>{const f=fixture();const source=legacy(f);f.advance(MIN);f.policy({effectiveAt:source.endingAt-60*MIN,departureContactMinutes:3,escalateMinutes:6,blockUnconfirmed:true});recognize(f);const row=f.s.fulfilmentDepartures[0];assert.equal(row.policySnapshot,null);assert.equal(row.contactDueAt,null);assert.equal(row.escalationDueAt,null);assert.deepEqual(fulfilmentBlockers(f.s,f.b),[]);});





