import test from 'node:test';
import assert from 'node:assert/strict';
import { seed, reduce, goodsSummary, money } from './engine.mjs';
import { goodsBillSettlementPanel, goodsRecoverySettlementPanel } from './goods-settlement-ui.mjs';
const user={role:'user',userId:'u1'},finance={role:'group',job:'finance'},support={role:'group',job:'support'},warehouse={role:'group',job:'warehouse'},store={role:'store',storeId:'xingfu'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const decode=v=>v.replace(/&quot;|&#39;|&lt;|&gt;|&amp;/g,c=>({'&quot;':'"','&#39;':"'",'&lt;':'<','&gt;':'>','&amp;':'&'}[c]));
const ui={esc,money,date:v=>v?new Date(v).toISOString():'—',field:(label,name,value='',type='text',attrs='')=>`<label class="field"><span>${esc(label)}</span><input name="${esc(name)}" value="${esc(value)}" type="${esc(type)}" ${attrs}></label>`,link:(label,path,kind='')=>`<a href="#${esc(path)}" class="${esc(kind)}">${esc(label)}</a>`};
function forms(html,type){return[...html.matchAll(/<form\b([^>]*)>([\s\S]*?)<\/form>/g)].map(([,raw,body])=>{const attrs=Object.fromEntries([...raw.matchAll(/([\w-]+)="([^"]*)"/g)].map(([,k,v])=>[k,decode(v)]));return{command:attrs['data-command'],payload:JSON.parse(attrs['data-payload']||'{}'),body};}).filter(x=>!type||x.command===type);}
function fixture(){let s=seed(),n=0;const f={get s(){return s;},get b(){return s.bills.at(-1);},get p(){return s.goodsOffsetPlans.at(-1);},run(type,p={},a=user){s=reduce(s,a,type,{requestId:`ui-settlement-${++n}`,...p});},submit(form,p={},a=finance){assert.ok(form,'当前状态应提供该表单');f.run(form.command,{...form.payload,...p},a);},page(a=finance,b=f.b){return goodsBillSettlementPanel(s,a,b,ui,{goodsSummary});},create(){f.run('promotion.enter',{storeId:'xingfu'});f.run('cart.set',{skuId:'oil',qty:1});f.run('goods.submit',{addressId:'AD1'});const id=s.goods.at(-1).id;f.run('goods.pay',{id,outcome:'success'});f.run('goods.ship',{id,carrier:'物流',tracking:`UI-${n}`},warehouse);f.run('goods.receive',{id});return id;},bill(){f.run('clock.advance',{minutes:10080});f.run('bill.create',{storeId:'xingfu'},finance);return f.b;},pay(){f.run('bill.confirm',{id:f.b.id,version:f.b.version},store);f.run('bill.pay',{id:f.b.id,outcome:'processing'},finance);f.run('bill.query',{id:f.b.id,outcome:'success'},finance);},refund(id){f.run('goods.case',{id,kind:'refund',skuId:'oil',qty:1,amountCents:10000,reason:'协商退款'});const caseId=s.goods.find(o=>o.id===id).cases.at(-1).id;f.run('goods.case-review',{id,caseId,decision:'approve',reason:'核实批准'},support);f.run('goods.refund',{id,caseId,outcome:'success'},finance);},debt(){const old=f.create();f.bill();f.pay();f.refund(old);f.create();f.bill();}};return f;}

test('差异与拆账表单按订单多选、带当前账单版本，岗位控件分开',()=>{
  const f=fixture(),a=f.create(),b=f.create();f.bill();const local=forms(f.page(store),'bill.dispute-lines')[0];assert.equal(local.payload.version,f.b.version);assert.match(local.body,new RegExp(`name="orderIds" value="${a}"`));assert.match(local.body,new RegExp(`name="orderIds" value="${b}"`));assert.equal(forms(f.page(),'bill.dispute-lines').length,0);assert.equal(forms(f.page(store),'bill.split').length,0);
  f.submit(local,{orderIds:[a],reason:'本店核对第一单差异，第二单无争议'},store);const split=forms(f.page(),'bill.split')[0];assert.equal(split.payload.version,f.b.version);assert.match(split.body,new RegExp(`value="${b}"`));assert.doesNotMatch(split.body,new RegExp(`value="${a}"`));f.submit(split,{orderIds:[b],reason:'无争议行先转子账'});assert.match(f.page(),/查看原账单/);assert.match(f.page(),/差异继续在原账处理/);assert.match(f.page(store),/逐项确认差异范围/);
});
test('旧整单差异未明确前无拆账控件；paid和processing没有新方案或拆分',()=>{
  const f=fixture();f.create();f.create();f.bill();f.run('bill.dispute',{id:f.b.id,version:f.b.version,reason:'原整单差异'},store);assert.equal(forms(f.page(),'bill.split').length,0);f.run('bill.resolve',{id:f.b.id,reason:'已核对原账'},finance);f.run('bill.confirm',{id:f.b.id,version:f.b.version},store);f.run('bill.pay',{id:f.b.id,outcome:'processing'},finance);assert.equal(forms(f.page()).length,0);f.run('bill.query',{id:f.b.id,outcome:'success'},finance);assert.equal(forms(f.page()).length,0);
});
test('抵扣提案与本店确认载荷正确；cash未知时只查询且说明未冲债',()=>{
  const f=fixture();f.debt();const proposal=forms(f.page(),'bill.offset-propose')[0];assert.equal(proposal.payload.version,f.b.version);assert.match(proposal.body,/data-unit="yuan"/);assert.match(proposal.body,/name="amountCents" value=""/);f.submit(proposal,{recoveryId:f.s.recoveries[0].id,amountCents:1000,reason:'本店明确商品债务'});assert.equal(forms(f.page(),'bill.offset-confirm').length,0);const confirm=forms(f.page(store),'bill.offset-confirm')[0];assert.equal(confirm.payload.planId,f.p.id);assert.equal(confirm.payload.version,f.p.version);f.submit(confirm,{decision:'accept',reason:'本店核对同意'},store);f.submit(forms(f.page(),'bill.offset-pay')[0]);assert.match(f.page(),/现金结果未知/);assert.match(f.page(),/原债务保持未清偿/);assert.equal(forms(f.page(),'bill.offset-query').length,1);assert.equal(forms(f.page(),'bill.offset-cancel').length,0);assert.equal(forms(f.page(store)).length,0);assert.equal(f.s.recoveries[0].recoveredCents,0);
});
test('失败重试控件使用同一付款方案；成功显示实际现金与抵扣并移除执行控件',()=>{
  const f=fixture();f.debt();f.submit(forms(f.page(),'bill.offset-propose')[0],{recoveryId:f.s.recoveries[0].id,amountCents:1000,reason:'明确商品债务'});f.submit(forms(f.page(store),'bill.offset-confirm')[0],{decision:'accept',reason:'本店同意'},store);f.submit(forms(f.page(),'bill.offset-pay')[0]);const paymentId=f.p.paymentId;f.submit(forms(f.page(),'bill.offset-query')[0],{outcome:'failed'});assert.match(f.page(),/原交易重新执行现金付款/);assert.equal(f.p.paymentId,paymentId);assert.equal(f.b.cashPaidCents,undefined);f.submit(forms(f.page(),'bill.offset-pay')[0]);f.submit(forms(f.page(),'bill.offset-query')[0],{outcome:'success'});assert.match(f.page(),/实际现金付款/);assert.match(f.page(),/实际债务抵扣/);assert.match(f.page(),/实际结佣¥20.00＝现金¥10.00＋抵扣¥10.00/);assert.equal(forms(f.page()).length,0);assert.equal(forms(f.page(store)).length,0);assert.equal(f.b.cashPaidCents+f.b.offsetSettledCents,f.b.grossSettledCents);
});
test('提示使用状态语义，依据转义，读取不迁移或反写且跨店不泄露',()=>{
  const f=fixture();f.debt();f.submit(forms(f.page(),'bill.offset-propose')[0],{recoveryId:f.s.recoveries[0].id,amountCents:1000,reason:'<script>恶意原文</script> & 特殊字'});const before=structuredClone(f.s),html=f.page();assert.match(html,/role="status"/);assert.match(html,/&lt;script&gt;恶意原文&lt;\/script&gt; &amp; 特殊字/);assert.doesNotMatch(html,/<script>/);assert.equal(f.page({role:'store',storeId:'silver'}),'');assert.equal(f.page(user),'');assert.equal(f.page(warehouse),'');assert.deepEqual(f.s,before);
});
test('本店追回投影显示占用与人工可收，其他门店/非财务不读本店债务',()=>{
  const f=fixture();f.debt();f.submit(forms(f.page(),'bill.offset-propose')[0],{recoveryId:f.s.recoveries[0].id,amountCents:600,reason:'部分债务抵扣方案'});const html=goodsRecoverySettlementPanel(f.s,store,f.s.recoveries,ui);assert.match(html,/方案占用¥6.00 · 人工可收¥4.00/);assert.match(html,/退出不能直接免除欠款/);assert.equal(goodsRecoverySettlementPanel(f.s,{role:'store',storeId:'silver'},f.s.recoveries,ui),'');assert.equal(goodsRecoverySettlementPanel(f.s,warehouse,f.s.recoveries,ui),'');
});
