import test from 'node:test';
import assert from 'node:assert/strict';
import { seed } from './engine.mjs';
import { workTaskView } from './work-tasks.mjs';
import { goodsSettlementTaskRows } from './goods-settlement.mjs';
import { createTaskReturnContext,taskReturnTarget } from './task-navigation.mjs';
const finance={role:'group',job:'finance'},store={role:'store',storeId:'xingfu'};
function fixture(){const s=seed();s.bills=[{id:'B1',storeId:'xingfu',status:'disputed',createdAt:s.now,amountCents:2000,version:2,dispute:{status:'open',reason:'原差异正文不进入待办',orderIds:['G1']},items:[{orderId:'G1',amountCents:2000}],childBillIds:['B2']},{id:'B2',storeId:'xingfu',status:'review',createdAt:s.now,amountCents:2000,version:1,parentBillId:'B1',items:[{orderId:'G2',amountCents:2000}],childBillIds:[]},{id:'B3',storeId:'silver',status:'review',createdAt:s.now,amountCents:2000,version:1,items:[],childBillIds:[]}];s.goodsOffsetPlans=[{id:'P1',billId:'B2',storeId:'xingfu',status:'proposed',version:1,createdAt:s.now,grossCents:2000,offsetCents:1000,cashCents:1000,allocations:[{recoveryId:'R1',amountCents:1000}]}];s.bills[1].activeOffsetPlanId='P1';s.goods=[{id:'G0',source:{storeId:'xingfu'},cases:[],payment:{status:'success'},status:'received'}];s.recoveries=[{id:'R1',orderId:'G0',storeId:'xingfu',version:1,amountCents:1000,recoveredCents:0,status:'open',records:[]}];return s;}
function context(s,a,task){return createTaskReturnContext(s,a,{taskKey:task.id,task,listHash:`/${a.role}/tasks?category=${task.category}&status=all&q=${task.sourceId}`,token:'settlement-navigation-1'});}
test('settlement tasks follow live stage, reserved debt and store/job scope without copying dispute body',()=>{const s=fixture(),before=structuredClone(s);const group=workTaskView(s,finance).tasks,local=workTaskView(s,store).tasks;assert.ok(local.every(r=>r.storeId==='xingfu'));assert.ok(group.some(r=>r.category==='goods-settlement-bill'&&r.sourceId==='B1'&&r.manageRoles.includes('group')));assert.ok(local.some(r=>r.category==='goods-settlement-offset'&&r.sourceId==='P1'&&r.manageRoles.includes('store')));assert.equal(group.find(r=>r.category==='goods-settlement-recovery').status,'waiting');assert.ok(workTaskView(s,{role:'group',job:'support'}).tasks.every(r=>!r.category.startsWith('goods-settlement-')));assert.doesNotMatch(JSON.stringify(group),/原差异正文不进入待办/);assert.deepEqual(s,before);s.goodsOffsetPlans[0].status='succeeded';s.recoveries[0].recoveredCents=1000;assert.equal(workTaskView(s,finance).tasks.find(r=>r.sourceId==='R1').status,'done');});
test('split parent/child links preserve filtered task return; unrelated or forged cross-store links reject',()=>{const s=fixture(),task=goodsSettlementTaskRows(s).find(r=>r.sourceId==='B1'),c=context(s,finance,task);assert.equal(taskReturnTarget(s,finance,c,'/group/bills/B2'),c.listHash);assert.equal(taskReturnTarget(s,finance,c,'/group/bills/B3'),null);s.bills[0].childBillIds.push('B3');s.bills[2].parentBillId='B1';assert.equal(taskReturnTarget(s,finance,c,'/group/bills/B3'),null);s.bills[1].parentBillId=null;assert.equal(taskReturnTarget(s,finance,c,'/group/bills/B2'),null);});
test('offset and recovery task returns reread original relationships and reject changed sources',()=>{const s=fixture(),offset=goodsSettlementTaskRows(s).find(r=>r.sourceId==='P1'),c=context(s,store,offset);assert.equal(taskReturnTarget(s,store,c,'/store/bills/B2'),c.listHash);s.goodsOffsetPlans[0].billId='B3';assert.equal(taskReturnTarget(s,store,c,'/store/bills/B2'),null);const recovery=goodsSettlementTaskRows(s).find(r=>r.sourceId==='R1'),r=context(s,finance,recovery);assert.equal(taskReturnTarget(s,finance,r,'/group/recoveries'),r.listHash);assert.equal(taskReturnTarget(s,finance,r,'/group/goods/G0'),r.listHash);s.goods[0].source.storeId='silver';assert.equal(taskReturnTarget(s,finance,r,'/group/recoveries'),null);});
