import test from 'node:test';
import assert from 'node:assert/strict';
import { seed, reduce, upgradeFinanceState } from './engine.mjs';
import { bookingView, upgradeBookings } from './booking.mjs';
import { createBookingDraft, patchBookingDraft, bookingDraftPayload, repeatBookingDraft } from './booking-draft.mjs';
import { handoffView, handoffSources } from './service-handoff.mjs';
import { canManageView } from './management.mjs';
const user={role:'user',userId:'u1'}, store={role:'store',storeId:'xingfu'};
function setup(){let s=seed(),n=0;return {get s(){return s},get b(){return s.bookings.at(-1)},get r(){return s.recipients.at(-1)},get record(){return s.serviceHandoffs.at(-1)},run(a,type,p={}){s=reduce(s,a,type,{requestId:'handoff-int-'+(++n),...p});return s;}};}
function profile(h,extra={}){h.run(user,'recipient.save',{kind:'family',name:'演示妈妈',relationship:'母亲',consent:true,...extra});return h.r;}
function draft(h){return {...createBookingDraft(h.s,'u1','new-order'),mode:'specified',techId:'lin',serviceId:'neck',startAt:Math.ceil((h.s.now+4*3600000)/1800000)*1800000,phone:'13800001111',recipientId:h.r.id,recipientVersion:h.r.version,recipientConfirmed:true,attention:'当次已沟通注意轻缓',preference:'偏好安静',adultConfirmed:true,healthConsent:true,identityVerified:true,identityConsent:true};}
function book(h,d=draft(h)){h.run(user,'booking.create',bookingDraftPayload(d));return h.b;}
function start(h){h.run(user,'booking.pay',{id:h.b.id,outcome:'success'});h.run({role:'tech',techId:h.b.techId},'booking.accept',{id:h.b.id});h.run(user,'clock.advance',{minutes:240});h.run({role:'tech',techId:h.b.techId},'booking.start',{id:h.b.id});}
function finish(h){h.run(user,'clock.advance',{minutes:45});h.run({role:'tech',techId:h.b.techId},'booking.finish',{id:h.b.id,mode:'normal'});}
function note(h,extra={}){h.run({role:'tech',techId:h.b.techId},'handoff.note',{bookingId:h.b.id,version:h.record.version,observation:'已按当次偏好执行并沟通',nextAdvice:'下次先重新确认偏好',occurredAt:h.s.now,...extra});return h.record.notes.at(-1);}

test('H02 项目下架引发草稿自动回退时，也需重新确认对象与健康',()=>{const h=setup();profile(h);const d={...draft(h),serviceId:'relax'};h.s.services.find(x=>x.id==='relax').active=false;const next=patchBookingDraft(h.s,d,{date:'2026-10-03'});assert.equal(next.serviceId,'neck');for(const key of ['recipientConfirmed','adultConfirmed','healthConsent'])assert.equal(next[key],false);assert.equal(next.identityVerified,true);});

test('H02 联系人与家人对象独立；修改档案不回写原订单或原交接',()=>{const h=setup();profile(h);const d=draft(h);book(h,d);upgradeBookings(h.s);const before=structuredClone(h.b),record=structuredClone(h.record);assert.equal(h.b.contactName,'王女士');assert.equal(h.b.recipientSnapshot.name,'演示妈妈');assert.equal(h.record.confirmation.attention,d.attention);h.run(user,'recipient.save',{id:h.r.id,version:h.r.version,kind:'family',name:'演示母亲新称呼',relationship:'母亲',consent:true});assert.deepEqual(h.b,before);assert.deepEqual(h.record,record);assert.equal(h.b.userId,'u1');});

test('H02 更换对象和事项需重确认健康与成年；下单人身份核验保持',()=>{const h=setup();profile(h);const d=draft(h);for(const patch of [{recipientId:'visit'},{attention:'当次更新'},{preference:'更新偏好'},{recipientKind:'other'}]){const changed=patchBookingDraft(h.s,d,patch);for(const key of ['recipientConfirmed','adultConfirmed','healthConsent'])assert.equal(changed[key],false);assert.equal(changed.identityVerified,true);assert.throws(()=>bookingDraftPayload(changed),/服务对象|当次/);}const changed=patchBookingDraft(h.s,d,{recipientId:'visit'});assert.equal(changed.attention,'');assert.equal(changed.preference,'');assert.equal(changed.recipientVersion,null);});

test('H02 选择档案锁定版本，重新渲染不能更新已选择版本；停用拒绝新单',()=>{const h=setup();profile(h);const selected=patchBookingDraft(h.s,createBookingDraft(h.s,'u1','stale'),{recipientId:h.r.id});assert.equal(selected.recipientVersion,1);const d={...draft(h),recipientVersion:selected.recipientVersion};h.run(user,'recipient.status',{id:h.r.id,version:h.r.version,active:false});assert.throws(()=>book(h,d),/版本|更新|停用|启用/);assert.equal(h.s.bookings.length,0);assert.equal(h.s.serviceHandoffs.length,0);});

test('H02 再次预约不沿用家庭对象或事项，原技师项目时间选择逻辑保留',()=>{const h=setup();profile(h);book(h);start(h);finish(h);const fresh=repeatBookingDraft(h.s,'u1',h.b.id,'next-order');assert.equal(fresh.next,'/user/booking/slots');assert.equal(fresh.draft.storeId,h.b.storeId);assert.equal(fresh.draft.serviceId,h.b.serviceId);assert.equal(fresh.draft.recipientId,'');assert.equal(fresh.draft.recipientConfirmed,false);assert.equal(fresh.draft.attention,'');assert.equal(fresh.draft.preference,'');assert.equal(fresh.draft.startAt,null);assert.equal(fresh.draft.identityConsent,false);});

test('H04 服务记录接受后才可主动复用，同店同对象且再次确认；新单保留独立快照',()=>{const h=setup();profile(h);book(h);start(h);const n=note(h);assert.equal(handoffSources(h.s,user,h.r.id,'xingfu').length,0);finish(h);h.run(user,'handoff.decide',{bookingId:h.b.id,version:h.record.version,noteId:n.id,decision:'accept'});const src=handoffSources(h.s,user,h.r.id,'xingfu')[0];assert.equal(src.noteId,n.id);assert.equal(handoffSources(h.s,user,h.r.id,'silver').length,0);assert.equal(handoffSources(h.s,{role:'user',userId:'u2'},h.r.id,'xingfu').length,0);let d=patchBookingDraft(h.s,draft(h),{sourceKey:`${src.bookingId}:${src.noteId}:${src.version}`});assert.equal(d.preference,src.advice);assert.equal(d.recipientConfirmed,false);d={...d,requestId:'next-with-advice',recipientConfirmed:true,adultConfirmed:true,healthConsent:true};book(h,d);assert.equal(h.record.confirmation.sourceNoteId,n.id);assert.equal(h.s.bookings.length,2);});

test('H04 来源更正后拒绝旧草稿复用，不偷偷用新文本替换旧确认',()=>{const h=setup();profile(h);book(h);start(h);const n=note(h);finish(h);h.run(user,'handoff.decide',{bookingId:h.b.id,version:h.record.version,noteId:n.id,decision:'accept'});const src=handoffSources(h.s,user,h.r.id,'xingfu')[0];let d=patchBookingDraft(h.s,draft(h),{sourceKey:`${src.bookingId}:${src.noteId}:${src.version}`});d={...d,requestId:'stale-source',recipientConfirmed:true,adultConfirmed:true,healthConsent:true};note(h,{correctionOf:n.id,reason:'更正表述',nextAdvice:'更正后需用户重新决定'});assert.equal(handoffSources(h.s,user,h.r.id,'xingfu').length,0);assert.throws(()=>book(h,d),/来源|更新|有效|更正|失效/);assert.equal(h.s.bookings.length,1);});

test('H04 已读不改变预约状态与派单时限；真实改派使旧技师失权，新技师重新读',()=>{const h=setup();profile(h);book(h);h.run(user,'booking.pay',{id:h.b.id,outcome:'success'});h.run({role:'tech',techId:'lin'},'booking.accept',{id:h.b.id});const b=structuredClone(h.b);h.run({role:'tech',techId:'lin'},'handoff.ack',{bookingId:h.b.id,version:h.record.version});assert.deepEqual(h.b,b);assert.equal(handoffView(h.s,{role:'tech',techId:'lin'},h.b.id).hasRead,true);h.run(store,'booking.assign',{id:h.b.id,techId:'chen',reason:'按原流程协调改派'});h.run(user,'booking.change-answer',{id:h.b.id,changeId:h.b.change.id,decision:'accept'});assert.equal(h.b.techId,'chen');assert.equal(handoffView(h.s,{role:'tech',techId:'lin'},h.b.id),null);assert.equal(handoffView(h.s,{role:'tech',techId:'chen'},h.b.id).hasRead,false);h.run({role:'tech',techId:'chen'},'handoff.ack',{bookingId:h.b.id,version:h.record.version});assert.equal(handoffView(h.s,{role:'tech',techId:'chen'},h.b.id).hasRead,true);});

test('H04 交接正文不会随普通订单视图或全局日志泄露给财务',()=>{const h=setup();profile(h);book(h);start(h);note(h,{observation:'PRIVATE-OBSERVATION',nextAdvice:'PRIVATE-ADVICE'});const finance={role:'group',job:'finance'};const data=JSON.stringify(bookingView(h.s,finance));for(const forbidden of ['PRIVATE-OBSERVATION','PRIVATE-ADVICE','当次已沟通注意轻缓','偏好安静']){assert.equal(data.includes(forbidden),false);assert.equal(JSON.stringify(h.s.logs).includes(forbidden),false);}for(const job of ['finance','operations','warehouse']){assert.equal(canManageView({role:'group',job},'handoffs'),false);assert.equal(handoffView(h.s,{role:'group',job},h.b.id),null);}assert.equal(canManageView({role:'group',job:'support'},'handoffs'),true);assert.ok(handoffView(h.s,{role:'group',job:'support'},h.b.id));});

test('H04 旧单只留未确认对象，加载升级不按联系人制造家庭档案',()=>{const h=setup();const old={storeId:'xingfu',serviceId:'neck',techId:'lin',regionId:'home',mode:'specified',startAt:h.s.now+4*3600000,contactName:'妈妈',phone:'13800009999',identityVerified:true,healthConsent:true,adultConfirmed:true};h.run(user,'booking.create',old);const before=structuredClone(h.b);upgradeFinanceState(h.s);assert.deepEqual(h.b,before);assert.equal(h.s.recipients.length,0);assert.equal(h.s.serviceHandoffs.length,0);const view=handoffView(h.s,user,h.b.id);assert.equal(view.canNote,false);assert.equal(view.canAck,false);const again=structuredClone(h.s);upgradeFinanceState(h.s);assert.deepEqual(h.s,again);});

test('H02 本次对象独立记录不强制保存；旧UI草稿必须补对象确认',()=>{const h=setup();const base={...createBookingDraft(h.s,'u1','visit'),mode:'specified',techId:'lin',serviceId:'neck',startAt:Math.ceil((h.s.now+4*3600000)/1800000)*1800000,phone:'13800001111',identityVerified:true,identityConsent:true,adultConfirmed:true,healthConsent:true};assert.throws(()=>bookingDraftPayload(base),/服务对象/);book(h,{...base,recipientId:'visit',recipientKind:'self',recipientName:'当次本人',recipientRelationship:'本人',recipientConfirmed:true});assert.equal(h.s.recipients.length,0);assert.equal(h.record.recipientSnapshot.name,'当次本人');assert.equal(handoffSources(h.s,user,'visit','xingfu').length,0);});

test('H04 建单幂等不会重复交接，越权对象在提交前事务整体回滚',()=>{const h=setup();profile(h);const d=draft(h);book(h,d);book(h,d);assert.equal(h.s.bookings.length,1);assert.equal(h.s.serviceHandoffs.length,1);const before=structuredClone(h.s);assert.throws(()=>h.run({role:'user',userId:'u2'},'booking.create',{...bookingDraftPayload(d),requestId:'cross-user',startAt:h.s.now+6*3600000}),/对象|权限|本人/);assert.deepEqual(h.s,before);});
