import { canManageView, JOBS, stockSummary, affectedBookings, productImpact, storeOpeningReadiness } from './management.mjs';
import { qualificationTechPanel } from './qualification-ui.mjs';
import { qualificationEligibility } from './tech-qualification.mjs';
import { organizationLifecyclePanel } from './organization-lifecycle-ui.mjs';

export function managementView(s, actor, route, ui) {
  const [section, id, child, childId] = route;
  if (!['catalog', 'categories', 'inventory', 'services', 'stores', 'technicians', 'rules', 'management-log'].includes(section)) return null;
  const { esc: e, money: m, date: d, field: f, select: select, link: link, tag, empty } = ui;
  const group = actor.role === 'group', local = ['store', 'manager'].includes(actor.role), base = '/' + actor.role;
  if (!canManageView(actor, section) || (!group && !(local && ['stores', 'technicians', 'services'].includes(section)))) return empty('当前身份没有此页面权限', '请使用页面顶部的演示身份和集团岗位切换。');
  const options = list => list.map(x => ({ value: x.id, label: x.name || x.id }));
  const yn = [{ value: 'true', label: '启用' }, { value: 'false', label: '停用' }];
  const path = (part = section, entityId = '') => `${base}/${part}${entityId ? '/' + entityId : ''}`;
  const l = (text, part = section, entityId = '', cls = 'secondary') => link(e(text), path(part, entityId), cls);
  const head = (title, sub, tools = '') => `<header class="page-head"><div><h1>${e(title)}</h1><p>${e(sub)}</p></div><div class="actions">${tools}</div></header>`;
  const panel = (title, body) => `<section class="panel management-panel"><h2>${e(title)}</h2>${body}</section>`;
  const table = (heads, rows) => rows.length ? `<div class="table-wrap"><table><thead><tr>${heads.map(h => `<th>${e(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row => `<tr>${row.map(v => `<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>` : empty('暂无记录', '可通过页面操作创建资料。');
  const textarea = (label, name, value = '', attrs = '') => `<label class="field wide"><span>${e(label)}</span><textarea name="${name}" rows="4" ${attrs}>${e(value)}</textarea></label>`;
  const moneyField = (label, name, cents, optional = false) => f(label, name, cents == null ? '' : (cents / 100).toFixed(2), 'number', `data-unit="yuan" min="0.01" step="0.01" ${optional ? '' : 'required'}`);
  const checks = (label, name, list, selected = []) => `<fieldset class="management-checks wide"><legend>${e(label)}</legend>${list.map(x => `<label><input type="checkbox" name="${name}" value="${e(x.id)}" ${selected.includes(x.id) ? 'checked' : ''}>${e(x.name)}</label>`).join('') || '<p>暂无可选项目</p>'}</fieldset>`;
  const form = (command, payload, fields, label = '保存资料', next = path(section, id || ''), confirm = '') => `<form class="management-form" data-management-form="${e(`${section}:${id || ''}:${child || ''}:${childId || ''}:${command}`)}" data-command="${command}" data-payload="${e(JSON.stringify({ ...payload, requestId: crypto.randomUUID() }))}" data-live-version="${payload.version ?? ''}" data-next="${e(next)}" data-confirm="${e(confirm)}"><div class="management-grid">${fields}${textarea('操作原因', 'reason', '', 'required maxlength="300" placeholder="记录本次变更的原因，便于后续核对"')}</div><p class="management-draft-note small muted" role="status">未保存内容会保留在当前标签页，保存成功后清除。</p><div class="actions"><button class="primary" type="submit">${e(label)}</button><button type="button" class="secondary" data-command="ui.management-discard">放弃本页草稿</button></div></form>`;
  const events = x => panel('操作记录', (x.events || []).length ? `<ol class="timeline">${[...x.events].reverse().map(v => `<li><small>${d(v.at)} · ${e(JOBS[v.job] || ({group:'集团',store:'门店后台',manager:'店长',user:'用户',tech:'技师'})[v.actor] || v.actor)}</small>${e(v.text)}</li>`).join('')}</ol>` : '<p class="muted">暂无变更记录。</p>');
  const histories = x => (x.history || []).length ? panel('历史版本', [...x.history].reverse().map(v => `<details><summary>v${v.version} · ${d(v.at)} · ${e(v.reason)}</summary><dl class="kv-grid">${Object.entries(v.data).filter(([key, value]) => ['name','status','duration','priceCents','nightCents','extensionMinutes','extensionCents','earliestHours','maxDays'].includes(key) && value != null).map(([key, value]) => `<div><dt>${e(({ name:'名称',status:'状态',duration:'时长',priceCents:'日间/售价',nightCents:'夜间价',extensionMinutes:'加时单位',extensionCents:'加时价',earliestHours:'提前小时',maxDays:'最远天数' })[key])}</dt><dd>${key.endsWith('Cents') ? m(value) : e(value)}</dd></div>`).join('')}</dl>${v.data.skus ? table(['规格编号','规格','售价','推广佣金'], v.data.skus.map(k => [e(k.id),e(k.spec),m(k.priceCents),e(k.commissionBps/100)+'%'])) : ''}</details>`).join('')) : '';
  const bookingStatus = b => ({unpaid:'待支付',waiting:'待确认',confirmed:'已确认',active:'进行中'})[b.status] || b.status;
  const scopeKey = { stores:'storeId', technicians:'techId', services:'serviceId' };
  const arrangementText = (b, key, entityId) => {
    const original = b[key] === entityId, pending = b.change?.status === 'pending' && ({ ...b, ...b.change })[key] === entityId;
    return [original ? (key === 'techId' ? '原约技师' : '原约关联') : '', pending ? (key === 'techId' ? '待确认候选' : '待确认拟约关联') : ''].filter(Boolean).join('、');
  };
  const appointmentTimes = b => `原约：${d(b.startAt)}${b.change?.status === 'pending' ? `<small>拟约：${d(b.change.startAt)} · 待用户确认</small>` : ''}`;
  const affected = (key, entityId) => {
    const records = affectedBookings(s, key, entityId);
    return panel('在途预约影响清单', records.length ? `<p class="notice">${records.length}笔预约仍在履约。资料名称与价格变更保留旧订单快照；停用或改变项目资格前须先处理在途安排。</p>` + table(['预约','状态','关联安排','原约 / 拟约时间','操作'], records.map(b => [e(b.id),e(bookingStatus(b)),e(arrangementText(b,key,entityId)),appointmentTimes(b),(canManageView(actor,'bookings') ? link('处理预约',`${base}/bookings/${b.id}`)+' · ' : '')+link('查看影响',path(section,entityId+'/impact/'+b.id))])) : '<p>没有在途预约。</p>');
  };
  const filters = (fields, part = section) => `<form class="management-filters" data-command="ui.filter" data-payload="${e(JSON.stringify({ path: path(part) }))}">${fields}<button class="secondary">筛选</button>${l('清除筛选', part)}</form>`;
  const q = ui.query.get('q') || '', status = ui.query.get('status') || '';
  const matches = x => !q || `${x.id} ${x.name || ''} ${x.phone || ''} ${x.spec || ''}`.toLowerCase().includes(q.toLowerCase());
  const lookup = (list, target) => list.find(x => x.id === target)?.name || '未选择';
  const upload = (name, label, current = '') => `<div class="management-image-field"><span>${label}</span><input type="hidden" name="${name}" value="${e(current)}"><img data-image-preview="${name}" src="${e(current || '../reference-demos/franchise-demo/products/igood-01.svg')}" alt="${label}预览" ${current ? '' : 'hidden'}><select data-image-choice="${name}" aria-label="${label}素材"><option value="">选择已有素材 / 清空</option><option value="../reference-demos/franchise-demo/products/igood-01.svg">修复液包装</option><option value="../reference-demos/franchise-demo/products/igood-02.svg">蛋白粉包装</option></select><label class="field"><span>上传${label}（PNG/JPG/WebP，300KB以内）</span><input type="file" accept="image/png,image/jpeg,image/webp" data-image-upload="${name}"></label></div>`;

  if (child === 'impact' && scopeKey[section]) {
    const key = scopeKey[section], entities = section === 'stores' ? s.stores : section === 'technicians' ? s.techs : s.services;
    const entity = entities.find(x => x.id === id);
    const scoped = entity && (group || (section === 'stores' ? entity.id === actor.storeId : section === 'technicians' && entity.storeId === actor.storeId));
    const booking = scoped ? affectedBookings(s,key,id).find(b => b.id === childId && (group || b.storeId === actor.storeId)) : null;
    if (!booking) return empty('该预约不在当前资料的在途影响范围内', '请返回资料页，按最新影响清单核对。') + l('返回资料',section,id);
    const b = booking, proposed = b.change?.status === 'pending' ? { ...b, ...b.change } : null;
    const rows = [[`原约${b.techId === id && key === 'techId' ? ' · 本技师' : ''}`, d(b.startAt), e(b.techSnapshot?.name || lookup(s.techs,b.techId)), '保留原安排']];
    if (proposed) rows.push([`拟约${proposed.techId === id && key === 'techId' ? ' · 本技师为待确认候选' : ''}`,d(proposed.startAt),e(lookup(s.techs,proposed.techId)),'待用户确认']);
    const store = s.stores.find(x => x.id === b.storeId);
    const handoff = canManageView(actor,'bookings') ? link('处理预约',`${base}/bookings/${b.id}`) : `<p>请将预约编号 <strong>${e(b.id)}</strong> 交给 ${e(store?.name || b.storeId)} 的门店负责人或集团客服，协调用户确认改约、改派或取消。处理完成后返回本清单核对，再维护资料。</p>`;
    return head('在途预约影响详情',`${entity.name} · ${arrangementText(b,key,id)}`,l('返回资料',section,id)) + panel('预约安排',`<dl class="kv-grid"><div><dt>预约编号</dt><dd>${e(b.id)}</dd></div><div><dt>状态</dt><dd>${e(bookingStatus(b))}</dd></div><div><dt>项目</dt><dd>${e(b.serviceSnapshot?.name || lookup(s.services,b.serviceId))}</dd></div><div><dt>用户技师偏好</dt><dd>${e(({any:'不限',male:'男性技师',female:'女性技师'})[b.genderPreference] || '不限')}</dd></div></dl>`+table(['安排','预约时间','技师','当前状态'],rows)) + panel('协调处理',`<p class="notice">先协调原约及待确认候选，确认不再占用后再修改资料。</p>${handoff}`);
  }

  if (section === 'catalog') {
    if (!id) {
      const category = ui.query.get('category') || '';
      const rows = s.products.filter(x => matches(x) && (!status || x.status === status) && (!category || category === x.categoryId));
      return head('商品管理', '维护商品资料、规格、售价和推广佣金。库存由仓储单独维护。', l('分类管理', 'categories') + l('新建商品', 'catalog', 'new', 'primary')) + filters(f('商品名称 / 编号', 'q', q, 'search') + select('销售状态','status',[{value:'',label:'全部'}, {value:'draft',label:'草稿'}, {value:'published',label:'已上架'}, {value:'offline',label:'已下架'}],status) + select('分类','category',[{value:'',label:'全部分类'},...options(s.categories)], category)) + panel('商品档案', table(['商品','分类','状态 / 版本','规格 / 售价','可售数量','操作'], rows.map(x => { const skus = s.skus.filter(k => k.productId === x.id), prices = skus.map(k => k.priceCents); return [`<div class="management-product">${x.image ? `<img src="${e(x.image)}" alt="">` : ''}<div><strong>${e(x.name || '未命名草稿')}</strong><small>${e(x.id)}</small></div></div>`,e(lookup(s.categories,x.categoryId)),tag(({draft:'草稿',published:'已上架',offline:'已下架'})[x.status]) + `<small>v${x.version}</small>`,`${skus.length}个规格<small>${prices.length ? m(Math.min(...prices)) + '—' + m(Math.max(...prices)) : '尚未配置'}</small>`,skus.reduce((v,k)=>v+stockSummary(s,k.id).available,0), l('管理','catalog',x.id,'')]; })));
    }
    const x = id === 'new' ? { name:'',categoryId:'',description:'',image:'',gallery:[],status:'draft' } : s.products.find(x=>x.id===id);
    if (!x) return empty('商品不存在');
    if (child === 'preview') {
      const skus=s.skus.filter(k=>k.productId===id), selected=skus.find(k=>k.id===ui.query.get('sku'))||skus[0];
      return head('商品发布预览','按已保存资料预览；草稿不会出现在用户商城。',l('返回商品','catalog',id))+`<div class="management-product-preview">${panel(x.name||'未命名草稿',`${x.image?`<img class="product-hero" src="${e(x.image)}" alt="${e(x.name)}">`:'<p class="notice warning">尚未添加主图</p>'}<p class="amount">${selected?m(selected.priceCents):'尚未配置规格'}</p><p>${e(x.description||'尚未填写详情')}</p><nav class="variant-list">${skus.map(k=>link(e(k.spec),path('catalog',id+'/preview')+'?sku='+k.id,k.id===selected?.id?'active':'')).join('')}</nav><p class="muted">${selected?`可售 ${stockSummary(s,selected.id).available} 件`:'请先添加规格'} · 集团统一销售发货</p>${(x.gallery||[]).map(src=>`<img class="product-hero" src="${e(src)}" alt="商品详情">`).join('')}`)}</div>`;
    }
    const impact = x.id ? productImpact(s,x.id) : {carts:0,orders:0};
    const warning = `关联购物车${impact.carts}个，已有有效订单${impact.orders}笔。已下单资料、价格和佣金沿用快照；购物车调价后需要用户重新确认。`;
    if (child === 'sku') {
      const k = childId === 'new' ? {spec:'',priceCents:null,commissionBps:0,enabled:true,lowStock:5} : s.skus.find(k=>k.id===childId && k.productId===id);
      if (!k) return empty('规格不存在');
      return head(k.id ? '编辑规格' : '新增规格', `${x.name} · 商品版本v${x.version}`, l('返回商品','catalog',id)) + panel('规格与售价', `<p class="notice">${warning}</p>` + form('manage.sku-save',{id:k.id,productId:id,version:x.version}, f('规格名称','spec',k.spec,'text','required maxlength="50"') + moneyField('售价（元）','priceCents',k.priceCents) + f('门店推广佣金（%）','commissionBps',k.commissionBps/100,'number','data-unit="percent" min="0" max="100" step="0.01" required') + select('规格可售状态','enabled',yn,String(k.enabled)) + f('低库存提醒值（件）','lowStock',k.lowStock,'number','min="0" max="100000" required'), '保存规格',path('catalog',id),x.status==='published'?warning:''));
    }
    const fields = f('商品名称','name',x.name,'text','maxlength="60"') + select('商品分类','categoryId',[{value:'',label:'请选择分类'},...options(s.categories)],x.categoryId) + textarea('商品详情','description',x.description,'maxlength="3000"') + `<div class="management-main-image wide">${upload('image','主图',x.image)}</div><details class="wide"><summary>详情图片（选填，最多4张）${x.gallery?.length ? ' · 已有'+x.gallery.length+'张' : ''}</summary><div class="management-image-grid">${[0,1,2,3].map(i=>upload('gallery'+i,'详情图'+(i+1),x.gallery?.[i])).join('')}</div></details>`;
    let html = head(x.id ? x.name || '未命名草稿' : '新建商品', x.id ? `${x.id} · v${x.version} · ${d(x.updatedAt)}` : '先保存草稿，再维护规格和库存，核对后发布。',l('返回商品列表','catalog')) + panel('商品资料', (x.id ? `<p class="notice">${warning}</p>` : '') + form('manage.product-save',{id:x.id,version:x.version}, fields, x.id ? '保存商品资料' : '保存商品草稿',path('catalog'),x.status==='published'?warning:''));
    if (!x.id) return html;
    html += `<div class="actions">${l('预览商品','catalog',id+'/preview')}</div>`;
    const skus = s.skus.filter(k=>k.productId===id);
    html += panel('规格与库存', `<div class="actions">${l('新增规格','catalog',id+'/sku/new')}</div>`+table(['规格 / 编号','售价','推广佣金','状态','实物 / 占用 / 可售','操作'],skus.map(k=>{const st=stockSummary(s,k.id);return [`${e(k.spec)}<small>${e(k.id)}</small>`,m(k.priceCents),`${k.commissionBps/100}%`,tag(k.enabled?'启用':'停用'),`${st.physical} / ${st.held} / ${st.available}`,l('编辑','catalog',id+'/sku/'+k.id,'')+(canManageView(actor,'inventory')?' · '+l('库存','inventory',k.id,''):'')];}))) + panel('发布与下架',`<p class="muted">${e(warning)} 上架前需有名称、分类、图片、详情和完整规格。上架后无库存会显示售罄。</p>`+form('manage.product-status',{id,version:x.version},select('调整销售状态','status',[{value:'published',label:'上架销售'},{value:'offline',label:'下架，停止新购买'}],x.status==='published'?'offline':'published'),'确认调整销售状态',path('catalog',id),warning)) + histories(x) + events(x);
    return html;
  }
  if (section === 'categories') {
    if (!id) return head('商品分类','分类停用前须先处理关联的上架商品。',l('商品列表','catalog')+l('新建分类','categories','new','primary'))+panel('分类列表',table(['分类','排序','状态','关联商品','操作'],[...s.categories].sort((a,b)=>a.sort-b.sort).map(c=>[e(c.name),c.sort,tag(c.active?'启用':'停用'),link(String(s.products.filter(p=>p.categoryId===c.id).length),path('catalog')+'?category='+c.id),l('编辑','categories',c.id,'')])));
    const c = id==='new'?{name:'',sort:10,active:true}:s.categories.find(c=>c.id===id);if(!c)return empty('分类不存在');
    return head('维护商品分类',c.id||'新分类',l('返回分类','categories'))+panel('分类资料',form('manage.category-save',{id:c.id,version:c.version},f('分类名称','name',c.name,'text','required maxlength="30"')+f('排序值（小的在前）','sort',c.sort,'number','required min="0" max="9999"')+select('分类状态','active',yn,String(c.active)),'保存分类',path('categories')))+events(c);
  }
  if (section === 'inventory') {
    if (!id) return head('库存管理','实物 − 有效订单占用 = 可售；入库、盘点、报损均生成流水。')+filters(f('商品名称 / 规格编号','q',q,'search')+select('库存状态','status',[{value:'',label:'全部'},{value:'low',label:'低库存'}],status))+panel('规格库存',table(['商品 / 规格','实物','待支付占用','已付待出库','可售','操作'],s.skus.filter(k=>matches(k)&&(!status||stockSummary(s,k.id).available<=k.lowStock)).map(k=>{const st=stockSummary(s,k.id);return[`${e(k.name||'未命名商品')}<small>${e(k.spec)} · ${e(k.id)}</small>`,st.physical,st.unpaid,st.paid,`${st.available} ${st.available<=k.lowStock?tag('低库存','warning'):''}`,l('库存明细与调整','inventory',k.id,'')];})));
    const k=s.skus.find(k=>k.id===id);if(!k)return empty('规格不存在');const st=stockSummary(s,id);
    return head('库存明细',`${k.name} · ${k.spec} · ${id}`,l('返回库存','inventory'))+panel('当前数量',`<dl class="kv-grid">${[['实物库存',st.physical],['有效占用',st.held],['可售数量',st.available]].map(([n,v])=>`<div><dt>${n}</dt><dd>${v} 件</dd></div>`).join('')}</dl>`)+panel('库存操作',form('manage.inventory',{skuId:id,stockVersion:k.stockVersion||1},select('操作类型','kind',[{value:'receive',label:'采购 / 初始入库'},{value:'count',label:'盘点调整（填写实盘总数）'},{value:'damage',label:'库存报损（填写损坏数量）'}],'receive')+f('操作数量 / 实盘总数','quantity','','number','required min="0" step="1"')+f('来源或凭证编号','reference','','text','required maxlength="100" placeholder="如采购单号、盘点单号；退货从售后验收入库"'),'确认库存调整',path('inventory',id),`当前实物${st.physical}，占用${st.held}；盘亏或报损不能占用订单库存。`))+panel('占用订单',table(['订单','占用阶段','件数','操作'],st.orders.map(o=>[e(o.id),o.status==='paid'?'已付待出库':'待支付',o.qty,link('查看订单',`${base}/goods/${o.id}`)])))+panel('库存流水',table(['时间 / 单据','类型','变动','调整前 → 后','来源 / 原因','岗位'],[...s.inventoryLedger].reverse().filter(v=>v.skuId===id).map(v=>[`${d(v.at)}<small>${e(v.id)}</small>`,e(({opening:'期初结转',receive:'入库',count:'盘点',damage:'报损',ship:'订单出库',return:'退货入库','return-damage':'退货报损'})[v.kind]),v.delta>0?'+'+v.delta:v.delta,`${v.before} → ${v.after}`,`${e(v.reference)}<small class="wrap-cell">${e(v.reason)}</small>`,e(JOBS[v.actor]||v.actor)])));
  }
  if(section==='services') {
    if(!id)return head('预约项目','日夜价、项目时长与加时配置，发布后接入原预约选择页。',group?l('新建预约项目','services','new','primary'):'')+filters(f('名称 / 项目编号','q',q,'search'))+panel('项目列表',table(['项目','日间 / 夜间','时长 / 加时','状态 / 版本','适用范围','操作'],s.services.filter(x=>matches(x)&&(group||s.stores.find(t=>t.id===actor.storeId)?.serviceIds.includes(x.id))).map(x=>[`${e(x.name)}<small>${e(x.id)}</small>`,`${m(x.priceCents)} / ${m(x.nightCents)}`,`${x.duration} / ${x.extensionMinutes||30}分钟`,tag(x.active?'已上架':'已下架')+`<small>v${x.version}</small>`,`${s.stores.filter(t=>t.serviceIds.includes(x.id)).length}家门店 / ${s.techs.filter(t=>t.serviceIds.includes(x.id)).length}位技师`,group?l('维护项目','services',x.id,''):'集团统一维护'])));
    if(!group)return empty('门店可查看项目，集团负责维护');
    const x=id==='new'?{name:'',duration:60,priceCents:null,nightCents:null,extensionMinutes:30,description:'',active:false}:s.services.find(x=>x.id===id);if(!x)return empty('项目不存在');
    return head('维护预约项目',x.id?`${x.id} · v${x.version}`:'新建后在门店与技师档案中配置适用项目。',l('返回项目','services'))+panel('项目配置',form('manage.service-save',{id:x.id,version:x.version},f('项目名称','name',x.name,'text','required maxlength="40"')+f('预约时长（分钟）','duration',x.duration,'number','required min="15" max="240" step="15"')+moneyField('日间价格（元）','priceCents',x.priceCents)+moneyField('21:00起夜间价格（元）','nightCents',x.nightCents)+f('加时单位（分钟）','extensionMinutes',x.extensionMinutes,'number','required min="15" max="120" step="15"')+moneyField('加时价格（元，留空按本单单价折算）','extensionCents',x.extensionCents,true)+select('预约状态','active',[{value:'true',label:'上架，可接受新预约'},{value:'false',label:'下架，保留原预约'}],String(x.active))+textarea('项目说明及告知','description',x.description,'required maxlength="1000"'),'保存项目',path('services'),x.id?'已有预约保留项目名称、时长、价格和加时快照，新预约使用新配置。':''))+(x.id?affected('serviceId',x.id)+histories(x)+events(x):'');
  }
  if(section==='stores') {
    const list=s.stores.filter(x=>group||x.id===actor.storeId);
    if(!id)return head('门店资料','预约营业和商品推广分别管理。',group?l('新建门店','stores','new','primary'):'')+panel('门店档案',table(['门店','地址','预约状态','商品推广','操作'],list.map(x=>[`${e(x.name)}<small>${e(x.id)}</small>`,e(x.address),tag(x.lifecycleStatus==='closed'||x.closedAt!=null?'已关闭':x.lifecycleStatus==='closing'?'关停办理中':x.active?'营业中':x.reviewStatus==='pending'?'待审核':'暂停营业'),tag(x.promotionDisabled?'停用':'启用'),l('维护档案','stores',x.id,'')])));
    const x=id==='new'&&group?{name:'',address:'',phone:'',contact:'',regionId:'home',lat:31.231,lng:121.475,serviceIds:[],radiusKm:20,bufferMinutes:30}:list.find(x=>x.id===id);if(!x)return empty('门店不存在或无权访问');
    const closed=x.lifecycleStatus==='closed'||x.closedAt!=null;
    const historicalDetails=closed ? `<p class="notice" role="status">门店已关闭，以下为保留的历史档案。原订单、资金及售后继续沿原主体限定承接办理。</p>${table(['资料','原记录'],[['门店名称',x.name],['门店地址',x.address],['负责人',x.contact],['联系电话',x.phone],['所属片区',lookup(s.regions,x.regionId)],['服务半径（公里）',x.radiusKm],['纬度',x.lat],['经度',x.lng],['后置缓冲（分钟）',x.bufferMinutes],['资质记录 / 附件编号',x.qualification],['收款主体记录',x.merchantNo],['经营预约项目',x.serviceIds.map(id=>lookup(s.services,id)).join('、')]].map(([label,value])=>[label,e(value==null||value===''?'未登记':value)]))}` : '';
    let html=head('门店档案',x.id?`${x.id} · v${x.version}`:'新门店保存后待集团审核上线。',l('返回门店','stores'))+panel('基础资料',closed ? historicalDetails : form('manage.store-save',{id:x.id,version:x.version},f('门店名称','name',x.name,'text','required maxlength="60"')+f('门店地址','address',x.address,'text','required maxlength="150"')+f('负责人','contact',x.contact,'text','required')+f('联系电话','phone',x.phone,'tel','required')+select('所属片区','regionId',options(s.regions.filter(r=>r.id!=='outside')),x.regionId)+f('服务半径（公里）','radiusKm',x.radiusKm,'number','required min="0.1" max="200" step="0.1"')+f('纬度','lat',x.lat,'number','required min="-90" max="90" step="any"')+f('经度','lng',x.lng,'number','required min="-180" max="180" step="any"')+f('后置缓冲（分钟）','bufferMinutes',x.bufferMinutes,'number','required min="0" max="120"')+f('资质记录 / 附件编号','qualification',x.qualification)+f('收款主体记录','merchantNo',x.merchantNo)+checks('经营预约项目','serviceIds',s.services,x.serviceIds),'保存门店资料',path('stores')));
    if(x.id&&!closed) { const readiness=storeOpeningReadiness(s,x); html+=panel('营业条件核验', `<p>${readiness.ready ? '当前营业条件齐全' : '待补齐：' + readiness.missing.map(e).join('；')}</p><p class="small muted">新店先建档并审核技师，再审核营业。营业期间更换已有资质或收款主体，须先暂停并重新审核。</p>`); }
    const activePause=(s.organizationLifecycleCases||[]).some(c=>c.kind==='store-pause'&&c.storeId===x.id&&c.stage==='effective');
    if(x.id)html+=affected('storeId',id)+(group&&!closed?panel('营业与推广资格',(activePause?'<p class="notice" role="status">当前停业案尚未结束，恢复营业请在下方原停业记录中办理。</p>':'')+form('manage.store-status',{id,version:x.version},select('执行操作','status',[...(!activePause?[{value:'open',label:'审核通过 / 恢复营业'},{value:'pause',label:'暂停预约营业'}]:[]),{value:'promotion-on',label:'启用商品推广'},{value:'promotion-off',label:'停用商品推广'}],activePause?(x.promotionDisabled?'promotion-on':'promotion-off'):x.active?'pause':'open'),'确认状态变更',path('stores',id),'暂停营业前检查在途预约；停止推广只影响新商品订单，历史佣金保留。')):'')+events(x);
    if (x.id) html+=organizationLifecyclePanel(s,actor,{storeId:x.id});
    return html;
  }
  if(section==='technicians') {
    const list=s.techs.filter(x=>group||x.storeId===actor.storeId);
    const newStores=s.stores.filter(t=>(group||t.id===actor.storeId)&&!['closing','closed'].includes(t.lifecycleStatus)&&t.closedAt==null);
    if(['new','import'].includes(id)&&!newStores.length)return head(id==='import'?'批量导入技师':'技师档案','先选择可建档门店，再完成资料审核和项目授权。',l('返回技师','technicians'))+empty('当前范围内没有可新增人员的门店，请先核对门店状态。');
    const newStoreId=newStores.some(t=>t.id===actor.storeId)?actor.storeId:newStores[0]?.id;
    if(id==='import')return head('批量导入技师','先校验重复和项目范围，再生成待审档案；不覆盖已有人员。',l('返回技师','technicians'))+panel('导入资料',`<p>每行一位技师，用英文逗号或表格制表符分隔。列顺序：姓名、手机号、性别、项目编号、证书记录、保单记录、有效期。多个项目以分号分隔；单批最多50行。</p><p class="small muted">可用项目：${s.services.map(x=>`${e(x.name)} = ${e(x.id)}`).join('；')}</p>`+form('manage.tech-import',{},select('所属门店','storeId',options(newStores),newStoreId)+textarea('待导入人员','content','','required placeholder="演示技师,13800001234,女,relax;neck,DEMO-CERT,DEMO-INS,2027-12-31"')+`<div class="wide"><button type="button" class="secondary" data-command="ui.tech-import-preview">校验并预览</button><div data-import-preview></div></div>`,'确认导入待审档案',path('technicians'),'将创建待审技师档案，资料审核和独立项目授权完成后才能参与预约。'));
    if(!id)return head('技师档案与审核','资料、项目资格和接单状态与原预约候选共用。',l('批量导入','technicians','import')+l('新建技师','technicians','new','primary'))+filters(f('姓名 / 手机号 / 编号','q',q,'search')+select('资料状态','status',[{value:'',label:'全部'},{value:'pending',label:'待审核'},{value:'approved',label:'已审核'},{value:'rejected',label:'已驳回'}],status))+panel('技师档案',table(['技师','门店','项目资格','审核 / 接单','资质有效期','操作'],list.filter(x=>matches(x)&&(!status||x.reviewStatus===status)).map(x=>[`${e(x.name)}<small>${e(x.phone||x.id)}</small>`,e(lookup(s.stores,x.storeId)),x.serviceIds.map(id=>e(lookup(s.services,id))).join('、'),tag(x.lifecycleStatus==='left'?'已离职':x.lifecycleStatus==='departure'?'离职办理中':({pending:'待审核',approved:'已审核',rejected:'已驳回'})[x.reviewStatus])+`<small>${!x.active?'资料未启用':x.serviceIds.some(id=>qualificationEligibility(s,x.id,id).allowed)?x.qualificationRequired||s.techQualifications?.some(q=>q.techId===x.id)?'按项目授权接单':'历史演示资格，待补录':'独立项目授权未通过'}</small>`,e(x.validUntil||'旧演示档案，待补录'),l('维护档案','technicians',x.id,'')])));
    const x=id==='new'?{name:'',storeId:newStoreId,serviceIds:[],gender:'female',lat:31.231,lng:121.475}:list.find(x=>x.id===id);if(!x)return empty('技师不存在或无权访问');
    const workEnded=Boolean(x.id)&&(x.lifecycleStatus==='left'||s.stores.some(t=>t.id===x.storeId&&(t.lifecycleStatus==='closed'||t.closedAt!=null)));
    let html=head('技师档案',x.id?`${x.id} · v${x.version}`:'新档案须完成资料审核与独立项目授权后才参与预约。',l('返回技师','technicians'))+panel('人员资料',workEnded ? `<p class="notice" role="status">工作身份已结束，以下为保留的历史档案。原资金和售后继续按原负责岗位办理。</p>${table(['资料','原记录'],[['姓名',e(x.name)],['所属门店',e(lookup(s.stores,x.storeId))],['可服务项目',x.serviceIds.map(id=>e(lookup(s.services,id))).join('、')],['证书记录',e(x.certificate||'未登记')],['保单记录',e(x.insurance||'未登记')],['原有效期',e(x.validUntil||'未登记')]])}` : form('manage.tech-save',{id:x.id,version:x.version},f('技师姓名','name',x.name,'text','required maxlength="40"')+f('手机号','phone',x.phone,'tel','required pattern="1[0-9]{10}"')+select('所属门店','storeId',options(x.id?s.stores.filter(t=>t.id===x.storeId):newStores),x.storeId)+select('性别','gender',[{value:'female',label:'女'},{value:'male',label:'男'}],x.gender)+f('当前位置纬度','lat',x.lat,'number','required step="any" min="-90" max="90"')+f('当前位置经度','lng',x.lng,'number','required step="any" min="-180" max="180"')+f('证书名称 / 记录编号','certificate',x.certificate)+f('保险保单 / 记录编号','insurance',x.insurance)+f('资质与保单共同有效至','validUntil',x.validUntil,'date')+checks('可服务项目（须在所属门店经营范围内）','serviceIds',s.services,x.serviceIds),'保存技师档案',path('technicians')));
    if(x.id)html+=qualificationTechPanel(s,actor,x,ui)+affected('techId',id)+(group&&!workEnded?panel('资料审核与启用',form('manage.tech-review',{id,version:x.version},select('处理决定','decision',[{value:'approve',label:'资料审核通过 / 启用'},{value:'reject',label:'驳回资料'},{value:'pause',label:'暂停接单'}],x.active?'pause':'approve'),'确认处理',path('technicians',id),'审核检查资质、有效期和所属门店项目，门店尚未营业也可先审核人员；实际接单仍要求门店营业及独立项目授权。资料启用不解除资格暂停。停用资料前须协调现有及拟变更预约。')):'')+events(x);
    if (x.id) html+=organizationLifecyclePanel(s,actor,{techId:x.id});
    return html;
  }
  if(section==='rules') {
    const x=s.bookingRules;
    return head('预约规则',`当前版本 v${x.version} · 新配置对新建预约生效。`)+panel('可约范围',form('manage.rules-save',{version:x.version},f('最早提前（小时）','earliestHours',x.earliestHours,'number','required min="2" max="24"')+f('最远可约（天）','maxDays',x.maxDays,'number','required min="1" max="13"'),'发布新版本',path('rules'),'既有预约、改约和加时使用订单规则快照；新建预约使用此版本。'))+panel('已确认的履约规则','<p>门店直接派单即确认；每轮截止取起算后30分钟和预约开始前60分钟的较早值。用户确认变更可开启新轮；候选切换与重试不能延期。</p><p>每单最多加时2次，支付锁定5分钟；正常完成须满足原项目与已付加时时长。最远预约范围受资金结算周期约束，最高13天。</p>')+histories(x)+events(x);
  }
  if(section==='management-log') {
    const list=s.logs.filter(x=>actor.job&&actor.job!=='all'?x.job===actor.job:true);
    return head('操作日志','按实际业务动作记录时间、岗位、对象和原因。')+panel('最近操作',table(['时间','岗位 / 身份','业务编号','操作内容'],[...list].reverse().slice(0,200).map(x=>[d(x.at),e(JOBS[x.job]||x.actor),e(x.id),`<span class="wrap-cell">${e(x.text)}</span>`])));
  }
}
