import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { seed, reduce, goodsAfterSaleAvailability } from './engine.mjs';
import { bookingRefundAvailable } from './booking.mjs';
import { closedRightsTransactionsUiView } from './privacy-closed-transactions-ui.mjs';
import { captureClosedRights, closedRightsView, assertClosedRightsCommand, CLOSED_RIGHTS_COMMANDS } from './privacy-closed-rights.mjs';
import { serviceExtraSourceToken } from './service-finance-extras.mjs';
import { prepareServiceExtraEvidence } from './service-extra-file-validation.mjs';
import { authorizedInvoiceFile } from './invoice-files.mjs';

const HOUR=3600000,DAY=24*HOUR;
const user={role:'user',userId:'u1'},other={role:'user',userId:'u2'},tech={role:'tech',techId:'lin'};
const group={role:'group',job:'all'},support={role:'group',job:'support'},warehouse={role:'group',job:'warehouse'},finance={role:'group',job:'finance'},store={role:'store',job:'store-manager',storeId:'xingfu'},storeFinance={role:'store',job:'store-finance',storeId:'xingfu'};
const bytes=new TextEncoder().encode('%PDF-1.4\nC09 synthetic old transaction UI evidence only\n%%EOF');
const file={ref:'invoice-file:'+createHash('sha256').update(bytes).digest('hex'),name:'C09技术验收.pdf',type:'application/pdf',size:bytes.length},blob=new Blob([bytes],{type:file.type});
const title={kind:'personal',title:'合成原票抬头',email:'closed-ui@example.invalid',taxId:''};
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ui={esc:e,money:n=>`¥${(n/100).toFixed(2)}`,date:n=>new Date(n).toISOString(),link:(label,path,cls)=>`<a class="${e(cls)}" href="#${e(path)}">${label}</a>`,getDraft(){throw new Error('旧权益不能创建预约草稿');},button(){throw new Error('旧权益不复用普通交易按钮');}};
const decoded=v=>v.replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
// Only this independent module's forms are parsed in tests. Production does not scrape original HTML.
const forms=html=>[...html.matchAll(/<form\b([^>]*)>([\s\S]*?)<\/form>/g)].map(([,attrs,body])=>({command:decoded(attrs.match(/data-command="([^"]*)"/)[1]),payload:JSON.parse(decoded(attrs.match(/data-payload="([^"]*)"/)[1])),body}));
const observedCommands=new Set();
const cmds=html=>forms(html).map(x=>x.command);
const find=(html,type,condition=()=>true)=>{const result=forms(html).find(x=>x.command===type&&condition(x.payload));assert.ok(result,`missing form ${type}`);return result;};
function harness(){
  let s=seed(),n=0;
  const h={get s(){return s;},get b(){return s.bookings.at(-1);},get o(){return s.goods.at(-1);},get c(){return h.o.cases.at(-1);},get i(){return h.o.incidents.at(-1);},get r(){return h.b.refunds.at(-1);},get issue(){return s.serviceRefundShortages.at(-1);},get advance(){return h.issue.advances.at(-1);},
    run(type,p={},actor=group,runtime=null){const payload={requestId:'C09-transactions-'+(++n),...p};s=reduce(s,actor,type,payload,()=>{},runtime);return s;},
    render(route,actor=user,options={}){const before=structuredClone(s),html=closedRightsTransactionsUiView(s,actor,route,ui,options);assert.deepEqual(s,before,'render must not commit isolated checks or change facts');if(html)for(const form of forms(html))observedCommands.add(form.command);return html;},
    submit(form,fields={},requestId=null){const payload={...form.payload,reason:'本人按原来源处理合成旧权益',...fields,requestId:requestId||'C09-real-form-'+(++n)};assertClosedRightsCommand(s,user,form.command,payload);s=reduce(s,user,form.command,payload);return payload;},
    book(finish=true){const startAt=Math.ceil((s.now+4*HOUR)/1800000)*1800000;h.run('booking.create',{storeId:'xingfu',serviceId:'relax',regionId:'home',techId:'lin',startAt,mode:'specified',genderPreference:'any',contactName:'CONTACT-CANARY',phone:'13800000001',healthConsent:true,identityVerified:true,adultConfirmed:true},user);const id=h.b.id;h.run('booking.pay',{id,outcome:'success'},user);h.run('booking.accept',{id},tech);if(finish){h.run('clock.advance',{minutes:(startAt-s.now)/60000});h.run('booking.start',{id},tech);h.run('clock.advance',{minutes:60});h.run('booking.finish',{id,mode:'normal'},tech);}return id;},
    goods(ship=true){h.run('cart.set',{skuId:'oil',qty:2},user);h.run('goods.submit',{addressId:'AD1',expectedSourceId:''},user);const id=h.o.id;h.run('goods.pay',{id,outcome:'success'},user);if(ship)h.run('goods.ship',{id,version:h.o.version,carrier:'合成原物流',tracking:'TRACK-SYNTHETIC'},warehouse);return id;},
    close(){h.run('privacy.request',{version:(s.privacyProfiles||[]).find(p=>p.userId==='u1')?.version||0,reason:'合成旧交易本人关闭申请',acknowledged:true},user);const x=s.privacyClosures.at(-1);h.run('privacy.close',{id:x.id,version:x.version,reason:'合成原关闭事务保留权益',custodian:'演示客服',acknowledged:true},support);},
    closeHistorical(){
      // Explicit isolated saved closure input for historically closed unresolved
      // sources. The original business facts were produced by commands above.
      // This is not privacy.close; its current unresolved-item guard stays intact.
      const id='PC-HISTORICAL-UI',closedAt=s.now,rights=captureClosedRights(s,'u1',closedAt);
      s.privacyClosures=[{id,userId:'u1',status:'use_closed',version:1,createdAt:closedAt-1,closedAt,rights,retention:[],historicalFixture:true}];
      s.privacyProfiles=[{userId:'u1',status:'use_closed',version:1,history:[{action:'账号使用关闭，历史材料待清理',closureId:id}]}];s.users.find(x=>x.id==='u1').status='closed';
    },
    case(kind='return',extra={}){h.run('goods.case',{id:h.o.id,version:h.o.version,kind,skuId:'oil',qty:2,amountCents:40000,shippingCents:0,reason:'原商品合成售后',...extra},user);return h.c.id;},
    review(decision='approve'){h.run('goods.case-review',{id:h.o.id,caseId:h.c.id,version:h.c.version,decision,reason:'合成原售后处理'},support);},
    returned(){h.case();h.review();h.run('goods.return',{id:h.o.id,caseId:h.c.id,version:h.c.version,carrier:'合成寄回',tracking:'RETURN-ORIGINAL'},user);},
    applyService(){h.run('invoice.apply',{bookingId:h.b.id,...title},user);return s.serviceInvoices.at(-1);},
    goodsRule(){h.run('commerce-invoice.rule-publish',{category:'goods',version:0,issuerName:'合成集团主体',issuerTaxId:'91320100000000000Y',invoiceItem:'合成原商品销售',effectiveAt:s.now,sourceFromAt:s.now-DAY,reason:'技术验收显式输入，不发布正式税务口径',applicationStage:'paid',shipping:'include',windowDays:90},finance);},
    applyGoods(){h.run('commerce-invoice.apply-goods',{orderId:h.o.id,...title},user);return s.commerceInvoices.at(-1);},
    async shortage(){const id=h.book(false);h.run('booking.cancel',{id,reason:'原取消退款合成来源'},user);h.run('booking.refund-pay',{id,refundId:h.r.id,outcome:'failed'},finance);const part=h.r.executions[0],p={requestId:'C09-SHORTAGE-'+(++n),version:0,bookingId:id,paymentId:h.b.payment.id,refundId:h.r.id,shortageCents:10000,failedAt:part.updatedAt,sourceToken:serviceExtraSourceToken(s,id,h.b.payment.id),reference:part.refundNo,occurredAt:part.updatedAt,file,reason:'合成PDF实际读取，核对原明确失败笔'};const runtime=await prepareServiceExtraEvidence(s,storeFinance,'service-extra.refund-shortage',p,{readFile:async()=>blob});h.run('service-extra.refund-shortage',p,storeFinance,runtime);h.run('clock.advance',{minutes:1440});h.run('service-extra.policy-publish',{path:'direct-user',version:0,effectiveAt:s.now,basis:'本次明确合成Demo路径，不作为正式业务默认值'},finance);const rule=s.serviceExtraPolicies.at(-1);h.run('service-extra.advance-decision',{id:h.issue.id,version:h.issue.version,decision:'approve',path:'direct-user',policyId:rule.id,amountCents:h.issue.refundCents,reason:'合成逐案原直接款方案'},finance);return id;}
  };return h;
}
const noNew=/data-command="(?:booking\.(?:create|pay|cancel|extension|change|propose)|goods\.(?:submit|pay|payment-query|address)|address\.|review\.|invoice\.apply|commerce-invoice\.apply|service-promotion\.)/;
function safeReturns(html){assert.match(html,/href="#\/user\/rights"/);assert.match(html,/href="#\/user\/privacy"/);assert.doesNotMatch(html,noNew);assert.doesNotMatch(html,/CONTACT-CANARY|13800000001|13800008000|示例路128|healthConsent|adultConfirmed|identityVerified|<img\b/);}

test('C09 五类精确详情之外返回null供下一renderer，active本人和员工仍保持原入口',()=>{const h=harness();for(const route of [[],['booking'],['booking','time'],['booking','B','pay'],['goods'],['care'],['care','new'],['invoices'],['commodity-invoices'],['service-promotion','withdrawals','SPW']])assert.equal(h.render(route),null);assert.equal(h.render(['booking','missing']),null);h.close();assert.equal(h.render(['booking','missing'],support),null);for(const route of [['booking','missing'],['goods','missing'],['care','case','missing'],['invoices','missing'],['commodity-invoices','missing'],['goods','%ZZ']]){const html=h.render(route);safeReturns(html);assert.match(html,/待人工核验/);assert.doesNotMatch(html,/missing|%ZZ|<form\b|¥/);}});

test('C09 正常原关闭后预约最小事实保留，退款原表单实际创建原申请，无新交易和资料泄露',()=>{const h=harness(),id=h.book();h.close();const html=h.render(['booking',id]);safeReturns(html);assert.match(html,/¥298\.00/);const form=find(html,'booking.refund-request');assert.match(form.body,new RegExp('refundAmount:'+h.b.payment.id));const p=h.submit(form,{requests:[{paymentId:h.b.payment.id,amountCents:5000}]});assert.equal(h.r.status,'requested');assert.equal(h.r.requests[0].amountCents,5000);assert.equal(h.b.payment.refundedCents,0);assert.equal(h.s.users[0].status,'closed');assert.equal(h.s.privacyClosures.length,1);assert.throws(()=>reduce(h.s,user,'booking.refund-request',{...p,requestId:'over-original',requests:[{paymentId:h.b.payment.id,amountCents:999999}]}),/尚可退|已有售后/);});

test('C09 原主款与加时分笔退款上限直接消费原getter，实际已退与旧付款替换继续校验',()=>{
  const h=harness(),id=h.book(false);h.run('clock.advance',{minutes:(h.b.startAt-h.s.now)/60000});h.run('booking.start',{id},tech);
  h.run('booking.extension-create',{id},user);const extensionId=h.b.extensions[0].id;h.run('booking.extension-pay',{id,extensionId,outcome:'success'},user);
  h.run('clock.advance',{minutes:90});h.run('booking.finish',{id,mode:'normal'},tech);
  const paymentId=h.b.payment.id;h.run('booking.refund-request',{id,requests:[{paymentId,amountCents:5000},{paymentId:extensionId,amountCents:2000}],reason:'合成原分笔部分退款'},user);
  h.run('booking.refund-review',{id,refundId:h.r.id,decision:'approve',reason:'原分笔申请批准'},store);h.run('booking.refund-pay',{id,refundId:h.r.id,outcome:'success'},finance);h.close();
  const form=find(h.render(['booking',id]),'booking.refund-request'),inputs=[...form.body.matchAll(/name="refundAmount:([^"]+)"[^>]*max="([^"]+)"/g)];
  assert.deepEqual(inputs.map(x=>[x[1],Number(x[2])]),[[paymentId,248],[extensionId,129]]);
  assert.equal(bookingRefundAvailable(h.b,paymentId),24800);assert.equal(bookingRefundAvailable(h.b,extensionId),12900);
  const sourceChanged=structuredClone(h.s);sourceChanged.bookings.at(-1).extensions[0].id='LATE-REPLACEMENT-EXTENSION';
  const sealed=closedRightsTransactionsUiView(sourceChanged,user,['booking',id],ui);assert.match(sealed,/待人工核验/);assert.doesNotMatch(sealed,/¥|refundAmount|LATE-REPLACEMENT/);
  h.submit(form,{requests:[{paymentId,amountCents:1000},{paymentId:extensionId,amountCents:2000}]});assert.deepEqual(h.r.requests,[{paymentId,amountCents:1000},{paymentId:extensionId,amountCents:2000}]);assert.equal(h.r.amountCents,3000);
});

test('C09 原退款接受经实际原reduce进入批准而非已退，金额/版本固定；旧版本和串号拒绝',()=>{const h=harness(),id=h.book();h.run('booking.refund-request',{id,requests:[{paymentId:h.b.payment.id,amountCents:5000}],reason:'原退款'},user);h.run('booking.refund-review',{id,refundId:h.r.id,decision:'offer',amountCents:3000,reason:'原协商方案'},store);h.closeHistorical();const html=h.render(['booking',id]),form=find(html,'booking.refund-answer',p=>p.decision==='accept'),old=structuredClone(form.payload);assert.equal(old.version,h.r.version);h.submit(form);assert.equal(h.r.status,'approved');assert.equal(h.r.amountCents,3000);assert.equal(h.b.payment.refundedCents,0);assert.throws(()=>reduce(h.s,user,'booking.refund-answer',{...old,version:old.version-1,decision:'accept'}),/方案已更新/);assert.throws(()=>reduce(h.s,user,'booking.refund-answer',{...old,refundId:'OTHER-RF',decision:'accept'}),/退款/);});

test('C09 原退款拒绝后升级与原申请撤回各保留原出口，过48小时不画新退款',()=>{for(const decision of ['escalate','withdraw']){const h=harness(),id=h.book();h.run('booking.refund-request',{id,requests:[{paymentId:h.b.payment.id,amountCents:5000}],reason:'原退款'},user);h.run('booking.refund-review',{id,refundId:h.r.id,decision:'reject',reason:'原驳回待本人处理'},store);h.closeHistorical();const form=find(h.render(['booking',id]),'booking.refund-answer',p=>p.decision===decision);h.submit(form);assert.equal(h.r.status,decision==='escalate'?'escalated':'withdrawn');}const h=harness(),id=h.book();h.closeHistorical();h.run('clock.advance',{minutes:2881});assert.ok(!cmds(h.render(['booking',id])).includes('booking.refund-request'));});

test('C09 原门店协助与原安全求助实际可提交，求助原2小时结束边界继续生效',()=>{const h=harness(),id=h.book();h.close();let html=h.render(['booking',id]);h.submit(find(html,'booking.assistance-request'));assert.equal(h.b.assistance.at(-1).status,'open');h.submit(find(h.render(['booking',id]),'booking.help'));assert.equal(h.s.safety.at(-1).bookingId,id);assert.equal(h.s.safety.at(-1).status,'open');assert.equal(h.b.status,'done');h.run('clock.advance',{minutes:121});html=h.render(['booking',id]);assert.ok(!cmds(html).includes('booking.help'));assert.ok(cmds(html).includes('booking.assistance-request'));assert.match(html,/原安全求助进度/);});

test('C09 关闭本人原预约反馈创建走原care命令，不混入退款或公开评价',()=>{const h=harness(),id=h.book();h.close();const form=find(h.render(['booking',id]),'care.case-create');assert.equal(form.payload.claim,'feedback');assert.equal(form.payload.sourceId,id);h.submit(form,{category:'quality',description:'原预约实际质量问题',evidence:'合成说明编号'});const c=h.s.serviceCareCases.at(-1);assert.equal(c.status,'store_pending');assert.equal(c.bookingId,id);assert.equal(h.b.payment.refundedCents,0);assert.ok(closedRightsView(h.s,user).items.some(x=>x.id===c.id&&x.path===`/user/care/case/${c.id}`));});

test('C09 原反馈本人说明、接受/升级/撤回继续走原cap与状态，不显示内部备注',()=>{for(const decision of ['accept','escalate','withdraw']){const h=harness(),id=h.book();h.run('care.case-create',{bookingId:id,sourceKind:'booking',sourceId:id,claim:'feedback',category:'quality',description:'原预约反馈'},user);let c=h.s.serviceCareCases.at(-1);h.run('care.case-respond',{id:c.id,version:c.version,decision:'respond',publicReply:'原公开处理回复',internalNote:'INTERNAL-CARE-CANARY',specialistAction:'none'},store);h.closeHistorical();c=h.s.serviceCareCases.at(-1);let html=h.render(['care','case',c.id]);safeReturns(html);assert.doesNotMatch(html,/INTERNAL-CARE-CANARY/);h.submit(find(html,'care.case-statement'),{text:'本人补充实际情况'});c=h.s.serviceCareCases.at(-1);assert.equal(c.statements.at(-1).text,'本人补充实际情况');html=h.render(['care','case',c.id]);h.submit(find(html,'care.case-answer',p=>p.decision===decision));c=h.s.serviceCareCases.at(-1);assert.equal(c.status,decision==='escalate'?'group_pending':decision==='withdraw'?'withdrawn':'closed');if(decision!=='escalate')assert.deepEqual(cmds(h.render(['care','case',c.id])),[]);}});

test('C09 原care过期/旧版本通过原同步拒绝，不以旧cap继续接受',()=>{const h=harness(),id=h.book();h.run('care.case-create',{bookingId:id,sourceKind:'booking',sourceId:id,category:'attitude',description:'原反馈'},user);let c=h.s.serviceCareCases.at(-1);h.run('care.case-respond',{id:c.id,version:c.version,decision:'respond',publicReply:'原回复'},store);h.closeHistorical();c=h.s.serviceCareCases.at(-1);const form=find(h.render(['care','case',c.id]),'care.case-answer',p=>p.decision==='accept');h.run('care.case-note',{id:c.id,version:c.version,text:'原员工核实记录'},store);assert.throws(()=>h.submit(form),/版本|更新/);c=h.s.serviceCareCases.at(-1);h.run('clock.advance',{minutes:2881});assert.ok(!forms(h.render(['care','case',c.id])).some(x=>x.command==='care.case-answer'&&x.payload.decision==='accept'));});

test('C09 未发货整单及按SKU取消均沿原额度，原待取消占件限制下一申请',()=>{for(const perLine of [false,true]){const h=harness(),id=h.goods(false);h.closeHistorical();let html=h.render(['goods',id]);safeReturns(html);const form=find(html,'goods.case',p=>p.kind==='cancel'&&Boolean(p.skuId)===perLine);h.submit(form,perLine?{qty:1}:{});assert.equal(h.c.status,'requested');assert.equal(h.c.kind,'cancel');assert.equal(h.o.status,'paid');assert.equal(h.o.lines[0].cancelledQty,0);assert.equal(h.o.refunds.length,0);html=h.render(['goods',id]);if(perLine){const next=find(html,'goods.case',p=>p.kind==='cancel'&&p.skuId==='oil');assert.match(next.body,/max="1"/);assert.throws(()=>h.submit(next,{qty:2}),/取消数量/);}else assert.ok(!forms(html).some(x=>x.command==='goods.case'&&x.payload.kind==='cancel'));}});

test('C09 原收货实际命令只记原收货，不支付、不改单；存在未结售后时无误导收货按钮',()=>{const h=harness(),id=h.goods();h.closeHistorical();let html=h.render(['goods',id]);const form=find(html,'goods.receive'),money=h.o.paidCents,stock=h.s.skus.find(x=>x.id==='oil').stock;h.submit(form);assert.equal(h.o.status,'received');assert.equal(h.o.paidCents,money);assert.equal(h.s.skus.find(x=>x.id==='oil').stock,stock);assert.ok(!cmds(h.render(['goods',id])).includes('goods.receive'));const j=harness(),jid=j.goods();j.case('refund',{qty:1,amountCents:1000});j.closeHistorical();assert.ok(!cmds(j.render(['goods',jid])).includes('goods.receive'));});

test('C09 原退货/仅退款/独立运费申请保留，当前占额及数量由原getter和提交核对',()=>{for(const kind of ['return','refund','shipping']){const h=harness(),id=h.goods();h.closeHistorical();const html=h.render(['goods',id]),form=find(html,'goods.case',p=>kind==='shipping'?p.kind==='refund'&&!p.skuId:p.kind===kind&&p.skuId==='oil');h.submit(form,kind==='shipping'?{shippingCents:300}:{qty:1,amountCents:1000,shippingCents:200});assert.equal(h.c.kind,kind==='shipping'?'refund':kind);assert.equal(h.o.refunds.length,0);assert.equal(h.o.lines[0].returnedQty,0);assert.equal(h.c.shippingCents,kind==='shipping'?300:200);}const h=harness(),id=h.goods();h.case('return',{qty:1,amountCents:20000});h.closeHistorical();const html=h.render(['goods',id]),form=find(html,'goods.case',p=>p.kind==='return');assert.match(form.body,/name="qty"[^>]*max="1"/);assert.match(form.body,/name="amountYuan"[^>]*max="200"/);assert.throws(()=>h.submit(form,{qty:1,amountCents:20001}),/尚可退|申请金额/);});

test('C09 商品原实际退款及活动占额直接消费原getter，未知占额不画退款动作或零额度',()=>{
  const h=harness(),id=h.goods();h.case('refund',{qty:1,amountCents:10000,shippingCents:700});h.review();h.run('goods.refund',{id,caseId:h.c.id,version:h.c.version,outcome:'success'},finance);
  h.case('return',{qty:1,amountCents:20000,shippingCents:100});h.closeHistorical();const before=structuredClone(h.s),caps=goodsAfterSaleAvailability(h.s,user,id);assert.deepEqual(h.s,before);assert.equal(caps.known,true);assert.equal(caps.availableCents,10200);assert.equal(caps.shippingCents,200);assert.equal(caps.lines[0].amountCents,10000);assert.equal(caps.lines[0].returnQty,1);
  const html=h.render(['goods',id]),form=find(html,'goods.case',p=>p.kind==='return');assert.match(form.body,/name="qty"[^>]*max="1"/);assert.match(form.body,/name="amountYuan"[^>]*max="100"/);assert.match(form.body,/name="shippingYuan"[^>]*max="2"/);assert.match(html,/商品金额与运费合计共用本单剩余额度/);assert.match(html,/减少数量时，请同时核对申请金额/);
  assert.throws(()=>h.submit(form,{qty:1,amountCents:10000,shippingCents:201}),/运费/);assert.throws(()=>h.submit(form,{qty:2,amountCents:100,shippingCents:0}),/数量/);
  const unknown=structuredClone(h.s);unknown.goods.at(-1).cases.at(-1).amountCents=null;assert.equal(goodsAfterSaleAvailability(unknown,user,id).availableCents,null);
  const page=closedRightsTransactionsUiView(unknown,user,['goods',id],ui);assert.match(page,/原商品支付金额、运费、数量、版本或售后占额依据待核对/);assert.ok(!forms(page).some(x=>x.command==='goods.case'));assert.doesNotMatch(page,/共用剩余额度[^<]*|name="(?:amountYuan|shippingYuan)"/);
  unknown.goods.at(-1).lines[0].qty=null;const quantityPage=closedRightsTransactionsUiView(unknown,user,['goods',id],ui);assert.match(quantityPage,/原数量待核对/);assert.doesNotMatch(quantityPage,/null件|undefined件/);
  h.submit(form,{qty:1,amountCents:10000,shippingCents:200});assert.equal(h.c.amountCents+h.c.shippingCents,10200);assert.ok(!forms(h.render(['goods',id])).some(x=>x.command==='goods.case'));
});

test('C09 原寄回、原拒绝申诉及撤回实际原命令不伪造验收退款',()=>{const h=harness(),id=h.goods();h.case();h.review();h.closeHistorical();let html=h.render(['goods',id]);const version=h.c.version;h.submit(find(html,'goods.return'),{carrier:'本人实际寄回物流',tracking:'RETURN-TEST'});assert.equal(h.c.status,'returning');assert.equal(h.c.returnShipment.tracking,'RETURN-TEST');assert.equal(h.o.refunds.length,0);assert.ok(!cmds(h.render(['goods',id])).includes('goods.case-withdraw'));assert.throws(()=>reduce(h.s,user,'goods.case-withdraw',{id,caseId:h.c.id,version,requestId:'stale',reason:'撤回'}),/版本|更新|寄回/);const j=harness(),jid=j.goods();j.case('refund',{qty:1,amountCents:1000});j.review('reject');j.closeHistorical();j.submit(find(j.render(['goods',jid]),'goods.appeal'));assert.equal(j.c.status,'requested');j.submit(find(j.render(['goods',jid]),'goods.case-withdraw'));assert.equal(j.c.status,'closed');assert.equal(j.o.refunds.length,0);});

test('C09 原验收拒退接受及实际返还收货沿原实物事实，不能凭确认造退款',()=>{const h=harness(),id=h.goods();h.returned();h.run('goods.inspect',{id,caseId:h.c.id,version:h.c.version,disposition:'disputed',reason:'原实物验收分歧'},warehouse);h.closeHistorical();h.submit(find(h.render(['goods',id]),'goods.return-back-accept'));assert.equal(h.c.status,'awaiting_return_to_customer');h.run('goods.return-back',{id,caseId:h.c.id,version:h.c.version,carrier:'原返还物流',tracking:'BACK-TEST',feePayer:'group',reason:'原返还约定'},warehouse);h.submit(find(h.render(['goods',id]),'goods.return-back-receive'));assert.equal(h.c.status,'closed');assert.equal(h.c.custody,'用户');assert.equal(h.o.refunds.length,0);assert.ok(!cmds(h.render(['goods',id])).includes('goods.return-back-receive'));});

test('C09 原验收分歧申诉走原review出口，非直接接受或退款',()=>{const h=harness(),id=h.goods();h.returned();h.run('goods.inspect',{id,caseId:h.c.id,version:h.c.version,disposition:'disputed',reason:'原验收事实'},warehouse);h.closeHistorical();h.submit(find(h.render(['goods',id]),'goods.appeal'));assert.equal(h.c.status,'inspection_review');assert.equal(h.o.refunds.length,0);});

test('C09 部分实收方案明确未寄回不退金额，接受和拒绝继续原实物/协商状态',()=>{for(const decision of ['accept','reject']){const h=harness(),id=h.goods();h.returned();h.run('goods.inspect-partial',{id,caseId:h.c.id,version:h.c.version,qty:1,evidence:'本次实际收到1件'},warehouse);h.run('goods.partial-propose',{id,caseId:h.c.id,version:h.c.version,resolution:'refund',qty:1,amountCents:20000,shippingCents:0,reason:'原部分实收方案'},support);h.closeHistorical();const html=h.render(['goods',id]);assert.match(html,/未寄回的1件由您继续保留，本案不退该部分金额/);h.submit(find(html,'goods.partial-confirm'),{decision});assert.equal(h.c.status,decision==='accept'?'awaiting_return_disposition':'partial_received');assert.equal(h.o.refunds.length,0);assert.equal(h.o.lines[0].returnedQty,0);}});

test('C09 原配送异常方案同意/拒绝只进入原等待/协调，不当成功办结',()=>{for(const decision of ['accept','reject']){const h=harness(),id=h.goods();h.run('goods.incident-open',{id,version:h.o.version,stage:'delivery',kind:'delay',reason:'原运输延迟'},support);h.run('goods.incident-propose',{id,incidentId:h.i.id,version:h.i.version,resolution:'continue',reason:'原继续履约方案'},support);h.closeHistorical();h.submit(find(h.render(['goods',id]),'goods.incident-confirm'),{decision});assert.equal(h.i.status,decision==='accept'?'waiting':'open');assert.equal(h.o.status,'shipped');assert.equal(h.o.refunds.length,0);}});

test('C09 签收争议实际收货输入先依原核实和已接受方案，原发生时间/版本守卫继续有效',()=>{const h=harness(),id=h.goods();h.run('goods.incident-open',{id,version:h.o.version,stage:'delivery',kind:'receipt-dispute',receiptClaim:'not-received',occurredAt:h.s.now,evidence:'原签收事实说明',reason:'本人未收到'},support);h.closeHistorical();assert.ok(!cmds(h.render(['goods',id])).includes('goods.incident-receipt'));h.run('goods.incident-verify',{id,incidentId:h.i.id,version:h.i.version,conclusion:'confirmed',occurredAt:h.s.now,evidence:'客服核实原事实',reason:'原核实结论'},support);h.run('goods.incident-propose',{id,incidentId:h.i.id,version:h.i.version,resolution:'continue',reason:'核实后继续原配送'},support);h.submit(find(h.render(['goods',id]),'goods.incident-confirm'),{decision:'accept'});const form=find(h.render(['goods',id]),'goods.incident-receipt');assert.match(form.body,/name="occurredAt"/);assert.throws(()=>h.submit(form,{occurredAt:h.s.now+HOUR,evidence:'实际收件'}),/时间/);h.submit(form,{occurredAt:h.s.now,evidence:'本人实际完整正确收到原货'});assert.equal(h.i.receiptFact.occurredAt,h.s.now);assert.equal(h.o.status,'shipped');assert.equal(h.o.refunds.length,0);assert.ok(!cmds(h.render(['goods',id])).includes('goods.incident-receipt'));});

test('C09 既有服务票补正原版本/期限有效，首次新票关闭；原文件元素仍交原授权hydrate',()=>{const h=harness(),id=h.book(),inv=h.applyService();h.run('invoice.reject',{id:inv.id,version:inv.version,reason:'原抬头待补正'},storeFinance);h.close();let html=h.render(['invoices',inv.id]);safeReturns(html);h.submit(find(html,'invoice.resubmit'),{...title,title:'本人原票补正抬头'});let x=h.s.serviceInvoices.find(x=>x.id===inv.id);assert.equal(x.status,'pending');assert.equal(x.title,'本人原票补正抬头');h.run('invoice.issue',{id:x.id,version:x.version,ticketNumber:'C09-BLUE-SERVICE',file},storeFinance);html=h.render(['invoices',inv.id]);assert.match(html,/data-invoice-file=/);assert.match(html,/data-invoice-slot="issued"/);assert.doesNotMatch(html,/data-invoice-domain="commerce"/);assert.equal(authorizedInvoiceFile(h.s,user,inv.id,'issued',file.ref).ref,file.ref);assert.deepEqual(cmds(html),[]);assert.throws(()=>reduce(h.s,user,'invoice.apply',{bookingId:id,...title,requestId:'new-invoice-after-close'}),/既有权益/);});

test('C09 服务票原退款红冲后净额重开实际原票链保留，未知退款时不画补正/重开',()=>{const h=harness(),id=h.book(),inv=h.applyService();h.run('invoice.issue',{id:inv.id,version:inv.version,ticketNumber:'C09-SERVICE-ORIGINAL',file},storeFinance);h.run('booking.refund-request',{id,requests:[{paymentId:h.b.payment.id,amountCents:5000}],reason:'原部分退款'},user);h.run('booking.refund-review',{id,refundId:h.r.id,decision:'approve',reason:'原退款批准'},store);h.run('booking.refund-pay',{id,refundId:h.r.id,outcome:'success'},finance);let x=h.s.serviceInvoices.find(x=>x.id===inv.id);assert.equal(x.status,'red_pending');h.run('invoice.red',{id:x.id,version:x.version,ticketNumber:'C09-SERVICE-RED',file},storeFinance);h.close();const form=find(h.render(['invoices',inv.id]),'invoice.reapply');h.submit(form,title);const newer=h.s.serviceInvoices.at(-1);assert.equal(newer.replacesId,inv.id);assert.equal(newer.amount,24800);assert.equal(h.s.serviceInvoices.find(x=>x.id===inv.id).replacedById,newer.id);assert.match(h.render(['invoices',newer.id]),/¥248\.00/);});

test('C09 原商品票补正和原票净额重开各走原命令，不开放集团月票或首次开票',()=>{for(const reopen of [false,true]){const h=harness(),id=h.goods();h.goodsRule();const inv=h.applyGoods();if(!reopen)h.run('commerce-invoice.reject',{id:inv.id,version:inv.version,reason:'原抬头待补正'},finance);else{h.run('commerce-invoice.issue',{id:inv.id,version:inv.version,ticketNumber:'C09-GOODS-BLUE',file},finance);h.case('refund',{qty:1,amountCents:1000});h.review();h.run('goods.refund',{id,caseId:h.c.id,version:h.c.version,outcome:'success'},finance);let x=h.s.commerceInvoices.find(x=>x.id===inv.id);assert.equal(x.status,'red_pending');h.run('commerce-invoice.red',{id:x.id,version:x.version,ticketNumber:'C09-GOODS-RED',file},finance);}h.closeHistorical();const html=h.render(['commodity-invoices',inv.id]);safeReturns(html);const form=find(html,reopen?'commerce-invoice.reapply':'commerce-invoice.resubmit');h.submit(form,title);const x=h.s.commerceInvoices.at(-1);assert.equal(x.status,'pending');if(reopen){assert.equal(x.replacesId,inv.id);assert.equal(x.amount,40000);assert.match(html,/data-invoice-domain="commerce"/);}assert.throws(()=>reduce(h.s,user,'commerce-invoice.apply-goods',{orderId:id,...title,requestId:'new-goods-invoice'}),/既有权益/);}});

test('C09 原直接垫付本人接受/拒绝走真实余额不足及明确方案链，不露银行证据或替代成功退款',async()=>{for(const decision of ['accept','reject']){const h=harness(),id=await h.shortage();h.closeHistorical();const html=h.render(['booking',id]);safeReturns(html);assert.doesNotMatch(html,new RegExp(file.ref));assert.doesNotMatch(html,/failureEvidence|policySnapshot|退款技术号/);const form=find(html,'service-extra.advance-confirm',p=>p.decision===decision);assert.equal(form.payload.version,h.issue.version);assert.equal(form.payload.advanceId,h.advance.id);h.submit(form);assert.equal(h.advance.status,decision==='accept'?'confirmed':'rejected');assert.equal(h.r.status,'failed');assert.equal(h.b.payment.refundedCents,0);assert.ok(!cmds(h.render(['booking',id])).includes('service-extra.advance-confirm'));}});

test('C09 未知原支付、未结退款及服务票过期按原领域拒绝，非财务门控无操作',()=>{const h=harness(),id=h.book(),inv=h.applyService();h.run('invoice.reject',{id:inv.id,version:inv.version,reason:'原驳回'},storeFinance);h.run('booking.refund-request',{id,requests:[{paymentId:h.b.payment.id,amountCents:1000}],reason:'原退款'},user);h.run('booking.refund-review',{id,refundId:h.r.id,decision:'approve',reason:'批准'},store);h.run('booking.refund-pay',{id,refundId:h.r.id,outcome:'processing'},finance);h.closeHistorical();assert.ok(!cmds(h.render(['invoices',inv.id])).includes('invoice.resubmit'));assert.deepEqual(cmds(h.render(['booking',id],user,{canCommand:()=>false})),[]);for(const days of [31,31,29])h.run('clock.advance',{minutes:days*1440});assert.ok(!cmds(h.render(['invoices',inv.id])).includes('invoice.resubmit'));});

test('C09 新根/串本人/原付款和闭域快照变化转人工，不恢复普通页面；敏感附件不泄露',()=>{const h=harness(),id=h.book(),gid=h.goods();h.closeHistorical();for(const mutate of [s=>s.bookings.find(b=>b.id===id).userId='u2',s=>s.bookings.find(b=>b.id===id).createdAt--,s=>s.bookings.find(b=>b.id===id).payment.id='REPLACED-P',s=>s.privacyProfiles.unshift({userId:'u1',status:'active',version:0,history:[]}),s=>s.privacyClosures[0].rights.roots=[]]){const next=structuredClone(h.s);mutate(next);const html=closedRightsTransactionsUiView(next,user,['booking',id],ui);assert.match(html,/待人工核验/);assert.doesNotMatch(html,/<form\b|¥|REPLACED-P|CONTACT-CANARY/);}assert.match(h.render(['goods',gid],other)||'ordinary',/ordinary/);const missing=closedRightsTransactionsUiView(h.s,user,['goods','NEW-UNKNOWN'],ui);assert.match(missing,/待人工核验/);assert.doesNotMatch(missing,/NEW-UNKNOWN|<form\b|¥/);const before=structuredClone(h.s);for(const route of [['booking',id],['goods',gid]])safeReturns(h.render(route));assert.deepEqual(h.s,before);});

test('C09 正常关闭继续拒绝未结原事项，历史未结分支测试不改变此规则',()=>{for(const setup of [h=>h.goods(),h=>{const id=h.book();h.run('booking.refund-request',{id,requests:[{paymentId:h.b.payment.id,amountCents:1000}],reason:'原待处理退款'},user);},h=>{const id=h.book();h.run('care.case-create',{bookingId:id,category:'quality',description:'原未结反馈',sourceKind:'booking',sourceId:id},user);}]){const h=harness();setup(h);assert.throws(()=>h.close(),/尚有未结事项/);assert.notEqual(h.s.users[0].status,'closed');assert.ok(h.s.privacyClosures.every(x=>x.status!=='use_closed'&&!x.rights));}});

test('C09 原票旧版本、原文件替换及跨本人继续拒绝，表单沿原草稿/静态反馈契约',()=>{const h=harness();h.book();const inv=h.applyService();h.run('invoice.reject',{id:inv.id,version:inv.version,reason:'原驳回'},storeFinance);h.close();let html=h.render(['invoices',inv.id]),form=find(html,'invoice.resubmit');assert.match(form.body,/class="management-draft-note small muted" role="status"/);assert.match(form.body,/type="button"[^>]*data-command="ui.management-discard"/);h.submit(form,title);let x=h.s.serviceInvoices.at(-1);h.run('invoice.reject',{id:x.id,version:x.version,reason:'原再次核实驳回'},storeFinance);assert.throws(()=>h.submit(form,title),/更新|版本/);form=find(h.render(['invoices',inv.id]),'invoice.resubmit');h.submit(form,title);x=h.s.serviceInvoices.at(-1);h.run('invoice.issue',{id:x.id,version:x.version,ticketNumber:'C09-VERSION-BLUE',file},storeFinance);assert.throws(()=>authorizedInvoiceFile(h.s,other,inv.id,'issued',file.ref),/无权|本人|交易/);const newer={...file,ref:'invoice-file:'+'b'.repeat(64),name:'合成原票更正.pdf'};x=h.s.serviceInvoices.at(-1);h.run('invoice.replace-file',{id:x.id,version:x.version,slot:'issued',file:newer,reason:'原凭证实际引用更正'},storeFinance);assert.throws(()=>authorizedInvoiceFile(h.s,user,inv.id,'issued',file.ref),/更新/);html=h.render(['invoices',inv.id]);assert.match(html,new RegExp(newer.ref));assert.doesNotMatch(html,new RegExp(file.ref));assert.ok([...html.matchAll(/<p class="notice[^>]*>/g)].every(([v])=>!v.includes('button')&&!v.includes('data-command')));});

test('C09 商品原付款替换、invalid精确编号及失效会话保持静态核验，敏感原地址不回读',()=>{const h=harness(),id=h.goods();h.closeHistorical();const s=structuredClone(h.s);s.goods[0].payment.id='REPLACED-GOODS-PAYMENT';const html=closedRightsTransactionsUiView(s,user,['goods',id],ui);assert.match(html,/待人工核验/);assert.doesNotMatch(html,/¥|REPLACED|<form\b/);for(const path of [['goods',''],['booking',' '],['invoices','%ZZ']]){const page=h.render(path);assert.match(page,/待人工核验/);assert.doesNotMatch(page,/<form\b|¥/);}const invalid={...user,accountId:'MISSING',sessionId:'INVALID',grantId:'INVALID'};const page=h.render(['goods',id],invalid);assert.match(page,/待人工核验/);assert.doesNotMatch(page,/<form\b|¥|TRACK-SYNTHETIC|江苏|南京/);});

test('C09 余22个原命令有对应详情入口和真实有效行为验收，未授权命令仍拒绝',()=>{const source=Object.keys({
  'booking.refund-request':1,'booking.refund-answer':1,'booking.assistance-request':1,'booking.help':1,
  'care.case-create':1,'care.case-statement':1,'care.case-answer':1,
  'goods.case':1,'goods.receive':1,'goods.appeal':1,'goods.return':1,'goods.return-back-accept':1,'goods.return-back-receive':1,'goods.case-withdraw':1,'goods.partial-confirm':1,'goods.incident-confirm':1,'goods.incident-receipt':1,
  'invoice.resubmit':1,'invoice.reapply':1,'commerce-invoice.resubmit':1,'commerce-invoice.reapply':1,'service-extra.advance-confirm':1
});assert.equal(source.length,22);assert.deepEqual([...observedCommands].sort(),source.sort());assert.deepEqual(source.sort(),CLOSED_RIGHTS_COMMANDS.filter(x=>!x.startsWith('service-promotion.')).sort());const h=harness(),id=h.book();h.closeHistorical();for(const type of ['booking.pay','booking.change-answer','booking.extension-create','goods.pay','goods.address-change','review.create','invoice.apply','commerce-invoice.apply-goods'])assert.throws(()=>reduce(h.s,user,type,{id,bookingId:id,requestId:'forbidden'}),/既有权益|关闭/);});
