import test from 'node:test';
import assert from 'node:assert/strict';
import {upgradePrivacy,privacyProfile,privacyCommand,privacyBlockers,privacyData,assertPrivacyCommand,captureBookingPrivacy} from './privacy.mjs';
const now=Date.parse('2026-10-03T12:00:00+08:00'),u={role:'user',userId:'u1'},other={role:'user',userId:'u2'},support={role:'group',job:'support',accountId:'staff-1'};
const seed=()=>({now,seq:0,users:[{id:'u1',name:'甲',phone:'13800000001'},{id:'u2',name:'乙',phone:'13800000002'}],bookings:[],goods:[],addresses:[{id:'A1',userId:'u1'},{id:'A2',userId:'u2'}],carts:{u1:[1],u2:[2]},promotions:{u1:{storeId:'s1'},u2:{storeId:'s2'}},logs:[]});
let seq=0;
const ctx=s=>({id:prefix=>prefix+(++s.seq),log:(_,text)=>s.logs.push(text)});
function run(s,type,p={},a=u){const n=structuredClone(s);privacyCommand(n,a,type,{requestId:'P'+(++seq),...p},ctx(n));return n;}
const request=(s=seed())=>run(s,'privacy.request',{version:privacyProfile(s,'u1').version,reason:'本人申请',acknowledged:true});
const closure=s=>s.privacyClosures.at(-1);
const close=s=>run(s,'privacy.close',{id:closure(s).id,version:closure(s).version,reason:'未结事项已核对，历史材料继续核查',custodian:'客服甲',acknowledged:true},support);
const booking=(extra={})=>({id:'B1',userId:'u1',status:'done',payment:{status:'success',amountCents:19800,refundedCents:0},refunds:[],extensions:[],...extra});
test('privacy migration is additive and does not fabricate historical authorization',()=>{const s=seed(),old=structuredClone(s);upgradePrivacy(s);const first=structuredClone(s);upgradePrivacy(s);assert.deepEqual(s,first);assert.deepEqual(s.users,old.users);assert.equal(privacyProfile(s,'u1').version,0);assert.equal(privacyProfile(s,'u1').identityConsent,null);assert.deepEqual(s.privacyProfiles,[]);});
test('legacy booking calls without privacy profile stay compatible and make no consent',()=>{const s=seed();assertPrivacyCommand(s,u,'booking.create',{});assert.equal(captureBookingPrivacy(s,u,{},ctx(s)),null);assert.equal(s.privacyProfiles,undefined);});
test('new booking records explicit purpose version and rejects stale consent',()=>{const s=seed();captureBookingPrivacy(s,u,{privacyVersion:0,privacyConsent:true,requestId:'book-1'},ctx(s));const p=privacyProfile(s,'u1');assert.equal(p.version,1);assert.equal(p.identityConsent.agreed,true);assert.equal(p.history[0].bookingRequestId,'book-1');assert.throws(()=>assertPrivacyCommand(s,u,'booking.create',{privacyVersion:0,privacyConsent:true}),/版本/);assert.throws(()=>assertPrivacyCommand(s,u,'booking.create',{privacyVersion:1,privacyConsent:false}),/明确同意/);});
test('withdrawal invalidates old draft but existing refund and help remain available',()=>{let s=run(seed(),'privacy.consent',{version:0,agreed:true});s=run(s,'privacy.withdraw',{version:1,reason:'暂不使用'});assert.equal(privacyProfile(s,'u1').identityConsent.agreed,false);for(const p of [{},{privacyVersion:1,privacyConsent:true},{privacyVersion:2,privacyConsent:false}])assert.throws(()=>assertPrivacyCommand(s,u,'booking.create',p));for(const t of ['booking.refund','booking.help','goods.create'])assert.doesNotThrow(()=>assertPrivacyCommand(s,u,t,{}));assert.doesNotThrow(()=>assertPrivacyCommand(s,u,'booking.create',{privacyVersion:2,privacyConsent:true}));});
test('successful booking retry is idempotent even after withdrawal and never reconsents',()=>{let s=seed(),p={requestId:'book-1',privacyVersion:0,privacyConsent:true};captureBookingPrivacy(s,u,p,ctx(s));s.bookings.push(booking({requestId:'book-1'}));s=run(s,'privacy.withdraw',{version:1,reason:'撤回'});const before=structuredClone(s);assertPrivacyCommand(s,u,'booking.create',p);captureBookingPrivacy(s,u,p,ctx(s));assert.deepEqual(s,before);assert.equal(privacyProfile(s,'u1').identityConsent.agreed,false);});
test('consent commands require explicit checkbox and support only their declared purpose',()=>{assert.throws(()=>run(seed(),'privacy.consent',{version:0}),/明确勾选/);assert.throws(()=>run(seed(),'privacy.consent',{version:0,agreed:true,purpose:'marketing'}),/独立流程/);for(const version of [undefined,true,'',1])assert.throws(()=>run(seed(),'privacy.withdraw',{version,reason:'撤回'}),/版本/);});
test('privacy commands and reads reject foreign roles and users',()=>{const s=request();for(const a of [{role:'store',storeId:'s1'},{role:'group',job:'finance'},{role:'tech',techId:'t1'},{role:'user',userId:'unknown'}]){assert.equal(privacyData(s,a),null);assert.throws(()=>run(s,'privacy.close',{id:closure(s).id,version:1},a),/无权/);}assert.deepEqual(privacyData(s,other).closures,[]);assert.throws(()=>run(s,'privacy.retract',{id:closure(s).id,version:1,reason:'撤回'},other),/无权/);});
test('request can record pending business but closing rechecks live blockers',()=>{const s=seed();s.bookings=[booking({status:'confirmed'})];const requested=request(s);assert.equal(privacyProfile(requested,'u1').status,'active');assert.throws(()=>close(requested),/预约尚未结束/);assert.doesNotThrow(()=>assertPrivacyCommand(requested,u,'booking.cancel',{}));});
test('service blockers include unknown split payments and rejected offers with open deadline',()=>{const s=seed();s.bookings=[booking({extensions:[{status:'processing'}],refunds:[{id:'R1',status:'rejected',deadline:now+1000}],disputes:[{id:'D1',status:'open'}]})];assert.deepEqual(privacyBlockers(s,'u1').map(x=>x.code),['payment','refund','dispute']);s.bookings[0].refunds=[{status:'success',executions:[{amountCents:100,status:'failed'}]}];assert.ok(privacyBlockers(s,'u1').some(x=>x.code==='refund'));});
test('safety orphan unresolved dispute, quality case, review appeal and invoice are blocking',()=>{const s=seed();s.bookings=[booking()];s.safety=[{id:'S1',bookingId:'B1',status:'closed',unresolvedDispute:true}];s.serviceCareCases=[{id:'C1',bookingId:'B1',status:'user_pending'}];s.serviceReviews=[{id:'V1',userId:'u1',appeal:{status:'group_pending'}}];s.serviceInvoices=[{id:'I1',userId:'u1',bookingId:'B1',status:'red_pending'}];const b=privacyBlockers(s,'u1');assert.deepEqual(b.map(x=>x.code),['safety','care','review','invoice']);assert.equal(b.find(x=>x.code==='care').path,'/user/care/case/C1');});
test('goods blockers include fulfillment, payment and unresolved return/refund',()=>{const s=seed();s.goods=[{id:'G1',userId:'u1',status:'shipped',payment:{status:'processing'},cases:[{status:'refund_failed'}],refunds:[]}];assert.deepEqual(privacyBlockers(s,'u1').map(x=>x.code),['goods','goods-payment','goods-case']);assert.deepEqual(privacyBlockers(s,'u2'),[]);});
test('merchant settlement, technician income, ordinary callbacks and unaccepted advice do not block',()=>{const s=seed();s.bookings=[booking()];s.serviceFinanceEntries=[{bookingId:'B1',status:'failed'}];s.techIncomePayouts=[{status:'pending'}];s.bills=[{status:'failed'}];s.recoveries=[{status:'open'}];s.serviceCareFollowups=[{bookingId:'B1',status:'open'}];s.serviceHandoffs=[{bookingId:'B1',notes:[{status:'pending'}]}];assert.deepEqual(privacyBlockers(s,'u1'),[]);});
test('terminal records do not add arbitrary service or invoice waiting periods',()=>{const s=seed();s.bookings=[booking({completedAt:now})];s.goods=[{id:'G1',userId:'u1',status:'received',receivedAt:now,payment:{status:'success'},cases:[{status:'done'}],refunds:[{status:'success'}]}];s.serviceInvoices=[{userId:'u1',status:'issued'}];assert.deepEqual(privacyBlockers(s,'u1'),[]);assert.equal(close(request(s)).privacyClosures[0].status,'use_closed');});
test('request retract and resubmit has independent immutable history and versions',()=>{let s=request(),id=closure(s).id;s=run(s,'privacy.retract',{id,version:1,reason:'继续使用'});assert.equal(closure(s).status,'retracted');assert.equal(privacyProfile(s,'u1').status,'active');s=request(s);assert.equal(s.privacyClosures.length,2);assert.notEqual(closure(s).id,id);assert.throws(()=>run(s,'privacy.retract',{id:closure(s).id,version:0,reason:'旧提交'}),/版本/);});
test('durable command idempotency is content bound and user scoped',()=>{const s=seed(),p={requestId:'same',version:0,reason:'申请',acknowledged:true};privacyCommand(s,u,'privacy.request',p,ctx(s));const before=structuredClone(s);privacyCommand(s,u,'privacy.request',p,ctx(s));assert.deepEqual(s,before);assert.throws(()=>privacyCommand(s,u,'privacy.request',{...p,reason:'另一次'},ctx(s)),/同一提交/);privacyCommand(s,other,'privacy.request',p,ctx(s));assert.equal(s.privacyClosures.length,2);});
test('close requires explicit retention acknowledgement, explanation and responsible person',()=>{const s=request(),p={id:closure(s).id,version:1,reason:'办理',custodian:'甲',acknowledged:true};for(const changes of [{reason:''},{custodian:''},{acknowledged:false}])assert.throws(()=>run(s,'privacy.close',{...p,...changes},support));});
test('close cleans only declared current basics and retains all business/financial facts',()=>{const s=seed();s.bookings=[booking({contactName:'旧联系人',phone:'13800000001'})];s.goods=[{id:'G1',userId:'u1',status:'received',payment:{status:'success'},address:{detail:'历史收货地址'}}];s.recipients=[{id:'R1',userId:'u1',name:'家人甲',relationship:'母亲',active:true,version:2,history:[{previous:{name:'旧家人'}}]},{id:'R2',userId:'u2',name:'其他家人',active:true}];s.serviceInvoices=[{id:'I1',userId:'u1',status:'issued',email:'sample@example.com',issued:{file:{ref:'file-ref'}}}];const before=structuredClone(s),closed=close(request(s));assert.deepEqual(closed.bookings,before.bookings);assert.deepEqual(closed.goods,before.goods);assert.deepEqual(closed.serviceInvoices,before.serviceInvoices);assert.equal(closed.users[0].name,'已关闭用户');assert.equal(closed.users[0].phone,undefined);assert.deepEqual(closed.users[1],before.users[1]);assert.deepEqual(closed.addresses,[before.addresses[1]]);assert.equal(closed.carts.u1,undefined);assert.deepEqual(closed.carts.u2,[2]);assert.equal(closed.recipients[0].active,false);assert.equal(closed.recipients[0].name,'已停用对象');assert.equal(closed.recipients[0].history[0].previous.name,'旧家人');assert.deepEqual(closed.recipients[1],before.recipients[1]);assert.equal(closure(closed).cleanupStatus,'pending_review');assert.ok(closure(closed).retention.some(x=>x.kind==='invoices'));assert.ok(closure(closed).retention.every(x=>x.deadline===null));});
test('closed user retains own receipt but cannot write new transactions or manipulate closure',()=>{const s=close(request());assert.equal(privacyData(s,u).closures[0].status,'use_closed');for(const type of ['booking.create','goods.create','recipient.save','privacy.consent'])assert.throws(()=>assertPrivacyCommand(s,u,type,{}),/使用已关闭/);assert.throws(()=>run(s,'privacy.retract',{id:closure(s).id,version:closure(s).version,reason:'恢复'}),/使用已关闭/);});
test('followup preserves pending status and records actual stable staff identity',()=>{let s=close(request()),c=closure(s);s=run(s,'privacy.followup',{id:c.id,version:c.version,note:'已核查发票附件，保留范围继续确认',custodian:'客服乙'},support);c=closure(s);assert.equal(c.cleanupStatus,'pending_review');assert.equal(c.followups[0].by.id,'staff-1');assert.equal(c.followups[0].status,'pending_review');assert.throws(()=>run(s,'privacy.followup',{id:c.id,version:2,note:'旧页',custodian:'甲'},support),/版本/);});
test('privacy views are pure and do not invent profiles',()=>{const s=seed(),before=structuredClone(s);privacyData(s,u);privacyData(s,support);privacyBlockers(s,'u1');assert.deepEqual(s,before);});

const receivedGoods=(extra={})=>({id:'G1',userId:'u1',status:'received',payment:{status:'success'},cases:[],refunds:[],incidents:[],...extra});
test('live goods invoice issuance and red maintenance block closing only their real owner source',()=>{
  const s=seed();s.goods=[receivedGoods(),receivedGoods({id:'G2',userId:'u2'})];s.commerceInvoices=[{id:'GI1',category:'goods',userId:'u1',orderId:'G1',status:'pending'},{id:'GI2',category:'goods',userId:'u1',orderId:'G1',status:'red_pending'},{id:'FI1',category:'fee',userId:'u1',storeId:'s1',status:'pending'},{id:'foreign',category:'goods',userId:'u2',orderId:'G2',status:'pending'},{id:'bad-binding',category:'goods',userId:'u1',orderId:'G2',status:'pending'},{id:'old',category:'goods',userId:'u1',orderId:'G1',status:'pending',replacedById:'GI1'}];
  const before=structuredClone(s),rows=privacyBlockers(s,'u1');assert.deepEqual(rows.map(x=>x.id),['GI1','GI2']);assert.equal(rows[0].path,'/user/commodity-invoices/GI1');assert.equal(privacyBlockers(s,'u1','group')[0].path,'/group/goods/G1');assert.deepEqual(s,before);
  assert.throws(()=>close(request(s)),/商品发票/);s.commerceInvoices[0].status='issued';s.commerceInvoices[1].status='red';assert.deepEqual(privacyBlockers(s,'u1'),[]);assert.equal(closure(close(request(s))).status,'use_closed');
});
test('optional invoice resubmission and reissue do not create a new indefinite cancellation gate',()=>{
  const s=seed();s.goods=[receivedGoods()];s.commerceInvoices=['rejected','red','issued'].map((status,n)=>({id:'GI'+n,category:'goods',userId:'u1',orderId:'G1',status}));assert.deepEqual(privacyBlockers(s,'u1'),[]);const c=closure(close(request(s)));assert.equal(c.retention.find(x=>x.kind==='commerce-invoices').count,3);assert.equal(c.cleanupStatus,'pending_review');
});
test('received goods retain every unfinished incident until the original source actually completes',()=>{
  const s=seed();s.goods=[receivedGoods({incidents:[{id:'I1',kind:'receipt-dispute',status:'awaiting_user'},{id:'I2',kind:'wrong-item',status:'waiting'},{id:'I3',status:'done'}]}),receivedGoods({id:'G2',userId:'u2',incidents:[{id:'foreign',status:'open'}]})];const rows=privacyBlockers(s,'u1');assert.deepEqual(rows.map(x=>x.id),['I1','I2']);assert.ok(rows.every(x=>x.path==='/user/goods/G1'));assert.throws(()=>close(request(s)),/商品异常/);s.goods[0].incidents.forEach(i=>i.status='done');assert.deepEqual(privacyBlockers(s,'u1'),[]);assert.equal(closure(close(request(s))).status,'use_closed');
});
function directFixture(status,executionStatus,partStatus='success'){
  const s=seed();s.bookings=[booking({storeId:'s1',refunds:[{id:'R1',status:partStatus==='success'?'success':'approved',executions:[{paymentId:'P1',refundNo:'RN1',amountCents:19800,status:partStatus}]}],payment:{id:'P1',status:'success',amountCents:19800,refundedCents:partStatus==='success'?19800:0}})];s.serviceRefundShortages=[{id:'S1',bookingId:'B1',storeId:'s1',userId:'u1',paymentId:'P1',refundId:'R1',refundNo:'RN1',refundCents:19800,status:'refunded',advances:[{id:'A1',path:'direct-user',status,...(executionStatus?{execution:{status:executionStatus}}:{})}]}];return s;
}
test('personal direct-refund confirmation reads original live failed execution and owner binding',()=>{
  const s=directFixture('awaiting_user',null,'failed');let rows=privacyBlockers(s,'u1');assert.ok(rows.some(x=>x.code==='direct-refund-confirm'&&x.id==='A1'&&x.path==='/user/booking/B1'));assert.throws(()=>close(request(s)),/本人直接退款方案/);
  s.serviceRefundShortages[0].refundNo='unbound';assert.ok(!privacyBlockers(s,'u1').some(x=>x.code==='direct-refund-confirm'));s.serviceRefundShortages[0].refundNo='RN1';s.bookings[0].refunds[0].executions[0].status='success';s.bookings[0].refunds[0].status='success';assert.deepEqual(privacyBlockers(s,'u1'),[]);
});
test('actual unknown direct payment blocks even after original refund succeeded; resolved facts unblock',()=>{
  const s=directFixture('processing','processing');assert.deepEqual(privacyBlockers(s,'u1').map(x=>x.code),['direct-refund-query']);assert.throws(()=>close(request(s)),/本人直接退款结果/);const a=s.serviceRefundShortages[0].advances[0];a.status='failed';a.execution.status='failed';assert.deepEqual(privacyBlockers(s,'u1'),[]);assert.equal(closure(close(request(s))).status,'use_closed');
});
test('duplicate actual personal direct funds remain under review without gating internal merchant debt',()=>{
  const s=directFixture('needs-review','success');const a=s.serviceRefundShortages[0].advances[0];a.amountCents=19800;a.returnedCents=100;a.reconciliationRecords=[{kind:'actual-user-return',amountCents:100}];s.serviceExtraRecoveries=[{id:'D1',bookingId:'B1',amountCents:19800,receivedCents:0,status:'open'}];assert.deepEqual(privacyBlockers(s,'u1').map(x=>x.code),['direct-refund-review']);assert.throws(()=>close(request(s)),/重复款/);
  a.status='reconciled';a.returnedCents=19800;assert.deepEqual(privacyBlockers(s,'u1'),[]);const closed=close(request(s));assert.deepEqual(closed.serviceExtraRecoveries,s.serviceExtraRecoveries);assert.equal(closure(closed).status,'use_closed');
});
test('merchant funding, service debt, offsets and other users personal direct funds cannot gate this user',()=>{
  const s=directFixture('needs-review','success');s.serviceRefundShortages[0].advances[0].path='merchant-balance';s.serviceRefundShortages.push({...structuredClone(s.serviceRefundShortages[0]),id:'S2',userId:'u2',advances:[{id:'A2',path:'direct-user',status:'processing',execution:{status:'processing'}}]});s.serviceExtraRecoveries=[{bookingId:'B1',status:'open'}];s.serviceExtraOffsets=[{bookingId:'B1',status:'processing'}];assert.deepEqual(privacyBlockers(s,'u1'),[]);assert.equal(closure(close(request(s))).status,'use_closed');
});
test('withdraw identity consent keeps original approved refund and personal confirmation rights intact',()=>{
  let s=directFixture('awaiting_user',null,'failed');s=run(s,'privacy.consent',{version:0,agreed:true});const before=structuredClone({bookings:s.bookings,shortages:s.serviceRefundShortages});s=run(s,'privacy.withdraw',{version:1,reason:'只撤回新增实名用途'});assert.deepEqual({bookings:s.bookings,shortages:s.serviceRefundShortages},before);assert.doesNotThrow(()=>assertPrivacyCommand(s,u,'booking.refund-answer',{id:'B1',refundId:'R1',decision:'accept'}));assert.doesNotThrow(()=>assertPrivacyCommand(s,u,'service-extra.advance-confirm',{id:'S1'}));assert.throws(()=>assertPrivacyCommand(s,u,'booking.create',{privacyVersion:2,privacyConsent:false}),/明确同意/);assert.ok(privacyBlockers(s,'u1').some(x=>x.code==='direct-refund-confirm'));
});
test('expanded manual review counts actual owned sources and request references without copying or changing facts',()=>{
  const s=seed();s.bookings=[booking(),booking({id:'B2',userId:'u2'})];s.goods=[receivedGoods({incidents:[{id:'INC1',status:'done'}],goodsDeliveryFacts:[{id:'GF1',status:'verified'}],addressHistory:[{detail:'保留的原地址'}]}),receivedGoods({id:'G2',userId:'u2',goodsDeliveryFacts:[{id:'GF2'}]})];s.commerceInvoices=[{id:'GI1',category:'goods',orderId:'G1',userId:'u1',status:'issued',email:'old@example.com',issued:{file:{ref:'shared-original-ref'}}},{id:'GI2',category:'goods',orderId:'G2',userId:'u2',status:'issued'}];
  s.fulfilmentRecords=[{id:'FUL1',bookingId:'B1',facts:[{id:'FACT1',status:'verified',position:{lat:31,lng:121}}]},{id:'FUL2',bookingId:'B2'}];s.fulfilmentDepartures=[{id:'EXIT1',bookingId:'B1',status:'confirmed'}];s.fulfilmentNotices=[{id:'N1',bookingId:'B1'}];s.serviceExtraEvidence=[{id:'E1',bookingId:'B1',status:'applied'},{id:'E2',bookingId:'B2'}];s.serviceRefundShortages=[{id:'SH1',bookingId:'B1',status:'refunded',advances:[]}];s.serviceExtraRecoveries=[{id:'D1',bookingId:'B1',status:'open'}];s.serviceExtraOffsets=[{id:'O1',bookingId:'B1',status:'succeeded'}];
  s.workEscalations=[{id:'goods-incident:INC1:handling',sourceSnapshot:{category:'goods-exception',sourceId:'INC1'},history:[{reason:'原责任理由'}]},{id:'wrong-category',sourceSnapshot:{category:'care',sourceId:'INC1'}},{id:'foreign',sourceSnapshot:{category:'goods-shipping',sourceId:'G2'}}];s.commerceInvoiceRequests=[{resultId:'GI1'},{resultId:'GI2'}];s.fulfilmentRequests=[{result:{id:'FUL1'}},{result:{bookingId:'B1'}},{result:{id:'FUL2'}}];s.serviceExtraRequests=[{id:'E1'},{id:'E2'}];s.workEscalationRequests=[{result:{id:'goods-incident:INC1:handling'}},{result:{id:'foreign'}}];s.goodsExceptionRequests=[{id:'INC1'},{id:'G2'}];
  const business=structuredClone({bookings:s.bookings,goods:s.goods,invoices:s.commerceInvoices,fulfilment:s.fulfilmentRecords,extras:s.serviceExtraRecoveries,work:s.workEscalations});const closed=close(request(s)),c=closure(closed),byKind=Object.fromEntries(c.retention.map(x=>[x.kind,x]));assert.equal(byKind['commerce-invoices'].count,1);assert.equal(byKind.fulfilment.count,3);assert.equal(byKind['goods-facts'].count,3);assert.equal(byKind['service-extras'].count,4);assert.equal(byKind['work-escalations'].count,1);assert.equal(byKind['source-requests'].count,6);
  assert.ok(c.retention.every(x=>x.status==='pending_review'&&x.custodian==='客服甲'&&x.basis===null&&x.deadline===null));assert.deepEqual({bookings:closed.bookings,goods:closed.goods,invoices:closed.commerceInvoices,fulfilment:closed.fulfilmentRecords,extras:closed.serviceExtraRecoveries,work:closed.workEscalations},business);assert.equal(c.cleanupStatus,'pending_review');assert.doesNotMatch(JSON.stringify(c.retention),/old@example|保留的原地址|shared-original-ref|原责任理由/);
});
test('old closure snapshot remains immutable while current linked sources get pure pending review supplements',()=>{
  const s=seed();s.bookings=[booking()];const closed=close(request(s)),original=structuredClone(closure(closed).retention);closed.commerceInvoices=[{id:'GI1',userId:'u1',orderId:'G1',category:'goods',status:'issued'}];closed.goods=[receivedGoods()];closed.fulfilmentNotices=[{id:'N1',bookingId:'B1'}];const before=structuredClone(closed),c=privacyData(closed,u).closures[0];
  assert.deepEqual(c.retentionSnapshot,original);assert.deepEqual(c.retention.filter(x=>!x.reviewScope),original);assert.deepEqual(c.retentionSupplements.map(x=>x.sourceKind),['goods','commerce-invoices','fulfilment']);assert.ok(c.retentionSupplements.every(x=>x.status==='pending_review'&&x.basis===null&&x.deadline===null&&x.custodian==='客服甲'&&x.label.includes('当前来源补充核查')));assert.deepEqual(privacyData(closed,support).closures[0].retention,c.retention);assert.deepEqual(closed,before);assert.deepEqual(closure(closed).retention,original);assert.throws(()=>assertPrivacyCommand(closed,u,'goods.submit',{}),/使用已关闭/);
  closed.fulfilmentNotices.push({id:'N2',bookingId:'B1'});const current=privacyData(closed,u).closures[0];assert.equal(current.retentionSupplements.find(x=>x.sourceKind==='fulfilment').count,2);assert.deepEqual(closure(closed).retention,original);
});
