import test from 'node:test';
import assert from 'node:assert/strict';
import {privacyUiView} from './privacy-ui.mjs';
import {privacyCommand,privacyProfile} from './privacy.mjs';
const u={role:'user',userId:'u1'},other={role:'user',userId:'u2'},support={role:'group',job:'support',accountId:'ST1'};
const decode=v=>v.replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
function forms(html,type){return [...html.matchAll(/<form\b([^>]*)>([\s\S]*?)<\/form>/g)].map(([,attrs,body])=>({attrs,body,command:/data-command="([^"]+)"/.exec(attrs)?.[1],payload:JSON.parse(decode(/data-payload="([^"]+)"/.exec(attrs)?.[1]||'{}')),key:decode(/data-management-form="([^"]+)"/.exec(attrs)?.[1]||'')})).filter(x=>!type||x.command===type);}
function fixture(){let s={now:Date.parse('2026-10-03T14:00:00+08:00'),seq:0,users:[{id:'u1',name:'甲'},{id:'u2',name:'乙'}],bookings:[],goods:[],logs:[]},seq=0;return {get s(){return s;},get closure(){return s.privacyClosures?.at(-1)},page:(a=u)=>privacyUiView(s,a,['privacy']),send(f,p={},a=u){assert.ok(f,'UI form exists');const n=structuredClone(s);const result=privacyCommand(n,a,f.command,{...f.payload,...p,requestId:'ui-'+(++seq)},{id:prefix=>prefix+(++n.seq),log:(_,message)=>n.logs.push(message)});s=n;return result;},request(a=u){return this.send(forms(this.page(a),'privacy.request')[0],{reason:'本人申请',acknowledged:true},a);},close(){return this.send(forms(this.page(support),'privacy.close')[0],{reason:'核对无未结事项，历史资料待清理',custodian:'客服甲',acknowledged:true},support);}};}
test('privacy only handles own route and valid user or support identities',()=>{const f=fixture();assert.equal(privacyUiView(f.s,u,['home']),null);assert.match(privacyUiView(f.s,u,['privacy','unknown']),/页面不存在/);for(const a of [{role:'tech'},{role:'store'},{role:'manager'},{role:'group',job:'finance'},{role:'group',job:'operations'},{role:'user',userId:'no'}])assert.match(f.page(a),/无权/);assert.match(f.page(support),/暂无待处理申请/);});
test('identity notice describes local demonstration and existing rights without preconsent',()=>{const f=fixture(),html=f.page(),consent=forms(html,'privacy.consent')[0];assert.match(html,/不采集真实身份证号/);assert.match(html,/已有订单、退款与求助继续可用/);assert.equal(consent.payload.version,0);assert.equal(consent.payload.purpose,'identity');assert.doesNotMatch(consent.body,/checked/);assert.match(consent.body,/name="agreed"[^>]*required/);assert.throws(()=>f.send(consent),/明确勾选/);});
test('user can consent then withdraw from actual forms; privacy version advances visibly',()=>{const f=fixture();f.send(forms(f.page(),'privacy.consent')[0],{agreed:true});assert.match(f.page(),/已明确同意/);const withdraw=forms(f.page(),'privacy.withdraw')[0];assert.equal(withdraw.payload.version,1);f.send(withdraw,{reason:'撤回演示授权'});assert.match(f.page(),/已撤回/);assert.equal(privacyProfile(f.s,'u1').identityConsent.agreed,false);assert.equal(forms(f.page(),'privacy.consent')[0].payload.version,2);});
test('stale forms reject while draft key stays stable for retained input',()=>{const f=fixture(),old=forms(f.page(),'privacy.withdraw')[0];f.send(forms(f.page(),'privacy.consent')[0],{agreed:true});assert.throws(()=>f.send(old,{reason:'旧表单'}),/版本/);const fresh=forms(f.page(),'privacy.withdraw')[0];assert.equal(old.key,fresh.key);assert.match(fresh.attrs,/data-live-version="1"/);assert.match(fresh.body,/role="status"/);});
test('privacy drafts carry user and stable employee identity in their keys',()=>{const f=fixture();const a=forms(f.page(),'privacy.request')[0],b=forms(f.page(other),'privacy.request')[0];assert.notEqual(a.key,b.key);f.request();assert.match(forms(f.page(support),'privacy.close')[0].key,/ST1/);});
test('pending booking shows real action link and user can submit a request without silently cancelling',()=>{const f=fixture();f.s.bookings.push({id:'B1',userId:'u1',status:'confirmed',payment:{status:'success'}});const before=structuredClone(f.s.bookings);assert.match(f.page(),/href="#\/user\/booking\/B1"/);assert.match(f.page(),/客服暂不能关闭账号使用/);f.request();assert.deepEqual(f.s.bookings,before);assert.equal(privacyProfile(f.s,'u1').status,'active');const staff=f.page(support);assert.match(staff,/href="#\/group\/bookings\/B1"/);assert.equal(forms(staff,'privacy.close').length,0);assert.equal(forms(f.page(),'privacy.retract').length,1);});
test('request acknowledgement and explanatory reason are mandatory from the UI',()=>{const f=fixture(),form=forms(f.page(),'privacy.request')[0];assert.match(form.body,/name="acknowledged"[^>]*required/);assert.match(form.body,/name="reason"[^>]*required/);assert.throws(()=>f.send(form,{reason:'申请'}),/确认已阅读/);assert.match(f.page(),/历史.*|附件可能仍需保留处理/);});
test('pending request can be withdrawn and new application stays available',()=>{const f=fixture();f.request();assert.equal(forms(f.page(),'privacy.request').length,0);f.send(forms(f.page(),'privacy.retract')[0],{reason:'继续使用'});assert.equal(f.closure.status,'retracted');assert.equal(forms(f.page(),'privacy.request').length,1);assert.match(f.page(),/已撤回/);});
test('support action from real form closes usage with explicit pending cleanup receipt',()=>{const f=fixture();f.request();const close=forms(f.page(support),'privacy.close')[0];assert.match(close.body,/name="custodian"/);assert.match(close.body,/name="acknowledged"/);f.close();const html=f.page();assert.match(html,/使用已关闭 · 资料清理待完成/);assert.match(html,/不代表全部数据删除或匿名化完成/);assert.match(html,/后续清理负责人/);assert.match(html,/具体期限待确认/);assert.match(html,/本申请编号交集团客服/);assert.equal(forms(html).length,0);assert.doesNotMatch(html,/申请关闭账号使用<\/h2>/);});
test('necessary materials list includes history and independent file storage boundary',()=>{const f=fixture();f.s.bookings.push({id:'B1',userId:'u1',status:'done',payment:{status:'success'}});f.s.serviceInvoices=[{id:'I1',userId:'u1',bookingId:'B1',status:'issued'}];f.request();f.close();const html=f.page();assert.match(html,/预约交易、原联系人快照与履约材料/);assert.match(html,/发票资料、修改历史及独立保存的附件/);assert.match(html,/各标签页缓存/);assert.doesNotMatch(html,/已全部清理|全部删除成功/);});
test('support can append real cleanup progress but cannot mark unverified cleanup completed',()=>{const f=fixture();f.request();f.close();const form=forms(f.page(support),'privacy.followup')[0];assert.match(form.body,/处理进度与实际结果/);f.send(form,{note:'已核对附件，继续确认保留范围',custodian:'客服乙'},support);assert.equal(f.closure.cleanupStatus,'pending_review');assert.match(f.page(),/已核对附件/);assert.match(f.page(),/负责人 客服乙/);assert.equal(forms(f.page(),'privacy.followup').length,0);});
test('receipts and blockers stay scoped to their owning user',()=>{const f=fixture();f.request();assert.match(f.page(),/本人申请/);assert.doesNotMatch(f.page(other),/本人申请/);f.close();assert.match(f.page(),/使用关闭回执/);assert.doesNotMatch(f.page(other),/使用关闭回执/);});
test('notices use status semantics, actions are distinct buttons and escaped content is inert',()=>{const f=fixture();f.request();f.close();f.send(forms(f.page(support),'privacy.followup')[0],{note:'<img src=x onerror=alert(1)>',custodian:'<script>甲</script>'},support);const html=f.page();assert.match(html,/&lt;img/);assert.doesNotMatch(html,/<img src=x|<script>/);for(const [,attrs] of html.matchAll(/<p\b([^>]*class="notice[^>]*)>/g)){assert.match(attrs,/role="status"/);assert.doesNotMatch(attrs,/data-command|role="button"|tabindex/);}assert.doesNotMatch(html,/class="(?:primary|secondary)"[^>]*>.*资料清理待完成/);});
test('privacy page rendering is pure including closed receipt',()=>{const f=fixture();f.request();f.close();const before=structuredClone(f.s);f.page();f.page(other);f.page(support);assert.deepEqual(f.s,before);});
test('任一关闭信号不让第一条active资料恢复授权或申请表单',()=>{
  const f=fixture();f.request();f.s.users[0].status='closed';
  const before=structuredClone(f.s),html=f.page();assert.match(html,/关闭依据需要人工核查/);assert.equal(forms(html).length,0);assert.deepEqual(f.s,before);
  f.s.privacyProfiles.push({userId:'u1',status:'use_closed',history:[]});assert.equal(forms(f.page()).length,0);
});
test('正常关闭回执提供既有权益入口，不把资料待清理状态画成动作',()=>{
  const f=fixture();f.request();f.close();const html=f.page();assert.match(html,/href="#\/user\/rights"/);assert.match(html,/查看既有权益/);assert.equal(forms(html).length,0);assert.doesNotMatch(html,/data-command="privacy\.consent"/);
});
