import test from 'node:test';
import assert from 'node:assert/strict';
import {seed,reduce,upgradeFinanceState} from './engine.mjs';
import {bookingOptions} from './booking.mjs';
import {qualificationEligibility,qualificationView,qualificationCaseBlockers} from './tech-qualification.mjs';
import {careClosureBlockers,careBlocksBooking} from './service-care.mjs';
const user={role:'user',userId:'u1'},store={role:'store',storeId:'xingfu'},group={role:'group',job:'operations'},support={role:'group',job:'support'};
function setup(){let s=seed(),seq=0;const h={get s(){return s},get t(){return s.techs.at(-1)},get q(){return s.techQualifications?.find(x=>x.techId===h.t.id)},get b(){return s.bookings.at(-1)},run(a,type,p={}){s=reduce(s,a,type,{requestId:'qual-int-'+(++seq),reason:'隔离测试依据',...p});return s},qual(type,p={},a=store){return h.run(a,'qualification.'+type,{techId:h.t.id,version:h.q?.version||0,...p})},advance(minutes){h.run(user,'clock.advance',{minutes})}};
 h.run(store,'manage.tech-save',{name:'准入测试师傅',phone:'13800005555',storeId:'xingfu',gender:'female',lat:31.231,lng:121.475,serviceIds:['relax','neck'],certificate:'DEMO-C',insurance:'DEMO-I',validUntil:'2027-12-31'});
 h.run(group,'manage.tech-review',{id:h.t.id,version:h.t.version,decision:'approve'});return h;}
function authorize(h,serviceIds=['neck'],extra={}){h.qual('assess',{serviceIds,batch:'测试批次',assessor:'测试考核人',proof:'DEMO-QA',occurredAt:h.s.now,result:'pass',kind:'initial',...extra});h.qual('request',{assessmentId:h.q.assessments.at(-1).id});h.qual('review',{grantId:h.q.grants.at(-1).id,decision:'approve',reviewer:'测试集团审核人',proof:'DEMO-QG'},group);}
function book(h,{techId=h.t.id,serviceId='neck',hours=5}={}){h.run(user,'booking.create',{storeId:'xingfu',serviceId,techId,regionId:'home',mode:'specified',genderPreference:'any',startAt:h.s.now+hours*3600000,contactName:'测试',phone:'13800001111',healthConsent:true,identityVerified:true,adultConfirmed:true});}
function payAccept(h){h.run(user,'booking.pay',{id:h.b.id,outcome:'success'});h.run({role:'tech',techId:h.b.techId},'booking.accept',{id:h.b.id});}
function pause(h,extra={}){h.qual('pause',{serviceIds:['neck'],owner:'演示复训负责人',...extra});return h.q.holds.at(-1).id;}
function resume(h,holdId){h.qual('resume',{holdId,reviewer:'演示恢复审核员'},group);}

test('Q02 新建资料审核通过仍不可约；实际考核申请批准后仅授权项目可约',()=>{const h=setup();assert.equal(h.t.active,true);assert.equal(qualificationEligibility(h.s,h.t.id,'neck').allowed,false);assert.throws(()=>book(h),/独立服务授权/);authorize(h);assert.equal(bookingOptions(h.s,{storeId:'xingfu',serviceId:'neck',regionId:'home',techId:h.t.id,mode:'specified'}).candidates.find(x=>x.id===h.t.id).available,true);assert.throws(()=>book(h,{serviceId:'relax'}),/独立服务授权/);book(h);payAccept(h);assert.equal(h.b.status,'confirmed');assert.equal(h.s.goods.length,0);});

test('Q03 未开始暂停保留原单与派单期限，拒绝接单派单和开始，原用户取消可执行',()=>{const h=setup();authorize(h);book(h);h.run(user,'booking.pay',{id:h.b.id,outcome:'success'});const original=structuredClone(h.b),hold=pause(h);assert.deepEqual(h.b,original);assert.throws(()=>h.run({role:'tech',techId:h.t.id},'booking.accept',{id:h.b.id}),/资格已暂停/);assert.throws(()=>h.run(store,'booking.assign',{id:h.b.id,techId:h.t.id}),/资格已暂停/);authorize(h,['neck'],{kind:'retraining',holdId:hold});assert.throws(()=>resume(h,hold),/协调/);h.run(user,'booking.cancel',{id:h.b.id,reason:'原流程取消'});resume(h,hold);assert.equal(h.q.holds[0].status,'resolved');assert.equal(h.b.round.deadline,original.round.deadline);assert.equal(h.b.status,'cancelled');});

test('Q03 暂停后未出发已确认订单不能开始，已出发事实允许原服务完成',()=>{for(const departed of [false,true]){const h=setup();authorize(h);book(h);payAccept(h);if(departed)h.b.departedAt=h.s.now; // legacy fulfillment fact, no new UI introduced
const before=structuredClone(h.b);pause(h);assert.deepEqual(h.b,before);h.advance(300);const a={role:'tech',techId:h.t.id};if(!departed){assert.throws(()=>h.run(a,'booking.start',{id:h.b.id}),/资格已暂停/);continue;}h.run(a,'booking.start',{id:h.b.id});h.advance(45);h.run(a,'booking.finish',{id:h.b.id,mode:'normal'});assert.equal(h.b.status,'done');}});

test('Q03 服务中暂停不退回派单、不重写履约，完成和求助保留',()=>{const h=setup();authorize(h);book(h);payAccept(h);h.advance(300);h.run({role:'tech',techId:h.t.id},'booking.start',{id:h.b.id});const before=structuredClone(h.b);pause(h);assert.deepEqual(h.b,before);h.run(user,'booking.help',{id:h.b.id,reason:'演示求助',note:'仍可求助'});assert.equal(h.b.status,'active');h.advance(45);h.run({role:'tech',techId:h.t.id},'booking.finish',{id:h.b.id,mode:'normal'});assert.equal(h.b.status,'done');});

test('Q04 资格暂停使支付复核及待确认变更失效，不能通过旧候选绕过',()=>{const h=setup();authorize(h);book(h);pause(h);h.run(user,'booking.pay',{id:h.b.id,outcome:'success'});assert.equal(h.b.status,'cancelled');const z=setup();authorize(z);book(z,{techId:'chen'});payAccept(z);z.run(store,'booking.assign',{id:z.b.id,techId:z.t.id,reason:'用户确认候选'});const c=structuredClone(z.b.change);pause(z);assert.throws(()=>z.run(user,'booking.change-answer',{id:z.b.id,changeId:c.id,decision:'accept'}),/资格已暂停/);assert.equal(z.b.techId,'chen');assert.equal(z.b.change.status,'pending');});

test('Q04 反馈限制专项按真实暂停复训授权恢复解除，原结案及资金阻断保留',()=>{const h=setup();authorize(h);book(h);payAccept(h);h.advance(300);h.run({role:'tech',techId:h.t.id},'booking.start',{id:h.b.id});h.advance(45);h.run({role:'tech',techId:h.t.id},'booking.finish',{id:h.b.id,mode:'normal'});h.run(user,'care.case-create',{bookingId:h.b.id,category:'quality',description:'演示专项跟进'});const c=()=>h.s.serviceCareCases.at(-1);h.run(store,'care.case-respond',{id:c().id,version:c().version,decision:'respond',publicReply:'需复训核实',specialistAction:'retraining'});h.run(user,'care.case-answer',{id:c().id,version:c().version,decision:'accept'});const hold=pause(h,{caseId:c().id,actionIndex:0,caseVersion:c().version});assert.ok(qualificationCaseBlockers(h.s,c()).length);assert.equal(careBlocksBooking(h.s,h.b),true);c().specialistActions[0].status='completed';assert.ok(careClosureBlockers(h.s,c()).length);c().specialistActions[0].status='pending';authorize(h,['neck'],{kind:'retraining',holdId:hold});assert.ok(qualificationCaseBlockers(h.s,c()).length);resume(h,hold);assert.deepEqual(qualificationCaseBlockers(h.s,c()),[]);h.run(store,'care.case-close',{id:c().id,version:c().version,conclusion:'实际复训授权恢复均已核验'});assert.equal(c().status,'closed');assert.equal(careBlocksBooking(h.s,h.b),false);assert.equal(h.b.status,'done');});

test('Q04 岗位分权与幂等版本共存；技术和跨店不能改资格',()=>{const h=setup();authorize(h);const p={techId:h.t.id,version:h.q.version,serviceIds:['neck'],owner:'负责人',reason:'核实暂停',requestId:'unique-pause'};h.run(support,'qualification.pause',p);h.run(support,'qualification.pause',p);assert.equal(h.q.holds.length,1);assert.throws(()=>h.run(support,'qualification.pause',{...p,reason:'改内容'}),/同一提交标识/);assert.throws(()=>h.qual('pause',{version:p.version,serviceIds:['neck'],owner:'负责人'}),/版本|更新/);for(const a of [{role:'store',storeId:'yinxing'},{role:'tech',techId:h.t.id},{role:'group',job:'finance'}])assert.throws(()=>h.qual('resume',{holdId:h.q.holds[0].id,reviewer:'越权'},a));assert.equal(qualificationView(h.s,{role:'store',storeId:'yinxing'}).technicians.some(t=>t.id===h.t.id),false);});

test('Q04 旧schema5只冻结原项目边界，纯渲染不补历史证据，原预约事实不变',()=>{const s=seed();const before=structuredClone(s.bookings);upgradeFinanceState(s);const original=structuredClone(s);qualificationView(s,store);bookingOptions(s,{storeId:'xingfu',serviceId:'neck',regionId:'home',mode:'nearest'});assert.deepEqual(s,original);assert.equal(s.techQualifications.length,0);assert.deepEqual(s.bookings,before);upgradeFinanceState(s);assert.deepEqual(s,original);const chen=s.techs.find(t=>t.id==='chen');chen.serviceIds.push('relax');assert.equal(qualificationEligibility(s,'chen','relax').allowed,false);assert.equal(qualificationEligibility(s,'chen','neck').legacy,true);});

