import { availableReports,reportView,reportStatusLabel } from './operations-reports.mjs';
export function reportsUiView(s,a,ui) {
  const types=availableReports(s,a),q=ui.query||new URLSearchParams(),f=Object.fromEntries(q),type=f.type||types[0]?.id;
  const m=reportView(s,a,{...f,type}),e=ui.esc,l=ui.link;
  const input=(label,name,value,kind='text')=>ui.field(label,name,value||'',kind);
  const options=ui.select('业务类别','type',types.map(x=>({value:x.id,label:x.label})),m.type);
  const stores=a.role==='group'?ui.select('来源/服务门店','store',[{value:'',label:'全部授权范围'},...s.stores.map(x=>({value:x.id,label:x.name}))],f.store||''):'';
  const statuses=ui.select('状态','status',[{value:'',label:'全部状态'},...[...new Set([...reportView(s,a,{...f,type,status:'',page:1}).allRows.map(r=>r.status),f.status].filter(Boolean))].sort().map(v=>({value:v,label:reportStatusLabel(type,v)}))],f.status||'');
  const filter=`<form data-command="ui.filter" data-payload="${e(JSON.stringify({path:`/${a.role}/reports`}))}" class="management-form"><input type="hidden" name="page" value="1"><input type="hidden" name="previousType" value="${e(type)}"><div class="management-grid">${options}${stores}${input('开始日期','from',f.from,'date')}${input('结束日期','to',f.to,'date')}${statuses}${input('业务编号/字段','q',f.q)}${ui.select('每页条数','size',[10,20,50,100].map(n=>({value:n,label:n+'条'})),m.filters.size)}</div><div class="actions"><button class="primary" type="submit">查询</button>${l('清除筛选',`/${a.role}/reports`,'secondary')}</div></form>`;
  const number=(r,c)=>c.key==='status'?reportStatusLabel(type,r[c.key]):c.key==='storeId'?(s.stores.find(x=>x.id===r[c.key])?.name||r[c.key]||'集团自然购买'):c.key==='techId'?(s.techs.find(x=>x.id===r[c.key])?.name||r[c.key]):c.key==='serviceId'?(s.services.find(x=>x.id===r[c.key])?.name||r[c.key]):c.format==='money'?(Number.isSafeInteger(r[c.key])?ui.money(r[c.key]):'金额待核对'):c.format==='date'?ui.date(r[c.key]):r[c.key]??'—';
  const table=m.rows.length?`<div class="table-wrap"><table><thead><tr>${m.columns.map(c=>`<th>${e(c.label)}</th>`).join('')}<th>来源</th></tr></thead><tbody>${m.rows.map(r=>`<tr>${m.columns.map(c=>`<td>${e(number(r,c))}</td>`).join('')}<td>${r.path?l('查看原记录',r.path):'—'}</td></tr>`).join('')}</tbody></table></div>`:ui.empty('没有符合条件的记录','可调整日期、门店和状态；未授权的业务不会进入结果。');
  const linkPage=n=>{const p=new URLSearchParams({...m.filters});for(const k of ['fromAt','untilAt'])p.delete(k);p.set('page',n);return `/${a.role}/reports?${p}`;};
  const pagination=`<div class="actions">${m.page>1?l('上一页',linkPage(m.page-1),'secondary'):''}<span role="status">第${m.page} / ${m.pages}页，共${m.total}条</span>${m.page<m.pages?l('下一页',linkPage(m.page+1),'secondary'):''}</div>`;
  const exportForm=`<form data-command="report.export" data-payload='${e(JSON.stringify({...m.filters,token:m.token}))}' class="management-form">${ui.field('导出用途','reason','','text','required maxlength="300"')}<div class="actions"><button class="secondary" type="submit">导出全部筛选结果 CSV</button></div></form>`;
  return `<header class="page-head"><div><h1>经营查询与报表</h1><p>${e(m.dateLabel)} · 北京时间（+08:00），日期含首尾当天。</p></div>${l('返回工作台',`/${a.role}/dashboard`,'secondary')}</header><section class="panel management-panel">${filter}</section><section class="panel"><h2>${e(m.label)}</h2><p role="status">完整筛选结果共${m.total}条；下方汇总包含所有页。</p><dl class="kv-grid">${m.summaries.map(x=>`<div><dt>${e(x.label)}</dt><dd>${e(ui.money(x.cents))}${x.unknown?` · ${x.unknown}条金额待核对`:''}</dd></div>`).join('')}</dl>${table}${pagination}</section><section class="panel"><h2>导出记录</h2><p>仅导出当前授权字段和全部筛选结果；联系方式、地址、健康信息、案件正文和附件不在文件中。</p>${exportForm}<p class="small muted">文件中的金额单位为元。下载前会重新核对业务数据与当前会话。</p></section>`;
}
