import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { prepareServicePromotionEvidence } from './service-promotion-file-validation.mjs';
import { upgradeServicePromotion, servicePromotionCommand } from './service-promotion.mjs';

const DAY = 86400000, NOW = Date.parse('2026-10-04T12:00:00+08:00');
const finance = {role:'group',job:'finance'}, support = {role:'group',job:'support'}, ops = {role:'group',job:'operations'}, manager = {role:'store',job:'store-manager',storeId:'a'}, user = {role:'user',userId:'u1'}, tech = {role:'tech',techId:'t1'};
const pdfBytes = Buffer.from('%PDF-1.7\n% Local technical file fixture, not an actual tax or identity record\n%%EOF\n');
const pngBytes = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aVxsAAAAASUVORK5CYII=','base64');
function attachment(bytes=pdfBytes,type='application/pdf',name='本机技术样本.pdf') { return {file:{ref:`invoice-file:${createHash('sha256').update(bytes).digest('hex')}`,name,type,size:bytes.length},blob:new Blob([bytes],{type})}; }
function fixture() {
  const first = attachment(), second = attachment(pngBytes,'image/png','实际图片样本.png');
  const r = {id:'R1',personKind:'user',personId:'u1',promoterType:'store-promoter',ownerType:'store',ownerStoreId:'a',status:'active',identity:{status:'verified'},transferAuthorization:{exempt:true},version:0,history:[]};
  const snapshot = {promoter:{id:r.id,personKind:r.personKind,personId:r.personId,ownerType:r.ownerType,ownerStoreId:r.ownerStoreId},capturedAt:NOW-4*DAY};
  const state = {schema:5,seq:100,now:NOW,users:[{id:'u1',serviceBinding:{status:'unbound',recordedAt:NOW,version:0}},{id:'u2'}],stores:[{id:'a',active:true},{id:'b',active:true}],techs:[{id:'t1',storeId:'a'}],servicePromoters:[r],bookings:[{id:'B1',userId:'u2',storeId:'a',createdAt:NOW-4*DAY,completedAt:NOW-3*DAY,status:'done',payment:{id:'P1',status:'success',amountCents:20000,refundedCents:0,paidAt:NOW-4*DAY},extensions:[],refunds:[],servicePromotionSnapshot:snapshot}],serviceCommissions:[{id:'C1',promoterId:'R1',personKey:'user:u1',bookingId:'B1',paymentId:'P1',storeId:'a',userId:'u2',sourceSnapshot:structuredClone(snapshot),version:1,known:true,commissionCents:4000,storeCents:2000,groupCents:2000,availableAt:NOW-1,status:'available',createdAt:NOW-3*DAY,adjustments:[]}],servicePromotionWithdrawals:[{id:'W1',promoterId:'R1',personKind:'user',personId:'u1',personKey:'user:u1',ownerType:'store',ownerStoreId:'a',createdAt:NOW-DAY,amountCents:4000,allocations:[{commissionId:'C1',amountCents:4000,storeCents:2000,groupCents:2000}],version:0,status:'requested',authorizationSnapshot:{exempt:true},execution:null,history:[]}],servicePromotionRecoveries:[{id:'D1',commissionId:'C1',bookingId:'B1',paymentId:'P1',promoterId:'R1',personKey:'user:u1',storeId:'a',amountCents:1000,storeCents:500,groupCents:500,createdAt:NOW-100*DAY,dueAt:NOW-10*DAY,status:'open',version:0,records:[],history:[]}],servicePromotionRisks:[{id:'K1',bookingId:'B1',userId:'u2',storeId:'a',promoterId:'R1',reference:'UPSTREAM-K1',kind:'suspicious-first',source:{reference:'UPSTREAM-K1',kind:'suspicious-first',evidenceIds:['technical-upstream'],at:NOW-DAY},status:'pending',version:0,createdAt:NOW-DAY,review:null,reviewHistory:[],history:[]}],servicePromotionInvites:[{id:'I1',personKind:'user',personId:'u1',ownerType:'store',ownerStoreId:'a',agreementSnapshot:{id:'AG1'},version:0,status:'pending'}],serviceFinanceEntries:[{id:'E1',bookingId:'B1',paymentId:'P1',storeId:'a',userId:'u2',version:1}],serviceFinanceRecoveries:[{id:'FD1',entryId:'E1',bookingId:'B1',paymentId:'P1',storeId:'a',type:'unshared-release',reasonCode:'finished-adjustment',payer:'store:a',payee:'group',version:1,amountCents:1000,receivedCents:0,createdAt:NOW-DAY,records:[],history:[]}],serviceFinanceRequests:[],serviceFinanceRules:[]};
  upgradeServicePromotion(state);
  const blobs = new Map([[first.file.ref,first.blob],[second.file.ref,second.blob]]), calls = [], readFile = async f => { calls.push(structuredClone(f)); return blobs.get(f.ref); };
  return {state,first,second,blobs,calls,readFile};
}
const prepare = (f,command,p={},actor=finance,readFile=f.readFile) => prepareServicePromotionEvidence(f.state,actor,`service-promotion.${command}`,{requestId:`request-${command}`,version:0,...p},{readFile});
const proof = (f,extra={}) => ({reference:'technical-ref',occurredAt:NOW,file:f.first.file,reason:'本机技术附件校验，未作真实业务证据',...extra});
const key = (value) => JSON.stringify(Array.isArray(value) ? value.map(v => JSON.parse(key(v))) : value && typeof value === 'object' ? Object.fromEntries(Object.keys(value).sort().map(k => [k,JSON.parse(key(value[k]))])) : value);
const promotionContext = (f,verified) => ({fail(m){throw new Error(m);},id(prefix){return prefix+(++f.state.seq);},log(){},validateEvidenceRefs(refs){return refs.every(r => verified.some(f => key(f) === key(r)));},serviceFinanceSummary(s,id,pid){const b=s.bookings.find(b=>b.id===id);return {canPayTech:b?.status==='done'&&b.payment.id===pid&&s.now>=b.completedAt+2*DAY,unknownRefund:false,blockers:[]};}});
async function execute(f,command,p,actor) { const prepared = await prepareServicePromotionEvidence(f.state,actor,`service-promotion.${command}`,p,{readFile:f.readFile}); return servicePromotionCommand(f.state,actor,`service-promotion.${command}`,p,promotionContext(f,prepared.evidenceRefs)); }

test('其他域返回空，不解析身份或读取文件；未知推广命令拒绝',async()=>{ let calls=0; assert.deepEqual(await prepareServicePromotionEvidence({},null,'booking.pay',{}, {readFile(){calls++;}}),{evidenceRefs:[]}); assert.equal(calls,0); await assert.rejects(prepareServicePromotionEvidence({},finance,'service-promotion.unknown',{}),/未知/); });
for (const [command,p,actor] of [
  ['risk-review',{id:'K1',decision:'approved'},support],['risk-review',{id:'K1',decision:'rejected'},support],['agreement-publish',{promoterType:'store-promoter'},support],['identity-review',{id:'R1',decision:'verified'},support],['identity-review',{id:'R1',decision:'rejected'},support],['withdraw-pay',{id:'W1',outcome:'success'},finance],['withdraw-query',{id:'W1',outcome:'success'},finance],['recovery-receive',{id:'D1'},finance],['recovery-return',{id:'D1'},finance],['recovery-loss',{id:'D1'},finance]
]) test(`${command} ${p.decision||p.outcome||''}必需凭证实读真实Blob与SHA，返回精确元数据，原账纯读`,async()=>{ const f=fixture(), before=structuredClone(f.state); const result=await prepare(f,command,{...p,...proof(f)},actor); assert.deepEqual(result,{evidenceRefs:[f.first.file]}); assert.deepEqual(f.calls,[f.first.file]); assert.deepEqual(f.state,before); result.evidenceRefs[0].name='外部修改'; assert.equal(f.first.file.name,'本机技术样本.pdf'); });
for (const outcome of ['processing','awaiting_user','failed','cancelled']) test(`提现${outcome}可不提供文件，实际提供则必须实读，不能冒称成功`,async()=>{ const f=fixture(); assert.deepEqual(await prepare(f,'withdraw-pay',{id:'W1',outcome,reference:'技术受理号',reason:'核查中'}),{evidenceRefs:[]}); assert.equal(f.calls.length,0); assert.deepEqual(await prepare(f,'withdraw-pay',{id:'W1',outcome,...proof(f)}),{evidenceRefs:[f.first.file]}); f.blobs.clear(); await assert.rejects(prepare(f,'withdraw-pay',{id:'W1',outcome,...proof(f)}),/不存在/); });
test('11个不消费文件命令先沿原ACL和本人范围核验，返回空而不读取混入附件',async()=>{ const f=fixture(); const list=[['policy-publish',{},finance],['rule-publish',{},finance],['invite',{},manager],['invite-confirm',{id:'I1'},user],['disable',{id:'R1'},manager],['transfer-authorize',{id:'R1'},user],['enter',{},user],['clear-expired',{},user],['withdraw-create',{promoterId:'R1'},user],['withdraw-confirm',{id:'W1'},user],['withdraw-cancel',{id:'W1'},user]]; for(const [c,p,a] of list) assert.deepEqual(await prepare(f,c,{...p,file:f.first.file},a),{evidenceRefs:[]}); assert.equal(f.calls.length,0); });
test('权限失败在文件读取之前拒绝：财务不审身份风险、客服不转账，门店财务不执行个人收付',async()=>{ const f=fixture(); for(const [c,p,a] of [['identity-review',{id:'R1',...proof(f)},finance],['risk-review',{id:'K1',...proof(f)},finance],['withdraw-pay',{id:'W1',outcome:'success',...proof(f)},support],['recovery-loss',{id:'D1',...proof(f)},{role:'store',job:'store-finance',storeId:'a'}],['disable',{id:'R1'},{...manager,storeId:'b'}],['transfer-authorize',{id:'R1'},{role:'user',userId:'u2'}]]) await assert.rejects(prepare(f,c,p,a),/无权/); assert.equal(f.calls.length,0); });
test('实际user/tech/promoter/原支付/佣金与父单串号不能只凭岗位或引用读文件',async()=>{ const mutations=[s=>s.users=s.users.filter(u=>u.id!=='u1'),s=>s.servicePromoters[0].personId='unknown',s=>s.servicePromotionWithdrawals[0].personKey='user:u2',s=>s.serviceCommissions[0].paymentId='another-payment',s=>s.serviceCommissions[0].bookingId='another-booking',s=>s.serviceCommissions[0].promoterId='missing',s=>s.servicePromotionWithdrawals[0].allocations=[],s=>s.serviceCommissions[0].personKey='user:u2']; for(const change of mutations){const f=fixture();change(f.state);await assert.rejects(prepare(f,'withdraw-pay',{id:'W1',outcome:'success',...proof(f)}));assert.equal(f.calls.length,0);} });
test('风险、追收与真实源关系错误先拒绝，不靠上传证明补造来源',async()=>{ const f=fixture(); f.state.servicePromotionRisks[0].userId='u1'; await assert.rejects(prepare(f,'risk-review',{id:'K1',...proof(f)},support),/串号/); f.state.servicePromotionRecoveries[0].paymentId='bad'; await assert.rejects(prepare(f,'recovery-receive',{id:'D1',...proof(f)}),/串号/); assert.equal(f.calls.length,0); });
test('调店停用的旧身份和跨店同人提现行保留，不能按当前门店改原来源',async()=>{ const f=fixture(); const r=f.state.servicePromoters[0];r.personKind='tech';r.personId='t1';r.promoterType='tech';r.status='disabled';f.state.techs[0].storeId='b';Object.assign(f.state.bookings[0].servicePromotionSnapshot.promoter,{personKind:'tech',personId:'t1'});const c=f.state.serviceCommissions[0];c.personKey='tech:t1';c.sourceSnapshot=structuredClone(f.state.bookings[0].servicePromotionSnapshot);const w=f.state.servicePromotionWithdrawals[0];w.personKind='tech';w.personId='t1';w.personKey='tech:t1';assert.deepEqual(await prepare(f,'withdraw-pay',{id:'W1',outcome:'success',...proof(f)}),{evidenceRefs:[f.first.file]});assert.deepEqual(await prepare(f,'withdraw-confirm',{id:'W1'},tech),{evidenceRefs:[]}); });
test('JSON、数字大小与文件名按原metadata规范化，PDF/PNG/JPEG字节均校验',async()=>{ const f=fixture(), jpeg=attachment(Buffer.from([255,216,255,224,0,2,255,217]),'image/jpeg','JPEG技术边界.jpg');f.blobs.set(jpeg.file.ref,jpeg.blob); const refs=[f.first.file,{...f.second.file,size:String(f.second.file.size),name:` ${f.second.file.name} `},jpeg.file]; const result=await prepare(f,'identity-review',{id:'R1',evidenceRefs:JSON.stringify(refs)},support);assert.deepEqual(result.evidenceRefs,[f.first.file,f.second.file,jpeg.file]);assert.equal(f.calls.length,3); });
test('必需文件、读函数或实际Blob缺失均不得宣称已核验；JSON错误、类型大小引用名严格拒绝',async()=>{ const f=fixture();await assert.rejects(prepare(f,'identity-review',{id:'R1'},support),/提供实际/);await assert.rejects(prepare(f,'identity-review',{id:'R1',file:f.first.file},support,null),/读取尚未接入/); for(const file of [{...f.first.file,ref:'fake'},{...f.first.file,type:'text/plain'},{...f.first.file,name:''},{...f.first.file,name:'x'.repeat(256)},{...f.first.file,size:0},{...f.first.file,size:true},{...f.first.file,size:LIMIT+1}]) await assert.rejects(prepare(f,'identity-review',{id:'R1',file},support)); await assert.rejects(prepare(f,'identity-review',{id:'R1',evidenceRefs:'bad JSON'},support),/格式/);await assert.rejects(prepare(f,'identity-review',{id:'R1',file:f.first.file},support,async()=>({size:f.first.file.size,type:f.first.file.type,arrayBuffer:async()=>pdfBytes.buffer})),/不是文件/); });
const LIMIT=5*1024*1024;
test('实际Blob大小、MIME、内容摘要或格式不符拒绝；payload自称验证无效',async()=>{ const f=fixture();const p={id:'R1',file:f.first.file,validateEvidence:true,evidenceValidated:true};for(const blob of [null,new Blob([pdfBytes],{type:'image/png'}),new Blob(['short'],{type:'application/pdf'}),new Blob([Buffer.from('%PDF-1.7\nX'.padEnd(pdfBytes.length-6,' ')+'%%EOF\n')],{type:'application/pdf'})]) await assert.rejects(prepare(f,'identity-review',p,support,async()=>blob));const fake=attachment(Buffer.from('pretend pdf'), 'application/pdf');f.blobs.set(fake.file.ref,fake.blob);await assert.rejects(prepare(f,'identity-review',{id:'R1',file:fake.file},support),/格式/); });
test('完全相同引用运行集合可去重，冲突metadata拒绝；原模型仍保留重复附件拒绝',async()=>{ const f=fixture();const refs=[f.first.file,{...f.first.file}];assert.deepEqual(await prepare(f,'identity-review',{id:'R1',evidenceRefs:refs},support),{evidenceRefs:[f.first.file]});assert.equal(f.calls.length,1);await assert.rejects(prepare(f,'identity-review',{id:'R1',evidenceRefs:[f.first.file,{...f.first.file,name:'另一标签'}]},support),/冲突/);const p={id:'R1',decision:'verified',version:0,requestId:'dupes',...proof(f),evidenceRefs:refs};const got=await prepareServicePromotionEvidence(f.state,support,'service-promotion.identity-review',p,{readFile:f.readFile});assert.throws(()=>servicePromotionCommand(f.state,support,'service-promotion.identity-review',p,promotionContext(f,got.evidenceRefs)),/文件缺失或未核验/); });
test('await期间原事项、本人链、请求或文件metadata变化必须重读拒绝，提交载荷不被改写',async()=>{ for(const change of [s=>s.servicePromotionWithdrawals[0].version++,s=>s.serviceCommissions[0].paymentId='tampered',s=>s.servicePromoters[0].personId='u2',s=>s.servicePromotionRequests.push({requestId:'request-withdraw-pay',actorDigest:'foreign',result:{id:'W1'}})]){const f=fixture(),p={id:'W1',outcome:'success',...proof(f)};const saved=structuredClone(p);await assert.rejects(prepare(f,'withdraw-pay',p,finance,async()=>{change(f.state);return f.first.blob;}),/变化|串号|不一致|缺失/);assert.deepEqual(p,saved);} });
test('缺会话、撤销或到期账号在读文件之前拒绝',async()=>{ const f=fixture();for(const a of [{...support,accountId:'missing'},{...support,sessionId:'missing'}])await assert.rejects(prepare(f,'identity-review',{id:'R1',file:f.first.file},a),/会话/);assert.equal(f.calls.length,0); });
test('实际审核生成原request与版本，重放读取当前risk槽且不再次审核/付款，内容变化先拒绝',async()=>{ const f=fixture(),p={id:'K1',version:0,requestId:'review-original',decision:'approved',...proof(f)};await execute(f,'risk-review',p,support);const before=structuredClone(f.state),calls=f.calls.length;const prepared=await prepareServicePromotionEvidence(f.state,support,'service-promotion.risk-review',p,{readFile:f.readFile});assert.equal(f.calls.length,calls+1);assert.deepEqual(servicePromotionCommand(f.state,support,'service-promotion.risk-review',p,promotionContext(f,prepared.evidenceRefs)),{id:'K1',version:1});assert.deepEqual(f.state,before);await assert.rejects(prepareServicePromotionEvidence(f.state,support,'service-promotion.risk-review',{...p,reason:'不同内容'},{readFile:f.readFile}),/同一提交标识/); });
test('原risk版本重放定位历史槽，最新不同文件不能替代原审核证据，删除旧文件不能算通过',async()=>{ const f=fixture(),first={id:'K1',version:0,requestId:'risk-old',decision:'approved',...proof(f)};await execute(f,'risk-review',first,support);const second={id:'K1',version:1,requestId:'risk-new',decision:'rejected',...proof(f,{file:f.second.file,reference:'second-review'})};await execute(f,'risk-review',second,support);const before=structuredClone(f.state);assert.deepEqual(await prepareServicePromotionEvidence(f.state,support,'service-promotion.risk-review',first,{readFile:f.readFile}),{evidenceRefs:[f.first.file]});assert.deepEqual(f.state,before);f.state.servicePromotionRisks[0].reviewHistory[0].evidenceRefs[0].name='wrong history metadata';await assert.rejects(prepareServicePromotionEvidence(f.state,support,'service-promotion.risk-review',first,{readFile:f.readFile}),/不一致/); });
test('原identity版本重放定位历史真实槽，并拒绝缺audit或替换旧槽',async()=>{ const f=fixture();f.state.servicePromoters[0].identity=null;const p={id:'R1',version:0,requestId:'identity-old',decision:'verified',...proof(f)};await execute(f,'identity-review',p,support);await execute(f,'identity-review',{id:'R1',version:1,requestId:'identity-new',decision:'rejected',...proof(f,{file:f.second.file,reference:'identity-second'})},support);assert.deepEqual(await prepareServicePromotionEvidence(f.state,support,'service-promotion.identity-review',p,{readFile:f.readFile}),{evidenceRefs:[f.first.file]});f.state.servicePromoters[0].history=[];await assert.rejects(prepareServicePromotionEvidence(f.state,support,'service-promotion.identity-review',p,{readFile:f.readFile}),/实际版本历史/); });
test('原协议发布重放从真实result协议槽实读，原完整内容和meta仍匹配',async()=>{ const f=fixture(),p={promoterType:'store-promoter',title:'原技术测试协议',body:'实际测试的固定条款',effectiveAt:NOW,version:0,requestId:'agreement-original',...proof(f)};const result=await execute(f,'agreement-publish',p,ops);const before=structuredClone(f.state);assert.deepEqual(await prepareServicePromotionEvidence(f.state,ops,'service-promotion.agreement-publish',p,{readFile:f.readFile}),{evidenceRefs:[f.first.file]});assert.deepEqual(f.state,before);f.state.servicePromotionAgreements.find(r=>r.id===result.id).evidenceRefs[0].size++;await assert.rejects(prepareServicePromotionEvidence(f.state,ops,'service-promotion.agreement-publish',p,{readFile:f.readFile}),/不一致/); });
test('原提现实际成功request重放重新读payment槽，不重付原款或更改原号',async()=>{ const f=fixture(),p={id:'W1',version:0,requestId:'withdraw-original',outcome:'success',...proof(f)};await execute(f,'withdraw-pay',p,finance);assert.equal(f.state.servicePromotionWithdrawals[0].status,'paid');const before=structuredClone(f.state);const prepared=await prepareServicePromotionEvidence(f.state,finance,'service-promotion.withdraw-pay',p,{readFile:f.readFile});servicePromotionCommand(f.state,finance,'service-promotion.withdraw-pay',p,promotionContext(f,prepared.evidenceRefs));assert.deepEqual(f.state,before);assert.equal(f.state.servicePromotionWithdrawals[0].execution.results.length,1);f.blobs.delete(f.first.file.ref);await assert.rejects(prepareServicePromotionEvidence(f.state,finance,'service-promotion.withdraw-pay',p,{readFile:f.readFile}),/文件不存在/);assert.deepEqual(f.state,before); });
test('提现失败原结果有附件时，后续原笔重试仍保留且重放正确旧result槽',async()=>{ const f=fixture(),p={id:'W1',version:0,requestId:'withdraw-failed',outcome:'failed',...proof(f)};f.state.servicePromotionRisks=[];f.state.bookings[0].servicePromotionSnapshot.rule={id:'TECHNICAL-RULE',version:1,firstBps:2000,repeatBps:1000,storeCostBps:5000,csRounding:'floor',concurrency:'completed-created-id',lateFullRefund:'reassign'};f.state.servicePromotionFirsts=[{id:'TECHNICAL-FIRST',userId:'u2',version:0,history:[],policySnapshot:{id:'TECHNICAL-RULE',version:1,concurrency:'completed-created-id',lateFullRefund:'reassign'}}];await execute(f,'withdraw-pay',p,finance);await execute(f,'withdraw-pay',{id:'W1',version:1,requestId:'withdraw-retry',outcome:'failed',...proof(f,{file:f.second.file,reference:'second-failure'})},finance);assert.deepEqual(await prepareServicePromotionEvidence(f.state,finance,'service-promotion.withdraw-pay',p,{readFile:f.readFile}),{evidenceRefs:[f.first.file]});f.state.servicePromotionWithdrawals[0].execution.results[0].facts.evidenceRefs[0].ref=f.second.file.ref;await assert.rejects(prepareServicePromotionEvidence(f.state,finance,'service-promotion.withdraw-pay',p,{readFile:f.readFile}),/不一致/); });
test('原个人扣回真实record重放读取同域同slot且不再次收款，元数据来源不能伪造',async()=>{ const f=fixture(),p={id:'D1',version:0,requestId:'recovery-original',amountCents:500,...proof(f)};await execute(f,'recovery-receive',p,finance);const before=structuredClone(f.state);const prepared=await prepareServicePromotionEvidence(f.state,finance,'service-promotion.recovery-receive',p,{readFile:f.readFile});servicePromotionCommand(f.state,finance,'service-promotion.recovery-receive',p,promotionContext(f,prepared.evidenceRefs));assert.deepEqual(f.state,before);assert.equal(f.state.servicePromotionRecoveries[0].records.length,1);f.state.servicePromotionRecoveries[0].records[0].evidenceRefs[0].name='bad original';await assert.rejects(prepareServicePromotionEvidence(f.state,finance,'service-promotion.recovery-receive',p,{readFile:f.readFile}),/不一致/); });

const financePrepare = (f,p,actor=finance,readFile=f.readFile) => prepareServicePromotionEvidence(f.state,actor,'finance.recovery-receive',{id:'FD1',requestId:'finance-origin',version:1,...p},{readFile});
test('推广关联原财务债必须集团finance/all、实际文件和真实source，原非推广行为返回空',async()=>{ const f=fixture();assert.deepEqual(await financePrepare(f,proof(f)),{evidenceRefs:[f.first.file]});for(const actor of [support,ops,user,manager,{role:'group'},{role:'store',job:'store-finance',storeId:'a'}])await assert.rejects(financePrepare(f,proof(f),actor),/无权/);await assert.rejects(financePrepare(f,{}),/提供实际/);await assert.rejects(financePrepare(f,proof(f),finance,null),/读取尚未接入/);const old=fixture();delete old.state.bookings[0].servicePromotionSnapshot;delete old.state.serviceFinanceRecoveries[0].reasonCode;assert.deepEqual(await financePrepare(old,{file:{ref:'unused'}},null,null),{evidenceRefs:[]});assert.equal(old.calls.length,0); });
test('明确finished-adjustment缺推广源不能退回旧H路径，原付款/收款方串号拒绝',async()=>{ for(const change of [s=>delete s.bookings[0].servicePromotionSnapshot,s=>s.serviceFinanceRecoveries[0].paymentId='other',s=>s.serviceFinanceRecoveries[0].storeId='b',s=>s.serviceFinanceRecoveries[0].payer='store:b',s=>s.serviceFinanceRecoveries[0].payee='store:a',s=>s.serviceFinanceEntries[0].storeId='b']){const f=fixture();change(f.state);await assert.rejects(financePrepare(f,proof(f)));assert.equal(f.calls.length,0);} });
test('原财务推广债重放按finance原签名、actual record与其自身附件槽读取，不能串个人债',async()=>{ const f=fixture(),p={id:'FD1',version:1,requestId:'finance-origin',amountCents:500,...proof(f)};const actor={role:'group',job:'finance',id:'group'};const record={id:'FRC1',requestId:p.requestId,amountCents:500,reference:p.reference,reason:p.reason,occurredAt:p.occurredAt,evidenceRefs:[f.first.file],at:NOW,actor};f.state.serviceFinanceRecoveries[0].records=[record];f.state.serviceFinanceRecoveries[0].receivedCents=500;f.state.serviceFinanceRequests=[{requestId:p.requestId,actor:key(actor),fingerprint:key({type:'finance.recovery-receive',p}),resultId:'FD1',at:NOW}];const before=structuredClone(f.state);assert.deepEqual(await prepareServicePromotionEvidence(f.state,finance,'finance.recovery-receive',p,{readFile:f.readFile}),{evidenceRefs:[f.first.file]});assert.deepEqual(f.state,before);await assert.rejects(prepareServicePromotionEvidence(f.state,finance,'finance.recovery-receive',{...p,reason:'changed'},{readFile:f.readFile}),/同一提交标识/);f.state.serviceFinanceRecoveries[0].records[0].evidenceRefs=[f.second.file];await assert.rejects(prepareServicePromotionEvidence(f.state,finance,'finance.recovery-receive',p,{readFile:f.readFile}),/实际文件记录/); });
test('真实工作session核验原财务推广文件途中被撤销，实读后复核拒绝，账本不伪造成功',async()=>{ const f=fixture();f.state.staffAccounts=[{id:'WA1',enabled:true,version:1,grants:[{id:'WG1',enabled:true,role:'group',job:'finance'}]}];f.state.staffSessions=[{id:'WS1',accountId:'WA1',grantId:'WG1',accountVersion:1}];const a={sessionId:'WS1'};await assert.rejects(financePrepare(f,proof(f),a,async()=>{f.state.staffSessions[0].revokedAt=NOW;return f.first.blob;}),/失效/);assert.equal(f.state.serviceFinanceRecoveries[0].receivedCents,0);assert.equal(f.state.serviceFinanceRecoveries[0].records.length,0); });
