import test from 'node:test';
import assert from 'node:assert/strict';
import { renderServiceFinanceExtras } from './service-finance-extras-ui.mjs';
import { upgradeServiceFinanceExtras } from './service-finance-extras.mjs';
const group={role:'group',job:'finance'},store={role:'store',job:'store-finance',storeId:'a'},now=Date.parse('2026-10-04T12:00:00+08:00');
function fixture(){const s={schema:5,now,stores:[{id:'a',name:'A门店'},{id:'b',name:'B门店'}],users:[{id:'u1'}],bookings:[{id:'B1',userId:'u1',storeId:'a',serviceId:'neck',createdAt:now-86400000*10,status:'done',completedAt:now-86400000*3,payment:{id:'P1',status:'success',amountCents:20000,refundedCents:0},extensions:[],refunds:[],disputes:[]}],serviceFinanceEntries:[{id:'SF1',bookingId:'B1',paymentId:'P1',storeId:'a',version:1,paidAt:null,sourceSnapshot:null,ruleSnapshot:null,split:null,splitHistory:[],finish:null,returns:[]}],serviceFinanceRecoveries:[],safety:[]};upgradeServiceFinanceExtras(s);return s;}
function issue(s,status='awaiting_store'){const row={id:'I1',bookingId:'B1',paymentId:'P1',userId:'u1',storeId:'a',refundId:'R1',refundNo:'R1-P1',refundCents:10000,shortageCents:6000,failedAt:now-86400000*2,dueAt:now-86400000,version:4,status,recharges:[],advances:[],history:[]};s.serviceRefundShortages.push(row);s.bookings[0].refunds.push({id:'R1',status:'failed',executions:[{refundNo:row.refundNo,paymentId:'P1',amountCents:10000,status:'failed'}]});return row;}
test('旧支付核对用人可填字段、原文件上传与稳定版本，读取不造证据',()=>{const s=fixture(),before=structuredClone(s),html=renderServiceFinanceExtras(s,store,'evidence','SF1');assert.match(html,/data-command="service-extra.evidence-submit"/);assert.match(html,/name="ruleVersion"/);assert.match(html,/name="ruleId"/);assert.match(html,/name="paidAt"/);assert.match(html,/data-invoice-upload/);assert.match(html,/data-live-version="0"/);assert.doesNotMatch(html,/<textarea[^>]+name="payload"/);assert.deepEqual(s,before);});
test('集团财务可核验原依据，门店和无岗位不能批准',()=>{const s=fixture();s.serviceExtraEvidence.push({id:'E1',bookingId:'B1',paymentId:'P1',storeId:'a',version:2,kind:'payment',status:'requested',reference:'TECH-123',occurredAt:now-86400000,reason:'<script>银行核验</script>',evidenceRefs:[{name:'银行流水.pdf'}],history:[]});const html=renderServiceFinanceExtras(s,group,'evidence','E1');assert.match(html,/service-extra.evidence-review/);assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(renderServiceFinanceExtras(s,store,'evidence','E1'),/service-extra.evidence-review/);assert.match(renderServiceFinanceExtras(s,{role:'group',job:'support'},'evidence','E1'),/暂无办理权限/);assert.doesNotMatch(renderServiceFinanceExtras(s,{role:'group',job:'support'},'evidence','E1'),/TECH-123/);});
test('门店充值显示原期限和实际凭证，空路径配置不给垫付默认方案',()=>{const s=fixture();issue(s);const local=renderServiceFinanceExtras(s,store,'shortages');assert.match(local,/service-extra.recharge/);assert.match(local,/原补足期限/);assert.match(local,/实际商户余额补足/);const groupHtml=renderServiceFinanceExtras(s,group,'shortages');assert.match(groupHtml,/尚未有启用的垫付路径依据/);assert.doesNotMatch(groupHtml,/data-command="service-extra.advance-pay"/);assert.match(groupHtml,/service-extra.advance-decision/);});
test('垫付未知只查询原笔，成功凭证不逼未知款伪造银行号',()=>{const s=fixture(),i=issue(s,'advance-query');i.advances.push({id:'A1',path:'merchant-balance',status:'processing',amountCents:6000,execution:{status:'processing'}});const html=renderServiceFinanceExtras(s,group,'shortages','I1');assert.match(html,/service-extra.advance-query/);assert.doesNotMatch(html,/data-command="service-extra.advance-pay"/);assert.doesNotMatch(html,/data-command="service-extra.advance-cancel"/);const reference=html.match(/<input name="reference"[^>]*>/)?.[0];assert.ok(reference);assert.doesNotMatch(reference,/required/);});
test('本人确认直接退款，其他用户无方案且内债与失败证据不泄露',()=>{const s=fixture(),i=issue(s,'awaiting_user');i.failureEvidence={reference:'SECRET-BANK',reason:'内部债務正文'};i.advances.push({id:'A1',path:'direct-user',status:'awaiting_user',amountCents:10000});const mine=renderServiceFinanceExtras(s,{role:'user',userId:'u1'});assert.match(mine,/service-extra.advance-confirm/);assert.match(mine,/接受本款直接退款并结清原退款/);assert.doesNotMatch(mine,/SECRET-BANK|内部债務正文/);const other=renderServiceFinanceExtras(s,{role:'user',userId:'u2'});assert.doesNotMatch(other,/I1|A1|100\.00/);});
test('同店服务追收待确认、未知与超额实际退回三个出口按阶段展示',()=>{const s=fixture(),p={id:'O1',entryId:'SF1',bookingId:'B1',paymentId:'P1',storeId:'a',recoveryId:'D1',version:4,status:'proposed',normalCents:2000,recoveryCents:2000,reason:'同店偿还',returnRecords:[],history:[]};s.serviceExtraOffsets.push(p);assert.match(renderServiceFinanceExtras(s,store,'offsets','O1'),/service-extra.offset-confirm/);assert.doesNotMatch(renderServiceFinanceExtras(s,group,'offsets','O1'),/service-extra.offset-pay/);p.status='processing';const querying=renderServiceFinanceExtras(s,group,'offsets','O1');assert.match(querying,/service-extra.offset-query/);assert.doesNotMatch(querying,/service-extra.offset-cancel/);p.status='succeeded';s.serviceFinanceEntries[0].paidAt=now-86400000*9;s.serviceFinanceEntries[0].sourceSnapshot={status:'known',customerType:'group'};s.serviceFinanceEntries[0].ruleSnapshot={groupBps:1000,storeBps:500};s.bookings[0].payment.refundedCents=20000;const returning=renderServiceFinanceExtras(s,group,'offsets','O1');assert.match(returning,/service-extra.offset-return/);assert.match(returning,/超额/);});
test('待办返回可保留入口，跨店不显示债务与实际凭证，通知没有按钮假象',()=>{const s=fixture();s.serviceExtraRecoveries.push({id:'D1',bookingId:'B1',storeId:'a',refundNo:'R1-P1',version:3,amountCents:6000,receivedCents:1000,records:[],history:[]});const before=structuredClone(s),html=renderServiceFinanceExtras(s,group,'recoveries','D1',{returnPath:'/group/tasks?kind=service-extra-recovery'});assert.match(html,/返回原待办列表/);assert.match(html,/service-extra.recovery-receive/);assert.match(html,/<p class="notice" role="status">/);assert.doesNotMatch(html,/<button[^>]*>[^<]*充值[^<]*不等/);assert.doesNotMatch(renderServiceFinanceExtras(s,{...store,storeId:'b'},'recoveries'),/D1|60\.00/);assert.deepEqual(s,before);});

test('专项资金核对有跟进和实际退回出口，草稿按动作隔离，用户不显示内部追收',()=>{const s=fixture(),i=issue(s,'needs-review');s.bookings[0].refunds[0].executions[0].status='success';i.advances.push({id:'A1',path:'direct-user',status:'needs-review',amountCents:10000,returnedCents:2000,execution:{status:'success'},reconciliationRecords:[{id:'AR1',kind:'actual-user-return',amountCents:2000,evidenceRefs:[{ref:`invoice-file:${'c'.repeat(64)}`,name:'实际退回.pdf'}]}]});const html=renderServiceFinanceExtras(s,group,'shortages','I1');assert.equal((html.match(/data-command="service-extra.advance-reconcile"/g)||[]).length,2);assert.match(html,/service-extra:group:finance:I1:advance-reconcile:note/);assert.match(html,/service-extra:group:finance:I1:advance-reconcile:return/);assert.match(html,/data-invoice-slot="advance-return:A1:AR1:0"/);assert.match(html,/max="80"/);assert.doesNotMatch(html,/data-command="service-extra.advance-pay"/);const user=renderServiceFinanceExtras(s,{role:'user',userId:'u1'});assert.doesNotMatch(user,/advance-reconcile|实际退回\.pdf|invoice-file:/);});
test('失败追收保留原重试与人工核对出口，垫付只给实际最具体的已生效路径',()=>{const s=fixture(),i=issue(s,'awaiting_group');s.serviceExtraPolicies.push({id:'GLOBAL',path:'merchant-balance',storeId:null,version:1,effectiveAt:now-60000},{id:'LOCAL',path:'merchant-balance',storeId:'a',version:1,effectiveAt:now-120000},{id:'FUTURE',path:'merchant-balance',storeId:'a',version:2,effectiveAt:now+60000});const html=renderServiceFinanceExtras(s,group,'shortages',i.id);assert.match(html,/LOCAL/);assert.doesNotMatch(html,/GLOBAL|FUTURE/);s.serviceExtraOffsets.push({id:'O1',entryId:'SF1',bookingId:'B1',paymentId:'P1',storeId:'a',recoveryId:'D1',version:4,status:'failed',normalCents:2000,recoveryCents:2000,reason:'原方案',returnRecords:[],history:[],execution:{attempts:5,nextRetryAt:now+60000}});const offset=renderServiceFinanceExtras(s,group,'offsets','O1');assert.match(offset,/name="manual"/);assert.match(offset,/人工办理依据/);assert.match(offset,/达到5次/);assert.match(offset,/service-extra.offset-pay/);});

test('余额不足从原失败结果选取精确时间，凭证输入保留秒和毫秒',()=>{
  const s=fixture(),first=now-60000+45123,later=first+60000;
  s.now=now+45123;
  s.bookings[0].refunds.push({id:'R1',status:'failed',executions:[{refundNo:'R1-P1',paymentId:'P1',amountCents:10000,status:'failed',updatedAt:later,results:[{at:first,outcome:'failed'},{at:later,outcome:'failed'},{at:first,outcome:'failed'},{at:first+1,outcome:'processing'}]}]});
  const html=renderServiceFinanceExtras(s,store,'shortages');
  const selector=html.match(/<select name="failedAt"[^>]*>([\s\S]*?)<\/select>/)?.[1];
  assert.ok(selector);
  assert.deepEqual([...selector.matchAll(/<option value="(\d+)"/g)].map(x=>Number(x[1])),[first,later]);
  assert.doesNotMatch(html,/<input name="failedAt"/);
  const current=issue(s),proof=renderServiceFinanceExtras(s,store,'shortages',current.id);
  assert.match(proof,/<input name="occurredAt" type="datetime-local" value="2026-10-04T12:00:45\.123" step="0\.001"/);
});
