import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { seed, reduce } from './engine.mjs';
import { serviceFinanceSummary } from './service-finance.mjs';
import { serviceFinanceComposition, serviceFinanceCompositionAllocationSources, serviceFinanceCompositionFingerprint } from './service-finance-composition.mjs';
import { serviceFinanceCompositionReview, serviceFinanceCompositionReviewCommand, prepareServiceFinanceCompositionEvidence, createServiceFinanceCompositionEvidenceValidator, authorizedServiceFinanceCompositionFile } from './service-finance-composition-review.mjs';
import { staffGrantCapabilities } from './staff-accounts.mjs';
import { prepareServicePromotionEvidence } from './service-promotion-file-validation.mjs';
import { commerceInvoiceCommand, feeInvoiceSummary, syncCommerceInvoices } from './commerce-invoices.mjs';

const DAY=86400000,finance={role:'group',job:'finance'},support={role:'group',job:'support'},manager={role:'store',job:'store-manager',storeId:'xingfu'},buyer={role:'user',userId:'u1'},person={role:'user',userId:'u2'},tech={role:'tech',techId:'lin'};
const bytes=new TextEncoder().encode('%PDF-1.4\nactual evidence bytes for cash review\n%%EOF'),blob=new Blob([bytes],{type:'application/pdf'}),file={ref:'invoice-file:'+createHash('sha256').update(bytes).digest('hex'),name:'逐笔原现金分类依据.pdf',type:blob.type,size:blob.size};
function harness(){let s=seed(),seq=0;const h={get s(){return s;},get entry(){return s.serviceFinanceEntries.find(e=>e.bookingId===h.bookingId);},get booking(){return s.bookings.find(b=>b.id===h.bookingId);},get key(){return 'split:'+h.entry.split.id;},proof:(reference='PROOF-'+ ++seq)=>({reference,occurredAt:s.now,file,reason:'原发生时间和实际Blob合成验证'}),
  async run(type,p={},actor=finance){const source=['servicePromoters','servicePromotionInvites','serviceFinanceEntries','serviceFinanceRecoveries'].flatMap(k=>s[k]||[]).find(x=>x.id===(p.id||p.promoterId));const payload={requestId:'ORIGINAL-'+ ++seq,version:source?.version||0,...p},runtime=await prepareServicePromotionEvidence(s,actor,type,payload,{readFile:async()=>blob});s=reduce(s,actor,type,payload,()=>{},runtime);return s;},
  async advance(minutes){while(minutes){const step=Math.min(minutes,44640);await h.run('clock.advance',{minutes:step});minutes-=step;}},
  async setup({cash=true}={}){await h.run('finance.rule-publish',{scope:'global',groupBps:1000,storeBps:500,effectiveAt:s.now,version:0,reason:'显式原H测试规则'});await h.run('service-promotion.agreement-publish',{promoterType:'store-promoter',title:'原协议',body:'本人核实的技术验证协议正文。',effectiveAt:s.now,...h.proof()},support);await h.run('service-promotion.invite',{userId:'u2',promoterType:'store-promoter',expiresAt:s.now+DAY,reason:'原本人邀请'},manager);const invite=s.servicePromotionInvites.at(-1);await h.run('service-promotion.invite-confirm',{id:invite.id,decision:'accept',agreementAccepted:true,agreementId:invite.agreementSnapshot.id,reason:'本人确认'},person);const promoter=s.servicePromoters.find(x=>x.personKind==='user'&&x.personId==='u2');await h.run('service-promotion.identity-review',{id:promoter.id,decision:'verified',...h.proof()},support);await h.run('service-promotion.rule-publish',{promoterType:'store-promoter',firstBps:2000,repeatBps:1000,storeCostBps:5000,csRounding:'floor',concurrency:'completed-created-id',lateFullRefund:'reassign',effectiveAt:s.now,version:0,basis:'显式原C技术配置，不代表财税批准'});await h.run('service-promotion.enter',{promoterId:promoter.id,version:s.users.find(u=>u.id==='u1').serviceBinding.version},buyer);await h.run('booking.create',{storeId:'xingfu',serviceId:'relax',regionId:'home',techId:'lin',startAt:Math.ceil((s.now+4*3600000)/1800000)*1800000,mode:'specified',genderPreference:'any',contactName:'本地合成顾客',phone:'13800000001',healthConsent:true,identityVerified:true,adultConfirmed:true},buyer);h.bookingId=s.bookings.at(-1).id;await h.run('booking.pay',{id:h.bookingId,outcome:'success'},buyer);await h.run('booking.accept',{id:h.bookingId},tech);await h.advance(Math.ceil((h.booking.startAt-s.now)/60000));await h.run('booking.start',{id:h.bookingId},tech);await h.advance(h.booking.duration);await h.run('booking.finish',{id:h.bookingId,mode:'normal'},tech);await h.advance(2881);if(cash)await h.run('finance.split-start',{id:h.entry.id,version:h.entry.version,outcome:'success'});},
  legacy(){delete h.entry.split.cashComposition;delete h.entry.split.cashCompositionRequest;},
  view(key=h.key,actor=finance){return serviceFinanceCompositionReview(s,actor,h.entry.id,key);},
  payload(extra={},key=h.key){const view=h.view(key);return{id:h.entry.id,version:view.entryVersion,sourceKey:key,sourceToken:view.sourceToken,requestId:'REVIEW-'+ ++seq,hCents:1490,csCents:view.facts.normalCents-1490,retainedCsCents:null,allocations:[],basisReference:'原逐笔分类依据-'+seq,basisDescription:'财务按本笔原分类凭据核对，未使用当前目标或默认比例',evidenceRefs:[file],reason:'补核实际历史款',...extra};},
  async command(p,type='finance.composition-confirm',actor=finance,options={},commandContext={}){const prepared=await prepareServiceFinanceCompositionEvidence(s,actor,type,p,{readFile:async()=>blob,getState:()=>s,...options}),next=structuredClone(s);const result=serviceFinanceCompositionReviewCommand(next,actor,type,p,{id:prefix=>prefix+ ++next.seq,validateCompositionEvidence:createServiceFinanceCompositionEvidenceValidator(prepared),...commandContext});s=next;return result;},
  cash(){return structuredClone({bookings:s.bookings,split:h.entry.split,splitHistory:h.entry.splitHistory,returns:h.entry.returns,recoveries:s.serviceFinanceRecoveries});},
  async refund(amount){await h.run('booking.special-aftersale',{id:h.bookingId,requests:[{paymentId:h.booking.payment.id,amountCents:amount}],reason:'真实原客服特批退款'},support);const r=h.booking.refunds.at(-1);await h.run('booking.refund-review',{id:h.bookingId,refundId:r.id,decision:'approve',reason:'原本款金额核准'},support);await h.run('booking.refund-pay',{id:h.bookingId,refundId:r.id,paymentId:h.booking.payment.id,outcome:'success'});},
  invoice(op,p={},actor=finance){const next=structuredClone(s),result=commerceInvoiceCommand(next,actor,'commerce-invoice.'+op,{requestId:'INVOICE-'+ ++seq,...p},{id:prefix=>prefix+ ++next.seq,fail:fail=>{throw Error(fail);},log:()=>{}});syncCommerceInvoices(next);s=next;return result;}
};return h;}
async function oldCash(){const h=harness();await h.setup();h.legacy();return h;}

test('摘要与标准SHA一致，原内部正文不出token',()=>{assert.equal(serviceFinanceCompositionFingerprint({b:2,a:'实际字段'}),'sha256:'+createHash('sha256').update(JSON.stringify({a:'实际字段',b:2})).digest('hex'));});
test('原reduce成功现金→实际读Blob→真实补核命令，原现金及历史不改',async()=>{const h=await oldCash(),before=h.cash(),p=h.payload(),row=await h.command(p);assert.equal(row.by.job,'finance');assert.equal(row.method,'verified-history');assert.equal(row.actualAt,h.entry.split.completedAt);assert.equal(row.hCents,1490);assert.equal(row.csCents,h.entry.split.amountCents-1490);assert.equal(row.basisReference,p.basisReference);assert.deepEqual(row.evidenceRefs,[file]);assert.deepEqual(h.cash(),before);assert.equal(serviceFinanceComposition(h.s,h.entry.id).known,true);assert.equal(h.view().state,'confirmed');assert.match(h.view().sourceToken,/^sha256:[a-f0-9]{64}$/);});
test('未核旧款纯投影不建容器，返回对象与原状态隔离',async()=>{const h=await oldCash(),before=structuredClone(h.s),view=h.view();assert.equal(view.canConfirm,true);view.facts.normalCents=0;view.supersedes.push({});assert.deepEqual(h.s,before);assert.equal(h.s.serviceFinanceCompositions,undefined);});
test('同原请求重放不重复核定或entry历史，异内容/跨账号标识拒绝',async()=>{const h=await oldCash(),p=h.payload();await h.command(p);const before=structuredClone(h.s);await h.command(p);assert.deepEqual(h.s,before);await assert.rejects(h.command({...p,hCents:1491,csCents:p.csCents-1}),/同一提交/);assert.deepEqual(h.s,before);});
test('旧token/version或证据字段变化、缺真实读取及复制proof均拒绝',async()=>{const h=await oldCash(),p=h.payload(),before=structuredClone(h.s);const prepared=await prepareServiceFinanceCompositionEvidence(h.s,finance,'finance.composition-confirm',p,{readFile:async()=>blob});assert.throws(()=>createServiceFinanceCompositionEvidenceValidator(structuredClone(prepared)),/复制/);assert.throws(()=>serviceFinanceCompositionReviewCommand(h.s,finance,'finance.composition-confirm',p,{validateEvidenceRefs:()=>true}),/可信核验/);for(const extra of [{version:p.version+1},{sourceToken:'sha256:'+'a'.repeat(64)},{reason:'读取之后变更'}])assert.throws(()=>serviceFinanceCompositionReviewCommand(h.s,finance,'finance.composition-confirm',{...p,...extra},{id:()=> 'FIXED',validateCompositionEvidence:createServiceFinanceCompositionEvidenceValidator(prepared)}),/核验|变化/);assert.deepEqual(h.s,before);});
test('缺/坏/异字节附件及读取中来源变化不发known',async()=>{for(const result of [null,new Blob(['broken'],{type:'application/pdf'}),new Blob([new TextEncoder().encode('%PDF-1.4\nwrong same-format bytes\n%%EOF')],{type:'application/pdf'})]){const h=await oldCash();await assert.rejects(h.command(h.payload(),undefined,finance,{readFile:async()=>result}),/实际证据/);assert.equal(h.s.serviceFinanceCompositions,undefined);}const h=await oldCash();await assert.rejects(h.command(h.payload(),undefined,finance,{readFile:async()=>{h.entry.version++;return blob;}}),/读取期间/);});
test('原岗位拒门店/客服/运营/管理员/失效工作会话，未接白名单不借其他命令',async()=>{const h=await oldCash(),before=structuredClone(h.s);for(const a of [support,{role:'group',job:'operations'},{role:'group',job:'account-admin'},{role:'store',job:'store-finance',storeId:'xingfu'},{sessionId:'missing'}]){assert.throws(()=>h.view(h.key,a),/财务|会话|账号/);await assert.rejects(h.command(h.payload(),undefined,a),/财务|会话|账号/);}assert.deepEqual(h.s,before);});
test('部分混合仅核真实历史，不自造正式批准/缺依据/超额/负数',async()=>{const h=await oldCash();for(const extra of [{hCents:-1},{hCents:1491},{basisReference:''},{basisDescription:''},{reason:''},{evidenceRefs:[]},{method:'approved-allocation',allocationPolicySnapshot:{id:'made-up',version:1,mode:'per-source-approved'}}]){const before=structuredClone(h.s);await assert.rejects(h.command(h.payload(extra)),/须|无效|填写|附件|批准/);assert.deepEqual(h.s,before);}});
test('显式更正替代全部原候选，连续更正沿精确链，旧行/现金保留',async()=>{const h=await oldCash();const first=await h.command(h.payload()),cash=h.cash(),view=h.view();const correction=h.payload({hCents:1000,csCents:h.entry.split.amountCents-1000,supersedes:view.supersedes,reason:'实际分类凭据证明此前误分类'});const row=await h.command(correction,'finance.composition-reconcile');assert.equal(row.version,2);assert.deepEqual(h.s.serviceFinanceCompositions[0],first);assert.deepEqual(h.cash(),cash);assert.equal(serviceFinanceComposition(h.s,h.entry.id).hNetCents,1000);const next=await h.command(h.payload({hCents:1200,csCents:h.entry.split.amountCents-1200,supersedes:h.view().supersedes}),'finance.composition-reconcile');assert.equal(next.version,3);assert.equal(serviceFinanceComposition(h.s,h.entry.id).hNetCents,1200);const before=structuredClone(h.s);await h.command(correction,'finance.composition-reconcile');assert.deepEqual(h.s,before);});
test('原新请求组成也须明确替代，普通confirm和漏候选/伪token更正拒绝',async()=>{const h=harness();await h.setup();await assert.rejects(h.command(h.payload()),/已有核定/);const refs=h.view().supersedes;for(const sup of [[],[{...refs[0],token:'sha256:'+'a'.repeat(64)}]])await assert.rejects(h.command(h.payload({supersedes:sup}),'finance.composition-reconcile'),/全部当前/);const raw=structuredClone(h.entry.split),row=await h.command(h.payload({hCents:1000,csCents:h.entry.split.amountCents-1000,supersedes:refs}),'finance.composition-reconcile');assert.equal(row.reconciliation.supersedes.length,1);assert.deepEqual(h.entry.split,raw);assert.equal(serviceFinanceComposition(h.s,h.entry.id).hNetCents,1000);});
test('旧格式known冲突仅隔离坏存档fixture，更正不能默选或构造循环',async()=>{const h=await oldCash();await h.command(h.payload());const old=structuredClone(h.s.serviceFinanceCompositions[0]);h.s.serviceFinanceCompositions.push({...old,id:'LEGACY-CONFLICT',requestId:'LEGACY-CONFLICT',hCents:1000,csCents:old.normalCents-1000});assert.equal(h.view().state,'composition-conflict');assert.equal(serviceFinanceComposition(h.s,h.entry.id).known,false);await h.command(h.payload({supersedes:h.view().supersedes}),'finance.composition-reconcile');assert.equal(serviceFinanceComposition(h.s,h.entry.id).known,true);const last=h.s.serviceFinanceCompositions.at(-1);last.reconciliation.supersedes.push({key:'ledger:'+last.id,path:'serviceFinanceCompositions[2]',id:last.id,version:last.version,token:serviceFinanceCompositionFingerprint(last)});assert.equal(serviceFinanceComposition(h.s,h.entry.id).known,false);});
test('真实未知回退占额不因补收入消失，查询原笔后可逐笔补退组成',async()=>{const h=await oldCash();await h.refund(10000);const split=h.entry.split;await h.run('finance.return-start',{id:h.entry.id,version:h.entry.version,splitId:split.id,splitRequestNo:split.requestNo,amountCents:500,outcome:'processing'});const ret=h.entry.returns.at(-1),key='return:'+ret.id;await h.command(h.payload());let projection=serviceFinanceComposition(h.s,h.entry.id);assert.equal(projection.known,false);assert.equal(projection.returnSources[0].unknownReservedCents,500);await assert.rejects(h.command(h.payload({hCents:200,csCents:300,allocations:[{incomeSourceId:h.key,incomeRequestNo:split.requestNo,hCents:200,csCents:300}]},key)),/真实成功/);await h.run('finance.return-query',{id:h.entry.id,version:h.entry.version,returnId:ret.id,outcome:'success'});await h.command(h.payload({hCents:200,csCents:300,allocations:[{incomeSourceId:h.key,incomeRequestNo:split.requestNo,hCents:200,csCents:300}]},key));projection=serviceFinanceComposition(h.s,h.entry.id);assert.equal(projection.known,true);assert.equal(projection.hReturnedCents,200);assert.equal(projection.csReturnedCents,300);});
test('缺原号/时间/错误支付或跨款重号仍阻断，不用补核伪造事实',async()=>{for(const change of [h=>delete h.entry.split.completedAt,h=>delete h.entry.split.requestNo,h=>{h.entry.paymentId='missing';},h=>h.s.stores.push({...h.s.stores.find(x=>x.id==='xingfu')}),h=>h.s.serviceFinanceEntries.push({...structuredClone(h.entry),id:'OTHER-CASH'})]){const h=await oldCash(),p=h.payload();change(h);assert.equal(h.view().canConfirm,false);const before=structuredClone(h.s);await assert.rejects(h.command(p),/无效|不唯一|串号|来源|原支付|重复/);assert.deepEqual(h.s,before);}});
test('原月票消费补核H，H更正只转原票待红冲，PDF和旧snapshot保留',async()=>{const h=await oldCash(),incomeAt=h.entry.split.completedAt,month=new Date(incomeAt+8*3600000).toISOString().slice(0,7);await h.advance(40*1440);h.invoice('rule-publish',{category:'fee',version:0,issuerName:'显式技术测试集团',issuerTaxId:'91320100000000000Y',invoiceItem:'平台服务费',effectiveAt:h.s.now,sourceFromAt:Date.parse(month+'-01T00:00:00+08:00'),reason:'技术测试范围，不代表正式税务批准',cycle:'monthly',timezoneMinutes:480,returnPolicy:'cash-month'});assert.equal(feeInvoiceSummary(h.s,'xingfu',month).blocked,true);await h.command(h.payload());assert.equal(feeInvoiceSummary(h.s,'xingfu',month).netCents,1490);const inv=h.invoice('apply-fee',{storeId:'xingfu',month,kind:'company',title:'原服务门店技术抬头',taxId:'91320100000000000X',email:'test@example.com'},{role:'store',job:'store-finance',storeId:'xingfu'});h.invoice('issue',{id:inv.id,version:inv.version,ticketNumber:'ORIGINAL-FEE',file});const issued=structuredClone(h.s.commerceInvoices.at(-1));await h.command(h.payload({hCents:1000,csCents:h.entry.split.amountCents-1000,supersedes:h.view().supersedes}),'finance.composition-reconcile');syncCommerceInvoices(h.s);const after=h.s.commerceInvoices.at(-1);assert.equal(after.status,'red_pending');assert.equal(after.amount,issued.amount);assert.deepEqual(after.issued,issued.issued);assert.deepEqual(after.sourceSnapshot,issued.sourceSnapshot);assert.equal(h.s.serviceFinanceCompositions.length,2);});

test('更正前后附件沿精确槽读回，历史证据保留，错误槽/岗位/复制结果拒绝',async()=>{const h=await oldCash(),first=await h.command(h.payload());assert.deepEqual(authorizedServiceFinanceCompositionFile(h.s,finance,first.id,'evidence:0',file.ref),file);await h.command(h.payload({hCents:1000,csCents:h.entry.split.amountCents-1000,supersedes:h.view().supersedes}),'finance.composition-reconcile');assert.deepEqual(authorizedServiceFinanceCompositionFile(h.s,finance,first.id,'evidence:0',file.ref),file);const latest=h.s.serviceFinanceCompositions.at(-1);for(const slot of ['evidence:01','evidence:-1','evidence:1','file','recovery:0'])assert.throws(()=>authorizedServiceFinanceCompositionFile(h.s,finance,latest.id,slot,file.ref),/槽/);assert.throws(()=>authorizedServiceFinanceCompositionFile(h.s,support,latest.id,'evidence:0',file.ref),/财务/);assert.throws(()=>authorizedServiceFinanceCompositionFile(h.s,finance,latest.id,'evidence:0','invoice-file:'+'a'.repeat(64)),/槽/);});
test('有效核定相同内容无需再次更正，凭据变化使原supersedes失效',async()=>{const h=await oldCash();await h.command(h.payload());await assert.rejects(h.command(h.payload({supersedes:h.view().supersedes}),'finance.composition-reconcile'),/无需重复/);const p=h.payload({hCents:1000,csCents:h.entry.split.amountCents-1000,supersedes:h.view().supersedes});h.s.serviceFinanceCompositions[0].basisDescription='实际核验正文有变';const before=structuredClone(h.s);await assert.rejects(h.command(p,'finance.composition-reconcile'),/已变化/);assert.deepEqual(h.s,before);});
test('同支付重复资金条目即使不同现金编号也拒绝，不只检查技术号',async()=>{const h=await oldCash(),p=h.payload(),copy=structuredClone(h.entry);copy.id='OTHER-ENTRY';copy.split.id='OTHER-CASH';copy.split.requestNo='OTHER-REQUEST';h.s.serviceFinanceEntries.push(copy);assert.equal(h.view().canConfirm,false);const before=structuredClone(h.s);await assert.rejects(h.command(p),/资金条目重复/);assert.deepEqual(h.s,before);});
test('实际原店债回款补核取record.reference/occurredAt，保留债款与登记时间',async()=>{const h=harness();await h.setup({cash:false});await h.advance(30*1440);const debt=h.s.serviceFinanceRecoveries.find(r=>r.entryId===h.entry.id&&r.type==='unshared-release');assert.ok(debt);const amount=debt.amountCents;await h.run('finance.recovery-receive',{id:debt.id,amountCents:amount,...h.proof('ACTUAL-BANK-RECEIPT')});const current=h.s.serviceFinanceRecoveries.find(r=>r.id===debt.id),record=current.records.at(-1);delete record.cashComposition;delete record.cashCompositionRequest;const key=`recovery:${debt.id}:${record.id}`,cash=h.cash(),p=h.payload({},key),row=await h.command(p);assert.equal(row.actualReference,'ACTUAL-BANK-RECEIPT');assert.equal(row.actualAt,record.occurredAt);assert.equal(row.sourceCreatedAt,record.recordedAt);assert.notEqual(row.actualReference,record.requestId);assert.equal(serviceFinanceComposition(h.s,h.entry.id).known,true);assert.deepEqual(h.cash(),cash);assert.deepEqual(authorizedServiceFinanceCompositionFile(h.s,finance,row.id,'evidence:0',file.ref),file);});
test('真实管理员建岗/实际进入财务：白名单缺命令拒绝，实际撤权会话拒绝',async()=>{const h=await oldCash();await h.run('account.enter',{accountId:'DEMO-ADMIN',grantId:'DEMO-ADMIN-GRANT'});const admin={sessionId:h.s.staffSessions.at(-1).id};await h.run('account.create',{name:'补核测试财务',job:'finance',reason:'原管理员创建实际测试账号'},admin);let account=h.s.staffAccounts.at(-1);if(!account.grants.length)await h.run('account.grant',{id:account.id,version:account.version,job:'finance',reason:'真实原岗位授予'},admin);account=h.s.staffAccounts.find(a=>a.id===account.id);const grant=account.grants.find(g=>g.job==='finance');assert.ok(grant);await h.run('account.enter',{accountId:account.id,grantId:grant.id});const actor={sessionId:h.s.staffSessions.at(-1).id},p=h.payload(),capability=staffGrantCapabilities(grant).commands.includes('finance.composition-confirm');if(capability){const row=await h.command(p,undefined,actor);assert.equal(row.by.accountId,account.id);}else{assert.equal(h.view(h.key,actor).canConfirm,false);await assert.rejects(h.command(p,undefined,actor),/岗位|无权/);}const before=structuredClone(h.s);await h.run('account.revoke',{id:account.id,version:account.version,grantId:grant.id,reason:'原实际撤权'},admin);await assert.rejects(h.command(h.payload(),undefined,actor),/会话|授权|账号/);assert.equal(h.s.serviceFinanceCompositions?.length??0,before.serviceFinanceCompositions?.length??0);});
test('跨原source的旧核定requestId缺新请求sidecar时仍全局拒重号',async()=>{const h=harness();await h.setup({cash:false});await h.advance(30*1440);const debt=h.s.serviceFinanceRecoveries.find(r=>r.entryId===h.entry.id&&r.type==='unshared-release');for(const [amount,reference] of [[2000,'ACTUAL-PART-A'],[debt.amountCents-2000,'ACTUAL-PART-B']])await h.run('finance.recovery-receive',{id:debt.id,amountCents:amount,...h.proof(reference)});const records=h.s.serviceFinanceRecoveries.find(r=>r.id===debt.id).records;for(const record of records){delete record.cashComposition;delete record.cashCompositionRequest;}const firstKey=`recovery:${debt.id}:${records[0].id}`,secondKey=`recovery:${debt.id}:${records[1].id}`,first=await h.command(h.payload({},firstKey));
  // Isolate the older independent-ledger format that has no new review request sidecar.
  h.s.serviceFinanceRequests=h.s.serviceFinanceRequests.filter(r=>r.resultId!==first.id);const before=structuredClone(h.s);await assert.rejects(h.command(h.payload({requestId:first.requestId,hCents:0,csCents:records[1].amountCents},secondKey)),/提交标识|重复/);assert.deepEqual(h.s,before);});
test('实际文件读取期间切出财务身份，不能沿旧prepared继续核定',async()=>{const h=await oldCash(),actor={...finance},before=structuredClone(h.s);await assert.rejects(h.command(h.payload(),undefined,actor,{readFile:async()=>{actor.job='operations';return blob;}}),/财务/);assert.deepEqual(h.s,before);});
test('原请求精确重放还须核输出正文冻结摘要，已改核定不能冒原成功结果',async()=>{const h=await oldCash(),p=h.payload();await h.command(p);h.s.serviceFinanceCompositions[0].basisDescription='原核定正文已遭变更';const before=structuredClone(h.s);await assert.rejects(h.command(p),/原核定结果|冻结|已变化/);assert.deepEqual(h.s,before);});
test('原ctx.log实际追加events后冻结完整结果，精确重放保留日志而已改events仍拒绝',async()=>{const h=await oldCash(),p=h.payload();const log=(entity,content)=>{const event={at:h.s.now,text:content,actor:'group',job:'finance',actorId:'group'};(entity.events??=[]).push(event);};const row=await h.command(p,undefined,finance,{}, {log});assert.equal(row.events.length,1);const request=h.s.serviceFinanceRequests.find(r=>r.resultId===row.id);assert.equal(request.resultToken,serviceFinanceCompositionFingerprint(row));const before=structuredClone(h.s);await h.command(p,undefined,finance,{}, {log});assert.deepEqual(h.s,before);h.s.serviceFinanceCompositions[0].events[0].text='已改原日志';const changed=structuredClone(h.s);await assert.rejects(h.command(p),/冻结|已变化/);assert.deepEqual(h.s,changed);});
test('本成功回退待补核仍可明确引用原收入，预览只移自身且最终全原账核守恒',async()=>{const h=await oldCash();await h.command(h.payload());await h.refund(10000);const split=h.entry.split;await h.run('finance.return-start',{id:h.entry.id,version:h.entry.version,splitId:split.id,splitRequestNo:split.requestNo,amountCents:500,outcome:'success'});const ret=h.entry.returns.at(-1),key='return:'+ret.id;delete ret.cashComposition;delete ret.cashCompositionRequest;const before=structuredClone(h.s),view=h.view(key),source=view.allocationSources?.find(x=>x.incomeSourceId===h.key);assert.ok(source);assert.equal(source.known,true);assert.equal(source.hRemainingCents,1490);assert.equal(view.returnSources[0].known,false);assert.deepEqual(h.s,before);await h.command(h.payload({hCents:200,csCents:300,allocations:[{incomeSourceId:h.key,incomeRequestNo:split.requestNo,hCents:200,csCents:300}]},key));assert.equal(serviceFinanceComposition(h.s,h.entry.id).known,true);const current=h.view(key);assert.equal(current.allocationSources[0].hRemainingCents,1490);assert.equal(current.returnSources[0].hRemainingCents,1290);});
test('逐笔份额预览扣其他成功回退与未知占额，超原份额最终仍拒绝且不改账',async()=>{const h=await oldCash();await h.command(h.payload({hCents:500,csCents:h.entry.split.amountCents-500}));await h.refund(10000);const split=h.entry.split,allocation=(hc,cs)=>[{incomeSourceId:h.key,incomeRequestNo:split.requestNo,hCents:hc,csCents:cs}];const make=async amount=>{await h.run('finance.return-start',{id:h.entry.id,version:h.entry.version,splitId:split.id,splitRequestNo:split.requestNo,amountCents:amount,outcome:'success'});const ret=h.entry.returns.at(-1);delete ret.cashComposition;delete ret.cashCompositionRequest;return 'return:'+ret.id;};const first=await make(100);await h.command(h.payload({hCents:100,csCents:0,allocations:allocation(100,0)},first));const target=await make(500),view=h.view(target);assert.equal(view.allocationSources[0].hReturnedCents,100);assert.equal(view.allocationSources[0].hRemainingCents,400);const before=structuredClone(h.s);await assert.rejects(h.command(h.payload({hCents:500,csCents:0,allocations:allocation(500,0)},target)),/余额|份额|占额/);assert.deepEqual(h.s,before);await h.command(h.payload({hCents:200,csCents:300,allocations:allocation(200,300)},target));await h.run('finance.return-start',{id:h.entry.id,version:h.entry.version,splitId:split.id,splitRequestNo:split.requestNo,amountCents:100,outcome:'processing'});const reserved=h.view(target).allocationSources[0];assert.equal(reserved.hReservedCents+reserved.csReservedCents,100);const unknown=h.entry.returns.at(-1);delete unknown.cashComposition;delete unknown.cashCompositionRequest;const current=h.view(target),source=current.allocationSources[0];assert.equal(source.known,false);assert.equal(source.unknownReservedCents,100);assert.equal(source.hRemainingCents,null);assert.equal(serviceFinanceComposition(h.s,h.entry.id).known,false);});
test('份额预览拒绝非本成功回退、跨款与冲突原源，旧source不因排除目标被补成可用',async()=>{const h=await oldCash();await h.command(h.payload());await h.refund(10000);const split=h.entry.split;await h.run('finance.return-start',{id:h.entry.id,version:h.entry.version,splitId:split.id,splitRequestNo:split.requestNo,amountCents:500,outcome:'success'});const key='return:'+h.entry.returns.at(-1).id;for(const [entryId,sourceKey] of [[h.entry.id,h.key],['OTHER-ENTRY',key],[h.entry.id,'return:OTHER-CASH']])assert.throws(()=>serviceFinanceCompositionAllocationSources(h.s,entryId,sourceKey),/成功正常回退|缺少|不存在|唯一/);const copied=structuredClone(h.entry);copied.id='OTHER-ENTRY';h.s.serviceFinanceEntries.push(copied);assert.throws(()=>serviceFinanceCompositionAllocationSources(h.s,h.entry.id,key),/不唯一/);h.s.serviceFinanceEntries.pop();const ret=h.entry.returns.at(-1);h.entry.returns.push({...structuredClone(ret),amountCents:ret.amountCents+1});assert.throws(()=>serviceFinanceCompositionAllocationSources(h.s,h.entry.id,key),/冲突/);});
test('收入明确更正后原回退若超份额仍待核，须原回退自身更正且现金不变',async()=>{const h=await oldCash();await h.command(h.payload());await h.refund(10000);const split=h.entry.split;await h.run('finance.return-start',{id:h.entry.id,version:h.entry.version,splitId:split.id,splitRequestNo:split.requestNo,amountCents:500,outcome:'success'});const returned=h.entry.returns.at(-1),key='return:'+returned.id;
  // Isolate the pre-composition return format without changing its real amount/status/number/time.
  delete returned.cashComposition;delete returned.cashCompositionRequest;const allocation=(hCents,csCents)=>[{incomeSourceId:h.key,incomeRequestNo:split.requestNo,hCents,csCents}];await h.command(h.payload({hCents:500,csCents:0,allocations:allocation(500,0)},key));const cash=h.cash();await h.command(h.payload({hCents:200,csCents:split.amountCents-200,supersedes:h.view().supersedes}),'finance.composition-reconcile');assert.equal(serviceFinanceComposition(h.s,h.entry.id).known,false);assert.equal(h.view(key).state,'composition-conflict');await h.command(h.payload({hCents:200,csCents:300,allocations:allocation(200,300),supersedes:h.view(key).supersedes},key),'finance.composition-reconcile');const projection=serviceFinanceComposition(h.s,h.entry.id);assert.equal(projection.known,true);assert.equal(projection.hReturnedCents,200);assert.equal(projection.csReturnedCents,300);assert.deepEqual(h.cash(),cash);});
