import test from 'node:test';
import assert from 'node:assert/strict';
import {upgradeQualifications,qualificationEligibility,qualificationImpacts,qualificationCaseBlockers,qualificationCommand,qualificationView} from './tech-qualification.mjs';
const HOUR=3600000, now=Date.parse('2026-10-03T10:00:00+08:00');
const group={role:'group',job:'operations'}, support={role:'group',job:'support'}, local={role:'store',storeId:'s1'};
function seed(){return {now,seq:0,techs:[{id:'t1',name:'甲',storeId:'s1',serviceIds:['a','b'],qualificationRequired:true,active:true,reviewStatus:'approved',certificate:'C1',insurance:'I1',validUntil:'2027-12-31'},{id:'t2',name:'乙',storeId:'s2',serviceIds:['a'],qualificationRequired:true,active:true,reviewStatus:'approved',certificate:'C2',insurance:'I2',validUntil:'2027-12-31'}],stores:[{id:'s1',name:'一店',serviceIds:['a','b']},{id:'s2',name:'二店',serviceIds:['a']}],services:[{id:'a',name:'舒缓',active:true},{id:'b',name:'肩颈',active:true}],bookings:[],serviceCareCases:[]};}
let req=0;
function run(s,type,p={},actor=local){const out=structuredClone(s);qualificationCommand(out,actor,'qualification.'+type,{techId:'t1',version:out.techQualifications?.find(x=>x.techId==='t1')?.version || 0,requestId:'q-'+(++req),reason:'实际人工核实',...p},{fail:m=>{throw new Error(m)},id:prefix=>prefix+(++out.seq),log:()=>{}});return out;}
const row=s=>s.techQualifications.find(x=>x.techId==='t1');
const assess=(s,p={})=>run(s,'assess',{serviceIds:['a','b'],batch:'成熟技师名单一期',assessor:'考核员',proof:'TEST-QA-01',occurredAt:s.now,result:'pass',kind:'mature',...p});
function approved(s,p={}){s=assess(s,p);s=run(s,'request',{assessmentId:row(s).assessments.at(-1).id});return run(s,'review',{grantId:row(s).grants.at(-1).id,decision:'approve',reviewer:'集团审核员',proof:'TEST-QG-01'},group);}
const pause=(s,p={},actor=local)=>run(s,'pause',{serviceIds:['a'],owner:'复训负责人',...p},actor);
function retrained(s,holdId,p={}){const h=row(s).holds.find(x=>x.id===holdId);return approved(s,{serviceIds:h.serviceIds,kind:'retraining',holdId,occurredAt:s.now,...p});}
const resume=(s,holdId)=>run(s,'resume',{holdId,reviewer:'恢复审核员'},group);
test('migration freezes old project scope without creating historical authorization',()=>{const s=seed();delete s.techs[0].qualificationRequired;upgradeQualifications(s);const once=structuredClone(s);upgradeQualifications(s);assert.deepEqual(s,once);assert.equal(s.techQualifications.length,0);assert.deepEqual(s.techs[0].legacyQualifiedServiceIds,['a','b']);s.techs[0].serviceIds.push('c');assert.equal(qualificationEligibility(s,'t1','c').allowed,false);assert.equal(qualificationEligibility(s,'t1','a').legacy,true);assert.equal(s.techs[1].legacyQualifiedServiceIds,undefined);assert.equal(qualificationEligibility(s,'t2','a').allowed,false);});
test('unmigrated historical tests retain legacy scope but required new staff do not',()=>{const s=seed();delete s.techs[0].qualificationRequired;assert.deepEqual(qualificationEligibility(s,'t1','a'),{allowed:true,reason:'',legacy:true});assert.equal(qualificationEligibility(s,'t2','a').allowed,false);});
test('first profile replaces legacy compatibility; passing assessment is not authorization',()=>{let s=seed();delete s.techs[0].qualificationRequired;upgradeQualifications(s);s=assess(s);assert.equal(qualificationEligibility(s,'t1','a').allowed,false);s=run(s,'request',{assessmentId:row(s).assessments[0].id});assert.equal(qualificationEligibility(s,'t1','a').allowed,false);s=run(s,'review',{grantId:row(s).grants[0].id,decision:'approve',reviewer:'审核员',proof:'真实凭证'},group);assert.equal(qualificationEligibility(s,'t1','a').allowed,true);assert.equal(qualificationEligibility(s,'t1','a',now-1).allowed,false);});
test('approved grant covers only its recorded projects and adding staff projects cannot expand it',()=>{const s=approved(seed(),{serviceIds:['a']});assert.equal(qualificationEligibility(s,'t1','a').allowed,true);assert.equal(qualificationEligibility(s,'t1','b').allowed,false);});
test('assessment facts are immutable and request needs a pass with a unique source',()=>{let s=assess(seed(),{result:'fail'});assert.throws(()=>run(s,'request',{assessmentId:row(s).assessments[0].id}),/考核通过/);s=assess(s);const snapshot=structuredClone(row(s).assessments);s=run(s,'request',{assessmentId:row(s).assessments[1].id});assert.deepEqual(row(s).assessments,snapshot);assert.throws(()=>run(s,'request',{assessmentId:row(s).assessments[1].id}),/已申请授权/);});
test('assessment validates true calendar time, no future, evidence and project ownership',()=>{assert.throws(()=>assess(seed(),{occurredAt:'2026-02-30T10:00'}),/发生时间/);assert.throws(()=>assess(seed(),{occurredAt:now+1}),/尚未发生/);assert.throws(()=>assess(seed(),{proof:''}),/凭证/);assert.throws(()=>assess(seed(),{serviceIds:['other']}),/范围内/);const s=assess(seed(),{occurredAt:'2026-10-03T10:00'});assert.equal(row(s).assessments[0].occurredAt,now);});
test('authorization approval rechecks staff documents and active service even after application',()=>{let s=assess(seed());s=run(s,'request',{assessmentId:row(s).assessments[0].id});const p={grantId:row(s).grants[0].id,decision:'approve',reviewer:'审核员',proof:'凭证'};for(const patch of [{certificate:''},{insurance:''},{validUntil:'2026-10-02'},{reviewStatus:'pending'},{active:false}]){const x=structuredClone(s);Object.assign(x.techs[0],patch);assert.throws(()=>run(x,'review',p,group),/证书|在岗/);}s.services[0].active=false;assert.throws(()=>run(s,'review',p,group),/项目范围/);});
test('rejected grant remains historical and requires fresh assessment for another application',()=>{let s=assess(seed());s=run(s,'request',{assessmentId:row(s).assessments[0].id});s=run(s,'review',{grantId:row(s).grants[0].id,decision:'reject',reviewer:'审核员',proof:'驳回凭据'},group);assert.equal(row(s).grants[0].status,'rejected');assert.throws(()=>run(s,'request',{assessmentId:row(s).assessments[0].id}),/新.*考核/);});
test('role and store scope protect every write and pure projected reads',()=>{const s=seed();for(const actor of [{role:'tech',techId:'t1'},{role:'user',userId:'u1'},{role:'store',storeId:'s2'},{role:'group',job:'finance'},{role:'group',job:'warehouse'}])assert.throws(()=>run(s,'assess',{serviceIds:['a'],batch:'B',assessor:'A',proof:'P',occurredAt:now,result:'pass',kind:'mature'},actor),/无权处理/);assert.throws(()=>run(s,'assess',{},support),/不能登记/);let x=assess(s);x=run(x,'request',{assessmentId:row(x).assessments[0].id});assert.throws(()=>run(x,'review',{grantId:row(x).grants[0].id},local),/仅集团/);const before=structuredClone(x);qualificationView(x,local);qualificationView(x,{role:'tech',techId:'t1'});qualificationImpacts(x,'t1',['a']);qualificationEligibility(x,'t1','a');assert.deepEqual(x,before);assert.equal(qualificationView(x,{role:'group',job:'finance'}).technicians.length,0);assert.equal(qualificationView(x,{role:'store',storeId:'s2'}).technicians.length,1);});
test('version and persistent idempotency stop stale writes and changed replays',()=>{const s=seed(),p={techId:'t1',version:0,requestId:'same',reason:'依据',serviceIds:['a'],owner:'负责人'};const ctx={id:x=>x+(++s.seq),fail:m=>{throw new Error(m)}};qualificationCommand(s,local,'qualification.pause',p,ctx);const copy=structuredClone(s);qualificationCommand(s,local,'qualification.pause',p,ctx);assert.deepEqual(s,copy);assert.throws(()=>qualificationCommand(s,local,'qualification.pause',{...p,reason:'另一依据'},ctx),/同一提交/);assert.throws(()=>run(s,'pause',{version:0,serviceIds:['a'],owner:'负责人'}),/已更新/);assert.throws(()=>run(s,'pause',{version:true,serviceIds:['a'],owner:'负责人'}),/缺少版本/);});
test('pause is an independent project gate preserving technician and booking facts',()=>{let s=approved(seed());s.bookings=[{id:'B1',techId:'t1',storeId:'s1',serviceId:'a',status:'confirmed',startAt:now+HOUR},{id:'B2',techId:'t1',storeId:'s1',serviceId:'a',status:'active',startedAt:now,startAt:now},{id:'B3',techId:'t2',storeId:'s1',serviceId:'a',status:'confirmed',startAt:now+HOUR,change:{status:'pending',techId:'t1',startAt:now+2*HOUR}}];const before=structuredClone(s.bookings),tech=structuredClone(s.techs[0]);s=pause(s,{},support);assert.deepEqual(s.bookings,before);assert.deepEqual(s.techs[0],tech);assert.equal(qualificationEligibility(s,'t1','a').allowed,false);assert.equal(qualificationEligibility(s,'t1','b').allowed,true);assert.deepEqual(row(s).holds[0].affectedBookingIds,['B1','B3']);assert.equal(row(s).holds[0].impacts.find(x=>x.bookingId==='B2').stage,'fulfilling');});
test('impact list treats departure, arrival, active and interrupted as fulfillment and completed as history',()=>{const s=seed();s.bookings=[{id:'dep',status:'confirmed',departedAt:now},{id:'arr',status:'confirmed',arrivedAt:now},{id:'act',status:'active'},{id:'int',status:'interrupted'},{id:'done',status:'done'}].map(x=>({techId:'t1',serviceId:'a',startAt:now,...x}));const impacts=qualificationImpacts(s,'t1',['a']);assert.deepEqual(impacts.map(x=>x.bookingId),['dep','arr','act','int']);assert.ok(impacts.every(x=>x.stage==='fulfilling'&&!x.needsCoordination));});
test('resume requires new linked retraining pass and corresponding approved grant then explicit action',()=>{let s=approved(seed());s=pause(s);const h=row(s).holds[0].id;assert.throws(()=>resume(s,h),/复训考核/);s=assess(s,{kind:'retraining',holdId:h,serviceIds:['a']});assert.throws(()=>resume(s,h),/对应集团授权/);s=run(s,'request',{assessmentId:row(s).assessments.at(-1).id});s=run(s,'review',{grantId:row(s).grants.at(-1).id,decision:'approve',reviewer:'审核员',proof:'复训授权'},group);assert.equal(qualificationEligibility(s,'t1','a').allowed,false);s=resume(s,h);assert.equal(qualificationEligibility(s,'t1','a').allowed,true);assert.equal(row(s).holds[0].resolution.assessmentId,row(s).assessments.at(-1).id);});
test('retraining cannot predate pause, omit held projects, or reuse another hold assessment',()=>{let s=pause(seed(),{serviceIds:['a','b']});const h=row(s).holds[0].id;assert.throws(()=>assess(s,{kind:'retraining',holdId:h,occurredAt:now-1}),/暂停后/);assert.throws(()=>assess(s,{kind:'retraining',holdId:h,serviceIds:['a']}),/覆盖全部/);s=pause(s,{serviceIds:['a']});const h2=row(s).holds[1].id;s=retrained(s,h);assert.throws(()=>resume(s,h2),/该次暂停/);});
test('multiple holds clear independently and resume rechecks renewed documents',()=>{let s=approved(seed());s=pause(s);const h1=row(s).holds[0].id;s=pause(s);const h2=row(s).holds[1].id;s=retrained(s,h1);s=resume(s,h1);assert.equal(qualificationEligibility(s,'t1','a').allowed,false);s=retrained(s,h2);const invalid=structuredClone(s);invalid.techs[0].validUntil='2026-10-02';assert.throws(()=>resume(invalid,h2),/有效证书/);s=resume(s,h2);assert.equal(qualificationEligibility(s,'t1','a').allowed,true);});
test('resume requires original unstarted appointments and proposed candidates to be coordinated',()=>{let s=approved(seed());s.bookings=[{id:'old',techId:'t1',serviceId:'a',status:'confirmed',startAt:now+HOUR},{id:'offer',techId:'t2',serviceId:'a',status:'confirmed',startAt:now+HOUR,change:{techId:'t1',status:'pending',startAt:now+2*HOUR}},{id:'active',techId:'t1',serviceId:'a',status:'active',startedAt:now,startAt:now}];s=pause(s);const h=row(s).holds[0].id;s=retrained(s,h);assert.throws(()=>resume(s,h),/old.*offer/);s.bookings[0].techId='t2';assert.throws(()=>resume(s,h),/offer/);s.bookings[1].change.status='withdrawn';s=resume(s,h);assert.equal(row(s).holds[0].status,'resolved');assert.equal(s.bookings[2].status,'active');});
test('same technician retimed appointment remains uncoordinated for held project',()=>{let s=approved(seed());s.bookings=[{id:'old',techId:'t1',serviceId:'a',status:'confirmed',startAt:now+HOUR}];s=pause(s);const h=row(s).holds[0].id;s=retrained(s,h);s.bookings[0].startAt+=HOUR;assert.throws(()=>resume(s,h),/old/);s.bookings[0].status='cancelled';s=resume(s,h);assert.equal(row(s).holds[0].status,'resolved');});
function sourceState(){const s=seed();s.bookings=[{id:'source',techId:'t1',storeId:'s1',serviceId:'a',status:'done'}];s.serviceCareCases=[{id:'SC1',bookingId:'source',techId:'t1',storeId:'s1',version:1,specialistActions:[{kind:'retraining',status:'pending'}],history:[]}];return s;}
test('source pause locks same technician and project plus case version and reciprocal reference',()=>{let s=sourceState();assert.throws(()=>pause(s,{caseId:'SC1',actionIndex:0,caseVersion:0}),/已更新/);assert.throws(()=>pause(s,{caseId:'SC1',actionIndex:0,caseVersion:1,serviceIds:['b']}),/来源预约/);s=pause(s,{caseId:'SC1',actionIndex:0,caseVersion:1});const hold=row(s).holds[0],c=s.serviceCareCases[0];assert.equal(c.version,2);assert.equal(c.specialistActions[0].qualificationHoldId,hold.id);assert.equal(hold.source.caseId,c.id);assert.equal(c.history.length,1);assert.throws(()=>pause(s,{caseId:'SC1',actionIndex:0,caseVersion:2}),/尚未关联/);});
test('source mismatch and formal penalty cannot be represented by qualification hold',()=>{let s=sourceState();s.serviceCareCases[0].techId='t2';assert.throws(()=>pause(s,{caseId:'SC1',actionIndex:0,caseVersion:1}),/本技师/);s=sourceState();s.serviceCareCases[0].specialistActions[0].kind='penalty';assert.throws(()=>pause(s,{caseId:'SC1',actionIndex:0,caseVersion:1}),/限制接单或复训/);assert.deepEqual(qualificationCaseBlockers(s,s.serviceCareCases[0]),[]);});
test('care blockers require actual retraining authorization and restoration not mutable action status',()=>{let s=sourceState();s.serviceCareCases[0].specialistActions[0].status='completed';assert.equal(qualificationCaseBlockers(s,s.serviceCareCases[0]).length,1);s=pause(s,{caseId:'SC1',actionIndex:0,caseVersion:1});const h=row(s).holds[0].id;assert.equal(qualificationCaseBlockers(s,s.serviceCareCases[0]).length,1);s=retrained(s,h);assert.equal(qualificationCaseBlockers(s,s.serviceCareCases[0]).length,1);s=resume(s,h);assert.deepEqual(qualificationCaseBlockers(s,s.serviceCareCases[0]),[]);row(s).holds[0].resolution.grantId='missing';assert.equal(qualificationCaseBlockers(s,s.serviceCareCases[0]).length,1);});
test('closed source evidence remains stable and another pending grant cannot be approved after restoration',()=>{let s=pause(sourceState(),{caseId:'SC1',actionIndex:0,caseVersion:1}),h=row(s).holds[0].id;for(let n=0;n<2;n++){s=assess(s,{kind:'retraining',holdId:h,serviceIds:['a'],proof:'RETRAIN-'+n});s=run(s,'request',{assessmentId:row(s).assessments.at(-1).id});}const g1=row(s).grants[0].id,g2=row(s).grants[1].id;s=run(s,'review',{grantId:g1,decision:'approve',reviewer:'审核员',proof:'AUTH-FIRST'},group);s=resume(s,h);const original=structuredClone(row(s).holds[0].resolution);assert.throws(()=>run(s,'review',{grantId:g2,decision:'approve',reviewer:'审核员',proof:'LATE-AUTH'},group),/暂停已结束/);s=pause(s);const other=row(s).holds.at(-1).id;s=retrained(s,other);s=resume(s,other);s=approved(s,{serviceIds:['a']});assert.deepEqual(row(s).holds[0].resolution,original);assert.deepEqual(qualificationCaseBlockers(s,s.serviceCareCases[0]),[]);});
test('technician projection exposes own progress without internal proof or other booking identities',()=>{let s=approved(seed());s.bookings=[{id:'PRIVATE',techId:'t1',serviceId:'a',status:'confirmed',startAt:now+HOUR}];s=pause(s);const v=qualificationView(s,{role:'tech',techId:'t1'});assert.equal(v.technicians.length,1);const out=v.technicians[0];assert.equal(out.canAssess,false);assert.equal(out.canPause,false);assert.equal(out.assessments[0].proof,undefined);assert.equal(out.grants[0].review.proof,undefined);assert.ok(!JSON.stringify(out).includes('PRIVATE'));assert.equal(qualificationView(s,support).technicians[0].canPause,true);assert.equal(qualificationView(s,support).technicians[0].canReview,false);});
