import test from 'node:test';
import assert from 'node:assert/strict';
import {seed,reduce,goodsSummary} from './engine.mjs';
import {resolveAccountActor} from './staff-accounts.mjs';
import {workTaskView} from './work-tasks.mjs';
const user={role:'user',userId:'u1'};
function fixture(){let s=seed(),request=0;const f={get s(){return s;},run(type,p={},a=user){let result;s=reduce(s,a,type,{...p,...(p.requestId?{}:{requestId:'work-integration-'+(++request)})},x=>{result=x;});return result;},actor(a){return resolveAccountActor(s,a);},tasks(a){return workTaskView(s,a).tasks;},order(id){return s.goods.find(o=>o.id===id);},create(source='xingfu'){if(source)this.run('promotion.enter',{storeId:source});else this.run('promotion.clear');this.run('cart.set',{skuId:'oil',qty:1});this.run('goods.submit',{addressId:'AD1'});return s.goods.at(-1).id;},pay(id){this.run('goods.pay',{id,outcome:'success'});},claim(a,id){const row=this.tasks(a).find(t=>t.id===id);assert.ok(row,'task available');this.run('work.claim',{id:row.id,version:row.assignmentVersion,sourceToken:row.sourceToken},a);return row;}};
  const admin=f.run('account.enter',{accountId:'DEMO-ADMIN',grantId:'DEMO-ADMIN-GRANT'});f.admin=admin;
  f.add=(name,job,storeId=null)=>{const account=f.run('account.create',{name,reason:'统一待办验收账号'},admin);f.run('account.grant',{id:account.id,version:account.version,job,...(storeId?{storeId}:{}),reason:'按职责授权'},admin);const saved=s.staffAccounts.find(a=>a.id===account.id);return f.run('account.enter',{accountId:saved.id,grantId:saved.grants.at(-1).id});};
  f.warehouse=f.add('仓储甲','warehouse');f.warehouse2=f.add('仓储乙','warehouse');f.support=f.add('客服甲','support');f.finance=f.add('集团财务甲','finance');f.store=f.add('幸福里主管','store-manager','xingfu');f.storeFinance=f.add('幸福里财务','store-finance','xingfu');f.otherStore=f.add('银杏主管','store-manager','silver');return f;}
const only=(f,a,id)=>f.tasks(a).find(t=>t.id===id);
const moneyFacts=s=>structuredClone({goods:s.goods,skus:s.skus,bills:s.bills,recoveries:s.recoveries,serviceFinanceEntries:s.serviceFinanceEntries,techIncomeEntries:s.techIncomeEntries});

test('paid goods appear for real warehouse account and promotion store tracks without fulfillment rights',()=>{const f=fixture(),id=f.create(),key=`goods:${id}:ship`;assert.equal(only(f,f.warehouse,key),undefined);f.pay(id);const task=only(f,f.warehouse,key);assert.equal(task.status,'open');assert.equal(task.canClaim,true);assert.equal(task.route,`/group/goods/${id}`);for(const a of [f.store,f.storeFinance]){const tracked=only(f,a,key);assert.equal(tracked.route,`/store/goods/${id}`);assert.equal(tracked.canClaim,false);assert.equal(tracked.canAssign,false);}assert.equal(only(f,f.otherStore,key),undefined);assert.equal(only(f,f.finance,key),undefined);assert.deepEqual(f.tasks(f.admin),[]);});
test('claiming a shipping responsibility never changes order, inventory or money',()=>{const f=fixture(),id=f.create();f.pay(id);const before=moneyFacts(f.s);f.claim(f.warehouse,`goods:${id}:ship`);assert.deepEqual(moneyFacts(f.s),before);const task=only(f,f.warehouse,`goods:${id}:ship`);assert.equal(task.ownerAccountId,f.warehouse.accountId);assert.equal(task.canClaim,false);assert.equal(task.status,'open');assert.equal(f.s.workTaskAssignments.length,1);});
test('original staff guard still rejects warehouse refund and promotion store shipment after task claim',()=>{const f=fixture(),id=f.create();f.pay(id);f.claim(f.warehouse,`goods:${id}:ship`);const before=structuredClone(f.s);assert.throws(()=>f.run('goods.ship',{id,carrier:'物流',tracking:'SHIP1'},f.store),/无权/);assert.throws(()=>f.run('goods.refund',{id,caseId:'unknown',outcome:'success'},f.warehouse),/无权/);assert.deepEqual(f.s,before);f.run('goods.ship',{id,carrier:'物流',tracking:'SHIP1'},f.warehouse);assert.equal(only(f,f.warehouse,`goods:${id}:ship`).status,'done');});
test('customer cancellation → support approval → failed refund → processing → original query success remains one live source',()=>{const f=fixture(),id=f.create();f.pay(id);f.run('goods.case',{id,kind:'cancel',reason:'实际取消申请'});const caseId=f.order(id).cases[0].id,key=`goods-case:${caseId}:handling`;assert.equal(only(f,f.support,key).status,'open');assert.equal(only(f,f.warehouse,`goods:${id}:ship`).status,'waiting');f.claim(f.support,key);f.run('goods.case-review',{id,caseId,decision:'approve',reason:'核实尚未发货'},f.support);assert.equal(f.order(id).status,'cancelled');let t=only(f,f.finance,key);assert.equal(t.status,'open');assert.match(t.statusLabel,/待执行退款/);assert.equal(only(f,f.store,key).canAssign,false);f.claim(f.finance,key);const beforeClaimed=goodsSummary(f.s,f.order(id));assert.equal(beforeClaimed.refundedCents,0);f.run('goods.refund',{id,caseId,outcome:'failed'},f.finance);t=only(f,f.finance,key);assert.equal(t.status,'open');assert.match(t.statusLabel,/失败/);assert.deepEqual(t.commands,['goods.refund']);const transactionId=f.order(id).refunds[0].id;f.run('goods.refund',{id,caseId,outcome:'processing'},f.finance);t=only(f,f.finance,key);assert.equal(t.status,'open');assert.match(t.statusLabel,/处理中/);assert.deepEqual(t.commands,['goods.refund-query']);assert.equal(goodsSummary(f.s,f.order(id)).refundedCents,0);assert.throws(()=>f.run('goods.refund',{id,caseId,outcome:'success'},f.finance),/查询/);f.run('goods.refund-query',{id,caseId,outcome:'success'},f.finance);f.run('goods.refund-query',{id,caseId,outcome:'success'},f.finance);assert.equal(f.order(id).refunds.length,1);assert.equal(f.order(id).refunds[0].id,transactionId);assert.equal(goodsSummary(f.s,f.order(id)).netCents,0);assert.equal(only(f,f.finance,key).status,'done');assert.equal(only(f,f.support,key).status,'done');assert.equal(only(f,f.store,key).status,'done');});
test('source transition invalidates an old responsibility form even if new staff has permissions',()=>{const f=fixture(),id=f.create();f.pay(id);f.run('goods.case',{id,kind:'cancel',reason:'取消'});const caseId=f.order(id).cases[0].id,key=`goods-case:${caseId}:handling`,old=only(f,f.support,key);f.run('goods.case-review',{id,caseId,decision:'approve',reason:'核对'},f.support);assert.throws(()=>f.run('work.claim',{id:key,version:old.assignmentVersion,sourceToken:old.sourceToken},f.finance),/阶段已更新/);assert.equal(only(f,f.finance,key).status,'open');});
test('assignment advances responsibility version and rejects an old tab without touching money',()=>{const f=fixture(),id=f.create();f.pay(id);const key=`goods:${id}:ship`,old=only(f,f.warehouse,key),before=moneyFacts(f.s);f.run('work.assign',{id:key,version:old.assignmentVersion,sourceToken:old.sourceToken,accountId:f.warehouse2.accountId,grantId:f.actor(f.warehouse2).grantId,reason:'安排乙处理'},f.warehouse);assert.equal(only(f,f.warehouse,key).ownerAccountId,f.warehouse2.accountId);assert.throws(()=>f.run('work.assign',{id:key,version:old.assignmentVersion,sourceToken:old.sourceToken,accountId:f.warehouse.accountId,grantId:f.actor(f.warehouse).grantId,reason:'旧页面覆盖'},f.warehouse),/责任记录已更新/);assert.deepEqual(moneyFacts(f.s),before);});
test('revoked owner becomes unassignable and needs reassignment; revoked session cannot write original source',()=>{const f=fixture(),id=f.create();f.pay(id);const key=`goods:${id}:ship`;f.claim(f.warehouse,key);const account=f.s.staffAccounts.find(a=>a.id===f.warehouse.accountId);f.run('account.status',{id:account.id,version:account.version,enabled:false,reason:'验收撤权'},f.admin);const t=only(f,f.warehouse2,key);assert.equal(t.ownerValid,false);assert.match(t.ownerLabel,/重新分派/);assert.equal(t.canClaim,true);assert.ok(!t.candidates.some(c=>c.accountId===account.id));assert.throws(()=>f.run('goods.ship',{id,carrier:'物流',tracking:'REVOKED'},f.warehouse),/失效/);f.claim(f.warehouse2,key);assert.equal(only(f,f.warehouse2,key).ownerValid,true);});
test('natural group sale has no promotion-store task and group still fulfills',()=>{const f=fixture(),id=f.create(null);f.pay(id);assert.ok(only(f,f.warehouse,`goods:${id}:ship`));assert.equal(f.tasks(f.store).filter(t=>t.sourceId===id).length,0);assert.equal(f.tasks(f.otherStore).filter(t=>t.sourceId===id).length,0);});
test('rejected goods application is done, user appeal reopens same source with changed token',()=>{const f=fixture(),id=f.create();f.pay(id);f.run('goods.case',{id,kind:'cancel',reason:'取消'});const caseId=f.order(id).cases[0].id,key=`goods-case:${caseId}:handling`;f.run('goods.case-review',{id,caseId,decision:'reject',reason:'请补充材料'},f.support);const old=only(f,f.support,key);assert.equal(old.status,'done');f.run('goods.appeal',{id,caseId,reason:'补充材料申请复核'});const reopened=only(f,f.support,key);assert.equal(reopened.status,'open');assert.equal(reopened.id,old.id);assert.notEqual(reopened.sourceToken,old.sourceToken);});
test('return sequence waits for customer before warehouse work then finance only refunds after real receipt',()=>{const f=fixture(),id=f.create();f.pay(id);f.run('goods.ship',{id,carrier:'物流',tracking:'SHIP1'},f.warehouse);f.run('goods.case',{id,kind:'return',skuId:'oil',qty:1,amountCents:10000,reason:'实际退货'});const caseId=f.order(id).cases[0].id,key=`goods-case:${caseId}:handling`;f.run('goods.case-review',{id,caseId,decision:'approve',reason:'允许寄回'},f.support);assert.equal(only(f,f.support,key).status,'waiting');assert.equal(only(f,f.store,key).status,'waiting');f.run('goods.return',{id,caseId,carrier:'退货物流',tracking:'RETURN1'});assert.equal(only(f,f.warehouse,key).status,'open');f.run('goods.inspect',{id,caseId,disposition:'sellable'},f.warehouse);assert.equal(only(f,f.finance,key).status,'open');assert.equal(goodsSummary(f.s,f.order(id)).refundedCents,0);f.run('goods.refund',{id,caseId,outcome:'success'},f.finance);assert.equal(only(f,f.finance,key).status,'done');assert.equal(goodsSummary(f.s,f.order(id)).refundedCents,10000);});
test('task model provides only metadata across roles, never order address or case reason',()=>{const f=fixture(),id=f.create();f.pay(id);f.run('goods.case',{id,kind:'cancel',reason:'隐私退款原因唯一文本'});for(const actor of [f.support,f.warehouse,f.finance,f.store,f.storeFinance]){const dump=JSON.stringify(workTaskView(f.s,actor));for(const secret of ['13800008000','示例路128号','隐私退款原因唯一文本'])assert.ok(!dump.includes(secret),secret);}assert.throws(()=>f.run('work.done',{id:'anything'},f.support),/无权|不支持/);});
test('scope and source filters still hold when actor fields try to override stored working grant',()=>{const f=fixture(),id=f.create('silver');f.pay(id);const forged={...f.store,role:'group',job:'warehouse',storeId:'silver'};assert.equal(f.tasks(forged).some(t=>t.sourceId===id),false);assert.throws(()=>f.run('goods.ship',{id,carrier:'物流',tracking:'FORGED'},forged),/无权/);});
