import test from 'node:test';
import assert from 'node:assert/strict';
import {seed,reduce} from './engine.mjs';
import {resolveAccountActor} from './staff-accounts.mjs';
import {workTaskView} from './work-tasks.mjs';
import {taskListFilters,filterWorkTasks,workTaskUiView,workTaskSummary} from './work-ui.mjs';

const user={role:'user',userId:'u1'};
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const decode=v=>v.replace(/&quot;|&#39;|&lt;|&gt;|&amp;/g,c=>({'&quot;':'"','&#39;':"'",'&lt;':'<','&gt;':'>','&amp;':'&'}[c]));
const ui=(query='')=>({esc:e,date:at=>new Date(at).toISOString(),query:new URLSearchParams(query),
  button:(label,command,p={},kind='')=>`<button type="button" data-command="${e(command)}" data-payload="${e(JSON.stringify(p))}" class="${e(kind)}">${e(label)}</button>`,
  link:(label,path,kind='')=>`<a href="#${e(path)}" class="${e(kind)}">${e(label)}</a>`,
  field:(label,name,value='',type='text',attrs='')=>`<label><span>${e(label)}</span><input name="${e(name)}" type="${e(type)}" value="${e(value)}" ${attrs}></label>`,
  select:(label,name,options,value)=>`<label><span>${e(label)}</span><select name="${e(name)}">${options.map(o=>`<option value="${e(o.value)}"${o.value===value?' selected':''}>${e(o.label)}</option>`).join('')}</select></label>`,
  tag:(label,kind='')=>`<span class="tag ${e(kind)}">${e(label)}</span>`,
  empty:(label,detail='')=>`<section><h2>${e(label)}</h2><p>${e(detail)}</p></section>`});
const cards=html=>[...html.matchAll(/<article\b([^>]*)>([\s\S]*?)<\/article>/g)].map(([,attrs,body])=>({id:decode(/data-task-id="([^"]+)"/.exec(attrs)?.[1]||''),body}));
const actions=(html,tag,command)=>[...html.matchAll(new RegExp(`<${tag}\\b([^>]*)>([\\s\\S]*?)<\\/${tag}>`,'g'))].map(([,attrs,body])=>({attrs,body,command:/data-command="([^"]+)"/.exec(attrs)?.[1],payload:JSON.parse(decode(/data-payload="([^"]+)"/.exec(attrs)?.[1]||'{}'))})).filter(x=>x.command===command);
const selected=(html,name)=>{const body=new RegExp(`<select name="${name}">([\\s\\S]*?)<\\/select>`).exec(html)?.[1]||'';return decode(/<option value="([^"]*)" selected/.exec(body)?.[1]||'');};
function fixture(){
  let s=seed(),seq=0;
  const f={get s(){return s;},run(type,p={},actor=user){let result;s=reduce(s,actor,type,{requestId:'task-ui-'+(++seq),...p},r=>result=r);return result;},actor(a){return resolveAccountActor(s,a);},page(a,query='category=goods-shipping'){return workTaskUiView(s,this.actor(a),['tasks'],ui(query));},task(a,id){return workTaskView(s,a).tasks.find(t=>t.id===id);},create(store='xingfu'){this.run('promotion.enter',{storeId:store});this.run('cart.set',{skuId:'oil',qty:1});this.run('goods.submit',{addressId:'AD1'});const id=s.goods.at(-1).id;this.run('goods.pay',{id,outcome:'success'});return id;}};
  f.admin=f.run('account.enter',{accountId:'DEMO-ADMIN',grantId:'DEMO-ADMIN-GRANT'});
  f.add=(name,job,storeId)=>{const a=f.run('account.create',{name,reason:'待办界面验收'},f.admin);f.run('account.grant',{id:a.id,version:a.version,job,...(storeId?{storeId}:{}),reason:'按岗位授权'},f.admin);const grant=s.staffAccounts.find(x=>x.id===a.id).grants.at(-1);return f.run('account.enter',{accountId:a.id,grantId:grant.id});};
  f.warehouse=f.add('仓储甲','warehouse');f.warehouse2=f.add('仓储乙','warehouse');f.store=f.add('本店主管','store-manager','xingfu');f.support=f.add('客服甲','support');f.finance=f.add('财务甲','finance');
  f.open=f.create();f.waiting=f.create();f.run('goods.case',{id:f.waiting,kind:'cancel',reason:'私密售后正文不能出现在统一待办'});f.done=f.create();f.run('goods.ship',{id:f.done,carrier:'物流',tracking:'UI-SHIP'},f.warehouse);f.remote=f.create('silver');
  return f;
}

test('task filters default to unfinished and preserve supplied query state',()=>{assert.deepEqual(taskListFilters(),{category:'',status:'active',q:'',owner:'',store:''});const q=new URLSearchParams('category=goods-shipping&status=waiting&owner=mine&store=xingfu&q=%20AbC%20');assert.deepEqual(taskListFilters(q),{category:'goods-shipping',status:'waiting',owner:'mine',store:'xingfu',q:'AbC'});});
test('default active list keeps waiting work visible and omits truly completed sources',()=>{const f=fixture(),html=f.page(f.warehouse),ids=cards(html).map(x=>x.id);assert.deepEqual(ids,[`goods:${f.open}:ship`,`goods:${f.waiting}:ship`,`goods:${f.remote}:ship`]);assert.match(html,/待处理 2 项 · 等待其他方 1 项 · 已办 1 项/);assert.match(html,/当前筛选 3 项/);assert.equal(selected(html,'status'),'active');});
test('open waiting and done filters reflect original records without a local completion flag',()=>{const f=fixture();for(const [status,ids] of [['open',[f.open,f.remote]],['waiting',[f.waiting]],['done',[f.done]],['all',[f.open,f.waiting,f.done,f.remote]]]){const html=f.page(f.warehouse,`category=goods-shipping&status=${status}`);assert.deepEqual(cards(html).map(x=>x.id),ids.map(id=>`goods:${id}:ship`));assert.equal(selected(html,'status'),status);}assert.match(f.page(f.warehouse,'status=done'),/查看原记录/);});
test('filter form retains category status owner store and escaped search text with the correct return list',()=>{const f=fixture(),html=f.page(f.warehouse,'category=goods-shipping&status=all&owner=unassigned&store=xingfu&q=%20%3Cabc%3E%20');for(const [name,value] of Object.entries({category:'goods-shipping',status:'all',owner:'unassigned',store:'xingfu'}))assert.equal(selected(html,name),value);assert.match(html,/name="q" type="search" value="&lt;abc&gt;"/);assert.doesNotMatch(html,/<abc>/);const form=actions(html,'form','ui.filter')[0];assert.deepEqual(form.payload,{path:'/group/tasks'});assert.match(html,/href="#\/group\/tasks"[^>]*>清除筛选/);assert.match(html,/当前没有符合条件的事项/);});
test('category store and case-insensitive source search combine without reading business body',()=>{const f=fixture(),model=workTaskView(f.s,f.warehouse).tasks;const result=filterWorkTasks(model,taskListFilters(new URLSearchParams({category:'goods-shipping',status:'all',store:'xingfu',q:f.open.toLowerCase()})),f.actor(f.warehouse));assert.deepEqual(result.map(x=>x.id),[`goods:${f.open}:ship`]);const privateFilter=f.page(f.support,'status=all&q=私密售后正文');assert.equal(cards(privateFilter).length,0);});
test('promotion store only sees its own metadata and gets tracking actions without assignment controls',()=>{const f=fixture(),html=f.page(f.store,'status=all'),ids=cards(html).map(x=>x.id);assert.ok(ids.includes(`goods:${f.open}:ship`));assert.ok(!html.includes(f.remote));assert.ok(!html.includes('value="silver"'));assert.match(html,/查看办理进度/);assert.doesNotMatch(html,/由我认领|分派处理人/);assert.equal(actions(html,'form','work.assign').length,0);assert.equal(actions(html,'button','work.claim').length,0);assert.equal(cards(f.page(f.store,'status=all&store=silver')).length,0);for(const b of actions(html,'button','ui.task-open'))assert.ok(ids.includes(b.payload.taskKey));});
test('unrelated jobs and nonstaff never receive goods sources in rendered output',()=>{const f=fixture();for(const actor of [f.finance,f.admin,user,{role:'tech',techId:'lin'},{role:'manager',storeId:'xingfu'}]){const html=f.page(actor,'status=all&category=goods-shipping');assert.equal(cards(html).length,0);for(const id of [f.open,f.waiting,f.done,f.remote])assert.ok(!html.includes(id));assert.equal(actions(html,'button','ui.task-open').length,0);}assert.equal(workTaskUiView(f.s,f.actor(f.warehouse),['goods'],ui()),null);});
test('actual assignment form carries source and responsibility versions and real eligible account-grant pairs',()=>{const f=fixture(),card=cards(f.page(f.warehouse)).find(x=>x.id===`goods:${f.open}:ship`),form=actions(card.body,'form','work.assign')[0],task=f.task(f.warehouse,card.id);assert.deepEqual(form.payload,{id:task.id,sourceToken:task.sourceToken,version:0});assert.match(form.attrs,/data-management-form="work:/);assert.match(form.attrs,/data-live-version="0"/);assert.match(form.body,/name="reason" required/);const values=[...form.body.matchAll(/<option value="([^"]+)"/g)].map(([,x])=>JSON.parse(decode(x)));assert.deepEqual(values.sort(),[[f.warehouse.accountId,f.actor(f.warehouse).grantId],[f.warehouse2.accountId,f.actor(f.warehouse2).grantId]].sort());const [accountId,grantId]=values.find(x=>x[0]===f.warehouse2.accountId);f.run('work.assign',{...form.payload,accountId,grantId,reason:'按实际排班转派'},f.warehouse);const next=cards(f.page(f.warehouse)).find(x=>x.id===card.id);assert.match(next.body,/仓储乙/);assert.match(next.body,/按实际排班转派/);assert.equal(actions(next.body,'form','work.assign')[0].payload.version,1);});
test('mine unassigned and invalid-owner filters distinguish responsibility after real claim and revocation',()=>{const f=fixture(),html=f.page(f.warehouse),claim=actions(cards(html).find(x=>x.id===`goods:${f.open}:ship`).body,'button','work.claim')[0];f.run('work.claim',claim.payload,f.warehouse);assert.deepEqual(cards(f.page(f.warehouse,'category=goods-shipping&owner=mine')).map(x=>x.id),[`goods:${f.open}:ship`]);assert.equal(cards(f.page(f.warehouse2,'category=goods-shipping&owner=mine')).length,0);assert.ok(!cards(f.page(f.warehouse2,'category=goods-shipping&owner=unassigned')).some(x=>x.id===`goods:${f.open}:ship`));const a=f.s.staffAccounts.find(x=>x.id===f.warehouse.accountId);f.run('account.status',{id:a.id,version:a.version,enabled:false,reason:'授权变化'},f.admin);const invalid=f.page(f.warehouse2,'category=goods-shipping&owner=invalid');assert.deepEqual(cards(invalid).map(x=>x.id),[`goods:${f.open}:ship`]);assert.match(invalid,/需重新分派/);assert.equal(actions(invalid,'button','work.claim').length,1);});
test('native safety owner is displayed once and uses the original handling page without sidecar assignment',()=>{const f=fixture(),id='HELP-UI';f.s.bookings.push({id:'BK-HELP-UI',userId:'u1',storeId:'xingfu',status:'help',rounds:[],refunds:[],disputes:[],assistance:[]});f.s.safety.push({id,bookingId:'BK-HELP-UI',status:'open',stage:'pending',ackDeadline:f.s.now-1,createdAt:f.s.now-60000,responsibleName:'原安全负责人'});f.s.workTaskAssignments.push({id:`booking-safety:${id}:handle`,accountId:f.support.accountId,accountName:'错误平行负责人',version:1,history:[]});const html=f.page(f.support,'category=safety'),card=cards(html)[0];assert.match(card.body,/原安全负责人/);assert.doesNotMatch(card.body,/错误平行负责人|分派处理人|由我认领/);assert.match(card.body,/进入原页面认领或转派/);assert.match(card.body,/已过期/);assert.equal(actions(card.body,'button','ui.task-open').length,1);assert.equal(cards(f.page(f.support,'category=safety&owner=unassigned')).length,0);});
test('goods deadlines stay explicitly unset and responsible department remains group warehouse for store tracking',()=>{const f=fixture(),card=cards(f.page(f.store)).find(x=>x.id===`goods:${f.open}:ship`);assert.match(card.body,/负责岗位/);assert.match(card.body,/仓储/);assert.match(card.body,/未设定办理期限/);assert.doesNotMatch(card.body,/已过期|小时内/);assert.match(card.body,new RegExp(e(f.s.stores.find(x=>x.id==='xingfu').name)));});
test('rendered metadata omits source contact address and case body and offers no manual done command',()=>{const f=fixture();f.s.goods.find(x=>x.id===f.waiting).recipient={name:'私密收货人',phone:'13977776666',address:'私密完整街道地址'};for(const actor of [f.warehouse,f.store,f.support,f.finance]){const html=f.page(actor,'status=all');for(const privateText of ['私密收货人','13977776666','私密完整街道地址','私密售后正文不能出现在统一待办'])assert.ok(!html.includes(privateText),privateText);const commands=[...html.matchAll(/data-command="([^"]+)"/g)].map(([,x])=>x);assert.ok(commands.every(x=>['ui.filter','ui.task-open','ui.management-discard','work.claim','work.assign','work-escalation.decline','work-escalation.raise','work-escalation.takeover'].includes(x)));assert.doesNotMatch(html,/work\.(done|close)|标记完成|手动完成/);}});
test('every assignment draft has separate status feedback and a non-submit discard action for stale versions',()=>{const f=fixture(),html=f.page(f.warehouse);for(const form of actions(html,'form','work.assign')){assert.match(form.attrs,/data-management-form="work:/);assert.match(form.attrs,/data-live-version="0"/);assert.match(form.body,/<p class="management-draft-note small muted" role="status">/);const discard=actions(form.body,'button','ui.management-discard');assert.equal(discard.length,1);assert.match(discard[0].attrs,/type="button"/);assert.match(discard[0].body,/放弃本页草稿/);}const waiting=cards(f.page(f.warehouse,'category=goods-shipping&status=waiting'))[0];assert.match(waiting.body,/查看办理进度/);assert.doesNotMatch(waiting.body,/进入办理|确认分派/);});
test('display names and assignment reasons are escaped and state feedback is separate from actions',()=>{const f=fixture(),danger=f.add('<img src=x onerror=alert(1)>','warehouse'),t=f.task(f.warehouse,`goods:${f.open}:ship`);f.run('work.assign',{id:t.id,version:t.assignmentVersion,sourceToken:t.sourceToken,accountId:danger.accountId,grantId:f.actor(danger).grantId,reason:'<script>仅展示</script>'},f.warehouse);const html=f.page(f.warehouse);assert.match(html,/&lt;img src=x/);assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/<img src=x|<script>/);for(const [,attrs,body] of html.matchAll(/<p\b([^>]*role="status"[^>]*)>([\s\S]*?)<\/p>/g)){assert.doesNotMatch(attrs,/data-command|role="button"/);assert.doesNotMatch(body,/<button/);}assert.match(html,/data-command="ui.task-open"/);});
test('summary counts follow current permissions, full page reads are pure, and nonstaff summaries stay absent',()=>{const f=fixture(),before=structuredClone(f.s),a=f.actor(f.warehouse),summary=workTaskSummary(f.s,a,ui());assert.match(summary,/待处理 2 项 · 等待其他方 1 项 · 已办 1 项/);assert.match(summary,/href="#\/group\/tasks"/);for(const actor of [user,{role:'tech',techId:'lin'},f.actor(f.admin)])assert.equal(workTaskSummary(f.s,actor,ui()),'');for(const actor of [f.warehouse,f.store,f.support,f.finance])f.page(actor,'status=all');assert.deepEqual(f.s,before);});
